### ISSUE TITLE
Ensure metabuild JSON is optional in source releases

### ISSUE THREAD

**Issue by neilcsmith-net** [apache/netbeans#3456]
The intention of having `netbeansrelease.properties` in source releases was so that building them is decoupled from the `metabuild.json` file. However the json parsing is still happening, and can overwrite the bundled information.  Needs guarding.

cc / @ebarboni what are the json and xml files written to `nbbuild/build` used for?  May affect where to fix this.

Opening as an issue so I can attach to milestone.

**Comment by ebarboni** [comment]
not sure if it related but #2421 may be triaged with that (potentially discarded)

xml file is for apidoc menu generation to get post/next apidoc to be parsed with xsl and so on.
json file  was intended as cache 

I think was I should have done is copy json + xml + properties in nbbuild and not nbuild/build. So we "lock what was used for build" and be sure we can rebuild offline from the "source package".
On jenkins it would'nt be present so will redownload each time.
On local build "master" or on "branch" it will no be updated except if we add a task to so or if we append ant clean maybe

**Comment by neilcsmith-net** [comment]
So rc2 build with `ant build -Dmetabuild.jsonurl=https://netbeans.apache.org/foo.json` succeeds where same with rc1 fails.

Closing - GH doesn't appear to have picked up it's made its way to master now.
