### ISSUE TITLE
Hint: “Convert Explicit Type to Var” shouldn’t be reported for method references or lambda expressions

### ISSUE THREAD

**Issue by ExE-Boss** [apache/netbeans#3466]
### Apache NetBeans version

Latest release

### What happened

**Convert Explicit Type to Var** is reported for method references and lambda expressions, e.g.:
```java
final Consumer<String> println = System.out::println;
```

But it's invalid to replace the above with:
```java
final var println = System.out::println;
```
which results in the compile error:
```
error: cannot infer type for local variable println
final var println = System.out::println;
          ^
  (method reference needs an explicit target-type)
```

### How to reproduce

See above

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Windows 10

### JDK

OpenJDK Runtime Environment [Temurin](https://adoptium.net/)-17.0.1+12 (build 17.0.1+12)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by mbien** [comment]
the hint is here:
https://github.com/apache/netbeans/blob/master/java/java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertToVarHint.java

potentially easy to fix. But maybe someone else can do it since I don't use 'var' at all :) 

adding the good-first-issue label.

**Comment by itsarraj** [comment]
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.
