### ISSUE TITLE
[php] typing parent:: does not provide methods of the parent's trait

### ISSUE THREAD

**Issue by naitsirch** [apache/netbeans#3486]
### Apache NetBeans version

Latest release

### What happened

Netbeans does not show the methods of a trait used by a parent class in the auto completion context.

### How to reproduce

Create a PHP file and insert following code:

```php
<?php

trait T {
    protected function foo() {}
}
class A {
    use T;
    protected function shownFnc() {}
}
class B extends A {
    protected function foo() {
        parent:: // <-- place your cursor here
    }
}
```

Now place your cursor at the hinted line and hit `ctrl + space` keys. Now, the auto complete menu shows the `shownFnc` method, but not `foo`.

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Debian 10.11, Linux version 4.19.0-14-amd64

### JDK

11.0.12; OpenJDK 64-Bit Server VM 11.0.12+7

### Apache NetBeans packaging

Other

### Anything else

Netbeans is installed via flatpak

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment]
Thanks for the report - needs someone involved with PHP support to take a look - cc @junichi11 @tmysik

**Comment by junichi11** [comment]
Fixed.

**Comment by naitsirch** [comment]
@junichi11 Great! Thank you very much :-)

**Comment by junichi11** [comment]
You're welcome :)
