### ISSUE TITLE
Find in Projects - Pressing enter does not start the search anymore

### ISSUE THREAD

**Issue by JoachimRohde** [apache/netbeans#3487]
### Apache NetBeans version

Latest release candidate

### What happened

Open the "Find in Projects" dialog, type something into the "Containing Text" text field and press enter. 
I expected the same behavior as in previous versions (12.6 and before): that the search gets triggered. Instead a line break is inserted into the text field.

### How to reproduce

Open the "Find in Projects" dialog, type something into the "Containing Text" text field and press enter. 

### Did this work correctly in an earlier version?

- [X] This used to work!

### Operating System

Linux Mint 20.2 Cinnamon

### JDK

11.0.13; OpenJDK 64-Bit Server VM 11.0.13+8-Ubuntu-0ubuntu1.20.04

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment]
You can use CTRL-Enter. There were changes to support multiline text. #3393 However this is the second report of confusion already. Maybe some rethinking of UI required? Maybe should look multiline without resize? cc @mbien

**Comment by emaphis** [comment]
Maybe include a note (as a label) in the dialog box for couple of releases.  Ugly but eye-catching.  Remove later.

**Comment by mbien** [comment]
the reason i haven't noticed this is because I never use enter on dialogs. Half of the software out there never does what you would expect - so it became a habit to use the mouse for ok/cancel - esp on important stuff.

Anyway, i made the text areas behave like a text fields if they are still small enough. Should cover both use cases without the need to break habits. Please test it if it works ok for you.

**Comment by neilcsmith-net** [comment]
@mbien some of us are used to NetBeans behaving correctly with the keyboard and try to use the mouse as little as possible!  I'm not sure your solution is correct so far, but let's take the discussion into #3489

@emaphis might be right about an ugly but eye catching label.
