### ISSUE TITLE
New class wizard superclass selection does not provide project classes as an option

### ISSUE THREAD

**Issue by jamoamo** [apache/netbeans#3511]
### Apache NetBeans version

Latest release

### What happened

When adding a new Java class to a project, one is presented with the option of browsing for a superclass for the new class to extend. In the "Find Type" dialog, when one enters the name of a class within the same project, the class is not presented as an option to select. The expectation is that classes from the same project should be options to be extended. This expected behaviour is seen when browsing for interfaces to implement.

### How to reproduce

Create a new Ant project [Java with Ant -> Java class library] (A Maven project can also reproduce the bug)
Right click source packages -> New -> Java Class
* Enter ParentClass as Class Name
* Enter a convenient package name
* Click Finish
Right click package -> New -> Java Class
* Enter ChildClass as Class Name
* Enter a convenient package name
* next to Superclass click "browse"
* In the "Find Type" dialog enter the name "ParentClass"
* The ParentClass class created earlier is not shown in the list

Attached is a screen recording showing how to reproduce
![NewClassSuperclassbug](https://user-images.githubusercontent.com/5406148/151182641-2eda116b-bcf8-421b-b18b-400f7069a1a4.gif)

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Windows 10 Home 21H2

### JDK

OpenJDK 64-bit server VM 17+35 

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I tracked this down to org.netbeans.modules.java.project.ui.ExtensionAndImplementationVisualPanel.java and the method `isNotFinalClass(ElementHandle<TypeElement>)` which looks as follows:
```
private boolean isNotFinalClass(ElementHandle<TypeElement> typeHandle) {
        try {
            Class<?> clazz = Class.forName(typeHandle.getQualifiedName());
            return typeHandle.getKind() == ElementKind.CLASS && !Modifier.isFinal(clazz.getModifiers());
        } catch (ClassNotFoundException ex) {
        }
        return false;
    }
```
In my understanding, Class.forName will only load classes that are on the IDE's class path. Any other classes, such as those from the project under development, will result in a ClassNotFoundException which will cause the class to be ignored.

I would provide a PR for this but am not sure how best to get Modifier information about the class to determine if it is final.

### Are you willing to submit a pull request?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by mbien** [comment]
Reproducible in 13rc2. Thanks for the detailed report.

**Comment by mbien** [comment]
I looked at this a little bit. I agree that `isNotFinalExceptionType` and `isNotFinalClass` methods should not use `Class.forName` since it doesn't know anything about the project.
To properly implement this we would have to call `typeHandle.resolve(compilationInfo)` then get a type mirror to get the modifiers. Getting a CompilationInfo is a bit of a ceremony unfortunately.

However, if we say that the filters only need to function on a best effort basis, we could simply return true.
```
  } catch (ClassNotFoundException ex) {
      return true; // we don't know
  }
```
this would show classes from project classpath even if they are final, instead of showing nothing. Maybe its still good enough for the wizzard - I don't know.

**Comment by mbien** [comment]
it might be worth investigating if it would make sense to add modifiers to the `ElementHandle` API.

Removing good-first-issue label again :)

**Comment by itsarraj** [comment]
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.
