### ISSUE TITLE
Netbeans 12.5 imported older project cannot be loaded - Unsupported class fle major version 61

### ISSUE THREAD

**Issue by paratechnical** [apache/netbeans#3517]
### Apache NetBeans version

Latest release

### What happened

Netbeans 12.5 - It worked in Netbeans 11
When I open the project I get this error

![image](https://user-images.githubusercontent.com/1389561/151247799-a13cf809-931d-4943-a723-3b4cf514dc8b.png)

When I tell Netbeans that I want to resolve it it doesn't work and I get this warning.
![image](https://user-images.githubusercontent.com/1389561/151247883-6e53578d-2949-4522-8bf7-1fc76dfe7c45.png)

```
Could not run build action using connection to Gradle installation 'C:\Users\ff.gradle wrap per\dists\gradle-7.0-bin\2p9eb qfab irfozi6 760gco7n\gradle~

Could not open cp_int generic class cache for intialzation script "c:\Program Files\NetBeans-12.5\netbeans\extide\modules\gradle\nb-toolng.gradie’ (C:\Users\ffi.gradie\caches\7.0\scripts\dtnvzzibbagvwi42m3qn4ji).

Could not open cp_int generic class cache for intialzation script ‘c:\Program Files\NetBeans-12.5\netbeans\extide\modules\gradle\nb-tooing.gradie’ (C:\Users\ffi.gradle\caches\7.0\scripts\dtnvzzibbagvwi42m3qn4ji).

BUG! exception in phase 'semantic analysis'in source unit‘ BuidScript_' Unsupported class fle major version 61

Unsupported class fie major version 61
```

I tried changing the gradle version in Tools->Options->Java->Gradle to 6 doesn't seem to change anything because the warning still mentions gradle 7. I tried changing the java version but that doesn't seem to work either.

![image](https://user-images.githubusercontent.com/1389561/151248055-13a180c7-56d6-4373-ae20-0fb2e7680afc.png)

I tried deleting the cache both in the project and in the gradle folder C:\Users\<user>\.gradle

### How to reproduce

create a gradle project in netbeans 11
open in netbeans 12

### Did this work correctly in an earlier version?

- [X] This used to work!

### Operating System

Windows 10 Pro

### JDK

17.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment]
Possibly try unticking the option to prefer the Gradle wrapper that comes with the project.  You can update the wrapper in that project later if you want to reenable that option.

cc/ @lkishalmi is there an easier way to handle this?  Maybe need a wrapper update UI?  Or am I missing there is one somewhere?

**Comment by lkishalmi** [comment]
Well, there is no real workaround can be don on NetBeans side. NetBeans 12.5 does not really support running on JDK 17. We have NetBeans 12.6 for that. Also NetBeans 13 will report such issues more detailed to users.

**Comment by lkishalmi** [comment]
Just briefly: Due to limitations in Gradle, it's no matter what version you set for Gradle, or JDK, the project introspection will happen with the JDK the IDE is running on, starting with the Gradle Tooling API the IDE is provided with. If the Tooling API does not support the JDK the IDE is running on, then this is what happens.
Gradle 7.3 is the first one which supports JDK 17 as runtime. We were lucky with 12.6 that Gradle released that just a few days before our last release candidate.

**Comment by neilcsmith-net** [comment]
Sorry, @lkishalmi missed the 12.5 in there.  So, yes, @paratechnical please upgrade to 12.6, or try out a 13 rc.

However, I have noticed a similar issue on 12.6 with projects with an older wrapper and JDK 17.
