### ISSUE TITLE
Startup Warnings 

### ISSUE THREAD

**Issue by ozziej** [apache/netbeans#3519]
### Apache NetBeans version

Latest release candidate

### What happened

Following warnings on startup:
WARNING: package sun.awt.X11 not in java.desktop
WARNING: package com.sun.java.swing.plaf.gtk not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/Users/james/Downloads/netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release

### How to reproduce

Startup from RC-2 binary on Mac OS X
./Downloads/netbeans/bin/netbeans

### Did this work correctly in an earlier version?

- [X] This used to work!

### Operating System

Mac OS X Monterey 12.1 Apple ARM silicon.

### JDK

Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Happens on each startup.

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment]
Thanks for the report.  This is just a warning added in JDK 17.  Can be ignored for now.  There is work going on already to address changes for future JDKs. eg. #3386
