### ISSUE TITLE
Netbeans the installation failed MacOS monterrey 

### ISSUE THREAD

**Issue by andresaaap** [apache/netbeans#3554]
### Apache NetBeans version

Latest release

### What happened

This is the error message: 
<img width="614" alt="Screen Shot 2022-02-03 at 2 53 01 PM" src="https://user-images.githubusercontent.com/12397217/152420085-173d8995-b8e4-4d55-b49c-bd382d7ed5ca.png">

the installation failed

### How to reproduce

This is the machine that I am using:
<img width="271" alt="Screen Shot 2022-02-03 at 3 04 36 PM" src="https://user-images.githubusercontent.com/12397217/152421214-a08d5a3b-f894-4ac0-aba7-8cdd58615093.png">

Steps to reproduce the problem:
1. Download the code from [here](https://dlcdn.apache.org/netbeans/netbeans-installers/12.6/Apache-NetBeans-12.6-bin-macosx.dmg).
2. Double click on the Apache-NetBeans-12.6-bin-macosx.dmg file
3. Follow the installation manager:
<img width="613" alt="Screen Shot 2022-02-03 at 3 07 25 PM" src="https://user-images.githubusercontent.com/12397217/152420700-e0104ffa-f2fc-4415-a77c-ec988a01c806.png">

<img width="606" alt="Screen Shot 2022-02-03 at 3 07 33 PM" src="https://user-images.githubusercontent.com/12397217/152420738-4af4a555-bc4c-455a-a2a8-08afef8c3e92.png">

<img width="602" alt="Screen Shot 2022-02-03 at 3 07 40 PM" src="https://user-images.githubusercontent.com/12397217/152420752-1f332e1e-55bc-46fe-886b-d365c91671c5.png">

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

MacOS monterrey 12.1

### JDK

openjdk version "11.0.14" 2022-01-18 LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by mcdonnell-john** [comment]
Hi @andresaaap,

Your screenshots with the error are from 12.2.  Can you confirm the error is with 12.6?

**Comment by andresaaap** [comment]
Hi @mcdonnell-john ,

Yes the problem is with 12.6. Sorry for the confusion, I also tried with 12.2 and I got the same problem. But when I looking in the apps screen I can see them and I can launch it. It works.

<img width="594" alt="Screen Shot 2022-02-03 at 3 26 43 PM" src="https://user-images.githubusercontent.com/12397217/152423624-c54d0816-2573-4704-ac0b-b246f96ee358.png">

It shows the error message, but it installs it. That is confusing

**Comment by mcdonnell-john** [comment]
Cool, I just wanted to be sure, as I know there was changing to the installer for Big Sur around 12.2/12.3 - so I wasn't sure if that might have been your issue.

Can you uninstall it, and then try installing it again and send a copy of the installer logs? (When installing Apache NetBeans 12.6 -   press `cmd + L` ) so we can see what might be happening during the installation process?

Thanks in advance

**Comment by andresaaap** [comment]
Sure let me do that I and will let you know
