### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by JeremyCavanagh** [apache/netbeans#3565]
### Apache NetBeans version

Latest release candidate

### What happened

Reformatting NB source code. Other than that I don't know exactly when the error occured, although it has appeared more than once

### How to reproduce

Sorry no idea

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

System: Mac OS X version 10.15.7 running on x86_64; UTF-8; en_GB (nb)

### JDK

 17.0.2; OpenJDK 64-Bit Server VM 17.0.2+8-LTS

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)
[messages.log](https://github.com/apache/netbeans/files/8016175/messages.log)

**Comment by Chris2011** [comment]
How to reproduce means exactly what did you do? Also formatting in which filetype? Java, XML, JS, PHP, CSS, etc. Please provice as much information as we need to figure out the problem. Also it would be good to attach the errornous file that you wanted to format. And did this happen while formatting on save or when exaclty?

**Comment by neilcsmith-net** [comment]
No response received after 14 days - closing.
