### ISSUE TITLE
Netbeans Language Server in VS Code - src/test/groovy classes not resolving classes from src/main/groovy

### ISSUE THREAD

**Issue by jamesdh** [apache/netbeans#3570]
### Apache NetBeans version

Latest release

### What happened

I apologize in advance if this isn't the correct place to report this.

I'm trying to get my Micronaut (groovy based) project working in VS Code using the GraalVM Extension Pack for Java, which relies on the Netbeans Language server. Oddly enough, VS Code is unable to resolve my main classes within my test code. However, any dependencies defined in build.gradle are resolved just fine. 

Despite VS Code saying the classes cannot be resolved, I'm able to run and debug the tests just fine from within VS Code. 

### How to reproduce

Using a simple Micronaut Groovy project, Add a class to `src/main/groovy`. Add a test class to `src/test/groovy` that references the main class. 

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

macOS 12.2

### JDK

OpenJDK 17.0.2 aarch64

### Apache NetBeans packaging

Apache VSNetBeans for VSCode

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by ppisl** [comment]
Hello, thanks for the report. I have already PR (https://github.com/apache/netbeans/pull/3802), that contains possible fix for this. I have tried a demo project generated from https://micronaut.io/launch/ on my branch and the project is withouth an error. I hope that the PR will be in master soon.

**Comment by jamesdh** [comment]
Fixed by #3802

**Comment by Wzhahai** [comment]
> ### 阿帕奇网豆版
> 最新版本
> 
> ### 发生了什么事
> 如果这不是报告此事的正确位置，我提前道歉。
> 
> 我正在尝试使用适用于 Java 的 GraalVM 扩展包（依赖于 Netbeans 语言服务器）让我的微纳特（基于时髦）项目在 VS 代码中工作。奇怪的是，VS Code无法在我的测试代码中解析我的主类。但是，在 build.gradle 中定义的任何依赖项都可以很好地解决。
> 
> 尽管 VS Code 说这些类无法解析，但我能够从 VS Code 中很好地运行和调试测试。
> 
> ### 如何重现
> 使用一个简单的微纳特 Groovy 项目，将类添加到 。向引用主类的测试类中添加一个测试类。`src/main/groovy``src/test/groovy`
> 
> ### 这在早期版本中是否正常工作？
> * [ ] 这曾经工作过！
> 
> ### 操作系统
> 苹果操作系统 12.2
> 
> ### 断续器
> 打开 JDK 17.0.2 aarch64
> 
> ### 阿帕奇网豆包装
> Apache VSNetBeans for VSCode
> 
> ### 别的东西
> _无响应_
> 
> ### 是否愿意提交拉取请求？
> * [ ] 是的，我愿意提交公关！
> 
> ### 行为准则
> * [x] 我同意遵守Apache软件基金会的[行为准则](https://www.apache.org/foundation/policies/conduct.html)
