### ISSUE TITLE
Html file cannot be parsed (has red flag)

### ISSUE THREAD

**Issue by mvorisek** [apache/netbeans#3571]
### Apache NetBeans version

Latest release

### What happened

The code snippet below from file named with `.html` suffix is not parsed even if the html is valid.

### How to reproduce

```
<div class="{_ui}ui{/} {$class} {_class}{/}" id="{$_id}" style="{$style}">{$Content}</div>
```

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

any

### JDK

any

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment]
You problem is not the HTML, but the broken CSS. `{$style}` is not valid CSS and that is what NetBeans marks as error. As there are also warnings on the lines, it is not obvious. You can make it easier to spot if you break the element onto multiple lines (one per attribute).

The error indicators allow you to disable CSS validation and then you should be happier.

**Comment by Chris2011** [comment]
hey @mvorisek is this somehow a templating engine that you use? Is it handlebars or what is it?

**Comment by mvorisek** [comment]
> hey @mvorisek is this somehow a templating engine that you use? Is it handlebars or what is it?

Hey Chris, thank you for follow up.

See https://github.com/atk4/ui/tree/3.1.0/template , we use `{$class}` and `{_class}{/}` in our templating engine https://github.com/atk4/ui/blob/3.1.0/src/HtmlTemplate.php#L491 .

The issue we have is that when we use such templating, the files are marked red in the whole project tree which disctracts every developer who uses Netbeans.

As the tags we use do not violate the html grammar (as pointed by Matthias above, only the style/CSS grammar is incorrect), I belive such html templates should be parsed successfully and the minor issues should be a line warnings instead, so the file itself is not marked red.

**Comment by matthiasblaesing** [comment]
As said: You can turn off CSS checking. (for a file, or a whole directory tree). But disabling in directly will yield a bug with a text: "Hey! This is an IDE why don't you even get basic syntax checking right?!!!!1". For you it is a minor details, for others it is just broken.

The Web decided not to go down the well defined way. With XHTML I have some ideas how you could sanely define a template language, but with the maschup that is HTML today, you have to guess. In the end the IDE would need  a crystal ball to decide, whether the author made a syntax error or if it is a template. I saw authors write curly braces into style attributes and they thought they used correct syntax, so no curly braces are not an indicator for the begin of a template.

There are other things in the HTML code, that could be better fixed, that this case, where two usescases (normal HTML editing vs. templating) collide hard.

**Comment by Chris2011** [comment]
So I checked VS Code and WebStorm and both also shows this as errors. As Matthias said, I also think, this is ok. If the toolkit, that you use have a language service like the Angular Language Service, that there could be a better solution to parse the file and and and but I guess that this is not available.

What WebStorm does is just a better error label for each error:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/795658/153730703-5aabf64b-31f4-413e-878b-19fb83c705b0.png">

With this errors I can understand the error better. NetBeans just show smth from the original parser which is not very friendly if I have no clue about tokens, parser, etc. But this is a whole other topic and not related to this here. It was just an information.
