### ISSUE TITLE
JS file cannot be parsed (has red flag)

### ISSUE THREAD

**Issue by mvorisek** [apache/netbeans#3572]
### Apache NetBeans version

Latest release

### What happened

The following two files:

- https://github.com/atk4/ui/blob/3.1.0/js/src/services/api.service.js
- https://github.com/atk4/ui/blob/3.1.0/js/src/services/vue.service.js

are marked red in Netbeans with error:

![image](https://user-images.githubusercontent.com/2228672/153043390-5b38cc1f-b61b-49ed-94ba-91719964f5c8.png)

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

any

### JDK

any

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment]
I could reproduce the problem for the `vue.service.js` file. The issue is here the usage of an async import statement. This was added in ecmascript ECMAScript 11 - 2020 and the parser did not support that. I'm currently trying to add ecmascript 2022 support to the graaljs fork  we are using and the JS modules in NetBeans.

**Comment by Chris2011** [comment]
I can also reproduce it on the api.service.js. Is looked like an error in the file but when I open the Action Items to see what errors NetBeans shows me, it is this strange error: 

`Error | class com.oracle.js.parser.ParserContextModuleNode cannot be cast to class com.oracle.js.parser.Pars |`

**Comment by matthiasblaesing** [comment]
@Chris2011 could you please provide the full text - it should be available in the IDE log.

**Comment by Chris2011** [comment]
Hey @matthiasblaesing unfortunately, it is not shown in the IDE log. I restarted NetBeans too to check whether I accidentally removed it but no. It just shows in the Actions Items and not in the notifications. Maybe running the master of NetBeans in debug mode and if NetBeans can handle this "pause on exception" that can help here.

**Comment by matthiasblaesing** [comment]
I got it now and needed to use the debugger to get the full message. The issue can only be hit when javascript module parsing takes place. I think I have that solved.

**Comment by matthiasblaesing** [comment]
So here is the promised PR: #3599. A test build can be downloaded here:

https://doppel-helix.eu/NetBeans-dev-dev-79e64bdff77d180b79ae712d060c9365e8118c96-release.zip

The testbuild is a merge of #3599, #3583 and #3597.
