### ISSUE TITLE
"Save Password" breaks Git authentication since 12.5

### ISSUE THREAD

**Issue by gitdode** [apache/netbeans#3579]
### Apache NetBeans version

Latest release

### What happened

With NetBeans 12.4 I could save the password for remote Git repos without problems.
With 12.5+ authentication fails when leaving "Save Password" checked and succeeds when it is unchecked.
Commandline Git works fine, I have `git config credential.helper` set to `store`.

I am not sure, but NetBeans 12.4 seems to have been using KWalletManager to store the passwords and that doesn't seem to work any more with NetBeans 12.5+.

### How to reproduce

Since this is probably related to KWalletManager, this may only be reproducible on KDE/Plasma desktops.

1. Try to Git -> Remote -> Pull from Upstream an existing project that worked with 12.4
2. "Specify Git repository location" dialog appears
3. Check "Save Password" and enter the (correct) password
    Result: "Specify Git repository location" dialog appears again
4. Uncheck "Save Password" and enter the (correct) password
    Result: pull succeeds

### Did this work correctly in an earlier version?

- [X] This used to work!

### Operating System

Kubuntu 20.04 LTS

### JDK

openjdk version "11.0.13" 2021-10-19

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment]
Please check the messages.log in `$HOME/.netbeans/dev/var/log/messages.log`. I remember, that a new provider for libsecret was introduced maybe there is some interaction, but even then it does not explain why it does not work when  you enter the password.

**Comment by gitdode** [comment]
Thanks for the hint to look in `messages.log`, it revealed this warning:

`WARNING [org.netbeans.modules.keyring.gnome.libsecret.GnomeLibSecretProvider]: 133/2: The name org.freedesktop.secrets was not provided by any .service files`

After installing `gnome-keyring`, "Save Password" works. So I guess that the previous libsecret provider used `kwallet` when `gnome-keyring` was not installed while the new one lets authentication fail when "Save Password" is checked.

**Comment by matthiasblaesing** [comment]
Ok - so the checks in `GnomeLibSecretProvider` should be redone. If the library can't work, because there is no provider it should yield and in the worst case fall back to the build-in provider.

**Comment by matthiasblaesing** [comment]
@gitdode could you test this build: doppel-helix.eu/doppel-helix.eu/NetBeans-dev-dev-95d19747200936da808116322d7b6b677e6a534d-release.zip

It should improve the situation in that regard, that the build should automatically detect, that libsecret can't be used on your system. I reproduced your problem (rename gnome-keyring, kill the running instance), but it would be great if you could give it a try.

**Comment by gitdode** [comment]
Great, it works fine, with uninstalled gnome-keyring

**Comment by matthiasblaesing** [comment]
@gitdode thanks for the check!

**Comment by gitdode** [comment]
@matthiasblaesing thanks for the quick solution!

**Comment by javierllorente** [comment]
> @gitdode could you test this build: https://doppel-helix.eu/NetBeans-dev-dev-95d19747200936da808116322d7b6b677e6a534d-release.zip
> 
> It should improve the situation in that regard, that the build should automatically detect, that libsecret can't be used on your system. I reproduced your problem (rename gnome-keyring, kill the running instance), but it would be great if you could give it a try.

I have tested this build on openSUSE 15.3 and I can also say that passwords are saved (ie: proxy password) without having to install gnome-keyring.
Thanks Matthias!
