### ISSUE TITLE
My Project not visible in projects pallate

### ISSUE THREAD

**Issue by deepak032002** [apache/netbeans#3582]
### Apache NetBeans version

Latest release

### What happened

When I creat new project it runs properly but after shutdown my system and again when my system start and I fire netbeans it not show my previous project.
when i try to open project it does not open whole project pallet empty show and message visible **_no project open_** .
please give me solution.

![image](https://user-images.githubusercontent.com/86599613/153196323-704effe2-349b-4bde-a144-8a9f8f103247.png)

### Did this work correctly in an earlier version?

- [X] This used to work!

### Operating System

Window 11

### JDK

jdk 15

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment]
Please fill in the _How to reproduce_ section as well as sharing the error / stacktrace.  What type of project?

Also try with NetBeans 13-rc3 - https://lists.apache.org/thread/5rkzr20z5n67j1jtzk0y76px5y6covmp

Is this related to https://issues.apache.org/jira/browse/NETBEANS-6117 ?

**Comment by HappierGore** [comment]
I had the same problem.
It was working well. My PC turned off because of electrical problem in my house. When I started Apache again, The project view wasn't showing my project. I tried reinstalling this again but it didn't work.

[UI LOG.txt](https://github.com/apache/netbeans/files/8112963/UI.LOG.txt)
[IDE_LOG.txt](https://github.com/apache/netbeans/files/8112964/IDE_LOG.txt)

**Comment by neilcsmith-net** [comment]
@HappierGore you seem to have a lot of pre-Apache modules installed there?  Does this replicate with a clean Apache NetBeans install?
