### ISSUE TITLE
Inconsistent font width when using variable monospace font (e.g.: Cascadia Code)

### ISSUE THREAD

**Issue by ExE-Boss** [apache/netbeans#3587]
### Apache NetBeans version

Latest release

### What happened

When using a monospaced variable font (such as [**Cascadia Code**](https://github.com/microsoft/cascadia-code)), bold characters are incorrectly wider in **NetBeans**.

### How to reproduce

1. Install [**Cascadia Mono**/**Cascadia Code**](https://github.com/microsoft/cascadia-code)
2. Compare the width of regular, bold, italic, and bold+italic text when using the variable font version to the width of said text when using the static version of **Cascadia Code**.

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Windows 10

### JDK

OpenJDK Runtime Environment [Temurin](https://adoptium.net/)-17.0.1+12 (build 17.0.1+12)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment]
No reply in in 3 weeks.
