### ISSUE TITLE
Sealed type hierarchy not shown in javadoc window

### ISSUE THREAD

**Issue by BlueGoliath** [apache/netbeans#3588]
### Apache NetBeans version

Latest release candidate

### What happened

When viewing the javadoc of a sealed class, any information about the sealed type hierarchy is missing. This can result in Netbeans suggesting to use a method that returns a compatible type but no indication that a child type extends the desired type.

### How to reproduce

SealedTest test = SealedTest2.get();

package org.goliath.crosspoint.test;

public sealed class SealedTest permits SealedTest2
{
    
}

package org.goliath.crosspoint.test;

public final class SealedTest2 extends SealedTest
{
    public static SealedTest2 get()
    {
        return new SealedTest2();
    }
}

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Arch Linux

### JDK

JDK 19, 86-64

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment]
JDK 19? Please see if you can replicate with JDK 17, and try uninstalling nbjavac.

**Comment by neilcsmith-net** [comment]
No follow up - closing.
