### ISSUE TITLE
Possible NPE on Gradle SubProjectsNode

### ISSUE THREAD

**Issue by lkishalmi** [apache/netbeans#3590]
### Apache NetBeans version

Latest release candidate

### What happened

Got an NPE after loading the NetBeans Gradle Project.

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Ubuntu

### JDK

JDK17

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment]
@lkishalmi you don't need to open an issue if there's a PR already - keeps the signal-to-noise ratio down a bit. And if you're a committer, you can remove the `needs:triage` yourself and/or open a ticket via the meta form too.

**Comment by lkishalmi** [comment]
Thank you @neilcsmith-net !
