### ISSUE TITLE
SVN lock failed

### ISSUE THREAD

**Issue by vladislavgolubev** [apache/netbeans#3592]
### Apache NetBeans version

Latest release

### What happened

Tortoisesvn installed with command line tools.
From Netbeans Commit/Update works correctly.
But lock thow error:

java.lang.UnsupportedOperationException: Not supported with commandline client.

I test in cmd: svn lock "path" - works correctly.

### How to reproduce

Install Netbeans 12.6
Install TortoiseSVN 1.14
Try lock files from Netbeans.

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Windows 11

### JDK

JDK 1.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by lkishalmi** [comment]
Well, try to get the java bindings to work. You may need to re-run the Tortoise SVN installer and select the JavaHL or something like that to be installed. (I do not have Windows.) Version 14 is supported by NetBeans 13 (which is in RC phase)

**Comment by vladislavgolubev** [comment]
I reinstalled TortoiseSVN - did not help.
I installed NetBeans 13 -  did not help.

In Options > Team > Versioning > Subversion  > Preferred clien set to CLI. 

I installed SlickSVN with javaHL support. Changed Preferred client to JavaHL, changed path to client, click apply - preferred client returned to CLI. Why I can't change preferred client?

**Comment by vladislavgolubev** [comment]
Restarted IDE - client changed successfully

**Comment by matthiasblaesing** [comment]
Great the this is fixed for you.

**Comment by Findulas** [comment]
Are you sure it changed to JavaHL? For me it switches back to CLI on restart.

**Comment by vladislavgolubev** [comment]
> Are you sure it changed to JavaHL? For me it switches back to CLI on restart.

Yes. Are you install SlickSVN with javaHL support? Try change client with change path to "C:\Program Files\SlikSvn\bin\" (see your own path), click apply and restart IDE

**Comment by Findulas** [comment]
I use the SlikSVN installation via scoop. The content of the bin directory has changes in the names of the libs, f.e. SlikSvn-libsvn_client-1.dll is named SlikSvn-svn_client-1.dll in the AdapterFactory (https://github.com/apache/netbeans/blob/master/ide/libs.svnClientAdapter.javahl/src/org/netbeans/libs/svnclientadapter/javahl/JavaHlClientAdapterFactory.java).

Below ist the content of my SlikSVN-bin-Directory. Does yours contain the same files?

d----          10.03.2022    10:07                engines
d----          10.03.2022    10:07                System64
-a---          07.05.2021    15:54         651776 libsvnjavahl-1.dll
-a---          07.05.2021    15:39         894976 SlikSvn-DB44-20-x64.dll
-a---          07.05.2021    15:40         208896 SlikSvn-libapr-1.dll
-a---          07.05.2021    15:48         287232 SlikSvn-libaprutil-1.dll
-a---          07.05.2021    15:47        3412480 SlikSvn-libcrypto-1_1-x64.dll
-a---          07.05.2021    15:48          61952 SlikSvn-libintl.dll
-a---          07.05.2021    15:49         205824 SlikSvn-libsasl21.dll
-a---          07.05.2021    15:47         673792 SlikSvn-libssl-1_1-x64.dll
-a---          07.05.2021    15:51         708096 SlikSvn-libsvn_client-1.dll
-a---          07.05.2021    15:50         148992 SlikSvn-libsvn_delta-1.dll
-a---          07.05.2021    15:50         112640 SlikSvn-libsvn_diff-1.dll
-a---          07.05.2021    15:50         221696 SlikSvn-libsvn_fs_base-1.dll
-a---          07.05.2021    15:50         398336 SlikSvn-libsvn_fs_fs-1.dll
-a---          07.05.2021    15:50          28672 SlikSvn-libsvn_fs_util-1.dll
-a---          07.05.2021    15:50         386048 SlikSvn-libsvn_fs_x-1.dll
-a---          07.05.2021    15:50          67584 SlikSvn-libsvn_fs-1.dll
-a---          07.05.2021    15:51         540160 SlikSvn-libsvn_ra-1.dll
-a---          07.05.2021    15:51         286720 SlikSvn-libsvn_repos-1.dll
-a---          07.05.2021    15:50        2122240 SlikSvn-libsvn_subr-1.dll
-a---          07.05.2021    15:51         877056 SlikSvn-libsvn_wc-1.dll
-a---          07.05.2021    15:52          26112 svn-populate-node-origins-index.exe
-a---          07.05.2021    15:51         450048 svn.exe
-a---          07.05.2021    15:52         136192 svnadmin.exe
-a---          07.05.2021    15:52          43008 svnauthz-validate.exe
-a---          07.05.2021    15:52          43008 svnauthz.exe
-a---          07.05.2021    15:52          78336 svnbench.exe
-a---          07.05.2021    15:52          50176 svndumpfilter.exe
-a---          07.05.2021    15:52          57344 svnfsfs.exe
-a---          07.05.2021    15:52          96256 svnlook.exe
-a---          07.05.2021    15:52          40960 svnmucc.exe
-a---          07.05.2021    15:52          64512 svnrdump.exe
-a---          07.05.2021    15:52         242176 svnserve.exe
-a---          07.05.2021    15:52          74752 svnsync.exe
-a---          07.05.2021    15:52          28672 svnversion.exe

**Comment by Findulas** [comment]
You need to have the **bin-folder in the path**, then it works. Could Netbeans add the given path during startup?

**Comment by vladislavgolubev** [comment]
libsvnjavahl-1.dll - only this file is matter

**Comment by vladislavgolubev** [comment]
during installation SlickSVN I set option something like "set PATH variable"

**Comment by Findulas** [comment]
> during installation SlickSVN I set option something like "set PATH variable"

Yes, this is important. It would be fine, if this could be done by NetBeans based on option set.
