### ISSUE TITLE
Gradle Multi-Projects don't get initial wrappers/build scripts

### ISSUE THREAD

**Issue by wiegleyj** [apache/netbeans#3596]
### Apache NetBeans version

Latest release

### What happened

Creation of gradle multi-projects doesn't generate wrapper/build scripts and leaves you with an unbuildable project.

### How to reproduce

Create a gradle multi-project with a single subproject. create a main hello world. try to compile. No build script. I'm guessing no wrapper either.

I'd be happy to work without multi-project and just use a "Java Application: Creates a simple Java SE application Gradle project." except it also creates a complex multi-project now.

gradle support is not present in a meaningful way. If you're a gradle-wizard at command line usage of gradle I guess you could find a work around. I am not such a wizard and Netbeans certainly reminds me of that daily.

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Windows 11

### JDK

java 17.0.2 2022-01-18 LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by lkishalmi** [comment]
I cannot reproduce this one either on 13-rc4, however #3480 could fixed this issue since 12.6
