### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by PavelStrejcek** [apache/netbeans#3614]
### Description

Hello

It would be great if Netbeans supported the new PHP 8.1 syntax and features. 

https://www.php.net/releases/8.1/en.php

For example enumerations and readonly properties.

### Use case/motivation

PHP enumerations are invalid in NetBeans.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by KacerCZ** [comment]
PHP 8.1 support is already tracked at https://issues.apache.org/jira/browse/NETBEANS-5599
Part of it is already implemented and will be included in upcoming NetBeans 13.

**Comment by PavelStrejcek** [comment]
There is already something in version 13, but enum support is missing.
