### ISSUE TITLE
NoClassDef Found Error

### ISSUE THREAD

**Issue by maich123** [apache/netbeans#3616]
### Apache NetBeans version

Latest release

### What happened

NoClassDef Found Error

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

windows

### JDK

JDK 17.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

everytime 

### Are you willing to submit a pull request?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment]
There is no error reported.

**Comment by matthiasblaesing** [comment]
If you want help, please provide more information. We don't own crystal balls to "know" what you did. Provide detailed step how to recreate your problem, what you saw and what you expected.
