### ISSUE TITLE
Netbeans 12 "diff window" does not always highlight added or removed spaces in the code

### ISSUE THREAD

**Issue by Eugene-Melbourne** [apache/netbeans#3650]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

I upgraded Netbenas 8 to Netbeans 12 and now my `diff window` does not always highlight added or removed spaces in the code.

It does highlight if spaces was added or removed in the middle of the line (after a non space character), and before a non space character.

But it does not highlight when the space was added or removed form the beginning of the line, or at the end of the line. Preceding and trailing spaces change does not get highlighted.

### How to reproduce

Opend Diff window, no matter what you compare.
Bug is there if you compare 2 different files, or if you compare 2 revisions of your file (I use GIT)

Tested on the Product Version: Apache NetBeans IDE 12.6

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windowns 10

### JDK

Java: 10.0.1; Java HotSpot(TM) 64-Bit Server VM 10.0.1+10

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

How often does this problem occur? - Every time.
Any relevant logs to include? - No 

It is working correctly on :
Product Version: NetBeans IDE Dev (Build 201804200002)
Java: 1.8.0_101; Java HotSpot(TM) 64-Bit Server VM 25.101-b13

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
This is a feature, not a bug. You can configure the behavior of the diff view:

![image](https://user-images.githubusercontent.com/2179736/155018847-5d61a189-c33f-4ea3-9a3c-47f26dfba1f4.png)

Just change the option and you are done.

**Comment by Eugene-Melbourne** [comment]
Thank you very much
