### ISSUE TITLE
PHP code formatting (ctrl+shift-f)

### ISSUE THREAD

**Issue by Eugene-Melbourne** [apache/netbeans#3652]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

I use PHP, it is very popular this days to use chaining like that

> $productPriceValidator
> &nbsp;&nbsp;&nbsp;&nbsp;->setProductPrice($price)
> &nbsp;&nbsp;&nbsp;&nbsp;->validate();

It should be formatted like in example above, and it was formatted this way  in Product Version: NetBeans IDE Dev (Build 201804200002)

But in new NetBeans Product Version: Apache NetBeans IDE 12.6.
The code formatter making every second line starts with the position of the initial line in the chain like this:

> $productPriceValidator
> ->setProductPrice($price)
> ->validate();

Which is not correct and not helping in making the code readable.

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windowns 10

### JDK

Java: 10.0.1; Java HotSpot(TM) 64-Bit Server VM 10.0.1+10

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Please check your formatting settings under Language PHP > Tabs And Indents > Continuation Indentation. If I set Continuation Indentation to 0 then I get the same format as you report.
It can be in global NetBeans settings or in project specific settings.

**Comment by Eugene-Melbourne** [comment]
Thank you for fixing it
