### ISSUE TITLE
Code hint not work to jakarta EE beans

### ISSUE THREAD

**Issue by deibidsonmesquita** [apache/netbeans#3659]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

When creating a jakarta EE 9 project the code suggestion does not work for the Beans inside the xhtml file.
Works on jakarta EE 8 project

### How to reproduce

1 - Create a project using jakarta EE 9 or higher.

2 - Create a Bean and try to use it using the Netbeans code suggestion in an xhtml page.

No suggestions

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

11

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by asbachb** [comment]
Should be fixed with: https://github.com/apache/netbeans/pull/6096

**Comment by asbachb** [comment]
Fixed in #6160
