### ISSUE TITLE
Gradle Compile a file in buildSrc folder fails with a NullPointer

### ISSUE THREAD

**Issue by maerevoet-wim** [apache/netbeans#3662]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

If you open a Custom Build Logic project and try to compile a file you get an NullPointerException

	at org.netbeans.modules.gradle.spi.GradleFiles.searchPropertyFiles(GradleFiles.java:108)
	at org.netbeans.modules.gradle.spi.GradleFiles.getPropertyFiles(GradleFiles.java:179)

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

Java 11 AdoptOpenjdk

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Removing triage label - discussion can happen in #3663

**Comment by mbien** [comment]
@lkishalmi is this fixed via #3795? If yes, please link and close.

**Comment by lkishalmi** [comment]
Yes, shall be resolved by #3795.
