### ISSUE TITLE
Can't type in output panel on NetBeans

### ISSUE THREAD

**Issue by aerielkrishia** [apache/netbeans#3682]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

I used import java.util.Scanner to make a project for my school but I can't type on the output panel
![image](https://user-images.githubusercontent.com/90703249/156290536-de2969b6-8c98-433b-a3a9-4756fa0f282a.png)

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

jdk-17.0.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Code of Conduct

Yes

**Comment by mbien** [comment]
seems to be working fine for me (tested with a NB 13 build), e.g:
```java
        try (Scanner scanner = new Scanner(System.in)) {
            System.out.println("you typed: "+scanner.next());
        }
```
works as expected.

Could be still a windows specific issue. Would be nice if someone could verify it on windows.

**Comment by neilcsmith-net** [comment]
Which build system?  And please try with 13.  I wonder if it's the same as https://lists.apache.org/thread/0jhgnn72w7lhcrnjmjv167lctf42qxd2 ?

**Comment by mbien** [comment]
> Which build system? And please try with 13. I wonder if it's the same as https://lists.apache.org/thread/0jhgnn72w7lhcrnjmjv167lctf42qxd2 ?

good catch. This might be fixed in 13 then since it bundles a newer maven release.

@aerielkrishia could you try again with NetBeans 13 and see if it is working?

**Comment by ebresie** [comment]
With NB13 in Windows with the above example scanner code from @mbien , it worked for me.

**Comment by mbien** [comment]
thanks for testing (helps to exclude that it is windows specific). 

Everything indicates that it is a problem with a specific version of maven as @neilcsmith-net pointed out. NB 13 ships with a newer version which does not have this problem.

The maven distribution used by default can be also changed in the settings to anything you want (even mvnd since NB 13). Closing this issue.
