### ISSUE TITLE
Netbeans 12.5/12.6 not working with CVS

### ISSUE THREAD

**Issue by reke175** [apache/netbeans#3684]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

Unable to use the cvs Server with Netbeans

### How to reproduce

checkout get a error

### Did this work correctly in an earlier version?

Apache NetBeans 12.4

### Operating System

Debian testing

### JDK

JDK 1.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Code of Conduct

Yes

**Comment by mbien** [comment]
I am pretty sure CVS is no longer supported

**Comment by matthiasblaesing** [comment]
As there is no CVS module in NetBeans, this must be an external module. If that is the case, this is not supported.
