### ISSUE TITLE
Netbeans fails to use specific Gradle version

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#3687]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

* I have cleaned-up old gradle files and caches
  *  In particular: `rm -rf  ~/.gradle/wrapper/dists/gradle-7.3-bin`
* Start netbeans with an open project
   * This project must be build with gradle v4.10.2
   * It will fail otherwise.
* I set specific gradle version as shown to 4.10.2
   ![image](https://user-images.githubusercontent.com/67028/156486383-bd758c38-7113-4b99-b090-3f952ff51368.png)
* Press the apply button
* Gradle poroject fails to load with the message shown in the screen shot

### How to reproduce

* I imagine set-up a small hello world gradle project with gradle 4.10.2
* Ensure gradlew uses 4.10.2
* try to use Netbeans
* If it does not reproduce the bug, you could tell netbeans to use gradle 7.3
* Try it out to build
* Change back to insist on Gradle 4.10.2

### Did this work correctly in an earlier version?

Apache NetBeans 12.4

### Operating System

Ubuntu 20.04.4 LTS Release:	20.04

### JDK

Java: 17.0.1; building with Java 1.8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

* Attached IDE log output
  * zip file:  [netbeans-12.6-IDEA.log.zip](https://github.com/apache/netbeans/files/8174586/netbeans-12.6-IDEA.log.zip)
 

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
I think you are seeing this one: https://issues.apache.org/jira/browse/NETBEANS-6004

Basically the JDK running the IDE is too high for the Gradle version that you are trying to use.

In NetBeans 13 it has been addressed by giving more information. See: #3320

**Comment by aplatypus** [comment]
* Not the same issue
* We are using gradlew and the version to use is command driver
* The IDE ought not change or override that
