### ISSUE TITLE
newer ssh keys not accepted for remote synchronization

### ISSUE THREAD

**Issue by mokraemer** [apache/netbeans#3691]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

at the moment only keys in legacy PEM private key format are accepted.
(not tested if newer type ed25519 works - I was glad get it to work)

### How to reproduce

just use ssh-keygen on a recent linux system, and get a RFC4716 compliant key
Try to add synchronisation to remote host (maybe a php-setting)

### Did this work correctly in an earlier version?

No

### Operating System

linux

### JDK

OpenJDK Runtime Environment 18.9 (build 11.0.13+8-LTS)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

it is not easy to understand you have to convert an existing key.

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
@mokraemer Could you please change/testbuild from #3700?

**Comment by mokraemer** [comment]
I can confirm test build fixes this issue.
