### ISSUE TITLE
class file for java.lang.annotation.Annotation not found

### ISSUE THREAD

**Issue by Polve** [apache/netbeans#3695]
### Apache NetBeans version

Apache NetBeans 13 release candidate

### What happened

I just updated netbeans to the latest version (13), and migrated my configuration from netbeans 12.6 that I was previously using.

I opened a file of my project and received this error:

Annotation: An error occurred during parsing of 'xxx.java'.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.annotation.Annotation not found

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Ubuntu Linux

### JDK

openjdk-17-jdk 17.0.1+12-1~21.10

### Apache NetBeans packaging

Apache NetBeans provided installer

### Code of Conduct

Yes

**Comment by Polve** [comment]
btw, the template does not list "netbeans 13" as available NetBeans version

**Comment by matthiasblaesing** [comment]
Please provide a minimal, reproduceable sample of the problem, else it won't be possible to help you.

**Comment by mbien** [comment]
> btw, the template does not list "netbeans 13" as available NetBeans version

thanks. update pending https://github.com/apache/netbeans/pull/3703

**Comment by Polve** [comment]
The problem seems related to a wrong detection of java install in my system (standard ubuntu linux with open jdk 17)

After reinstallation and manual selection of the JDK to use everything seems fine.

So maybe that's a bug in the installer?
Are you interested in more details?
