### ISSUE TITLE
NetBeans installer does not detect OpenJDK

### ISSUE THREAD

**Issue by j-pro-git** [apache/netbeans#3698]
### Apache NetBeans version

Apache NetBeans 13 release candidate

### What happened

I intended to upgrade from Netbeans 12 to Netbeans 13. I downloaded the installer and started it. It immediately failed with the following error message:
![grafik](https://user-images.githubusercontent.com/77408703/156852902-1b7c52d0-ca0e-47f8-926f-9c9925298672.png)

I expected that the installer would detect OpenJDK. Alternatively, I expected some settings where I could enter the JDK branch.

### How to reproduce

Download and install OpenJDK and NetBeans 12.0. Check that it works properly. Then use the installer to install NetBeans 13.0. The installer fails as described above. 

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10 version 10.0 running on amd64; Cp1252; de_DE (nb)

### JDK

Java: 14.0.2; OpenJDK 64-Bit Server VM 14.0.2+12-46 Runtime: OpenJDK Runtime Environment 14.0.2+12-46

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Also occurs with NetBeans 12.6 installer 

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
It's likely you don't have a suitable environment variable or registry key pointing to a JDK. Although I'm not sure why you're having different result with NetBeans 12.0.

You can try running the installer from the CLI passing `--javahome <JDK>`.  Or you could try a third-party installer with bundled runtime - eg. https://www.codelerity.com/netbeans/

**Comment by neilcsmith-net** [comment]
No response - closing.

**Comment by j-pro-git** [comment]
Just for the record: Running the installer from the terminal and appending `--javahome %JAVA_HOME%` solved it.
