### ISSUE TITLE
Outdated Jcraft JSCH Library Causes Incorrect Credentials For Remote Git Repository

### ISSUE THREAD

**Issue by Ojambo** [apache/netbeans#3700]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

Originally reported on 2021-09-27 here https://issues.apache.org/jira/browse/NETBEANS-6067

I am running Fedora 35 and NetBeans 12.6 and just upgraded to 13.  I get incorrect credentials when I attempt a git push.  It works fine on the command line so I can up with a workaround until this issue is resolved.  A quick alternative for Netbeans is to use a fork of JSch-01.55 here [https://github.com/mwiede/jsch ](https://github.com/mwiede/jsch)that is actually updated allowing modern encryption algorithms.

**Workaround**:
Perform a commit using the GUI in NetBeans then on the command line run "git push" in the folder containing your project and/or local git repository.

**Problems**:
- JSch only supports weak ssh-rsa which is disabled by default in OpenSSH 8.8
- JSch has not been updated since 2018 according to SourceForce 
- Problematic key headers due to OpenSSH 7.8 or newer having  "----BEGIN OPENSSH PRIVATE KEY---" instead of "---BEGIN RSA PRIVATE KEY----"
- Replacing the official JSch JAR file with the one by mwiede did not work for me, looks like NetBeans hard-coded something in their version of EGit.

**References**:
1. Matez Blog the future of jsch without ssh-rsa https://www.matez.de/index.php/2020/06/22/the-future-of-jsch-without-ssh-rsa
2. Bug 520927: moving away from JSch https://www.eclipse.org/lists/jgit-dev/msg03696.html
3. Gerrit 3.4.0 Disables JCraft JSch client library by default https://www.gerritcodereview.com/3.4.html
4. JSch Last SourceForge Update https://sourceforge.net/projects/jsch/files/jsch/
5. Invalid Private Key When Using JSch https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch

### How to reproduce

Git push will result in incorrect credentials in Netbeans if using recent versions of OpenSSH on the remote server or stronger encryption methods.

### Did this work correctly in an earlier version?

No

### Operating System

Locally Linux Fedora 35: Remotely Debian 11, and CentOS 7.9

### JDK

OpenJDK 11.0.14.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This occurs for every GIT Push.
I also tried locally it without port numbers from a laptop to the work station both running Fedora 35.
The cause is that the jcraft JSCH library is old.  Google already moved away from it and Eclipse is in the process of replacing it

I have attached a message.log file after removing the original remote repository.

[username_netbeans_13_var_log_messages.log](https://github.com/apache/netbeans/files/8189338/username_netbeans_13_var_log_messages.log)
.

### Code of Conduct

Yes

**Comment by mbien** [comment]
@Ojambo thank you for the detailed report.

I personally prefer to use the shell for most git tasks so I never noticed. I put NB 14 milestone on this issue since i think we should try to fix this if there is time/interest.

**Comment by matthiasblaesing** [comment]
I created a pull request and here is a test build:

https://doppel-helix.eu/NetBeans-dev-dev-ff00b6542e7a8c5e8fa39a0d8f0df663b7061e0f-release.zip

I tested ecdsa and ed25519 keys on linux. Support for SSH Agents was only tested with an rsa key on Windows and Linux (PAgent and SSHAgent). The ssh bundle was marked to depend on:

- JNA (Integration of PAgent)
- JUnixsocket (Integration of SSHAgent)
- Bouncy Castle (Support for more exotic Keys on not so new JDKs)

The updated SSH library integrates support for agent integration, so the dedicated NetBeans modules was removed.

**Comment by Ojambo** [comment]
I tested the DEV version and was able to successfully perform a GIT push in the IDE. 
The fix should also take care of Issue newer ssh keys not accepted for remote synchronization #3691 https://github.com/apache/netbeans/issues/3691

**Comment by norrisjeremy** [comment]
As on the caretakers of this newer JSch fork, please let me know if you have any questions about integrating it.

**Comment by q3769** [comment]
Hi, for the current 13 release, is there some jar files I could download and replace to make the GitHub push work? Thanks!

**Comment by mbien** [comment]
@q3769 the easiest way would be to simply use a RC build
https://www.mail-archive.com/dev@netbeans.apache.org/msg10693.html

**Comment by q3769** [comment]
> @q3769 the easiest way would be to simply use a RC build https://www.mail-archive.com/dev@netbeans.apache.org/msg10693.html

Thank you!

**Comment by MB2A** [comment]
this issue has resurfaced with  netbeans 29 
tested with ssh-rsa , ed25519, and ecdsa key for user. added the old ssh-rsa to the sshd_config.

catching debug on sshd :
`
Connection from 10.0.21.46 port 53820 on 10.205.44.133 port 2222 rdomain ""
debug1: Local version string SSH-2.0-OpenSSH_10.0p2 Debian-7
debug1: Remote protocol version 2.0, remote software version JSCH-0.1.72
debug1: compat_banner: no match: JSCH-0.1.72

`
