### ISSUE TITLE
Customized action entry added will automatically get disabled

### ISSUE THREAD

**Issue by rickqinj** [apache/netbeans#3701]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

Saying we are working on a Java maven project.
On the window of the project properties, users can add customized maven command(or action?) in the Action section. However, the customized entry gets automatically disabled once the entry is added into the list box located left side. User cannot edit the entry but only delete/remove it.
An alternative way to create a customized one is to go creating an entry by "Run maven -> Goals...". and configure it and check the "Remember as" checkbox after creation.

### How to reproduce

Win10 pro 64bit
Java 11.0.8
1. Right-click on the project name in the Project perspective and select "Properties";
2. Click on the "Actions" item, which is located on the Properties window's left side.
3. On the right side, click on the "Add custom..." button and then give it a name in the popped-up dialog, and then click OK.
4. You will see the entry just added is disabled and no way to activate it.

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Win10 pro 64bit

### JDK

Oracle JDK 11.0.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
This should be fixed in NetBeans 13. The corresponding PR is here: https://github.com/apache/netbeans/pull/3454

Please retest with it.
