### ISSUE TITLE
saved password of remote connections are not imported to new release

### ISSUE THREAD

**Issue by AlohaWebSolutions** [apache/netbeans#3702]
### Apache NetBeans version

Apache NetBeans 13 release candidate

### What happened

since version 12, after each update, saved passwords stored in properties of remote connections are cleared. 

### How to reproduce

i have many projects definitions for each customers, and each specific works. So i have record multiple remote connections for each server i use. And when i save a script file, it will be uploaded automatically on remote server.  
Actually, i have more than 10 remote connections server, and all the passwords crash after a minor or major update.
And i had try import/export configuration : same result !

Please solve this problem. 

### Did this work correctly in an earlier version?

No

### Operating System

linux ubuntu 20.04

### JDK

? 

### Apache NetBeans packaging

Other

### Anything else

netbeans from snap

### Code of Conduct

Yes

**Comment by mbien** [comment]
> and all the passwords crash after a minor or major update

what does this mean, what is the exception?

**Comment by AlohaWebSolutions** [comment]
no exception, no errors... after the update, i re-open netbeans, open my project, and when i open the project properties, and open remote connections, all the password are disappeared !!

**Comment by mbien** [comment]
ok, so nothing breaks, the passwords of the connections are just not imported to the next release?

**Comment by AlohaWebSolutions** [comment]
exactly ! but i have more than 10 passwords... and i don't to re-enter each time the software update !!!

**Comment by matthiasblaesing** [comment]
My suspicion is, that the identifier for the password entries contains the version number. People on a dev build will never notice, because it does not change there. I'll have a look at that.

**Comment by mbien** [comment]
@matthiasblaesing does the snap distribution use the same config migration mechanism as regular upgrades? (never used it)

**Comment by AlohaWebSolutions** [comment]
@matthiasblaesing : yes i think it is true. i just have discover that it has created a new folder ( for the new version ) in my home dir, subdir netbeans, like this :
/home/snap/netbeans/52 ( old version )
/home/snap/netbeans/58 ( new version )
/home/snap/netbeans/current ( link to 58 )
dir-52 and dir-58 have same subdirs...

what can i do to get back my passwords ?

**Comment by matthiasblaesing** [comment]
@AlohaWebSolutions NetBeans has multiple keyring implementations and it depends on the runtime enviroment which is used. At this time I would expect the libsecret based implementation, but that is speculation.

Please run NetBeans with the following command line argument: `-J-Dorg.netbeans.modules.keyring.level=FINE`. This enabled logging from the keyring provider and it will create a logging output like this:

```
FINE [org.netbeans.modules.keyring]: Using provider: org.netbeans.modules.keyring.gnome.libsecret.GnomeLibSecretProvider@63edd129
```

In the sample the `GnomeLibSecretProvider` is used. Please post the output here.

**Comment by matthiasblaesing** [comment]
@mbien I assume, that the snap distribution also makes the native keyrings available, thus I would expect behavior of ZIP distribution and snap to be identical.

**Comment by AlohaWebSolutions** [comment]
sorry, but where is the logfile ?
don't find anything like this...

**Comment by matthiasblaesing** [comment]
The logfile is placed into the configuration directory of NetBeans. On Linux the normal installation places the configuration in:

```
$HOME/.netbeans/$VERSION/var/log/messages.log
```

I don't know whether or not the snap distribution follows that convention.

**Comment by AlohaWebSolutions** [comment]
snap distribution respect the convention. Found the log file... but can't find the requested line...
i attach the complete log. Hope you will find and information in this flow !
thanks for your help.
[messages.log](https://github.com/apache/netbeans/files/8193076/messages.log)
!

**Comment by matthiasblaesing** [comment]
The option was picked up (see line 560). The big question: Did you start an operation, that needed the keyring? Accessing databases or running sync should do it.

**Comment by matthiasblaesing** [comment]
> not launch any operation except open/close project and save script ( with auto publish on FTP website )... so, what can i do ? What would do you want to say by "running should do it" ??

An operation in NetBeans, that uses the keyring will initialize it. At that moment the implementation will be logged. I gave two most common:

- accessing databases will nearly always trigger password access (file based database are partially special cased). For example when you connect to a MySQL or PostgreSQL you will be propted for a password and before that the keyring is queried.
- synchonising files in PHP projects will most probably invoke keyring, if it is not using SSH keys

> a question : if i rename old config dir (52) as the current (58), what's happen ?? Dangerous ?

In general it works, NetBeans will use the old config. BUT depending on the Keyring implementation it most probably won't bring back the passwords. Only the fallback implementation stores the files locally, everything else will use the native keyrings.

**Comment by AlohaWebSolutions** [comment]
Trying renaming config dir, but no changes... Really passwords of remote connection of FTP or SFTP server are lost !

Am very sorry, but this is a real handicap for working safely. I work on multiples projects for many customers, so on different apache host server, and it is not comfortable to re-enter all passwords each time Netbeans install an update ! 

It is the only tool since many years that i have this problem. Even Filezilla that updating soon had never loose any password.

so disappointed and sad. !

**Comment by matthiasblaesing** [comment]
@AlohaWebSolutions I described what needs to be done. I also said, that copying config won't help in most cases. If you are willing to take another approach. Assuming you are using default Ubuntu, your keyring will be the gnome one. So install the tool "seahorse". That tool allows you to browse the active keyrings. For my local setup it looks like this:

![image](https://user-images.githubusercontent.com/2179736/157286998-5a9f4c62-f42c-45e5-ad71-64a5215c1539.png)

The interesting part is the part before the hyphen. I suspect you'll find entries where the version number is part of the description.

**Comment by matthiasblaesing** [comment]
So as @AlohaWebSolutions did not reply, I tested myself and yes, the version number becomes part of the entry:

![image](https://user-images.githubusercontent.com/2179736/158578766-f02240fe-b79f-4575-8c7c-78ee0b357418.png)

compare first and third entry.

**Comment by AlohaWebSolutions** [comment]
i have see the results with seahorse... exact it depends on version of software... So i must re-enter all passwords after each update. I prefer that than change software ( free or paid ) because netbeans offer me the workspace that i need for my activity.
thanks for your help.

**Comment by matthiasblaesing** [comment]
With the change from #3869 the prefix will become constant:

![image](https://user-images.githubusercontent.com/2179736/160252565-8412103f-2ecd-4338-bdfa-8b3371f54d71.png)

You will "loose" passwords once again, but then it should be fixed as the name change will not happen with the next update.
