### ISSUE TITLE
Windows Installer can't handle Oracle Java 17 version number

### ISSUE THREAD

**Issue by McPringle** [apache/netbeans#3707]
### Apache NetBeans version

Apache NetBeans 13 release candidate

### What happened

Today I downloaded the installer for Windows (`Apache-NetBeans-13-bin-windows-x64.exe`). I have Oracle Java 17 installed. The NetBeans installer can't handle the version number and does not allow to continue the installation:

![Ii9SYXEpAi](https://user-images.githubusercontent.com/1254039/156881047-69a33442-4fd9-48ea-b9da-b03b0fbd192a.png)

### How to reproduce

- Have Java 17 from Oracle installed on your computer
- Download the NetBeans 13 installer from https://www.apache.org/dyn/closer.cgi/netbeans/netbeans-installers/13/Apache-NetBeans-13-bin-windows-x64.exe
- Start the installer and follow the steps
- When asked to specify the JDK for the NetBeans IDE, select the folder of Oracle Java 17
- An error pops up at the bottom of the dialog complaining about the version number
- The `Next >` button is greyed out

I have not used NetBeans for many years, so I'll answer the following question with `No`. There should be an option like `not tested`.

### Did this work correctly in an earlier version?

No

### Operating System

Windows 11 Pro

### JDK

Oracle Corporation Java 17 2021-09-14 LTS (build 17+35-LTS-2724)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I was not able to install NetBeans at all. I tested it on three different computers (all with Windows 11 and Oracle JDK 17).

### Code of Conduct

Yes

**Comment by geertjanw** [comment]
Just installed 13 without a problem on the latest OpenJDK 17 by Azul, downloaded from foojay.io/download. (On Windows, i.e., same binary as above.)

**Comment by matthiasblaesing** [comment]
The error looks real (only glancing at the screenshot). I suppose the installer might parse the wrong properties and makes assumptions of the java version number, that don't hold anymore.

Someone would need have a look at the place in the installer where the error message is generated and retry with an Oracle JDK.

I assume, that not many people use Oracle JDKs. At my employers place after the binary license stunt Oracle pulled for JDKs, usage of them is treated with scepticism and so Alternatives from Azul, Amazon, Adoptium or even Microsoft are more popular.

**Comment by McPringle** [comment]
Most companies I know use the Oracle JDK. I'm working in the enterprise environment and a lot of companies have already existing contracts with Oracle for many years or even decades. In these companies, this is more a management decision than technically or legally based.

Anyhow, it would be great to take a look at the installer. It should work with Oracle JDK, even if it is not a very popular JDK in the open-source world.

Thanks for taking care!

**Comment by geertjanw** [comment]
Can you see if you can reproduce your issue with a different JDK?

**Comment by McPringle** [comment]
After the weekend, when I have access to the Windows machine again.

**Comment by matthiasblaesing** [comment]
I think I ran the installer the first time and I'm not able to reproduce the problem. I fetched the ZIP distribution of the JDK from here:

https://www.oracle.com/java/technologies/downloads/#jdk17-windows

Then I ran the installer with JDK 11 set in JAVA_HOME and PATH like this:

```
Apache-NetBeans-13-bin-windows-x64.exe --verbose --output installer.log
```

I selected the expanded directory from the downloaded zip and it was accepted as I would expect it to be.

The installer log showed this:

```
[2022-03-05 20:35:57.251]: executing command: C:\temp\jdk-17_windows-x64_bin\jdk-17.0.2\bin\java.exe -classpath C:\Users\matthias\.nbi\tmp TestJDK, in directory: .
[2022-03-05 20:35:57.437]:     [stdout]: 17.0.2
[2022-03-05 20:35:57.437]:     [stdout]: 17.0.2+8-LTS-86
[2022-03-05 20:35:57.437]:     [stdout]: Oracle Corporation
[2022-03-05 20:35:57.437]:     [stdout]: Windows 10
[2022-03-05 20:35:57.437]:     [stdout]: amd64
[2022-03-05 20:35:57.437]:     [return]: 0
[2022-03-05 20:35:57.437]: ... command execution finished
[2022-03-05 20:35:57.437]: ... java.version    = 17.0.2
[2022-03-05 20:35:57.437]: ... java.vm.version = 17.0.2+8-LTS-86
[2022-03-05 20:35:57.437]: ... java.vendor     = Oracle Corporation
[2022-03-05 20:35:57.437]: ... os.name         = Windows 10
[2022-03-05 20:35:57.437]: ... os.arch         = amd64
[2022-03-05 20:35:57.437]: ... version string : 17.0.2+8-LTS-86
[2022-03-05 20:35:57.437]: ... put jdk info to the Java map
```

This looks reasonable, so something must be different at your end. Could you please:

a) check the JDK again - is it maybe a prerelease version, this might mess up the detection code (and would make this less of an issue, given, that the previous/next released version is always less than 6 months in the future)
b) run the installer with verbose logging, review the log for security sensitive information and put it here (or a subset of it)

**Comment by neilcsmith-net** [comment]
No response - closing.
