### ISSUE TITLE
Add preview for markdown files

### ISSUE THREAD

**Issue by PavelTurkish** [apache/netbeans#3714]
### Description

Nowadays preview is one of the most common feature for texts that have visual presentation and can be previewed. For example, look here:
![Screenshot from 2022-03-05 23-09-29](https://user-images.githubusercontent.com/10261361/156899993-448c6298-efe9-4f9b-89d0-e771cf767cfa.png)
So, I suggest to add preview for markdown files, because it is impossible to work with markdown files normally, in a convenient way.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment]
See #3477 for a discussion about it

**Comment by PashaTurok** [comment]
Please, someone, explain @matthiasblaesing  what I am talking about. I don't understand - he doesn't work to develop NB?

**Comment by matthiasblaesing** [comment]
@PashaTurok look at the commits to the code base and you will find my name. 

I did not realise you were the author of the original ticket. From my perspective, this is not free beer, you want something, you pay either by finding someone to do it or doing it yourself. I see the same in other projects: They are driven by the needs of the contributors, not by feature-requesters.

**Comment by spyhunter99** [comment]
i think there's a plugin for this one. try this one https://github.com/madflow/flow-netbeans-markdown

**Comment by patton73** [comment]
That plugin is outdated. It should be merged with netbeans editor according to me.
