### ISSUE TITLE
Respect init.defaultBranch configuration value when initializing a Git repository

### ISSUE THREAD

**Issue by julianmontague** [apache/netbeans#3719]
### Description

Git added the [init.defaultBranch](https://git-scm.com/docs/git-config#Documentation/git-config.txt-initdefaultBranch) config value a while ago. It allows specifying the default branch name (to deviate from the historical default "master"). Netbeans currently (version 13.0) uses master regardless of the git global config.

### Use case/motivation

When I use Netbeans to initialize a Git repo, I want it to use the branch specified by the mentioned config value. Instead, when I initialize a Git repo and make my first commit it is always on the master branch.

In my case, `git config --global init.defaultBranch` returns `main` so I expect NetBeans to respect this.

### Related issues

Jira issue [NETBEANS-4990](https://issues.apache.org/jira/browse/NETBEANS-4990). Another duplicate Jira issue was created in August 2021: [NETBEANS-5903](https://issues.apache.org/jira/browse/NETBEANS-5903).

Comments on these issues mentioned this not being supported in JGit, but this has since changed. [Bug 564794](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564794) was [resolved in late February 2021](https://bugs.eclipse.org/bugs/show_activity.cgi?id=564794).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by ChristoforosKor** [comment]
This is a very nice feature to have.
