### ISSUE TITLE
Add simple code completion for Spock test framework

### ISSUE THREAD

**Issue by ppisl** [apache/netbeans#3730]
### Description

The Spock test framework is widely used framework for creating test in Groovy

### Use case/motivation

It would be useful to offer Spock block names and Spock test method parameters in cc. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment]
No need to open an issue if you have a PR!
