### ISSUE TITLE
modify criteria on existing search results loosing current criteria

### ISSUE THREAD

**Issue by thanasis-oob** [apache/netbeans#3737]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I made some searches on a project. I saw the results of each one in the Search Results window.  I tried to re-run a search(not the last) using the "modify criteria" button. 
![Screenshot from 2022-03-09 11-56-31](https://user-images.githubusercontent.com/16305291/157418017-66ad4200-f761-42b8-8b10-9539036e2c5a.png).
This button opens the search form pre-filled with the selected criteria, but instead of the "containing text" of this search it is filled the text from the last search!
 

### How to reproduce

Make 2 different searches with different text. Then go to the results of the first search and push the "modify criteria" button. The input of the "containing text" it has the text of the second search!

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Ubuntu 16.04

### JDK

openjdk 1.8.0_292

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Officially installation via the "ubuntu Software" service. As I know the ubuntu install the netbeans via snap.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
I can reproduce this, thanks.
Might be caused by https://github.com/apache/netbeans/pull/3393 or https://github.com/apache/netbeans/pull/3489

going to take a look.
