### ISSUE TITLE
JavaHL not selectable

### ISSUE THREAD

**Issue by Findulas** [apache/netbeans#3738]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Selecting javaHL as preferred client for subversion does not work. SlikSVN(1.14.1) and subclipse-javahl(1.14.0) are not accepted.

I think the problem is that the list of dlls in JavaHlClientAdapterFactory (https://github.com/apache/netbeans/blob/master/ide/libs.svnClientAdapter.javahl/src/org/netbeans/libs/svnclientadapter/javahl/JavaHlClientAdapterFactory.java) is wrong. Some libraries don't exist any more.

### How to reproduce

Open the options dialog, choose Team->Versioning->Subversion and try to set the preferred client to javaHL. Then select the directory of the SlikSVN or Subclipse-javahl installation.
Clicking Apply prefered client switches back to CLI

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 11

### JDK

temurin 11

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Installed via scoop

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
Could you post the name of the Java native clients on Windows. I only work with Ubuntu, so I have no details here. However the SVN JavaHL upgrade PR was on me.

**Comment by Findulas** [comment]
Okay, I try to use:
**subclipse-javahl** (https://github.com/subclipse/javahl-windows/releases)

Existing Libraries:
![image](https://user-images.githubusercontent.com/20240482/157628132-e930e872-fb19-4e5d-a549-ae6fdd8bd705.png)

For Example the libraries "libeay32.dll", "ssleay32.dll" are missing.

**Sliksvn** (https://sliksvn.com/pub/Slik-Subversion-1.14.1-x64.msi)

Existing Libraries:
![image](https://user-images.githubusercontent.com/20240482/157628695-bf4c9375-1d4d-4d8a-a50d-77bc7c0c7cb3.png)

Here all svn-libs are named Sliksvn-libsvn.... instead of Sliksvn-svn.....

Hope this helps.

**Comment by lkishalmi** [comment]
@Findulas please see #3592, there might be a workaround for you.

**Comment by Findulas** [comment]
#3592 continues with the information. It works, if the bin-folder is on the path.
