### ISSUE TITLE
Proxy authentication is not working

### ISSUE THREAD

**Issue by shoblingr** [apache/netbeans#3748]
### Apache NetBeans version

Apache NetBeans 13

### What happened

The proxy is configured in the config panel, with user and password specified. But for the test we get message "407 Proxy Ahtentication Required".
Connection is not working, eg. fetching plugins is ko.
See attached image for detail.
![manual config](https://user-images.githubusercontent.com/3625366/157617870-08e22bbd-001c-49fe-b9f6-0273df322400.png)
![proxy test](https://user-images.githubusercontent.com/3625366/157617913-241aad2e-e440-4295-9c0b-9d1ce6ff4e79.png)

### How to reproduce

configure proxy and click test...

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10

### JDK

jdk-11.0.8+10

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
Please provide the message.log file. On windows it can be found in the directory `C:\Users\$USERNAME\AppData\Roaming\NetBeans\$VERSION\var\log\messages.log`.

**Comment by shoblingr** [comment]
Hi,

Here it is
[messages.log](https://github.com/apache/netbeans/files/8230284/messages.log)
.

**Comment by vieiro** [comment]
Hi @shoblingr ,
You're getting an HTTP 407 "Proxy Authentication Required" (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407)

- Click the "More..." button at the right of the "Manual Proxy Settings".
- Check the "Proxy Requires Explicit Authentication" 
- The "Advanced Proxy Options" dialog appears, enter the username and password that you need for that proxy.

![imagen](https://user-images.githubusercontent.com/564140/157976209-aef8c7d0-e68c-46bb-9744-f25007ee68f1.png)

**Comment by shoblingr** [comment]
Hi,
Thanks @vieiro for your advice, unfortunately this is already done, chek my screnshots in the first post, but it is not working...
Stef

**Comment by vieiro** [comment]
Ah, very true, I didn't notice you were already setting user/password.
What kind of proxy authentication are you using, @shoblingr ? Is it basic, NTLM or what?

**Comment by matthiasblaesing** [comment]
I'll risk a guess: Your password (or the username) contains characters outside the ASCII range. If I remember correctly Basic Auth was only defined for Latin1, but was extended to UTF-8 . Do you have the option to test with a password containing only ASCII characters?

**Comment by shoblingr** [comment]
No, password is in only standard letters and numbers...

**Comment by shoblingr** [comment]
Interesting: I just saw this info for the JMeter Java Sampler vs HttpClient4:
There is a bug in the handling of HTTPS via a Proxy (the CONNECT is not handled correctly). See Java bugs 6226610 and 6208335.

**Comment by shoblingr** [comment]
Ok I found a solution :)
Following this article : https://stackoverflow.com/questions/41505219/unable-to-tunnel-through-proxy-proxy-returns-http-1-1-407-via-https
It seems the problem is comming from:
_Change in Java 8 Update 111:
Now, proxies requiring Basic authentication when setting up a tunnel for HTTPS will no longer succeed by default. If required, this authentication scheme can be reactivated by removing Basic from the jdk.http.auth.tunneling.disabledSchemes networking property, or by setting a system property of the same name to "" ( empty ) on the command line._

To fix the issue, I added the option -Djdk.http.auth.tunneling.disabledSchemes="" to netbean conf as follow:
etbeans_default_options="-J-XX:+UseStringDeduplication -J-Xss2m **-J-Djdk.http.auth.tunneling.disabledSchemes=\"\"** -J-Dapple.laf.useScreenMenuBar=true (...)

Now it works great :)
Maybe this conf could be added by default in netbean distribution ?
Thanks for your help!

Stef

**Comment by neilcsmith-net** [comment]
> Maybe this conf could be added by default in netbean distribution ?

Doesn't that amount to disabling a security feature of the JDK by default?  In which case, probably not.  Better error message maybe?  Also see https://bugzilla.redhat.com/show_bug.cgi?id=1386103

**Comment by matthiasblaesing** [comment]
> > Maybe this conf could be added by default in netbean distribution ?
> 
> Doesn't that amount to disabling a security feature of the JDK by default? In which case, probably not. Better error message maybe? Also see https://bugzilla.redhat.com/show_bug.cgi?id=1386103

If we warn the user, it is a feature, not a CVE. If your IT department requires you to use an authenticated proxy, you probably won't have a chance to change their thinking.

The problem is, that the JDK at least partitially uses aggressive caching of the property:

https://github.com/openjdk/jdk/blob/47b1c51bbd28582d209db07052e553a76acced65/src/java.net.http/share/classes/jdk/internal/net/http/common/Utils.java#L260-L274

So if you want to make that dynamic you have to reflect into an internal module.

**Comment by mbien** [comment]
we could add a hint to the proxy settings window explaining that a flag might be required to get legacy auth behavior back.

Accessing JDK internals should only be used as last resort IMO. Ideally we should try to shrink the --add-opens list if possible.

**Comment by vieiro** [comment]
I created this PR for the website explaining the problem https://github.com/apache/netbeans-website/pull/592
Maybe we can add a link to this page from the dialog, so users can learn about the problem (and the solution) in the future.

**Comment by shoblingr** [comment]
Hi, this is already done, please look at the screenshot I posted
Regards,
Stef

Le ven. 11 mars 2022 à 23:03, Antonio Vieiro ***@***.***> a
écrit :
