### ISSUE TITLE
Warning while using the keyword "ReadOnly" in php namespace on php7.4 project

### ISSUE THREAD

**Issue by pse-nltjtt** [apache/netbeans#3749]
### Apache NetBeans version

Apache NetBeans 13

### What happened

HI, 

First of all, thank you to all the contributors for maintaining this NetBeans. 

I'm using NetBean to work on project under PHP 7.4 (properly set in Project Properties)

Since PHP 8.1 support and the introduction of the new "readonly" keyword (unfortunately used in some of my projects as part of namespace, for models) I have a lot of warning and errors.

![image](https://user-images.githubusercontent.com/4329458/157620299-69fa54f8-ca6c-4327-a348-539a1ce5155a.png)

![image](https://user-images.githubusercontent.com/4329458/157620429-e1495aa1-ff4a-44de-8a0e-644100ad521e.png)

This new keyword was introduced in commits : 
https://github.com/apache/netbeans/commit/6c4457f594f3ed7a6340d39fc872a2800fb36aa3
https://github.com/apache/netbeans/commit/5f3e694a37a0342834a760df18641eebc3638251

Is it possible to silent keyword notices, warnings and errors according to the project's PHP version ?

PS : since PHP 8.0 keywords seems to be allowed in namespace.

![image](https://user-images.githubusercontent.com/4329458/157623404-408b0757-1ce9-4962-926d-dcaff6b0eb3b.png)

https://3v4l.org/UEnf8

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Debian GNU/Linux 10 (buster) Linux 4.19.0-18-amd64 x86-64

### JDK

OpenJDK Runtime Environment 11.0.14+9-post-Debian-1deb10u1

### Apache NetBeans packaging

Third-party package

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by pse-nltjtt** [comment]
Hi, @junichi11 (special thanks for the plugin PHP Enhancements)

As you wrote the commit that introduced the new php 8.1 keyword "readonly", I ask you the following gentle question: do you think this bug can be fix or not?

If yes, great, I'll wait till someone have time to fix it (I'm not a java developer)
If no, no big deal, I'll stay on 12.6

**Comment by junichi11** [comment]
@pse-nltjtt I know this problem: https://issues.apache.org/jira/browse/NETBEANS-5523

Currently, I'm working on the Enumeration feature of PHP 8.1 support. So, I can't fix that problem soon, sorry.

> As you wrote the commit that introduced the new php 8.1 keyword "readonly", I ask you the following gentle question: do you think this bug can be fix or not?

I'm not sure whether it's easy at the moment, but I'll give it a try later. (I can't promise when I will do it.)

> If no, no big deal, I'll stay on 12.6

Yes, we can use it as a workaround :)

Thank you for your understanding.
