### ISSUE TITLE
Baisic search form "find" button does not submit the form if the cursor is focused on "containing text" input.

### ISSUE THREAD

**Issue by thanasis-oob** [apache/netbeans#3752]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I noticed this behavior changing at the version 13. On the search form I write a text into the 'containing text' input, then while the cursor is still on this input, I click the "find" button to start the searching. Regularly, I expect the beginning of the search, instead of this it only happens to blur the cursor from the input. Then I click the find button and the search begins! This strainge behavior arise with the latest version 13. In addition, this "double clicking" does not happens with the other fields of the form.

### How to reproduce

Scenario 1: Open  the search form, click on the "containing text" input. Write something, then click the find button. Nothing happens! Then click again the find button. The search begins!
Scenario 2: Open  the search form, click on the "containing text" input. Write something, then click somewhere else than the input inside the window in order to blur the input. then click the find button. The search begins!

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Ubuntu 16.04

### JDK

openjdk 1.8.0_292

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
and I thought my mouse was broken :)

fix is pending, thanks for the report

**Comment by thanasis-oob** [comment]
:)! Please keep in mind that the same happens at the replace form!

**Comment by mbien** [comment]
> :)! Please keep in mind that the same happens at the replace form!

yes, this should fix both cases.
