### ISSUE TITLE
nb 13 after ok install , IDE not starting

### ISSUE THREAD

**Issue by sysmat** [apache/netbeans#3789]
### Apache NetBeans version

Apache NetBeans 13

### What happened

- install ok
- IDE not showing up

### How to reproduce

just install it on windows

### Did this work correctly in an earlier version?

Apache NetBeans 12.5

### Operating System

windows

### JDK

8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ebarboni** [comment]
Hi,  I you did a default install , you should have a message.log file over there C:\Users\<username>\AppData\Roaming\NetBeans\13\var\log
maybe preserve it next time for feedback

**Comment by neilcsmith-net** [comment]
> JDK 8

Also, note that JDK 11 is now the minimum requirement for NetBeans 13.
