### ISSUE TITLE
Gradle Project opens with problem and it cannot be resolved

### ISSUE THREAD

**Issue by makiam** [apache/netbeans#3801]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Once I opened Gradle project I see message Project Cannot be loaded...
Once I try to invoke Reolve Project Problems I see next message in dialog:
Could not open cp_init generic class cache for initialization script 'C:\Users\MaksK\AppData\Local\NetBeans\Cache\dev\gradle\nb-tooling.gradle' (C:\Users\MaksK\.gradle\caches\7.4.1\scripts\lq5c633n4lhixxj9vx3i6swd). Could not compile initialization script 'C:\Users\MaksK\AppData\Local\NetBeans\Cache\dev\gradle\nb-tooling.gradle'. startup failed: initialization script 'C:\Users\MaksK\AppData\Local\NetBeans\Cache\dev\gradle\nb-tooling.gradle': 22: Unexpected character: '\'' @ line 22, column 25. classpath files('C:\netbeans\extide\modules\gradle\netbeans-gradle-tooling.jar') ^

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Windows 10 version 10.0 running on amd64

### JDK

Java: 13.0.1; Java HotSpot(TM) 64-Bit Server VM 13.0.1+9

### Apache NetBeans packaging

Own source build

### Anything else

IDE options set to use Custom Gradle installed 7.41
Prefer to use wrapper is turned off

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
Thank you for catching this one the new code was not tested on Windows (as I'm lucky enough to have none around). I'll provide a fix today.
