### ISSUE TITLE
autocomplete error on throw statement

### ISSUE THREAD

**Issue by eglic** [apache/netbeans#3806]
### Apache NetBeans version

Apache NetBeans 13

### What happened

from version 12.5 to 13.0: 

1. create or open any php file
2. input "throw new \Exc" anywhere
3. wait autocomplete menu popuped
4. press "Enter" to select only option "Exception()     Exception"
5. netbeans insert "throw new Exception()" without character "\"

### How to reproduce

from version 12.5 to 13.0: 

1. create or open any php file
2. input "throw new \Exc" anywhere
3. wait autocomplete menu popuped
4. press "Enter" to select only option "Exception()     Exception"
5. netbeans insert "throw new Exception()" without character "\"

### Did this work correctly in an earlier version?

Apache NetBeans 12.5

### Operating System

windows 11

### JDK

jdk-17.0.2-x64

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Chris2011** [comment]
You are missing the \ before the Exception() or what is the expeacted behaviour?

**Comment by eglic** [comment]
editor will **FORCE** remove the namespace leader "\"  while auto complete on "Exception" or "\Exception".
On the contrary，
auto complet is correct on "ArrayAccess" ,"Countable" ... the namespace leader "\" is inserted correctly.

**Comment by matthiasblaesing** [comment]
Tested on master and found it fixed.
