### ISSUE TITLE
When creating new Webapp and try to launch it, I have error

### ISSUE THREAD

**Issue by akaouane** [apache/netbeans#3814]
### Apache NetBeans version

Apache NetBeans 13

### What happened

When I create a new Webapp and try to launch it, I receive this error message :

SEVERE:   Exception while loading the app
SEVERE:   Undeployment failed for context /WebApplication1
SEVERE:   Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.RuntimeException: javax.faces.FacesException: Unable to find CDI BeanManager

### How to reproduce

Create a new Webapp

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Ubuntu 20.04

### JDK

OpenJdk11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
There were many improvements in the support for JakartaEE and CDI please test again. If you can still reproduce, please describe the exact steps. For JavaEE/JakartaEE for example it is relevant onto which sever you try to deploy and/or what version of the server you are deploying. It might also be helpful if you provide the project you use to test.
