### ISSUE TITLE
Inspect: strange Java Hints

### ISSUE THREAD

**Issue by ostermannBernd** [apache/netbeans#3816]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I used the source inspector for analysing my netbeans projects. I use nebeans version 12.6.
I got some strange Java hints.
For instance: 
1. all parameters in JavaDoc are declared as missing, altough they were declared  as @param in JavaDoc and the head of the methode.

When I choose the configuration FindBugs I was asked to install an addition plugin. When I clicked the install button I got the message:
- FindBugs Integration module has not been downloaded.

I found some comments in the internet station the the plugin FindBugs is no longer supported. The you should remove FindBugs for the instector.
[screenshot-unknown-paramters.odt](https://github.com/apache/netbeans/files/8309732/screenshot-unknown-paramters.odt)

### How to reproduce

Create a methode with some paramters. Add Javadoc declaring these paramters. Then run the source Inspector with the configuraion Netbeans Java Hints.
[screenshot-unknown-paramters.odt](https://github.com/apache/netbeans/files/8309728/screenshot-unknown-paramters.odt)

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

1.8.0

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
> I use nebeans version 12.6.

please upgrade to NetBeans 13. The issues you are facing should be fixed there. FindBugs was indeed removed and some improvements were made to the inspection dialogs.

> 1.8.0

The minimum requirements are also JDK 11+

as a sidenote: please upload screenshots as image files not as text documents. I am not going to open that.
