### ISSUE TITLE
Can't print multi-byte character in the Output window with Java 18

### ISSUE THREAD

**Issue by kishida** [apache/netbeans#3824]
### Apache NetBeans version

Apache NetBeans 13

### What happened

With JDK 18 as NetBeans runtime, the output window can't show multi-byte character correctly.

### How to reproduce

Running the code below.
```
public class Main {
    public static void main(String[] args) {
        System.out.println("こんにちは");
    }
}
```

It shows this.
![image](https://user-images.githubusercontent.com/1178746/159217759-2f230f1d-e6a3-4073-9cea-f7bf54233c53.png)

### Did this work correctly in an earlier version?

No

### Operating System

Windows

### JDK

JDK-18

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Adding `-J-Dfile.encoding=COMPAT` for `netbeans_default_options` in netbeans.conf should be the solution with Java 18.
![image](https://user-images.githubusercontent.com/1178746/159218454-dc1cbdfe-c152-497d-8a81-9bb79359de70.png)

But it affects with Java 17 incorrectly.
![image](https://user-images.githubusercontent.com/1178746/159218275-43cd77e2-6980-4d34-804d-a247c41e9b63.png)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by geertjanw** [comment]
NetBeans does not support JDK 18 and, in fact, JDK 18 does not exist.

**Comment by kishida** [comment]
Sorry, it will release tomorrow...but same binary will be used for the GA.
And it will be a problem to support Java 18 or later in the future version.

**Comment by mbien** [comment]
assuming NB 13 on JDK 17 works as expected (it does, right?), is the issue also triggered if you start NB 13 on JDK 17 with `-J-Dfile.encoding=UTF-8` set in netbeans.conf?

i agree that we can set the compat mode for NB 14 (which will support JDK 18), however this is no real fix, just some bought time. Ideally someone will have to investigate which stream doesn't like UTF-8 on windows (linux should do fine) and update it.

i am going to resurrect an old draft PR later #3265 for the compat flag proposal

**Comment by mbien** [comment]
@kishida could you do me a favor and test the following?
- JDK 17 + `-J-Dfile.encoding=UTF-8` and verify that the same issue appears
- JDK 11 + `-J-Dfile.encoding=COMPAT` and verify that everything still works (you tested on 18 already so we know it works)

**Comment by kishida** [comment]
related?
https://bugs.openjdk.java.net/browse/JDK-8283620
