### ISSUE TITLE
Terminally Deprecated method has been called

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#3852]
### Apache NetBeans version

Apache NetBeans 13

### What happened

* New Netbeans v13 install
* Using flatpack "stable" from flathub
  *  As follows . . . 
```
flatpak run org.apache.netbeans     \
    -J-Dawt.useSystemAAFontSettings=on               \
    --jdkhome     /opt/lib/java/jdk/v17.00     \
    --userdir     /home/william/.config/netbeans/v13.00/4ams/v17.00/user-00     \
    --cachedir    /home/william/.cache/netbeans/v13.00/4ams/v17.00/cache-00
```

*  The following Warning messages are emitted
```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/app/netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/app/netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
```
*   **Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager**

### How to reproduce

* I have just installed the new v13 Netbeans as a flatpak
* I'm using a user directopry from v12.06 
   *  This is so I may retain continuity of plugins, etc.
* Run netbeans with command line above

I went back to v16.06 and yes a similar message paragraph is also issued on start:
```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/Cheatah/prod/tools/netbeans/v12.06/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
```
  * This project is using a different user folder and cache folder.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Ubuntu 21.10

### JDK

openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)

### Apache NetBeans packaging

Third-party package

### Anything else

openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)

* You ought to make the Java version field a multi-line text area.
* You need to provide **flatpak** for the package manager 
  * I have no idea why you feature snap -- Snaps do not work on machines with $HOME on a different disk

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
we know about JEP 411 :) 
see comment in #3519
