### ISSUE TITLE
unable to download javadoc / sources for maven dependencies

### ISSUE THREAD

**Issue by wumpz** [apache/netbeans#3854]
### Apache NetBeans version

Apache NetBeans 13

### What happened

In Netbeans 12.6 I was able to right click a maven dependency (in projects view) and do 'download sources / download javadoc'. This does not work in Netbeans 13.0. So far I have no Exceptions. It simply does nothing. 

### How to reproduce

Netbeans 13 was installed using Windows installer. 

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 10/11

### JDK

Java 11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ebarboni** [comment]
I cannot reproduce, do you have a precise example of artefact that is failing ?

**Comment by wumpz** [comment]
I had to remove the netbeans cache directory. After it was rebuild, now this seems to work. However, my colleague has the same problem. Strange.

Now its running.
