### ISSUE TITLE
Failed to load module "xapp-gtk3-module"

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#3856]
### Apache NetBeans version

Apache NetBeans 13

### What happened

During start-up Netbeans logged a message to the console.  Since people probably usually start Netbeans as a gui they likely don't see console output.  

Console output

```
 $ flatpak run org.apache.netbeans         -J-Dawt.useSystemAAFontSettings=on                   --jdkhome     /opt/lib/java/jdk/v17.00         --userdir     /home/william/.config/netbeans/v13.00/4ams/v17.00/user-00         --cachedir    /home/william/.cache/netbeans/v13.00/4ams/v17.00/cache-00
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/app/netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
Gtk-Message: 09:35:57.337: Failed to load module "xapp-gtk3-module"
```

* Please note this may be an effect of the `flatpak` packaging.

### How to reproduce

Start netbeans flatpak from console.
>  ` $ flatpak run org.apache.netbeans         -J-Dawt.useSystemAAFontSettings=on      --jdkhome     /opt/lib/java/jdk/v17.00`

I would also start the normal binary install too.   

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Ubuntu 21.10

### JDK

openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)

### Apache NetBeans packaging

Third-party package

### Anything else

* the Netbeans option (presumably in the `user/` directory) are set to "maximise native look and feel"
    ![image](https://user-images.githubusercontent.com/67028/160114156-05545169-19f6-4d7f-9761-cb72227a1c3f.png)
* add fltpak to the drop-down list
* Are you planning to use gtk4

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
this is most likely harmless. I have seen this before in other applications, a quick search resulted in:
https://github.com/linuxmint/xapp/issues/134#issuecomment-817364455

The default Look and Feel is FlatLAF btw, the other selections are less tested - use on your own risk.

**Comment by aplatypus** [comment]
Some more information has bubbled up.
* Netbeans fails to find a GTK libarary: `libgtk3-nocsd.so.0`
   * This is found on this path natively: `/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0`
* However the `flatpak` seems to keep such things here:
```
 $ ll ~/.var/app/org.apache.netbeans/.ld.so
total 60
drwxr-xr-x 1    140 May  3 11:49 ./
drwxr-xr-x 1     42 Apr 21 15:01 ../
-rw-r--r-- 1  56692 May  3 11:49 87d15bf52ffceca6aac5ae3ca838aeb5ef0cb5581a1462f12ae8e6633b448870
lrwxrwxrwx 1     64 May  3 11:49 active -> 87d15bf52ffceca6aac5ae3ca838aeb5ef0cb5581a1462f12ae8e6633b448870
```

*  The long hex number is a blob.  `hexdump` yields the following a the top of the file:
```
$ hexdump  -C  ~/.var/app/org.apache.netbeans/.ld.so/87d15bf52ffceca6aac5ae3ca838aeb5ef0cb5581a1462f12ae8e6633b448870 

00000000  67 6c 69 62 63 2d 6c 64  2e 73 6f 2e 63 61 63 68  |glibc-ld.so.cach|
00000010  65 31 2e 31 46 03 00 00  6b 8e 00 00 02 00 00 00  |e1.1F...k.......|
q
```
  * Which is almost inscrutable.  One imagines this is ment to resolve to absent shared libraries
*  To me that suggests there is a packaging problem or versioning mismatch in the flatpak

At home I have a desktop PC with the same Ubuntu version, flatpak Netbeans installed, etc.  The flatpak Netbeans works on that PC.  I have removed and reinstalled Netbeans twice today.  Still getting that error.


On another tack, I thought I might use `flatseal` configure Netbeans so it can "see" that library locally.  Apparently flatseal doesn't work like that.

**Comment by neilcsmith-net** [comment]
@aplatypus flatpak isn't listed in the dropdown because it's not produced by ASF.  If you can reproduce the issue with the zip (or Linux installer or Snap package) then report here.  If not, I suggest starting with https://github.com/flathub/org.apache.netbeans/issues
