### ISSUE TITLE
Persist support for `org.gradle.java.home` Java platform Gradle property

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#3858]
### Description

*  There is no way to set and PERSIST a sub-project build properties
    * The Jetty and HTTP code we use require Java 1.8
    * Everytime I open a sub-project (library) I must manually set the build to Java1.8

### Use case/motivation

* Find and open sub-projects faster and more effectively
* I am looking for a specific sub-project (say TestSupport) well, it is not after "S" it might be anywhere
* With TestSupport looking for "Test..." is as fast as it might be because 
   *  3 or 4 sub-projects may be available in
   * they can be in  completely different locations on the tree
*  Want projects of similar nomencluature say TestSupport, TestingData, TestUi, etc.
    * These are named so to keep them together and then Netbeans project tree just shuffles the up
*  This implementaton just slows me / others down scanning the list

### Related issues

*  There is no way to set and PERSIST a sub-project build properties
    * The Jetty and HTTP code we use require Java 1.8
    * Everytime I open a sub-project (library) I must manually set the build to Java1.8
* see: #3857

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by lkishalmi** [comment]
From NetBeans 17 Java Platform are to be set on root project level.
