### ISSUE TITLE
Can't build, edit, and run a Jfram

### ISSUE THREAD

**Issue by Bluemorpho61** [apache/netbeans#3882]
### Apache NetBeans version

Apache NetBeans 13

### What happened

[](url
[Uploading log.zip…]()
)

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10

### JDK

JDK 16

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
It's unclear what you're reporting and the link to "Uploading log.zip" doesn't go anywhere. Please try again, but make sure to fill in more information, including the _How to reproduce_ section.  If you're unclear about usage, etc. please try opening a discussion question instead.
