### ISSUE TITLE
Tomcat start delay hardcoded to 180s

### ISSUE THREAD

**Issue by jocelyn44** [apache/netbeans#3898]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Hello,

I'm trying to use netbeans to work on a big project, this project takes about 200s to start in debug mode. After 180s netbeans throw a message "Starting of Tomcat failed".

I saw the message in netbeans-master\enterprise\tomcat5\src\org\netbeans\modules\tomcat5\optional\Bundle.properties
I think that it's due to hardcoded timeout in netbeans-master\enterprise\tomcat5\src\org\netbeans\modules\tomcat5\optional\StartTomcat.java L113 : 
    private static final long TIMEOUT_DELAY = 180000;

Is it possible to change this timeout ? At least increase the time to solve the bug, best option would be to have an option to set it in servers > startup menu (new feature) 

### Did this work correctly in an earlier version?

No

### Operating System

Linux rhel 7.6

### JDK

adopt openjdk 11.0.9 openj9

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
I know that this is not a solution, but is it possible to try a JVM with HotSpot instead of OpenJ9? OpenJ9 has a terrible performance when starting in Debug mode.

**Comment by jocelyn44** [comment]
Hello,
No it's not possible, we've some constraints in my company and i'm forced to use openJ9.

**Comment by lkishalmi** [comment]
Well, you might just check out NB 13 code change that timeout value and compile one for yourself.
Also it is possible to start Tomcat externally, then attach the debugger it.

This is a so rare case, that I do not feel introducing an API for it. Even as small as add a System Property to be able to change that timeout. Though others can have other opinion. You can also file a PR if you would like to push that through.

**Comment by jocelyn44** [comment]
Okay I'll do that.
I'm migrating from eclipse, and this feature was useful for me :) that's why i was asking. 
![image](https://user-images.githubusercontent.com/6944744/161004710-b30c33f4-a142-4e47-95c1-e678a405263c.png)

Thanks for your help.
