### ISSUE TITLE
Add Restore operation for "Start Page" / "What's New" tab

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#3910]
### Description

* When "`Whats' New`" tab of the Netbeans "'Start Page'" tab shos "Failed to Load"
  * Show a [`Restore news feed`] button to _reboot_ the news feed.
* I have a work-around to do this.  The cause has eluded my search of the logs, etc.
* To "reset" hanging the URL at the start of the `welcome.properties` config file to:
   * `blogs.apache.org/netbeans/` and then
   * reload the tab

### Use case/motivation

* Since the time of Netbeans v7 and perhaps before the "`Whats' New`" tab of the Netbeans "'Start Page'" tab has randomly stopped working
* This happened again wth Netbeans v13
* I have a work-around since the cause eluded my search of the logs, etc.
* When this problem occurs the "Reload feed" button in use now has not result
  * It seems to just retry the existing URL

* With some experimentation it is demonstrated that the URL itself is not the problem
   * It works fine once the URL has been reset.
* Replacing it with: `blogs.apache.org/netbeans/` manually;
   * This seems to be enough to cause Netbeans to reinitialise the feed settings
   * Once Netbeans restarts the new feed is restored.

* While this may not be a high priority as a functional item
* I believe it is a very important **communication** and **marketing** tool

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by ebresie** [comment]
Believe this is related but when attempting new release of NetBeans and "importing" from previous revision, some of the setup seems to get corrupted.  

My workaround involves the usual removal of NetBeans user files.

1. Assume a previous NetBeans revision with applicable NetBeans settings present.
2. [On Windows] Removing my C:\Users\<userid>\AppData\Roaming\NetBeans\<latest netbean version>
3. Start NetBeans (fresh), 
4. Select No to "import previous version", 
5. View start page which should so current "What's new" and related page info and links.

Does this at least resolve the initial issue?

**Comment by aplatypus** [comment]
* That's ok then
* The work around solve the issue if it comes back
