### ISSUE TITLE
NPE Parsing javax.swing.DefaultListModel.java

### ISSUE THREAD

**Issue by lkishalmi** [apache/netbeans#3911]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Just invoked code completion on a variable with type ```DefaultListModel```

This might be a bug in javac. AFAIK there is at least one issue something like this reported in or JIRA as well.

[DefaultListModel.dump.log](https://github.com/apache/netbeans/files/8393754/DefaultListModel.dump.log)

### How to reproduce

1. Create a new project. (Ant, Maven, Gradle)
1. Add the following lines, to the main method:
    ```java
        javax.swing.DefaultListModel model = null;
        model.
    ```
1. Invoke code completion on ```model.```
1. See the exception in the notifications

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Ubuntu 21.10

### JDK

JDK17

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
just tested it and its also reproducible while using javac of 17.0.2 and 18+36. So we can rule out it being nb-javac specific.

**Comment by lkishalmi** [comment]
It seems #3924 was not a solution on this after all.

**Comment by ShadowOfLies** [comment]
Re-tested this on NB 22 and the latest master branch, using both JDK21 and JDK17 on Ubuntu.

The referenced use case is no longer reproducible and the issue has likely been fixed during the last 2 years of development.

**Comment by matthiasblaesing** [comment]
@ShadowOfLies thanks for checking and reporting. I can verify, so lets close this again ;-)
