### ISSUE TITLE
Add Open in terminal for Project

### ISSUE THREAD

**Issue by PashaTurok** [apache/netbeans#3922]
### Description

In Projects Tab we have list of project. When we use console, we often need to enter the root of the project. So, it would be nice, if we could do right click on project (for example, maven project) and choose `Open in terminal` and get terminal in the root folder of the project. This feature exists in VS Code ans is widely used. For example, when we need basic operations like clean, build etc.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by jtulach** [comment]
Select root of a project. Choose from menu Tools/Open in Terminal.

**Comment by PashaTurok** [comment]
@jtulach Thank you for your answer. The idea of this issue to open project in terminal without opening and looking through project tree. In projects tab we first of all have projects. With right click on project (not on some of nodes of project tree) we should have ability to open project in terminal. Please, look, how it is implemented in other IDE's. 

I am not speaking here how to get the same result - there are a few ways to get it. I am talking how to get this result the most convenient way.

**Comment by neilcsmith-net** [comment]
I agree with @PashaTurok - I think this is a valid feature request.  You can do it on package nodes, basic folders, etc. already.  Makes sense on project nodes, and something I used to find deeply frustrating.

The other workaround is to use `ALT-SHIFT-K` with a project or file selected.

**Comment by PashaTurok** [comment]
I also should fix this issue https://github.com/apache/netbeans/issues/3822  - because, now it is possible to open terminal from any node, but the most important keys in terminal simply don't work.

**Comment by robozb** [comment]
> Select root of a project. Choose from menu Tools/Open in Terminal.

You saved my life :) Thank you!
