### ISSUE TITLE
Add java regex flags for text matching and Example generator from Regular Expression

### ISSUE THREAD

**Issue by mishrasandeep** [apache/netbeans#3927]
### Description

![Regex-Flags](https://user-images.githubusercontent.com/72914639/161727408-db830eb9-b58e-4109-a62f-1e5efc879ef0.gif)

### Use case/motivation

The Java Pattern Class Flags can be used while string matching in the Check Regex Window. The IDE can give these options and can also generate examples from the Regular Expression.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment]
Please don't open an issue if you have a pull request. This information / example screencast should be in the PR.

**Comment by mishrasandeep** [comment]
@neilcsmith-net Sure. Thanks for the input. Was trying to migrate a JIRA issue to Github issues.
