### ISSUE TITLE
Validate external snippet attributes like file, class, region to check for improper attribute values (JEP-413)

### ISSUE THREAD

**Issue by MegJayan** [apache/netbeans#3937]
### Description

Add validation for external snippet attributes like file, class, region to check if invalid/empty attr values are provided.
![External-Snippet validation](https://user-images.githubusercontent.com/100354762/162122556-3c608c2b-b3ea-49bf-86da-11cd7a5eb572.gif)

### Use case/motivation

Added to check if values entered by user for the external snippet attributes(file, class, region) are proper or not and throws error dialog in case of invalid values.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by MegJayan** [comment]
Closing the issue raised for feature demonstration

**Comment by mbien** [comment]
@MegJayan awesome feature. Btw the issue would close itself automatically if the PR is integrated since it was linked to the PR. But closing it manually is fine too :)
