### ISSUE TITLE
Background scanning of npm projects 

### ISSUE THREAD

**Issue by BD-A** [apache/netbeans#3943]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Installed from dmg installer

Steps taken:

 **1:**

Config imported from version 12.6 on NB start

Regular php projects scans quickly, but when a node project is opened background scanning starts again and get stuck.

Not possible cancel running task from bottom status bar (not responding / not cancelling )

On IDE exit dialog appears that following processes will be terminated: Background scanning of projects

 **2:**

Removed caches in:
> User directory: /Users/WebMac3/Library/Application Support/NetBeans
> Cache directory: /Users/WebMac3/Library/Caches/NetBeans

Preferences from 12.6 **not imported** on NB launch

Added node and npm paths to Preferences/html/node.js

Disabled auto scanning of projects in Preferences/Miscellaneous/Files

Opened existing node project

Background scanning jumps to 50% and stuck

Not possible cancel running task from bottom status bar (not responding / not cancelling )

On IDE exit dialog appears that following processes will be terminated: Background scanning of projects

System:

> Product Version: Apache NetBeans IDE 13
> Java: 18; OpenJDK 64-Bit Server VM 18+0
> Runtime: OpenJDK Runtime Environment 18+0
> System: Mac OS X version 12.3 running on x86_64; UTF-8; es_ES (nb)
> User directory: /Users/WebMac3/Library/Application Support/NetBeans/13
> Cache directory: /Users/WebMac3/Library/Caches/NetBeans/13

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

MacOS 12.3 (Monterrey)

### JDK

OpenJDK Runtime Environment Homebrew (build 18+0)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
This could be https://github.com/apache/netbeans/issues/3669 or https://github.com/apache/netbeans/issues/4038. Closing this as there is not enough to work on.
