### ISSUE TITLE
[cnd] gdb debugger on Windows

### ISSUE THREAD

**Issue by vieiro** [apache/netbeans#3947]
### Description

The cnd debugger fails with gdb on Windows [as reported in the users mailing list](https://lists.apache.org/thread/p8jvq14qtcjbp2xg8wl3rlm1vnj5296f)

The problem was reported with the C/C++ plugins from NetBeans 8.2, and has been inherited. Both MINGW and CYGWIN gdb fail.

It seems both paths to source files and binaries are wrong. Will try to attach a log file.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by vieiro** [comment]
Debugger log file

[gdb-cmds8524435212509870501.log,txt](https://github.com/apache/netbeans/files/8455823/gdb-cmds8524435212509870501.log.txt)

**Comment by vieiro** [comment]
The debugger log file, after https://github.com/apache/netbeans/issues/3947 is applied: NetBeans is sending proper "Cygwin-like" file names to gdb again, so gdb can understand what we're debugging and where the breakpoints are.

[nb-gdb-log-2.txt](https://github.com/apache/netbeans/files/8464676/nb-gdb-log-2.txt)

**Comment by mbien** [comment]
@vieiro this can be closed, right? I suppose gh didn't close it since it isn't in master yet.

**Comment by vieiro** [comment]
Ah, ok. Let's close it. Thanks, @mbien !
