### ISSUE TITLE
Invalid php error detection for ReadOnly google class

### ISSUE THREAD

**Issue by wadealer** [apache/netbeans#3972]
### Apache NetBeans version

Apache NetBeans 13

### What happened

NetBeans 13 detects error at google grpc-gcp library for line 
`$ro = new Google\Cloud\Spanner\V1\TransactionOptions\ReadOnly();`

It shows error "Syntax error. Unexpected readonly after \; expected identifier.
With 12.6 there is no such issue.

### How to reproduce

Add this library to project and NetBeans shows error inside vendor.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 10

### JDK

16.0.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
NetBeans 13 has partial support for PHP 8.1 and "readonly" is reserved keyword (https://wiki.php.net/rfc/readonly_properties_v2).

NetBeans always supports only latest version of PHP - it means that "readonly" is now always recognized as keyword even if you set lower PHP version in settings.

Related issue: https://githubhot.com/repo/googleapis/google-cloud-php/issues/5129

**Comment by wadealer** [comment]
I have a question. Is there any way to filter out `vendor` folder from error analyzing?
