### ISSUE TITLE
Replace invalid chars when pasting text into branch name when creating a new branch

### ISSUE THREAD

**Issue by jepsar** [apache/netbeans#3980]
### Description

When you create a new branch, it would be nice if you would be able to just paste the description copied from the issue tracker into the branch name. Now you will get a "invalid branch name" when it (for example) contains spaces. If those invalid chars could be replaced with underscores, that would speed things up a lot.

### Use case/motivation

Creating branches simply isn't fun now, as you need to replace invalid chars by hand.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by mbien** [comment]
sounds like a good first issue. Added it to the [list](https://github.com/apache/netbeans/labels/good%20first%20issue)

**Comment by jepsar** [comment]
For anyone ending up here by searching: this feature must be enabled first:

<img width="851" alt="Screenshot 2022-09-27 at 15 56 16" src="https://user-images.githubusercontent.com/7500178/192546827-2af745b3-e047-4944-9650-72de6f397521.png">
