### ISSUE TITLE
lombok 1.18.24

### ISSUE THREAD

**Issue by sysmat** [apache/netbeans#3997]
### Description

when using lombok:1.18.24 NetBeans 12.5, 13 not recognize classes

### Use case/motivation

to upgrade lombok

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by sysmat** [comment]
hm, now it works in NB 13, but not in NB 12.5

**Comment by matthiasblaesing** [comment]
Closing - lombok is known to be problematic. If there is a reproducible case it can be looked into. Without it no diagnosis is possible.
