### ISSUE TITLE
[macos] website steps Building from Source probably deprecated 

### ISSUE THREAD

**Issue by ans1genie** [apache/netbeans#4016]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Using MacOS:  
Following the steps, the path was not found after the ant run was completed. 
step: cd to that directory, and then run ant to build the Apache NetBeans IDE. Once built you can run the IDE by typing ./nbbuild/netbeans/bin/netbeans

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/16513804/164573935-4d0fdb1d-53eb-4876-8231-0183133df8de.png">

https://netbeans.apache.org/download/nb13/nb13.html

### How to reproduce

Building from Source
To build Apache NetBeans 13 from source you need:

A distribution of OpenJDK 8 or 11.

Apache Ant 1.10 or greater (https://ant.apache.org/).

Once you have everything installed then:

Unzip [netbeans-13-source.zip](https://www.apache.org/dyn/closer.cgi/netbeans/netbeans/13/netbeans-13-source.zip) in a directory of your liking.

cd to that directory, and then run ant to build the Apache NetBeans IDE. Once built you can run the IDE by typing ./nbbuild/netbeans/bin/netbeans

### Did this work correctly in an earlier version?

I don't know

### Operating System

MacOS

### JDK

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12-39) OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ebarboni** [comment]
Hi, does your ant  end with build successful or build failed ?
like this:

BUILD SUCCESSFUL
Total time: 6 minutes 8 seconds

Minimum  jdk is 11  we should remove 8 , not sure it can be build on jdk 17.

**Comment by neilcsmith-net** [comment]
For NB14 page we should make sure to remove JDK 8. NB13 can actually be built with JDK 8.

NB13 definitely doesn't support being built with JDK 17. I think NB14 might now - haven't tested personally yet.

I think this issue can be closed. The instructions look correct to me.

**Comment by mbien** [comment]
@neilcsmith-net the github actions build `ant -Dcluster.config=release build-nozip` on both JDK 11 and 17. So unless something is automatically skipped on 17, it should build just fine.

**Comment by mbien** [comment]
@ans1genie if you want to build NetBeans on JDK 17, just wait a little bit until NetBeans 14 is released and try again. For NetBeans 13 you will need JDK 11, it won't work with 17.

closing this issue since the instructions do look correct for me too
