### ISSUE TITLE
In "Projects" for Gradle projects, please sort entries in the "Sub Projects" branch

### ISSUE THREAD

**Issue by demonti** [apache/netbeans#4019]
### Description

When using Netbeans 13.0 with Gradle projects, the "Projects" tool window shows various information, among these a subtree named "Sub Projects". Within this subtree, the various Gradle subprojects are shown in the correct hierarchy, but in random order. For larger projects, this is confusing; it would be better if they are sorted alphabetically.

BTW: I am not a native English speaker, but IMHO the correct spelling is "Subprojects" (i.e. single word).

### Use case/motivation

This is a usability improvement. Sorting the entries makes them easier to be located.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by lkishalmi** [comment]
Fixed as #3861
