### ISSUE TITLE
No Java EE 8 Web Server option for TomEE 8.0.11 and TomEE 9.0.0 M7

### ISSUE THREAD

**Issue by tswern** [apache/netbeans#4027]
### Apache NetBeans version

Apache NetBeans 13

### What happened

[Tomee.pdf](https://github.com/apache/netbeans/files/8549601/Tomee.pdf)

After adding TomEE 8.0.10, 8.0.11 and 9.0.0 M7 as servers, there no option to select TomEE as Java EE 8 Web Server when creating new Web Applications

### How to reproduce

[Tomee.pdf](https://github.com/apache/netbeans/files/8549608/Tomee.pdf)

Steps to reproduce as attached. 
TomEE plume edition used:
https://tomee.apache.org/download.html

A similar issue was experienced on Netbeans 12.5

### Did this work correctly in an earlier version?

No

### Operating System

Microsoft Windows [Version 10.0.19044.1645]

### JDK

Microsoft Windows [Version 10.0.19044.1645]

### Apache NetBeans packaging

Third-party package

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by johbor** [comment]
I wanted to submit this bug, but this one is exactly what is happening when you want to create a ANT based web project.
And after the EE 7 web project is created you can't change the version afterwards and you get only the deployment descriptors belonging to EE 7.

I'm using Netbeans 13 om MacOS 12.3.1 and JDK 11.0.14.1 (x86_64) "Eclipse Temurin" and Tomee 8.0.11

<img width="810" alt="Screenshot 2022-05-15 at 17 05 59" src="https://user-images.githubusercontent.com/9353297/168480084-ff303437-8887-407c-a4f1-f19f975ac55f.png">

**Comment by pepness** [comment]
Fix with [PR-4822](https://github.com/apache/netbeans/pull/4822)
