### ISSUE TITLE
Unable to start TomEE 9 and TomEE 8 within Netbeans

### ISSUE THREAD

**Issue by tswern** [apache/netbeans#4028]
### Apache NetBeans version

Apache NetBeans 13

### What happened

When TomEE 8 or TomEE 9 added as servers within Netbeans, they are not able to be started from within the IDE.

However, they are able to start without issues by running the startup.bat file external to the IDE.

TomEE 8 & 9 can only be started by editing the startup.bat file and removing double quotes in front of the "set" keyword.

### How to reproduce

[TomEE9-cannot-start-in-netbeans.pdf](https://github.com/apache/netbeans/files/8549848/TomEE9-cannot-start-in-netbeans.pdf)

### Did this work correctly in an earlier version?

No

### Operating System

Microsoft Windows [Version 10.0.19044.1645]

### JDK

Oracle Java(TM) SE Runtime Environment (build 1.8.0_311-b11)

### Apache NetBeans packaging

Third-party package

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by pepness** [comment]
@tswern Can you test with NB17 or master ? Maybe [PR-4822](https://github.com/apache/netbeans/pull/4822) fix this too.

**Comment by mbien** [comment]
going to close this since the issue was filed against NB 13 and we are at 19 now. This is likely already fixed as mentioned above.
