### ISSUE TITLE
CDI bean as "@Named" is not listed in the xhtml for selection (Jakarta EE version 9.1.0)

### ISSUE THREAD

**Issue by howardfun** [apache/netbeans#4035]
### Apache NetBeans version

Apache NetBeans 13

### What happened

CDI bean is supposed to be found in the xhtml file after typing the "#{}" keyword. Also, when ctrl + click on class/ method name of CDI statement in xhtml, the "go to declaration" function is not working in the Netbeans IDE.

*Found that the bug can be fixed when turning it back to Jakarta EE 8.0.0 version instead of 9.1.0. Second, change the "jakarta.xxxx" back to "javax.xxxx" for a temporary fixing.

### How to reproduce

Please use the example here to reproduce 
https://github.com/juneau001/jakarta_cdi_reservations

Open the part 2 project, open the "reservations.xhtml" file in Apache Netbean 13 (in fact, it is also happen in version 12).

<p:inputText id="firstName" value="#{reservationController.currentReservation.firstName}"/>

When you ctrl + click on the  "currentReservation" or "firstName", Netbeans not able to "go to declaration".

Besides, when type the "#{}" the CDI bean is not even found in the list as captured below:

![image](https://user-images.githubusercontent.com/53899971/165225760-f18f1590-ba9d-41c8-8528-653a4e6645d6.png)

I believe a similar error is like the following:
https://bz.apache.org/netbeans/show_bug.cgi?id=178687

Lastly, the workaround is to change the Jakarta EE version from 9.1.0 back to 8.0.0 and change the "jakarta.xxxx" to "javax.xxxx" for all java files. This works but defeats the purpose, please take note.

I hope this bug can be solved very soon as this already spent me a long time to try and error.  Thank you in advance!

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10 home edition

### JDK

OpenJDK 11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mtbadi39** [comment]
Hey !
May be its related with #4033, in my case am using **Spring @Component** not **CDI** in a [Joinfaces](https://github.com/joinfaces/joinfaces/releases/tag/5.0.0-m2) project (JSF + Spring Boot).

**Comment by howardfun** [comment]
> Hey ! May be its related with #4033, in my case am using **Spring @component** not **CDI** in a [Joinfaces](https://github.com/joinfaces/joinfaces/releases/tag/5.0.0-m2) project (JSF + Spring Boot).

Thanks for the comment, but this is a different issue as I checked.

**Comment by fakhrkh** [comment]
> ### Apache NetBeans version
> Apache NetBeans 13
> 
> ### What happened
> CDI bean is supposed to be found in the xhtml file after typing the "#{}" keyword. Also, when ctrl + click on class/ method name of CDI statement in xhtml, the "go to declaration" function is not working in the Netbeans IDE.
> 
> *Found that the bug can be fixed when turning it back to Jakarta EE 8.0.0 version instead of 9.1.0. Second, change the "jakarta.xxxx" back to "javax.xxxx" for a temporary fixing.
> 
> ### How to reproduce
> Please use the example here to reproduce https://github.com/juneau001/jakarta_cdi_reservations
> 
> Open the part 2 project, open the "reservations.xhtml" file in Apache Netbean 13 (in fact, it is also happen in version 12).
> 
> <p:inputText id="firstName" value="#{reservationController.currentReservation.firstName}"/>
> 
> When you ctrl + click on the "currentReservation" or "firstName", Netbeans not able to "go to declaration".
> 
> Besides, when type the "#{}" the CDI bean is not even found in the list as captured below:
> 
> ![image](https://user-images.githubusercontent.com/53899971/165225760-f18f1590-ba9d-41c8-8528-653a4e6645d6.png)
> 
> I believe a similar error is like the following: https://bz.apache.org/netbeans/show_bug.cgi?id=178687
> 
> Lastly, the workaround is to change the Jakarta EE version from 9.1.0 back to 8.0.0 and change the "jakarta.xxxx" to "javax.xxxx" for all java files. This works but defeats the purpose, please take note.
> 
> I hope this bug can be solved very soon as this already spent me a long time to try and error. Thank you in advance!
> 
> ### Did this work correctly in an earlier version?
> No
> 
> ### Operating System
> Windows 10 home edition
> 
> ### JDK
> OpenJDK 11
> 
> ### Apache NetBeans packaging
> Apache NetBeans provided installer
> 
> ### Anything else
> _No response_
> 
> ### Are you willing to submit a pull request?
> No
> 
> ### Code of Conduct
> Yes

I'm having the same issue when using Jakarta naming instead of javax

**Comment by adamo901** [comment]
I have the same issue with Netbeans 15 with OpenJDK 11 on MacOS 12.6

**Comment by king-martinien** [comment]
I have the same issue with Netbeans 17 with OpenJDK 17 on Pop OS

**Comment by saladmaker** [comment]
I have the same issue with (Netbeans 17 + Jakarta EE 10 projects).

**Comment by juneau001** [comment]
I believe that I have a fix for this issue on the way.  Thanks for the reports.  Josh JuneauOn Apr 12, 2023, at 4:55 PM, saladmaker ***@***.***> wrote:﻿
I have the same issue with (Netbeans 17 + Jakarta EE 10 projects).

**Comment by saladmaker** [comment]
There is a strange behavior with Facelet pages autocompletion some times it gives you angular properties suggestions I believe.
It would be great if the angular support could be disabled all together because as of now it's part html5 support I think.

**Comment by juneau001** [comment]
I am placing a PR that should repair this issue.  The PR contains a new module jakarta.web.beans so that the Jakarta EE namespace is supported for CDI injection.

**Comment by saladmaker** [comment]
> 
Netbeans 17 doesn't support the Jakarta Faces new namaspace like jakarta.faces.html and others, but it supports old ones.

**Comment by asbachb** [comment]
> > 
> 
> Netbeans 17 doesn't support the Jakarta Faces new namaspace like jakarta.faces.html and others, but it supports old ones.

see https://github.com/apache/netbeans/pull/6096

**Comment by hichamglia** [comment]
I have the same issue with Netbeans 18

**Comment by asbachb** [comment]
@hichamglia It should be fixed in upcoming release NB19. There's a currently a release candidate feel free to verify.

**Comment by hichamglia** [comment]
it is working perfectly with Netbeans 19. Thanks a lot
