### ISSUE TITLE
Background scanning of projects stalls

### ISSUE THREAD

**Issue by Jakub-Plan-d-k** [apache/netbeans#4038]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I am now using NetBeans 12.3 and I wanted to switch to 13 (and to 12.6 earlier, but encountered the same problem). The PHP/JS projects, which open normally in 12.3, cause the background scanning of projects to stall at 78%. Also the go-to-declaration (ctrl+click) does not seem to work in version 13, but I assume it is because the scanning was not completed? Also looks like the memory usage is around 2x higher in version 13 on startup of the same projects.

I am getting the following 2 errors (first the 1. one, then the 2. one), please find logs for both of them attached (too long to paste)
[error1.txt](https://github.com/apache/netbeans/files/8571237/error1.txt)
[error2.txt](https://github.com/apache/netbeans/files/8571238/error2.txt)

Overall, the updates (12.6 and 13) are completely unusable and I am still using 12.3. 

### How to reproduce

1) Install version 13,
2) Open the program and import project from previous version
3) Try to use the program, but not possible. 
4) Close and open again - happens on every time on startup.

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10

### JDK

JDK16, JAVA_VERSION_DATE="2021-03-16", OS_ARCH="x86_64", OS_NAME="Windows", SOURCE=".:git:eb3a076a428e open:git:4de3a6be9e60"

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

The projects were imported after the installation discovered an older version of Netbeans. In case of the 12.6 I installed previously, it imported them from 12.3, in case of 13 now, it imported them from 12.6. 

There are 3 projects, but 2 of them matter - they are quite big (both around 55000 files, out of this node_modules is 44000) and also contain some (~750kB) vue compiled js files. npm is not managed through Netbeans in this case. 

PHP version is 8 in case of one of them and 7.4 in the other. 

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
Error 1 should be fixed by this PR: https://github.com/apache/netbeans/pull/3696 (it will be part of NB 14).
Error 2 looks interesting, can you pinpoint which structures causes this? My gut feeling, that this could be easily plastered over (there is only a single String#equals, that is a good candidate and that could be reworked to Objects#equals), but I'd like to have a test case.

**Comment by Jakub-Plan-d-k** [comment]
Thanks for a quick answer! I imagine NB14 is not really coming soon, since 13 has just been published? Is there any 
As per error 2 - I will see what I can do. Hope I can answer within a week from now. From what I understand from the backtrace, it is connected with JS, right?

**Comment by neilcsmith-net** [comment]
@Jakub-Plan-d-k it's due in about a month. The first release candidate can be found at https://lists.apache.org/thread/hydrglnm2cst3s31tkbfgktwg4rsylgb

**Comment by matthiasblaesing** [comment]
> Hope I can answer within a week from now. From what I understand from the backtrace, it is connected with JS, right?

Yes - there is at least one JS file, where the NetBeans parser/indexer fails to correctly interpret the structure, that would be the interesting part. Last time something in that region happend it was a file generated by a transpiler, which created a recursive structure definition, which caused the analyse to choke.

**Comment by matthiasblaesing** [comment]
The second problem might be fixed by this:

https://github.com/apache/netbeans/pull/4058/commits/ede7f14da1ba2f1c6744c3c7804a5de8ce117981 - that is part of https://github.com/apache/netbeans/pull/4058 (which is a draft with general improvents for JS).
