### ISSUE TITLE
getting error java.nio.file.Path.startswith 

### ISSUE THREAD

**Issue by sharad1123** [apache/netbeans#4056]
### Apache NetBeans version

Apache NetBeans 13

### What happened

[https://ibb.co/P6cgRFw](url) i got this error every time when i add mysql jdbc connector java ,in any project

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

windows 10

### JDK

18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

no

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
It is invalid to report issues without a description (no you can't expect people to follow cryptic links) and steps to reproduce.
