### ISSUE TITLE
Run Main Project and other commands have lost their keyboard shortcuts and cannot even be added in Preferences

### ISSUE THREAD

**Issue by pandemonica** [apache/netbeans#4063]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Starting to use Apache Netbeans 13 I notice my keyboard shortcuts for clean-compile-run and compile-run no longer work.
Worse, they cannot be edited in keyboard references.

### How to reproduce

Open (on Mac) Preferences > keyboard shortcuts

click in Search by name box

enter run

None of the choices allow to run the project in any manner.

Another manifestation:

Click and hold Run menu. There is no keyboard shortcut on the first entry, "Run Main Project"
and none can be added no way nohow.

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

MacOS Monterey 12.3.1

### JDK

JDK17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by pandemonica** [comment]
This goes all the way to pull-down menus. In V12.3 I can see Save and Save All have Command-S and Shift-Command-S shortcuts.

In V13, these shortcut indications are missing.

Picture shows V12.3 -- Had problems getting a V13 screenshot.

![Menu commands V12 3](https://user-images.githubusercontent.com/1839342/166315757-492a014b-8e17-4117-bb9e-65b57019640e.png)

**Comment by neilcsmith-net** [comment]
Did you upgrade from a previous version and import settings?  Does running with a clean userdir and cache dir (see locations in Help / About) show the same issue?

**Comment by pandemonica** [comment]
I imported settings from 12.3
I will check the dirs.

**Comment by pandemonica** [comment]
I removed the offending dirs and restarted. It fixed the problem. I have Command-S for save, etc.

Only one I'm missing is the stop run shortcut. Doesn't seem to be any way to add it in keymap. I know I used to have a shortcut key under 12.3 :-) 

Thanks for sorting this  for me.
