### ISSUE TITLE
Netbeans 13 Crash with out of memory

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#4065]
### Apache NetBeans version

Apache NetBeans 13

### What happened

* My laptop started running slow.
* I went to the console and looked in the `syslog` file, _viz_.:

```
May  3 10:32:35 4TELLT132 kernel: [421366.701123] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-org.apache.netbeans-393562.scope,task=java,pid=393802,uid=1000
May  3 10:32:35 4TELLT132 kernel: [421366.701215] Out of memory: Killed process 393802 (java) total-vm:13589940kB, anon-rss:1715920kB, file-rss:0kB, shmem-rss:148kB, UID:1000 pgtables:5180kB oom_score_adj:0
May  3 10:32:35 4TELLT132 kernel: [421366.778631] oom_reaper: reaped process 393802 (java), now anon-rss:0kB, file-rss:0kB, shmem-rss:148kB
May  3 10:31:03 4TELLT132 rtkit-daemon[1415]: message repeated 15 times: [ Supervising 1 threads of 1 processes of 1 users.]
May  3 10:32:35 4TELLT132 systemd[1]: session-c2.scope: A process of this unit has been killed by the OOM killer.
May  3 10:32:35 4TELLT132 systemd[2145]: app-flatpak-org.apache.netbeans-393562.scope: A process of this unit has been killed by the OOM killer.
May  3 10:32:35 4TELLT132 systemd[1]: user@1000.service: A process of this unit has been killed by the OOM killer.
```

* Fortunately I'm running netbeans from the terminal so I have output from the failed Netbeans command:
   *  `flatpak run org.apache.netbeans -J-Dawt.useSystemAAFontSettings=on`
   * `--jdkhome /opt/lib/java/jdk/v17.00`
   * `--userdir $HOME/.config/netbeans/v13.00/4ams/v17.00/user-02`
   * `--cachedir $HOME//.cache/netbeans/v13.00/4ams/v17.00/cache-02`

```
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/app/netbeans/platform/lib/nbexec: line 434:   225 Killed                  "/opt/lib/java/jdk/v17.00/bin/java" -Djdk.home="/opt/lib/java/jdk/v17.00" -classpath "/app/netbeans/platform/lib/boot.jar:/app/netbeans/platform/lib/org-openide-modules.jar:/app/netbeans/platform/lib/org-openide-util.jar:/app/netbeans/platform/lib/org-openide-util-lookup.jar:/app/netbeans/platform/lib/org-openide-util-ui.jar" -Dnetbeans.default_userdir_root="/home/william/.netbeans" -Dnetbeans.running.environment=gnome -Dnetbeans.dirs="/app/netbeans/nb:/app/netbeans/ergonomics:/app/netbeans/ide:/app/netbeans/extide:/app/netbeans/java:/app/netbeans/apisupport:/app/netbeans/webcommon:/app/netbeans/websvccommon:/app/netbeans/enterprise:/app/netbeans/mobility:/app/netbeans/profiler:/app/netbeans/python:/app/netbeans/php:/app/netbeans/identity:/app/netbeans/harness:/app/netbeans/cnd:/app/netbeans/cndext:/app/netbeans/cpplite:/app/netbeans/dlight:/app/netbeans/groovy:/app/netbeans/extra:/app/netbeans/javacard:/app/netbeans/javafx:" -Dnetbeans.home="/app/netbeans/platform" '-Dnetbeans.importclass=org.netbeans.upgrade.AutoUpgrade' '-Djava.io.tmpdir=/var/tmp' '-XX:+UseStringDeduplication' '-Xss2m' '-Dapple.laf.useScreenMenuBar=true' '-Dapple.awt.graphics.UseQuartz=true' '-Dsun.java2d.noddraw=true' '-Dsun.java2d.dpiaware=true' '-Dsun.zip.disableMemoryMapping=true' '-Dplugin.manager.check.updates=false' '-Dnetbeans.extbrowser.manual_chrome_plugin_install=yes' '--add-opens=java.base/java.net=ALL-UNNAMED' '--add-opens=java.base/java.lang.ref=ALL-UNNAMED' '--add-opens=java.base/java.lang=ALL-UNNAMED' '--add-opens=java.base/java.security=ALL-UNNAMED' '--add-opens=java.base/java.util=ALL-UNNAMED' '--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED' '--add-opens=java.desktop/javax.swing.text=ALL-UNNAMED' '--add-opens=java.desktop/javax.swing=ALL-UNNAMED' '--add-opens=java.desktop/java.awt=ALL-UNNAMED' '--add-opens=java.desktop/java.awt.event=ALL-UNNAMED' '--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED' '--add-opens=jdk.jshell/jdk.jshell=ALL-UNNAMED' '--add-modules=jdk.jshell' '--add-exports=java.desktop/sun.awt=ALL-UNNAMED' '--add-exports=java.desktop/java.awt.peer=ALL-UNNAMED' '--add-exports=java.desktop/com.sun.beans.editors=ALL-UNNAMED' '--add-exports=java.desktop/sun.swing=ALL-UNNAMED' '--add-exports=java.desktop/sun.awt.im=ALL-UNNAMED' '--add-exports=java.desktop/com.sun.java.swing.plaf.motif=ALL-UNNAMED' '--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED' '--add-exports=java.management/sun.management=ALL-UNNAMED' '--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' '--add-exports=jdk.jdeps/com.sun.tools.classfile=ALL-UNNAMED' '--add-exports=jdk.jdeps/com.sun.tools.javap=ALL-UNNAMED' '--add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED' '--add-opens=java.desktop/javax.swing.plaf.synth=ALL-UNNAMED' '--add-opens=java.desktop/com.sun.java.swing.plaf.gtk=ALL-UNNAMED' '--add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED' '--add-opens=java.desktop/sun.awt.im=ALL-UNNAMED' '--add-opens=java.base/java.nio=ALL-UNNAMED' '-XX:+IgnoreUnrecognizedVMOptions' '-Dawt.useSystemAAFontSettings=on' -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/home/william/.config/netbeans/v13.00/4ams/v17.00/user-02/var/log/heapdump.hprof" -Djava.security.manager=allow org.netbeans.Main --cachedir "/home/william/.cache/netbeans/v13.00/4ams/v17.00/cache-02" --userdir "/home/william/.config/netbeans/v13.00/4ams/v17.00/user-02" "--branding" "nb" 0<&0

[1]+  Exit 137                flatpak run org.apache.netbeans -J-Dawt.useSystemAAFontSettings=on --jdkhome /opt/lib/java/jdk/v17.00 --userdir /home/william/.config/netbeans/v13.00/4ams/v17.00/user-02 --cachedir /home/william/.cache/netbeans/v13.00/4ams/v17.00/cache-02
```

### How to reproduce

* I do not know.
* Netbeans was started about 9 am this morning.  I have only done a gradle build.
* When it crashed, I was updating a confluency web page

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Distributor ID:	Ubuntu Description:	Ubuntu 21.10 Release:	21.10 Codename:	impish

### JDK

17.0.1.fx-zulu openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)

### Apache NetBeans packaging

Other

### Anything else

**Netbeans via flatpak**

```
$ flatpak list
Name                 Application ID                Version    Branch    Installation
  :
NetBeans           org.apache.netbeans    13            stable      system
```

**Java**

```
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)
```

**Operating system**

```
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by aplatypus** [comment]
* I have just restated Netbeans v13.  
* It only lasted about 5 minutes adn then was killed again by using too much memory:

```
May  3 11:19:11 4TELLT132 kernel: [424162.701878] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/ap
p-flatpak-org.apache.netbeans-406200.scope,task=java,pid=406443,uid=1000
May  3 11:19:11 4TELLT132 kernel: [424162.701973] Out of memory: Killed process 406443 (java) total-vm:12411404kB, anon-rss:1884300kB, file-rss:0kB, shmem-rss:56kB, UID:1000 pgtables:5228kB oom_score_adj:0
May  3 11:19:11 4TELLT132 kernel: [424162.787252] oom_reaper: reaped process 406443 (java), now anon-rss:0kB, file-rss:0kB, shmem-rss:56kB
```

* This is very strange as I've been using Netbeans v13 for several weeks on my PC at home and on this laptop.  
    *  Both systems have same configuration and use the `flatpak` install
    * Both use same command to start
    * The laptop where the error shows issues these errors at netbeans start-up: 
    	* `ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

* I have the same JDK, we use gradlew in projects and target Java 1.8 on both and haven't updated it recenlt

The important factor is that Netbeans consumes memory while it is NOT Doing Anything.

I am attaching the last log file produced from the netbeans  `$HOME/.config/netbeans/v13.00/4ams/v17.00/user-02` directory.
* [messages.log](https://github.com/apache/netbeans/files/8607807/messages.log)


* What ever is going wrong, needs to be caught by Netbeans.  It should not run rogue and consume all the memory it can.

**Comment by mbien** [comment]
would be interesting to test if the same happens outside of flatpack. I don't know the details how flatpack works, but assuming it is a regular container, it could give the JVM arbitrary RAM values if misconfigured.

you have 16GB ram is this correct? The log shows that the JVM decided to use max 4GB of that. So unless this is a non trivial leak in a native library, it wouldn't be possible for the JVM to use up all of your system memory (assuming that nothing else on your system uses it).

**Comment by neilcsmith-net** [comment]
As stated on your #3856 issue, please check if this can be reproduced with the binary zip, Linux installer or Snap package. We don't provide the flatpak package, so issues that cannot be reproduced elsewhere should be opened there.  I think that means https://github.com/flathub/org.apache.netbeans/issues

**Comment by lkishalmi** [comment]
Also it could happen that somewhere else in your system needs memory for some reason (e.g. background scheduled antivirus/maleware scan), and the Java process running NetBeans as a "fat one" could be an easy target for OOM killer.
That actually happens with me from time to time when I use my corporate VM image. (So, I turned on the auto save functionality on).

**Comment by aplatypus** [comment]
* yes 16GB ram
* Happens on different projects
* @lkishalmi ...
  * I run Clam anti-virus regularly.  Also this is a Linux system so viruses are a bilt thin (they do exist though)
  * The same project can be open in Netbeans  for days.  It sporatically gets killed by OOM (I think it is OOM)
  * The PID is the netbeans process, not another.  It got zapped today after 10 min.  
  * Since I restarted everything is fine for many hours now.

**Comment by aplatypus** [comment]
* the Netbeans ZIP didn't fail -- but neither does the flatpak version most of the time
* Mostly a want some diagnosticeor log I can look at

**Comment by lkishalmi** [comment]
Try to check at ```/var/log/kern.log```. We have removed the memory settings from NetBeans command line a few years ago. AFAIK java uses the 1/4th of the system memory (maxed at 4 Gb), for default max heap size. You can try to reduce that number by passing -J-Xmx2g to the command line (2g is just an example, of course), so OOM killer would less likely target that process.

Also you might check the Gradle daemons and the started Gradle daemon processes they could be memory hungry too.

Well, I could discuss this in more detail if you wish, though I do not think NetBeans could do anything about the OOM killer reaping it.

If you'd use the Snap version you could try:

```
snap set system resilience.vitality-hint=netbeans
```

So the OOM killer would less likely take actions against the NetBeans Snap

Source: https://snapcraft.io/docs/system-options

**Comment by aplatypus** [comment]
* snap still fails using HOME on a different device
* anyway have settled on flatpak -- don't want two "management" systems
* If we need to use the zip inistall that what we'll use.  
* This particular flatpak version emitts a bunch of messages about: `ld.so` and `LD_PRELOAD` that other set-up do not.
  * for example:
    `ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
  * I also get that error when I run or debut from inside Netbeans
  * I saw nothing in the `messages.log` file though to point a finger in that direction

**Comment by aplatypus** [comment]
Me again, fresh stuff - Just got OOM killed again:
*  Netbeans via flatpak on command line: `[1]+  Exit 137` (which is probably out of memory.
  *  At the time I was doing a gradle compile (not even a build)
  * From console output stderr: `/app/netbeans/platform/lib/nbexec: line 434:   225 Killed`
  * then it dumps the entire command line and options: [nb-command-line.txt](https://github.com/apache/netbeans/files/8705342/nb-command-line.txt)

* It looks like a lot of memory to me: **code**
```
oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-c2.scope,task=code,pid=63792,uid=1000
Out of memory: Killed process 63792 (code) total-vm:17266204kB, anon-rss:29172kB, file-rss:0kB, shmem-rss:992kB, UID:1000 pgtables:812kB oom_score_adj:200
oom_reaper: reaped process 63792 (code), now anon-rss:0kB, file-rss:0kB, shmem-rss:988kB
```
  * 17,266.204 mb  ... looks like all memory

* and this looks like the JVM(??): **java**
```
oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-org.apache.netbeans-91050.scope,task=java,pid=91287,uid=1000
Out of memory: Killed process 91287 (java) total-vm:13342636kB, anon-rss:2239304kB, file-rss:0kB, shmem-rss:184kB, UID:1000 pgtables:5992kB oom_score_adj:0
oom_reaper: reaped process 91287 (java), now anon-rss:0kB, file-rss:0kB, shmem-rss:184kBsystemd[1]: session-c2.scope: A process of this unit has been killed by the OOM killer.
rtkit-daemon[1394]: The canary thread is apparently starving. Taking action.
systemd[1]: user@1000.service: A process of this unit has been killed by the OOM killer.
rtkit-daemon[1394]: Demoting known real-time threads.
systemd[2903]: app-flatpak-org.apache.netbeans-91050.scope: A process of this unit has been killed by the OOM killer.
```
  * How does a compile get lost like this?

**Comment by lkishalmi** [comment]
Well, I'm closing this one as it is beyond what we can deal with.
