### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by max6186** [apache/netbeans#4068]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Every time I try to run the program, even just as simple as printing a string line. It just show me "java.lang.IllegalArgumentException".

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

JDK 8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
where do you see that Exception?

The most useful part of an Exception is it's stack trace, which you decided to omit.

**Comment by max6186** [comment]
when I try to run the any process.
example for a code:

class main{
public static void main(String[] args){
System.out.println("Test Code");
}
}

the weird part is when I try the same codes on other IDE, they work just fine
![IMG_0436 (1)](https://user-images.githubusercontent.com/65102624/166622494-4da0b27c-29a5-4d7a-8677-94ddc4bd477f.jpg)

**Comment by mbien** [comment]
ok, you aren't actually using NetBeans 13

I recommend getting the latest version from the link on your screenshot and running it on JDK 11 or 17 as described on the download page and everything should be working fine.
