### ISSUE TITLE
Autofocus new name field when renaming folder

### ISSUE THREAD

**Issue by SimonVanacco** [apache/netbeans#4076]
### Description

When using the "Projects" tab to rename a folder (either with right click -> refactor -> rename, or CTRL+R), the "New Name" field is not autofocused, and i think it would be really great if it was.

This behavior is already present when renaming a file in the same interface (right click -> rename) so i figure it should probably be a trivial fix.

![](https://issues.apache.org/jira/secure/attachment/13033718/13033718_image-2021-09-16-15-31-04-822.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by mbien** [comment]
@SimonVanacco what project type is this?

**Comment by SimonVanacco** [comment]
> @SimonVanacco what project type is this?

This is when renaming a folder in a PHP Project

**Comment by mbien** [comment]
ah, thanks. I can reproduce it there. It happens with PHP projects when folders or the project itself is renamed.

Giving this a good-first-issue label.
