### ISSUE TITLE
gradle build issues

### ISSUE THREAD

**Issue by mehtaab003** [apache/netbeans#4085]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

WARNING [org.openide.util.WeakListenerImpl]: Can't remove java.beans.PropertyChangeListener using method org.netbeans.modules.gradle.NbGradleProjectImpl.removePropertyChangeListener from Gradle: springmvc[FALLBACK]
WARNING [null]: Last record repeated 2 more times.

### Did this work correctly in an earlier version?

Apache NetBeans 12.5

### Operating System

windows11

### JDK

17

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
Which daily build is that? I'd hope #4001 fixed these issues.
