### ISSUE TITLE
GUI of the app not displayed fully.

### ISSUE THREAD

**Issue by Mo-Gamer-2000** [apache/netbeans#4088]
### Apache NetBeans version

Apache NetBeans 13

### What happened

The GUI of the app I created is not displaying on my laptop fully and my laptop display size is the largest that it comes in.
When I run my app on my friend's laptop which has the same display size then the GUI is displayed properly and all the information can be seen clearly. There should be a zoom in and out feature on NetBeans so we can zoom out and see the whole GUI.
![App](https://user-images.githubusercontent.com/91951677/167292107-b41bd9d3-0d74-4db2-a22e-c5363edcfc9d.png)

### How to reproduce

This bug is seen whenever the app is executed.

### Did this work correctly in an earlier version?

Apache NetBeans 12.5

### Operating System

Windows 11

### JDK

JDK 11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Everytime the app is executed.

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
This is not an issue of NetBeans. You need to learn about the different layouts Swing offers out of the box and if that is not enough learn about how to implement a LayoutManager yourself.
