### ISSUE TITLE
VS Code extension cannot organize imports alphabetically (no groupings)

### ISSUE THREAD

**Issue by stewartadam** [apache/netbeans#4092]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I would like to organize imports alphabetically - no groups. I adjusted the settings for the VS Code settings to remove all default groups, leaving only the catch-all:

```
    ...
    "netbeans.java.imports.groups": [
      ""
    ],
```

However imports are still organized by java, org, and then others (per default setting value).

### How to reproduce

1. Edit VS Code extension setting to disable groupings (per above)
2. Organize imports or save a file

### Did this work correctly in an earlier version?

No

### Operating System

MacOS 12.3.1

### JDK

OpenJDK 11 (installed via brew) and temurin 18 (MacOS)

### Apache NetBeans packaging

Apache VSNetBeans for VSCode

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by MartinBalin** [comment]
This is not planned to be done.
