### ISSUE TITLE
IDE Creates Multiple Folders as File Path is Being Typed

### ISSUE THREAD

**Issue by usernane** [apache/netbeans#4099]
### Apache NetBeans version

Apache NetBeans 13

### What happened

While trying to create a new PHP class, I was typing the location where the class will be created. As I was typing, The IDE created multiple folders that I Don't need.

## Expected to happen
Only the folders that hold the class should be created.

### How to reproduce

* Created new PHP Application
* Created new folder with name `src`
* Right-clicked on the folder and selected `New` > `PHP Class...`
* Entered `File` as class name, typed `src/webfiori/framework` as `Folder` and, `webfiori\framework` as `namespace`
* As typing the folder name, the IDE will start by creating folders.

### Did this work correctly in an earlier version?

Not Sure

### Operating System

Windows 10 version 10.0 running on amd64; Cp1252; en_US (nb)

### JDK

Java: 15.0.2; OpenJDK 64-Bit Server VM 15.0.2+7-27

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Here is an image that shows the created folders.

![image](https://user-images.githubusercontent.com/12120015/167664471-5fdd97c2-bbf6-45cc-b143-b91739fbe0e0.png)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Thanks @tmysik I realised that after debugging the problem and finding the comment about the BZ issue.  I wonder if we can approach the other way and add optional support for making the text field non-editable instead?  Anyway, feel free to close as Won't Fix if you want - was checking through open issues for things that might be NB14 relevant.

**Comment by tmysik** [comment]
This problem does not happen _so often_, I believe (therefore, not many reports in the last years :)

Let me explain - the typical situation is that one selects some existing option (directory), to add a PHP class. This issue occurs for cases, when one wants to create a new PHP class in non-existing directory (as I wrote above, hopefully not so typical use case).

**Comment by tmysik** [comment]
@junichi11 

Junichi, I am not sure if we can do something here... and disabling the field would cause more "damage" than the current situation, I think.

**Comment by tmysik** [comment]
@junichi11 

Thanks for the idea, that could work! And yes, it is a hack :)

Will you please create a PR for it? Thank you.
