### ISSUE TITLE
Starting bug

### ISSUE THREAD

**Issue by katlegokgotse** [apache/netbeans#4101]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I downloaded Apache Netbeans 13 but after sometime my netbeans did not want to open but rather opened a plain java form. It refuses to run no matter how long I have to delete the "lock" file and the program including it's files. I had to install Netbeans 12.6 until the same issue arose. It is getting tiring and demotivating trying to learn a new language and this happens. I urge and ask politely for the Netbeans team to please fix this issue.

### Did this work correctly in an earlier version?

No

### Operating System

Windows 

### JDK

17.0.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
Without steps to reproduce there is not enough to help you.
