### ISSUE TITLE
groupId completion stops working

### ISSUE THREAD

**Issue by mbien** [apache/netbeans#4102]
### Apache NetBeans version

Apache NetBeans latest master

### What happened

i noticed a problem:
 - after the IDE (NB 15 dev build) is restarted `groupId` completion in maven poms doesn't give any results
 - completion in other tags, like `artifactId` or `version` still works fine

most likely caused by #4077 since reverting to the commit before that restores the functionality. Haven't investigated any further.

since this PR is fairly small it should be easy to revert in case no solution is found until NB15, this does not affect NB14. I am filing this mostly so that we don't forget.

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

linux

### JDK

17.0.3

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
https://github.com/apache/maven-indexer/pull/201 reverting this fixes the issue. Should help to figure out what the cause is.

**Comment by matthiasblaesing** [comment]
I think the issue was introduced by:

https://github.com/apache/maven-indexer/commit/c231db602b5cea9ed20eba617de5a5a846ef5faa

A costly workaround is:

```diff
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
+++ b/java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
@@ -261,6 +261,7 @@
             File indexDirectory, String repositoryUrl, String indexUpdateUrl, List<? extends IndexCreator> indexers) throws IOException {
 
         IndexingContext context = indexer.createIndexingContext(id, repositoryId, repository, indexDirectory, repositoryUrl, indexUpdateUrl, true, true, indexers);
+        context.rebuildGroups();
         indexingContexts.put(context.getId(), context);
         return context;
     } 
``

**Comment by matthiasblaesing** [comment]
I think we need to reintroduce the caching of the groups ourselfs. Building he indexes at runtime each time the index is opened will people even more mad than the repo scanning.
