### ISSUE TITLE
VSNetBeans: Latest VSCode 1.67 breaks icons in projects views 

### ISSUE THREAD

**Issue by MartinBalin** [apache/netbeans#4113]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Installed VSNetBeans 13.0.1073 build from master and icons are broken on latest VSCode 1.67, works with 1.63.1
![Screenshot 2022-05-13 at 11 50 17](https://user-images.githubusercontent.com/26064232/168258800-8bec82dc-55e8-492f-8dc0-2e5b1e990d31.png)

### How to reproduce

Install VSIX and open any gradle or maven project.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

macOS

### JDK

graalVM 22.1 EE JDK11

### Apache NetBeans packaging

Apache VSNetBeans for VSCode

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by sdedic** [comment]
Actually it seems that this is a bug in vscode - I traced that down to commits [vscode/#d79928](https://github.com/microsoft/vscode/commit/d79928be53a807a9bff45814b6dab65bae685879) and [vscode/#a9c3c0](https://github.com/microsoft/vscode/commit/a9c3c0e4b0384fe2b2c907b94a99fda18d3f34a6) -- `ThemeIcon` specification is completely ignored in vscode 1.67, if the `TreeItem` has a `resourceUri` defined. I am going to file a bug with an example code for vscode.

**Comment by ebarboni** [comment]
is this ok now ?

**Comment by sdedic** [comment]
OK from the NBLS user's point of view, I still need to file a bug for vscode to make a real fix, will reference it here

**Comment by MartinBalin** [comment]
Yes, please file it with your sample VSIX.

**Comment by sdedic** [comment]
@MartinBalin seems I've lost the race -- there are already at least two issues filed on this: microsoft/vscode#151087 and microsoft/vscode#150610

**Comment by MartinBalin** [comment]
And it also seems fixed by https://github.com/microsoft/vscode/pull/151090 so some next iteration of vscode will have it fixed. Hopefully correctly now.
