### ISSUE TITLE
String Variables longer 100000 Characters are shown as <Unreadable> in Debug

### ISSUE THREAD

**Issue by hrotkogabor** [apache/netbeans#4123]
### Apache NetBeans version

Apache NetBeans 13

### What happened

String Variables longer 100000 Characters are shown in Debugger as <Unreadable>

instead of its content.

Tested with Netbeans 12.0 and 12.6 with Amazon Corretto open-jdk11.0.12_7 64 Bit and

Amazon Corretto open-jdk15.0.2_7 64 Bit and Oracle JDK 11.0.2

### How to reproduce

Debug a code, and give a String variable a big content. You cannot view it's content.

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Linux

### JDK

11.0.15

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Imported from https://issues.apache.org/jira/browse/NETBEANS-6382

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
Does that work with JDB? You might be stretching the limits of Java Debug protocol with that.

**Comment by hrotkogabor** [comment]
At least a save to file button would help.

**Comment by SirIntellegence** [comment]
I can confirm that this still happens with Netbeans 16

**Comment by SirIntellegence** [comment]
#5299 Fixes this

**Comment by SirIntellegence** [comment]
@matthiasblaesing This one is fixed and hasn't been closed yet.

**Comment by matthiasblaesing** [comment]
@SirIntellegence thank you for the heads-up.
