### ISSUE TITLE
NetBeans only supports obsolete node 6 debug protocol

### ISSUE THREAD

**Issue by helpmex-001** [apache/netbeans#4127]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Cannot use debug on node.js project, need some example step by step

### How to reproduce

C:\nodejs\node.exe: [DEP0062]: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` and `node --inspect-brk` instead.
Message i get on attempt to debug.

### Did this work correctly in an earlier version?

No

### Operating System

win 10 pro node 12.13.1

### JDK

13

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Forever

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by helpmex-001** [comment]
who can do something? please advise.

**Comment by matthiasblaesing** [comment]
See the referenced PR for an implementation. A test build is available here:

http://doppel-helix.eu/NetBeans-dev-dev-8c9b627ced2efe6149d4df4df5f5e6d4e62181bb-release.zip

It would be good if you could test it.

**Comment by helpmex-001** [comment]
done the settings in https://github.com/apache/netbeans/pull/4220
in 2 img we see same problems
![fail1](https://user-images.githubusercontent.com/58513382/173530381-10a7075a-5087-4660-b83d-d9f5ed1dcbe2.png)
![fail2](https://user-images.githubusercontent.com/58513382/173530397-44ea6dea-250f-497e-b0d8-bfdb1243f6fc.png)

**Comment by matthiasblaesing** [comment]
Not sure what you want to tell me. What I see is, that yo configured a node  in version 12 and then you overrode the default with the wrong protocol.

Since node 6.X the debug protocol is the "Chrome DevTools protocol". "V8 debug protocol" supported ended with the 6 series.

It would help if you would not just throw in some screenshots without context and describe what you did, what you expected and what really happened. Screenshots can help, but without context they are useless.

**Comment by helpmex-001** [comment]
you posted to set on V8, my question is simple can we debug nodejs with
netbeans, if is posible ...give example hot to set exactly for versions
nodejs like 12.

On a sceen you posted i see version 10 nodejs so i am confused

**Comment by matthiasblaesing** [comment]
I assume, that you mean the second screenshot. That screenshot was only done to show the available protocols.

> you posted to set on V8, my question is simple can we debug nodejs with netbeans, if is posible

Yes - I tried it with a simple script. And could inspect variables, single step through the code, set breakpoints and in general do what I'd expect from a debugger. 

> ...give example hot to set exactly for versions nodejs like 12. On a sceen you posted i see version 10 nodejs so i am confused

As written node 6+ is "Chrome DevTools protocol" and this is also true for 12.

**Comment by helpmex-001** [comment]
i selected Chrome DevTools protocol booth in tools options...and project options
it say please wait 
![fail3-15062022](https://user-images.githubusercontent.com/58513382/173807589-3eb94930-f617-4164-a2fd-c03fe8789e9d.png)
When i stop de debbuger and try again...
Netbeans go in a state where i cannot click on any button , in task manager it do not say "Not reponding"
I used your link distribution to try.

**Comment by matthiasblaesing** [comment]
Please show the message log from the NetBeans run (See: https://stackoverflow.com/questions/50462124/netbeans-where-to-find-the-ide-log). Please also get a thread dump from the moment where NetBeans seems to be unresponsive. With a JDK installed you can run:

```
# Get the PID of the Java process (look for the entry named "Main")
jps
# Get the threaddump
jstack <PID> > stacktrace.txt
```

**Comment by matthiasblaesing** [comment]
Changing milestone to NB16 - I currently have no personal use case and the reported did not yet test.

**Comment by neilcsmith-net** [comment]
I'm removing milestone from this issue entirely. @matthiasblaesing please feel free to manage this one as you wish.

**Comment by ChristoforosKor** [comment]
Hello, I am having the same problem with Netbeans 19 on Centos 9.  At my HTML/JS node options there is not any debug protocol to choose. 
How can I resolve it?

**Comment by matthiasblaesing** [comment]
@ChristoforosKor what do you want to do? If you want to debug code running in a webbrowser, this is not the right PR. This is about debugging CLI node programms. In theory the Chrome Developer Tools Protocol can be used with Chrome/Chromium, but given lack of interest in this, I did not followup. I don't like Chrome and Firefox seems to have only a very limited implementation of CDT available, that at my time of checking did not include JS debugging.

**Comment by ChristoforosKor** [comment]
I want to debug a node application.


με εκτίμηση
Χριστόφορος Κορυφίδης

κιν./mob. : +30 6932606269
Διεύθυνση: Κώτσου 9, 34100 Χαλκίδα.
Address   : Kotsou 9,  34100 Chalkida Greece.

**Comment by ChristoforosKor** [comment]
Hello, 
Anyone can help? I am using netbeans 19 on a centos 8 pc for development.
I cannot start the debugger cause I get the message that I use the old version of debugging tools.
I also don't see a way to select a debug protocol on options like those shown at https://github.com/apache/netbeans/issues/4127#issuecomment-1154873407 as seen at the screen shots below.

![screenshot_node](https://github.com/apache/netbeans/assets/9007569/87517f84-564e-4b4d-bc4d-9ed1c311ae20)

![screenshot_properties](https://github.com/apache/netbeans/assets/9007569/e855f4da-acab-409a-88cc-3d40d78a159e)


Any help is appreciated.

**Comment by matthiasblaesing** [comment]
@ChristoforosKor  please give this some time. PR #4220 was bitrotting for more than a year because no further testing happend, I'll not just drop everything just because now the question is raised again. The debug options are not there because #4220 was never finalized.

**Comment by matthiasblaesing** [comment]
@ChristoforosKor please have a look at PR #4220. I updated it to be based on current master. This should allow you to test whether that would help you. The Checks page offers a testable development build:

- Test summary page: https://github.com/apache/netbeans/actions/runs/6449668960
- Direct link to download: https://github.com/apache/netbeans/suites/17008902928/artifacts/971564310

**Comment by matthiasblaesing** [comment]
@ChristoforosKor did this work for you?

**Comment by ChristoforosKor** [comment]
@matthiasblaesing Hello, I am sorry, I am not able to download from https://github.com/apache/netbeans/suites/17008902928/artifacts/971564310.
I get a 404 error (following is the response from wget):
 wget https://github.com/apache/netbeans/suites/17008902928/artifacts/971564310
--2023-10-15 10:24:54--  https://github.com/apache/netbeans/suites/17008902928/artifacts/971564310
Εύρεση του github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... συνδέθηκε.
Η αίτηση για HTTP στάλθηκε, αναμονή απάντησης... 404 Not Found
2023-10-15 10:25:35 ΣΦΑΛΜΑ 404: Not Found.

Translating the above from greek language to english
wget https://github.com/apache/netbeans/suites/17008902928/artifacts/971564310
--2023-10-15 10:24:54--  https://github.com/apache/netbeans/suites/17008902928/artifacts/971564310
Searching github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP send, waiting for response... 404 Not Found
2023-10-15 10:25:35 Error 404: Not Found.

**Comment by matthiasblaesing** [comment]
Don't know what github did to break downloads, but it works from browser. Please try again.

**Comment by neilcsmith-net** [comment]
As far as I know you need to be signed in to GitHub to download workflow artefacts, so it might be that (although 404 an odd response).

**Comment by matthiasblaesing** [comment]
@neilcsmith-net you are right. In a private browsing tab I can open the checks results overview page, but the artifact is not accessible. In this case a 404 is indeed wrong and 403 or 401 would be right.

**Comment by ChristoforosKor** [comment]
Ok, O downloaded  ( I was loged in) and I managed to debug with chrome dev tools.
Thanks a lot!.

Will this patch be imported in the next version (20)?

**Comment by matthiasblaesing** [comment]
@ChristoforosKor thank you for the check. No this will not make it for NB20. I'll have to get back into the PR, rereview it and get it into a mergeable state.

**Comment by ChristoforosKor** [comment]
Hello, 

Is this available on 21 release or will it be available on 22 release?

**Comment by matthiasblaesing** [comment]
@ChristoforosKor thank you for the reminder. I just merged the change to master - if nothing catastrophic happens, the change will be part of NB22.
