### ISSUE TITLE
SSH Key Based login Bug OpenSSH

### ISSUE THREAD

**Issue by nadeemshafi9** [apache/netbeans#4132]
### Apache NetBeans version

Apache NetBeans 13

### What happened

When adding an ssh connection for remote files using windows and netbeans 13 as client connecting to ubuntu 22 server it fails key auth. On Ubuntu 22 by default ssh-rsa is disabled in (ubuntu 22 and latest openssh ) since recent - Encryptions and cyphers can get a little complex when setting these up if your not a master of encryption so netbeans should work out of the box as it normally does, all my terminals, putty, windows powershell etc can ssh into the ubuntu 22 machine with no issue they adapt to the default openssh server PubkeyAcceptedAlgorithms setting. 

When ssh-rsa is disabled on the ubuntu 22 machine in sshd_config in variable PubkeyAcceptedAlgorithms netbeans cant connect.

Netbeans however fails until i enable the following - note ssh-rsa at the begging, remove ssh-rsa and netbeans connection breaks add it back and it works, by default PubkeyAcceptedAlgorithms  is not defined in openssh sshd_config everything after ssh-rsa is default according to openssh docs.

PubkeyAcceptedAlgorithms ssh-rsa,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256

i have read its got something to do with com-jcraft-jsch.jar

ubuntu 18 or < worked fine with their version of openssh.

### How to reproduce

create an ubuntu 22 server, setup a key and try to create a new project via remote files ssh using private key

### Did this work correctly in an earlier version?

No

### Operating System

windows 10 home

### JDK

java version "18.0.1.1" 2022-04-22 Java(TM) SE Runtime Environment (build 18.0.1.1+2-6) Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

openssh say ssh-rsa is weak that's why the disabled it by default

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
can you test if this is still a problem with 14rc4?
https://lists.apache.org/thread/6yvfgy43p0skpv6vp9f6j9d5nsqzp9ww

**Comment by neilcsmith-net** [comment]
No response, closing.
