### ISSUE TITLE
very very slow output window when running ant projects

### ISSUE THREAD

**Issue by notzed** [apache/netbeans#4141]
### Apache NetBeans version

Apache NetBeans 13

### What happened

The output window has just always been very slow in general but _fails hard_ with long lines.  It makes netbeans feel very clunky and heavy and i always blamed it on swing and 'well, java is just kinda slow' even though i know it isn't.

I traced it down to two trivial problems in `extide/o.apache.tools.ant.module`, file `org.apache.tools.ant.module.bridge.impl.ForkedJoinOverride.java`, method `Copier::run()`.

1. The `if (!STACK_TRACE.matcher(str).find())` call (ForkedJoinOverride.java:318) takes an extraordinary amount of time to execute on long lines.  This could be an openjdk issue.  Changing this to `if (!STACK_TRACE.matcher(str).matches())` speeds this up considerably but it's still terribly slow.  Note: `java.project.JavaAntLogger` uses .matches() and not .find() with the same regex.
2. Calling `in.read()` and `outputLine.write()` one byte at a time. Changing this to read into a buffer first and then searching the buffer for '\n' with some simple logic to do everything in batches and avoid the conditional substring() delivers a further greater-than 20x speed improvement.  Note that simply using a `BufferedInputStream` doesn't help much.

`LOGGER_MAX_LINE_LENGTH` default of 3000 also seems unreasonably long to avoid looking for stack traces.

### How to reproduce

run this in an ant project.
```java
    public static void main(String[] args) throws InterruptedException {
        for (int i = 0; i < 10000; i++) {
            for (int j = 0; j < 1000; j++) {
                System.out.print(j);
            }
            System.out.println();
        }
    }
```

As released netbeans will take in the order of 25 minutes(!!)  to run it to completion (ryzen 3900x, estimated, it was 16s for just 100 lines).  Just changing find() to matches() as suggested in 1. above it will complete in under 2 minutes.  Fixing the code to use a locally buffered read and iterating over the byte array it will take about 5 seconds.

### Did this work correctly in an earlier version?

No

### Operating System

slackware64-current, gentoo

### JDK

openjdk 18.0.1 from openjdk.net.  17.0.1 is no better.

### Apache NetBeans packaging

Own source build

### Anything else

I have prototype code but no suitable patch for this.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by notzed** [comment]
So as above i've created a patch for this.  It's not a particularly large patch because it's a small file but it does change almost all the logic.  I'm sorry I don't really know how github works as i prefer just mailing diffs around so i'm not sure what's next.  I also apologise that I messed up the username in the commit and can't seem to change it in-place, but i suppose i can create another branch before submitting a pull request to fix that.  Is this the place to discuss or should i subscribe to the dev list?

The primary changes are using matches() rather than find() in the regex and using a buffer to stream.read().  The former has identical behaviour since the regex has a greedy match at both ends.  For the latter I believe the semantics should be the same (i.e. non-delayed reading) as InputStream.read() is documented to return when some data is ready and doesn't wait to fill the buffer.

There were also some serious logic problems with the existing code which has clearly been patched multiple times with 'hot fixes' which only hid any problems and also made the code worse. e.g. https://bz.apache.org/netbeans/show_bug.cgi?id=200365

There are several but one example 'logLevel' is passed around as an Integer and used as nullable flag to determine whether to use the 'outputstream' or the 'NbBuildLogger' variables for the output - however set*Stream() calls can set the logLevel when using a delegate stream or if os is null ... but that stream is never even used because logLevel gets set to non-null.  In fact the nbbuildlogger might not be present (hence the null checks for ow, etc).  There were also multiple places this stuff is checked and re-checked.  I've removed all that and replaced it with separate classes for each case to that both can work with guaranteed invariants and this greatly simplifies the logic and readability.

Other smaller changes include using an ExecutorService to create and manage the threads, isolating the critical sections to small functions, removing ThreadDeath exception handling (only for Thread.close() which is never called), and removing things like flushing the output from the stop() function since this is always called in the finally block and so on.  And finally just rearranging the if() test for calling findHyperLinks to be clearer (that was hellishly confusing for such a simple check).

I'm sorry I don't really use ant other than for the default netbeans and build.xml for modular projects (i use GNU Make for anything more complicated) so i'm not sure how to test it to the level such a set of changes require.

**Comment by mbien** [comment]
to open a PR, all you have to do is to go to your fork
https://github.com/notzed/netbeans/tree/nozed-antio
it should show a "Open PR" notification somewhere on top for you.

The PR is automatically updated if you push to that branch. So if you want to fix your commit details, you still can, just force push to the same branch with the corrected commit. No need to create a new branch if there is a mistake. In fact, we often squash PRs down to 1-2 commits before merge to keep the history clean. So if you have an idea and want to add a commit, just do so, clean up can be done before merge, before/after review.

Discussions about details can be done via the PRs. For higher level stuff and big changes the dev list is probably better.
