### ISSUE TITLE
"Exit 137" "Out of Memory"

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#4152]
### Apache NetBeans version

Apache NetBeans 13

### What happened

* I have reinstalled Netbeans v13 from the zip file:
  *  `netbeans-13-bin.zip`
* Started Netbeans and things were running smoothly for about 2 hours.
* At the time I had just finishe an edit and was: `Save All Files` just before running a debug session.
* The PC went slow
* Finally the `OOM` killer killed Netbeans
```
kernel: [124161.947973] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-c2.scope,task=java,pid=158987,uid=1000
kernel: [124161.948098] Out of memory: Killed process 158987 (java) total-vm:12534476kB, anon-rss:1910204kB, file-rss:0kB, shmem-rss:160kB, UID:1000 pgtables:5288kB oom_score_adj:0
kernel: [124162.020306] oom_reaper: reaped process 158987 (java), now anon-rss:0kB, file-rss:0kB, shmem-rss:160kB
rtkit-daemon[1487]: message repeated 9 times: [ Supervising 0 threads of 0 processes of 0 users.]
rtkit-daemon[1487]: The canary thread is apparently starving. Taking action.
systemd[1]: session-c2.scope: A process of this unit has been killed by the OOM killer.
rtkit-daemon[1487]: Demoting known real-time threads.
systemd[1]: session-c2.scope: A process of this unit has been killed by the OOM killer.

```
* On the command line Netbeans exited with an error exit:
```
 $ 
/prod/tools/netbeans/home/platform/lib/nbexec: line 434: 158987 Killed                  "/opt/lib/java/jdk/v17.00/bin/java" -Djdk.home="/opt/lib/java/jdk/v17.00" -classpath "/prod/tools/netbeans/hom . . .
```
  * With a long command line following from the launcher (I guess?)

### How to reproduce

* This has been happening for a while.  Previously I was running from a flatpak Netbeans package
    * _see_:  #4065
    * Now I have unpacked the `netbeans-13-bin.zip` distribution build
* I'm running the command from a bash terminal as follows, to catch any error messages:
```
nice -n 8  /prod/tools/netbeans/home/bin/netbeans                               \
    -J-Dawt.useSystemAAFontSettings=on                                          \
    --jdkhome     /opt/lib/java/jdk/v17.00                                      \
    --userdir     /home/william/.config/netbeans/v13.00/4ams/v17.00/user-02     \
    --cachedir    /home/william/.cache/netbeans/v13.00/4ams/v17.00/cache-02     &
```
* I am attatching the messages log and a dump file.  It seems to blow-up just before or just after writing a dump file.
  * I have a great many ".dump" files.  More than I expect in a non-Beta release that;s for sure
  * There is nothing special in the java code for  these files.
* To reproduce.  Work for a while on a big Gradle project (I have 16GiG ram is should not be all used like this).

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Ubuntu 22.04 LTS

### JDK

openjdk version "17.0.1" 2021-10-19 LTS

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

* Lots of .dump files: 378 files
* According to Git, I have only edited 2 files since lunch
* Attaching log and last dump written:
  * [messages.log](https://github.com/apache/netbeans/files/8776535/messages.log)
  * [ProcessNotes_75.dump.log](https://github.com/apache/netbeans/files/8776537/ProcessNotes_75.dump.log) -- Had to rename it to kee[ github happy.
* I am looking for some way to identify the problem  -- I've edited this project on a desktop with Netbeans (but it has more memory).

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by aplatypus** [comment]
A follow-up query:
* Is there somewhere that documents how to "clean" out the Netbeans user area, without losing my plugins and settings?

**Comment by lkishalmi** [comment]
Well. Let's ask what do you expect us with this issue. It is clearly outside of the JVM. OOM Killer just terminates a fat Java process.

I do not see that you've tried to limit your JVM memory footprint as were recommended in https://github.com/apache/netbeans/issues/4065#issuecomment-1128400539

We also do not know what other processes are running on your computer when these unfortunate events were happening.
Having 16 Gb of RAM is not necessary a guarantee that the OOM killer won't appear. I have systems from 8Gb - 64Gb, but even 64 Gb is not a guarantee for that.

You've done more than our regular bug reporter does so far, but you still have to do your homework monitoring what's happening on your machine.

**Comment by lkishalmi** [comment]
Also you might experiencing: https://www.omgubuntu.co.uk/2022/06/ubuntu-22-04-systemd-oom-killing-apps

**Comment by aplatypus** [comment]
The app is killed because Netbeans encourages Gradle to run about 15GB of build tasks to analyse a project.

After i removed Gradle 7.4 and limited the gradle runners to just use 16; life became more sensible.

Imho this issue is NOT closed because the cause has not been addressed.
