### ISSUE TITLE
Error with splitted windows

### ISSUE THREAD

**Issue by edrobal** [apache/netbeans#4155]
### Apache NetBeans version

Apache NetBeans 13

### What happened

It' version 13 and issues I reported for version 8 are always in it.
Breakpoints and bookmarks are badly set.

### How to reproduce

1) Split the windows.
2) Click on panel margin to set breakpoint. If you don't have click on this panel the breakpoint is not set in the good panel.
3) Click on bookmark button for the down panel. Bookmark is always set on the upper panel.

### Did this work correctly in an earlier version?

No

### Operating System

Linux version 5.3.18-150300.59.63-default running on amd64; UTF-8; fr_CH (nb)

### JDK

Java: 11.0.15; OpenJDK 64-Bit Server VM 11.0.15+10-jvmci-22.1-b06 Runtime: OpenJDK Runtime Environment 11.0.15+10-jvmci-22.1-b06

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Error happens always

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by edrobal** [comment]
And also splited windows cannot be unsplited.

**Comment by epliskin** [comment]
NetBeans 21, Windows 10, JDK 21. Same problem with "Toggle Bookmark" button in the lower split panel. It toggles bookmark in the upper panel instead.

**Comment by edrobal** [comment]
I suggest that developers use Netbeans. They might discover the problems in use.

**Comment by neilcsmith-net** [comment]
Most developers on NetBeans use it every day. That doesn't mean every feature gets used often.

This is curious - looks like the toggle applies before focus change to the other split occurs.  Let's see if we can get this fixed for NB23 - should hopefully be an easy one.

Split windows can easily be unsplit by dragging the divider to the side.

**Comment by matthiasblaesing** [comment]
I looked at this and from my tests only "Toggle bookmarks" via the editor toolbar reproduced the problem.

![image](https://github.com/apache/netbeans/assets/2179736/a1cf6fb5-6364-4625-af95-95614bc13e58)

Toggling breakpoints using the keyboard worked correctly from both split panes I tested with.

Unsplitting works for me by dragging the splitter to one site or calling "Clear" from context menu:

![image](https://github.com/apache/netbeans/assets/2179736/3e97350b-5e22-42fa-8d10-8ef1fa1e7f2f)


@edrobal 
> I suggest that developers use Netbeans. They might discover the problems in use.

I think your comment is out of line and doesn't help your case.

**Comment by matthiasblaesing** [comment]
@edrobal @epliskin please test the suggested fix available from #7384: https://github.com/apache/netbeans/suites/23945896463/artifacts/1517369467

That fix covers the toggle bookmarks case as that was the one I could reproduce.

**Comment by epliskin** [comment]
@matthiasblaesing Yes, for me that dev build fixes the toggle bookmarks buttons in a split view. Windows 10, JDK 21.

**Comment by matthiasblaesing** [comment]
@epliskin thank you for the verification!

**Comment by matthiasblaesing** [comment]
@edrobal you raised the issue about the break points, please check the fix @neilcsmith-net created via #7386. A test build with that fix is available as Neil indicated here: https://github.com/apache/netbeans/issues/4155#issuecomment-2120614578

**Comment by edrobal** [comment]
I try to install netbeans 21 with java 22. I use Linux. Netbeans freeze each time I open a netbeans 8 project.

**Comment by matthiasblaesing** [comment]
@edrobal there are breaking changes in JDK22. For NB21 use JDK21. NB22 (currently being in release) will support running on JDK22+
