### ISSUE TITLE
Code completion does not work in JSFs

### ISSUE THREAD

**Issue by helper14** [apache/netbeans#4162]
### Apache NetBeans version

Apache NetBeans 13

### What happened

The code completion does not work for managed beans in JSF pages. Affected are maven-web-projects with EE 9.1 (EE 7 still works). See screenshot. A sample project is attached
![bug-code-completion](https://user-images.githubusercontent.com/83238864/170776941-312e9077-b3b6-4c2d-8678-6a62589bbfb8.png)
[mavenWEBprojectEE91.zip](https://github.com/apache/netbeans/files/8789286/mavenWEBprojectEE91.zip)
.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 10 version 10.0 running on amd64; Cp1252; en_US (nb)

### JDK

Java 17.0.3; OpenJDK 64-Bit Server VM 17.0.3+7

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
Tested on NB 19, the completion works.

**Comment by helper14** [comment]
Thank you - that is a big relieve!
