### ISSUE TITLE
Adding JSF to jakarta ee project

### ISSUE THREAD

**Issue by diegosilval** [apache/netbeans#4181]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

I assumed that this version of NetBeans includes JSF support at JakartaEE 9

### How to reproduce

1. Create new maven web project, with GlassFish server and Java EE version "Jakarta EE 9 Web".
2. In properties window, at Frameworks category, add "JavaServer Faces" framework.
3. Click in OK button
4. Netbeans shows message:"Project contains unknown version or unparsable deployment descriptor which was not recognized. You have to do Struts registration into web.xml manually."

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

11

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by pepness** [comment]
It works with PR-4438. Tested with GlassFish 6.2.5 and Jakarta EE 9.1

![Screenshot from 2022-07-30 12-13-09](https://user-images.githubusercontent.com/9832133/181934662-1c6e1d33-e97b-40cc-9ed3-4334c6a7d2d1.png)
