### ISSUE TITLE
FileAlreadyExistsException (JGit issue - upgrade req.)

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#4197]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Netbeans notifications displayed this message after start-up.
> A java.nio.file.FileAlreadyExistsException exception has occurred.
Please report this at https://netbeans.apache.org/nb/report-issue,
including a copy of your messages.log file as an attachment.
The messages.log file is located in your /home/william/.config/netbeans/v13.00/4ams/v17.00/user-02/var/log folder.

### How to reproduce

* Well I just started Netbeans.
* The file exists but there is an error because it exists.  
* I believe it should exist
* I have uploaded logs and the exception error log

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Ubuntu 22.04 LTS

### JDK

openjdk version "17.0.1" 2021-10-19 LTS

### Apache NetBeans packaging

Other

### Anything else

* [Uploading netbeans-exception.log…]()

* [messages.log](https://github.com/apache/netbeans/files/8837272/messages.log)

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Thanks for the report.  The log shows this throwing in `org.eclipse.jgit.util.SystemReader`.  Looks like this may be a bug with the version of JGit we're shipping.  Is it possibly this?  https://bugs.eclipse.org/bugs/show_bug.cgi?id=565637

**Comment by aplatypus** [comment]
Same error happened again today.  I took another look at the stack trace.  The directory:
* `/home/william/.config` 
Is a linux desktop standard folder for config files.  

On this system the Git config is:

- `/home/william/.config/git/config`

and 

- `/home/william/.config`  is a symlink  --> `../../data/home/william/.config/`
- Which collects all these things under a `data/` file tree:  `/data/home/william/.config/`

I noticed in the Eclipse error there is an association with a symbolic link.

One thing to remark on, this error doesn't come-up too often  So, most of the time it seems to work find with the symlink.

**Comment by neilcsmith-net** [comment]
Thanks for confirming that `.config` is a symlink so it is that bug - should have asked that directly.  I think we can only fix this by upgrade of JGit. Should only be an annoyance rather than causing any usability issues?

**Comment by neilcsmith-net** [comment]
Bumping this forward. Annoying bug, but shouldn't affect usage, and late in cycle to risk library upgrade.
