### ISSUE TITLE
Incorrect variable highlighting in PHP arrow function

### ISSUE THREAD

**Issue by qmegas** [apache/netbeans#4209]
### Apache NetBeans version

Apache NetBeans 13

### What happened

When there is a ternary operator inside arrow function in PHP then variable highlighting works incorrectly.

Example code:

```php
$a = 5;
$b = fn() => $a > 5 ? $a + 1 : 10;
```

When put cursor on variable `$a` on first line, then first `$a` variable inside arrow function is also highlighted (which is correct), but second variable doesn't (which is incorrect). Same bug happens when put cursor on variables inside arrow function.

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

16.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by junichi11** [comment]
Reproducible. Thanks for reporting it :)
