### ISSUE TITLE
Keyboard shortcut for code completion popup(CTRL+SPACE) not working on MACOS Monterrey 12.4, Netbeans 13

### ISSUE THREAD

**Issue by dnielben** [apache/netbeans#4212]
### Apache NetBeans version

Apache NetBeans 13

### What happened

The keyboard shortcut CTRL+SPACE does not show the code completion popup. 

- Other IDEs like IntelliJ use the same shortcut and it works ok.
- If code completion is invoked from the menu it always works.
- Randomly the shortcut gets displayed in the menu, sometimes it does but others it does not.
- Adding an alternative shortcut for the code completion popup works always.

 

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

MAc OS Monterry 12.4

### JDK

Oracle java version "17" 2021-09-14 LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

[netbeanslogs.txt](https://github.com/apache/netbeans/files/8865406/netbeanslogs.txt)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by akronenw** [comment]
Hello, 

I just installed NetBeans 13 on my MacBook M1, also Monterey 12.4 with JDK 17 from Azul. The shortcut works without any issues here.

**Comment by oyarzun** [comment]
@dnielben  I think you are running into this JDK bug. https://bugs.openjdk.org/browse/JDK-8272602

**Comment by oyarzun** [comment]
@dnielben Can you test using the latest JDK 17? This is most likely that JDK bug.

**Comment by SirIntellegence** [comment]
I had this issue with JDK 17. It was fixed when I switched Netbeans to run on 18. There is something Funky about 17. I don't remember off hand what web article pointed me to that solution. It appears to global to all Macs.

**Comment by oyarzun** [comment]
The issue is due JDK bug https://bugs.openjdk.org/browse/JDK-8272602 which has been fix in JDK 18 and back ported to earlier JDKs. Update your JDK and the problem is resolved.

**Comment by Alonso-del-Arte** [comment]
The keyboard shortcut worked on my MacBook M2 Pro until I added an input method editor for Japanese. Now it's been co-opted by the OS's IME switching.
