### ISSUE TITLE
JS parsing bug: "this" not declared

### ISSUE THREAD

**Issue by qmegas** [apache/netbeans#4213]
### Apache NetBeans version

Apache NetBeans 13

### What happened

In some cases parser alert about the error in JS code when it's not actually there.

Code example:

```js
class Test {
	state = {
		test: null
	};
	
	setCategory(url) {
		this.state.test = {url};
	}
}
```

That code produce an alert on line 7: `The global variable "this" is not declared`, however that is absolutely correct code.

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

16.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

That bug was reported by me 2 years ago: https://issues.apache.org/jira/browse/NETBEANS-3948

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Reproducible also in NetBeans 14.
Thanks for your report.

**Comment by matthiasblaesing** [comment]
Please have a look at the reference PR. That should fix the problem. A nightly build is available from the CI/CD summary page:

https://github.com/apache/netbeans/actions/runs/4646997912

or directly:

https://github.com/apache/netbeans/suites/12111203659/artifacts/638179968

**Comment by qmegas** [comment]
@matthiasblaesing problem fixed
