### ISSUE TITLE
Support JavaScript private methods and properties

### ISSUE THREAD

**Issue by qmegas** [apache/netbeans#4215]
### Description

It's almost [3 years](https://github.com/tc39/notes/blob/main/meetings/2019-01/jan-30.md#private-fields-and-methods-refresher]) since private properties and methods are added to ECMA standard. Starting Chrome 84 we are allowed to use both natively in the browser (without Babel). Private properties are available in Chrome even starting version 74 (released 2019-04-23).

Code example:

```js
class A {
	#privateProp = 0;
	
	#privateMethod() {
		return 0;
	}
}
```

But in both cases we get parsing error in NetBeans.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment]
Works in master (and most probably in NB14:  https://github.com/apache/netbeans/pull/3599)
