### ISSUE TITLE
Netbeans icon on linux is doubled

### ISSUE THREAD

**Issue by PavelCibulka** [apache/netbeans#4221]
### Description

When you add netbeans icon into favorite bar (Ubuntu 22.04 Gnome) you get icon to easily start netbeans. When you start netbeans with this icon, second icon will appear in favorite bar. This is due to icon file (**~/.local/share/applications/Apache NetBeans-14.desktop**) not havving StartupWMClass property.

This can be easily fixed. (But I don't know, where is code for this icon in Netbeans source code). Adding **StartupWMClass=Apache NetBeans IDE 14** will fix this issue.

Example of original **Apache NetBeans-14.desktop** file:
```
[Desktop Entry]
Encoding=UTF-8
Name=Apache NetBeans IDE 14
Comment=The Smarter Way to Code
Exec=/bin/sh "/home/pavel/netbeans-14/netbeans/bin/netbeans"
Icon=/home/pavel/netbeans-14/netbeans/nb/netbeans.png
Categories=Application;Development;Java;IDE
Version=1.0
Type=Application
Terminal=0
```

Example of fixed version:
```
[Desktop Entry]
Encoding=UTF-8
Name=Apache NetBeans IDE 14
Comment=The Smarter Way to Code
Exec=/bin/sh "/home/pavel/netbeans-14/netbeans/bin/netbeans"
Icon=/home/pavel/netbeans-14/netbeans/nb/netbeans.png
Categories=Application;Development;Java;IDE
Version=1.0
Type=Application
Terminal=0
StartupWMClass=Apache NetBeans IDE 14
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by mbien** [comment]
you were using the linux installer I suppose?

**Comment by PavelCibulka** [comment]
Yes, Apache-NetBeans-14-bin-linux-x64.sh from https://dlcdn.apache.org/netbeans/netbeans-installers/14/

**Comment by neilcsmith-net** [comment]
This is a known issue.  However, are you saying that _just_ setting `StartupWMClass` fixes the issue?  Previously this only worked when using `--nosplash` as GNOME picked up the WM class from that and didn't consider the full IDE window in terms of icon grouping.  The other workaround is to rename the desktop file to eg. `apache-netbeans-ide-14.desktop` which does the same thing but doesn't seem to be affected by the splash.

Incidentally, there is a DEB package under [community installers](https://netbeans.apache.org/download/nb14/nb14.html#_community_installers) (with or without bundled runtime) that does set both and shouldn't be affected by this issue.

**Comment by neilcsmith-net** [comment]
Thanks @PavelCibulka - good to know GNOME have fixed their side of this issue. Should be a simpler fix in the Linux installer now.
