### ISSUE TITLE
Annoying autocomplete

### ISSUE THREAD

**Issue by vegaskyo** [apache/netbeans#4225]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I just downloaded the lastest version of Netbeans. And I encounter the problem with autocomplete.  Each time I dot and continue typing, it automatically choose the first that show in the suggestion table.
The thing is I want to continue typing to choose the exact method I want to use. And that's so annoying !

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 11

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
what language? please give a concrete (minimal) example as reproducer.

**Comment by vegaskyo** [comment]
Java.
Here the pics!

In the first photo. After dot, I press ctrl+space to show suggestions, assume that I want to choose hashpw() method, but when I type 'h' it automatically choose the first method (in the second pic as you can see) and the letter 'h' stands in the end of the statement!

Imagine it has a thousand methods and I have to press up and down key! Please help!

![Screenshot 2022-06-16 001230](https://user-images.githubusercontent.com/51159554/173886487-f2838561-1f35-44bd-86c8-fc41843ff730.jpg)


![Screenshot 2022-06-16 001247](https://user-images.githubusercontent.com/51159554/173886531-ed7fa338-67ea-463e-a904-e417484827db.jpg)

**Comment by mbien** [comment]
I assume thats spring. I can't reproduce this in NB 13 and 14:
![gensalt_completion](https://user-images.githubusercontent.com/114367/173889320-57f6e09c-38aa-4c65-8a50-3e1fd82f7480.png)

Can you reproduce this in a fresh new project like I just tried to do?

**Comment by vegaskyo** [comment]
It happens in every projects I make. Not only Spring! I don't know why!

![image](https://user-images.githubusercontent.com/51159554/173974105-9a44967c-16b1-444d-bf46-057f466477bb.png)

**Comment by mbien** [comment]
you could try to reset the settings, assuming you imported them from 12.6:
https://github.com/apache/netbeans#log-config-and-cache-locations

I can't come up with a scenario when NetBeans would insert the completion after a dot, as soon you start typing. There is something weird going on there.

**Comment by vegaskyo** [comment]
It works. Thanks you!
