### ISSUE TITLE
NetBeans 14 text antialiasing doesn't respect system settings on KDE Plasma

### ISSUE THREAD

**Issue by NickLion** [apache/netbeans#4228]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

NetBeans 14 run in KDE Plasma has grayscale antialiasing, though it's subpixel system-wide.

NB: I've chosen latest build, though I'm using official 14 version, but there is no such option in selector.

### How to reproduce

1. Enter KDE Plasma session.
2. Enable subpixel antialiasing.
3. Start NetBeans.
4. Check text antialias — it's graysacle.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Linux — openSUSE Tumbleweed x86_64, KDE Plasma

### JDK

OpenJDK 18.0.1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

It seems this behaviour was introduced with 921e5c3df8e0137cb5f22c122b0435e289693007, where for KDE session is set
`-J-Dawt.useSystemAAFontSettings=on`
And `on` means — grayscale antialiasing.

Commenting out this line or replacing it with `-J-Dawt.useSystemAAFontSettings=lcd` fixes it for me, but `lcd` won't work for those who prefer grayscale.

What was the reason of introducing that change for antialiasing? NetBeans under KDE Plasma respected system text antialiasing before. Were there some problems for other people?

If this change is really necessary it's better to check for antialiasing mode, at least `Xft.rgba`.

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
@eirikbakke something for you :)

@Nicklion My guess is that the JVM couldn't detect the system AA mode on some distributions, thats why the property is set. The commit msg you linked seems to confirm that.
old doc here:
https://docs.oracle.com/javase/7/docs/technotes/guides/2d/flags.html#aaFonts
also mentions KDE specifically. Maybe things changed and the JVM can now detect system settings there too?

**Comment by eirikbakke** [comment]
Thanks for the report! @mbien is correct; on some KDE systems (including the one I tested), JVM could not detect the system AA mode, and reverted to no anti-aliasing at all. Greyscale antialiasing was the conservative choice, as subpixel antialiasing looks bad if the wrong mode is selected (HRGB vs. HBGR).

The interesting question is how OpenJDK managed to detect antialiasing by itself on your particular system. I don't see any recent changes in the relevant OpenJDK code, so this probably has to do with your particular setup.

Do you have both Gnome and KDE installed on your system? Perhaps JDK is picking up settings from another installed window manager.

If Xft.rgba has a useful value, we could use that, though, as you suggest. Could you run the following, and let us know the output?
```
command xrdb -query 2> /dev/null | grep Xft.rgba
```

**Comment by NickLion** [comment]
> @NickLion My guess is that the JVM couldn't detect the system AA mode on some distributions, thats why the property is set. The commit msg you linked seems to confirm that. old doc here: https://docs.oracle.com/javase/7/docs/technotes/guides/2d/flags.html#aaFonts also mentions KDE specifically. Maybe things changed and the JVM can now detect system settings there too?

Yes, there were problems before OpenJDK 11, openSUSE kept patches for fonts for earlier OpenJDK versions. But with 11 and later haven't seen problems with antialiasing.

**Comment by NickLion** [comment]
> Thanks for the report! @mbien is correct; on some KDE systems (including the one I tested), JVM could not detect the system AA mode, and reverted to no anti-aliasing at all. Greyscale antialiasing was the conservative choice, as subpixel antialiasing looks bad if the wrong mode is selected (HRGB vs. HBGR).

Yes, but that could be deduced from `Xft.rgba` too.

> The interesting question is how OpenJDK managed to detect antialiasing by itself on your particular system. I don't see any recent changes in the relevant OpenJDK code, so this probably has to do with your particular setup.

AFAIK, openSUSE removed font patches for OpenJDK 11 and later. I'll check later maybe I was wrong.

> Do you have both Gnome and KDE installed on your system? Perhaps JDK is picking up settings from another installed window manager. Or it might be a fontconfig thing...

No, just KDE Plasma. X11 or Wayland (NetBeans through XWayland) both worked fine.

> If Xft.rgba has a useful value, we could use that, though, as you suggest. Could you run the following, and let us know the output?
> 
> ```
> command xrdb -query 2> /dev/null | grep Xft.rgba
> ```

```
Xft.rgba:       rgb
```

**Comment by NickLion** [comment]
If there is issue for some people with KDE + OpenJDK, maybe something like this would be fine:

```
            case "$(command xrdb -query 2> /dev/null | grep Xft.rgba | cut -d ':' -f2 | xargs)" in
                rgb)
                    extra_automatic_options="-J-Dawt.useSystemAAFontSettings=lcd"
                    ;;
                bgr)
                    extra_automatic_options="-J-Dawt.useSystemAAFontSettings=lcd_hbgr"
                    ;;
                vrgb)
                    extra_automatic_options="-J-Dawt.useSystemAAFontSettings=lcd_vrgb"
                    ;;
                vbgr)
                    extra_automatic_options="-J-Dawt.useSystemAAFontSettings=lcd_vbgr"
                    ;;
                *)
                    extra_automatic_options="-J-Dawt.useSystemAAFontSettings=on"
                    ;;
            esac
```

**Comment by eirikbakke** [comment]
@NickLion Yes, the proposed case statement based on Xft.rgba is a great idea, inserted in the KDE_FULL_SESSION case.

Feel free to prepare a PR updating the same two files as in https://github.com/apache/netbeans/commit/921e5c3df8e0137cb5f22c122b0435e289693007 . Or happy to do it if you prefer.

**Comment by eirikbakke** [comment]
I created a PR to fix this issue at https://github.com/apache/netbeans/pull/5161.

@NickLion if you have a chance, could you test the patched launcher script (nb/ide.launcher/unix/netbeans , to be copied into the "bin" directory in the NetBeans installation folder) and see if it fixes the problem on your machine?

(I did test it on Ubuntu and confirmed both the original issue and the fix.)

**Comment by NickLion** [comment]
Hi,

Sorry for disappearance. Yes, it works perfectly for me. Thank you!
