### ISSUE TITLE
Netbeans v14 fails to load Gradle project and subproject

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#4234]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

* I have a working Gradle project checked-out of github -- I loaded in Netbeans v13 yesterday
* I did a flatpak update ...
  * There was apparently an upgrade to Netbeans on Flathub from v13 to v14
  * Unnoticed netbeans was upgraded on me
  * This was apprent when the slpash screen showed v14
*  When I opened my project there wre multiple errors can't load gradle
   * Also Netbeans has been set to use Gradle 7.2 to match the Gradlew version used
   * The load process keeps trying to load a later gradle -- The latter gradle causes many problems with this gradle project and is deliberately blocked.  
   * Netbeans appears to ignor the gradle settings

### How to reproduce

* Install flatpak Netbeans
* There was no error information about the Gradle load error, so I cannot say what the gradle issue is

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Ubuntu 22.04 LTS

### JDK

JDK 17.0 / Gradle build uses JDK 1.8 

### Apache NetBeans packaging

Other

### Anything else

* I think the Netbeans project needs to take control of the flatpak / flathub install
* On the news page there is no release announcement for netbeans 14
* Also the update apparently broke the "Whats New" feed on the start page
* CAN NOT make a copy of the Notification-s about this error.
  * I am attaching a screenshot of one panel.
  * Load fail notification  ![image](https://user-images.githubusercontent.com/67028/174212029-51cdd9b5-b21e-48c1-84a1-b43c891912c5.png)
  * Gradle settings:  ![image](https://user-images.githubusercontent.com/67028/174212332-41dcf69e-ffeb-46bd-acd3-d7a6b66041b4.png)

  

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
When running JDK 17 NetBeans forced to use Gradle 7.3 or above. NetBeans 14 reports this kind of issue as a project problem with more details.
