### ISSUE TITLE
Font ligatures fail to render between tokens in italics

### ISSUE THREAD

**Issue by haustvindr** [apache/netbeans#4237]
### Apache NetBeans version

Apache NetBeans 14

### What happened

When installed and configured a font with ligatures, ligatures are not drawn when they appear between tokens in italics.

![image](https://user-images.githubusercontent.com/33665098/174293393-d0877e10-0a33-453f-9a4e-e23704305ef1.png)

This is from a PHP editor, unsure if it happens in other languages' editors.

### How to reproduce

It seems to happen when it is surrounded by 2 tokens drawn in italics. If any of the surrounding tokens is changed to normal style, it works fine:

![image](https://user-images.githubusercontent.com/33665098/174294089-5cb92ae5-f22f-428a-a06c-361acf270152.png)
![image](https://user-images.githubusercontent.com/33665098/174294181-48a86617-4927-4fe2-a415-11469526ba50.png)

It doesn't matter if there are spaces around either:

![image](https://user-images.githubusercontent.com/33665098/174294479-002b1cc6-8f94-40f5-821a-d5b8d653f1aa.png)
Working fine as strings are not in italic.
![image](https://user-images.githubusercontent.com/33665098/174294558-8a38872a-f0e8-4e5b-a9b3-e92c0b56aa90.png)
But not when switching the string with a token drawn in italics.

Also, it seems to happen with any ligature:
![image](https://user-images.githubusercontent.com/33665098/174294979-9865f320-1d6b-4eb4-a136-87378688d048.png)

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10 x64

### JDK

No JDK, only JRE 1.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
please use a recent JDK and check if the same issue occurs, font rendering is implemented in the JDK.

17 would be the latest long term release. NetBeans doesn't really support 8 anymore.

**Comment by haustvindr** [comment]
Ok, I've downloaded and tested with JDK 18, and indeed it seems to work fine with it.

![image](https://user-images.githubusercontent.com/33665098/174624141-8d22d2b3-f1bf-4b93-847e-fcb4f9d6cbc1.png)

It is a little weird that these things won't work fine in JRE, since it was updated not much time ago (and I don't do Java so the JDK is a little overkill), but as I'm understanding it has nothing to do with NetBeans itself but with Java's underlying text rendering systems.

Guess this can be closed. Sorry for wasting your time!

**Comment by mbien** [comment]
@haustvindr no problem. Glad that everything is working now. Jave 8 (1.8) is getting really old, many features are not backported. Technically NetBeans only supports 11 and up. 

But there is no good reason from an user perspective to use an old java version, so sticking with 17 or later is a good decision to get the best experience.
