### ISSUE TITLE
Error loading Gradle project in Netbeans 14 - Could not run build action using connection to Gradle installation

### ISSUE THREAD

**Issue by hamishg** [apache/netbeans#4239]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Tried to load a Gradle project using Gradle v5.2.1 in Netbeans 14 and got this error:

`Could not run build action using connection to Gradle installation '/Users/{myuser}/.gradle/wrapper/dists/gradle-5.2.1-bin/9lc4nzslqh3ep7ml2tp68fk8s/gradle-5.2.1'`

This project loads correctly in Netbeans 13.

### How to reproduce

- Fresh Netbeans 14 install. Settings not imported from older version.
- Open the attached sample Hello World project with Gradle wrapper v5.2.1 .
- Try and build the project
- (hopefully see the error)

[gradleloading.zip](https://github.com/apache/netbeans/files/8929314/gradleloading.zip)

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

macOS 11.6 Big Sur running on aarch64 (M1 Mac)

### JDK

OpenJDK Runtime Environment 11.0.13+8-LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Things I have tried:
* Deleting Netbeans cache in ~/Library/Caches/NetBeans/14
* Deleting Netbeans data in ~/Library/Application Support/NetBeans/14
* Deleting Gradle wrappers in ~/.gradle

When the Gradle wrapper is not present then Netbeans is downloading it ok but still has the same problem loading the project.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
Well the sample project works correctly with NetBeans 15

**Comment by hamishg** [comment]
I tried with a fresh install of Netbeans 15. I now get a different error message when trying to build the sample project provided earlier:

> org.codehaus.groovy.runtime.metaclass.MissingPropertyExceptionNoStack: No such property: classesDirectory for class: org.gradle.api.internal.file.DefaultSourceDirectorySet

**Comment by neilcsmith-net** [comment]
Concur with @lkishalmi - working fine on NetBeans 15 (on Linux at least).  Are you using an aarch64 or amd64 JDK on your M1?  Will try and replicate on my M1 machine at some point.

**Comment by hamishg** [comment]
Thank you. I appreciate you taking time to look at this. Yes I'm using an arm build of openjdk11 from Azul.

I've managed to build/run the project by toggling "Prefer to use gradle wrapper that comes with the project" off. Then building the project and turning it back on again. The project is now building/running with the gradle wrapper option on again.

**Comment by lkishalmi** [comment]
More than one year old, seems to have a workaround. Closing.

**Comment by JoshMcCullough** [comment]
Where is the "Prefer to use gradle wrapper that comes with the project" option in NetBeans 16?

**Comment by neilcsmith-net** [comment]
@JoshMcCullough please ask usage questions in discussions or on the user mailing list.  NetBeans 16 is no longer support - try NetBeans 21 (or imminent 22).  The option is in `Tools / Options / Java / Gradle`.
