### ISSUE TITLE
Examining the Swing Interop Sample

### ISSUE THREAD

**Issue by TheGeeko61** [apache/netbeans#4248]
### Description

On NB website (https://netbeans.apache.org/tutorials/72/nbm-javafx.html), it begins by instructing to download a project from Netbeans that no longer exists.  I think it should be updated.

### Use case/motivation

I long to work through the site as advertised...

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by mbien** [comment]
no need to track this as an issue. its already in the page header. Anyone interested can press the edit button, rewrite it and create a PR which will show up at: https://github.com/apache/netbeans-website/pulls
