### ISSUE TITLE
Update Flexmark to more recent one

### ISSUE THREAD

**Issue by nigjo** [apache/netbeans#4251]
### Description

Currently Flexmark v0.50.36 (Released 2019-09-05) is bundled with NetBeans 13/14. Latest Release-tag of the flexmark-java project is [0.64.0](https://github.com/vsch/flexmark-java/releases/tag/0.64.0).

There are some "major changes" in 0.60.0 so this might break something.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by nigjo** [comment]
Currently I am using an own version of it in my RCP and what to replace it with the bundled one.

None the less there are a bunch of bugfixes in flexmark since 2019.

**Comment by mbien** [comment]
flexmark is currently at 64.x (NB 21) and we update it periodically (e.g https://github.com/apache/netbeans/pull/6918)

forgot to close the issue
