### ISSUE TITLE
Netbeans Output window uses wrong encoding

### ISSUE THREAD

**Issue by duoduobingbing** [apache/netbeans#4261]
### Apache NetBeans version

Apache NetBeans 14

### What happened

* Have `-J-Dfile.encoding=utf-8` inside the `netbeans_default_options` under `{INSTALLDIR}/netbeans/etc/netbeans.conf`
* Create a new Maven Project
* Have it print something like
  ```
  System.out.println("%s, %s".formatted(System.getProperty("file.encoding"), Charset.defaultCharset()));
  System.out.println("✨✨✨");
  ```
* Add `-Dfile.encoding=utf-8` to `exec.vmArgs` inside the project's `nbactions.xml` for the *Run* action 
* Run
* Instead of the expected '✨✨✨' or Tofu Boxes it spits out:
  ```
  utf-8, UTF-8
  âœ¨âœ¨âœ¨
  ```

### How to reproduce

Probably is a Windows only problem, as the Output window seems to just use the Windows default encoding, which in my case is WIN1252 and ignore the encoding that has been set JVM-wide.

Interpreting ✨✨✨ as WIN1252 instead of UTF-8 yields the mangled output 'âœ¨âœ¨âœ¨' which I got.

Having `JAVA_TOOL_OPTIONS=-Dfile.encoding=utf-8` and `MAVEN_OPTS=-Dfile.encoding=utf-8` set as system variables under `HKCU\Environment` also does not fix the problem.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Windows 10

### JDK

17.0.3 (Eclipse Adoptium Temurin)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

This does work in Netbeans 13 and before, so this bug was introduced in Netbeans 14.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by duoduobingbing** [comment]
Update:

Switching to JDK18 does not fix the problem. 
Running Netbeans under JDK18 and the Project under JDK18 yields:
```
utf-8, UTF-8
???
```

Setting `native.encoding=utf-8`, `file.encoding=utf-8` to `MAVEN_OPTS`, `JAVA_TOOL_OPTIONS`, `nbactions.xml` and/or `nbactions.xml` does nothing to change this result.

Running Netbeans under JDK18 and the Project under JDK17 yields:
```
utf-8, UTF-8
âœ¨âœ¨âœ¨
```

**Comment by duoduobingbing** [comment]
I've investigated this further and found the culprit. It's because of [PR#3863](https://github.com/apache/netbeans/pull/3836). 

Printing out
```
System.out.println(Charset.defaultCharset());
System.out.println(System.getProperty("file.encoding"));
System.out.println(System.getProperty("native.encoding"));
System.out.println(System.getProperty("sun.jnu.encoding"));
```
got the answer.

This got me the following results for JDK18 and JDK17:
```
UTF-8
UTF-8
Cp1252
Cp1252
```

Setting `native.encoding` via `-Dnative.encoding=utf-8` under Windows does not change the value that is obtainable via `System.getProperty("native.encoding")`. It always reflects the output of `sun.jnu.encoding` which is also not changeable via java command line under Windows.

PR#3863 incorrectly assumes that `native.encoding` is `null` when not set explicitly, which its not true under Windows. Neither for JDK17 nor JDK18. So under Windows Netbeans just uses `sun.jnu.encoding` regardless of configuration for the output window which is for my machine always Windows1252.

**Comment by duoduobingbing** [comment]
@matthiasblaesing Would it be possible to just revert #3836 ? 
If it is desired behavior to keep the platform native encoding and not revert #3836, another option would be to have a property like `-J-Dnetbeans.encoding.preferNativeEncoding=false` that could be set, so that `Charset.defaultCharset()` is used instead of the `native.encoding`-Property, so that Windows users at least regain the option to switch their Netbeans Output encoding to UTF-8

**Comment by mossaab0** [comment]
I'm facing this issue (on Windows 11) in NB14 and NB15. I've tried JDK17 and JDK19 with no success.
NB13 works just fine.

**Comment by duoduobingbing** [comment]
@mossaab0 If you run Netbeans 15 with JDK19+, you will need to add `-Dstdout.encoding=utf-8`; with JDK18 you will need to add `-Dsun.stdout.encoding=utf-8` as `native.encoding` is not settable.

**Comment by mossaab0** [comment]
> @mossaab0 If you run Netbeans 15 with JDK19+, you will need to add `-Dstdout.encoding=utf-8`; with JDK18 you will need to add `-Dsun.stdout.encoding=utf-8` as `native.encoding` is not settable.

That helped. Thanks, @duoduobingbing!

**Comment by marccollin** [comment]
this issue is still there with netbeans 17 and jdk 17

**Comment by olivalpaulino** [comment]
Solved! Watch this video: https://youtu.be/kXvWm64RBU0

**Comment by robozb** [comment]
> Solved! Watch this video: https://youtu.be/kXvWm64RBU0 JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -Dconsole.encoding=UTF-8
> 
> Java JDK 21 with Netbeans 21

Thank you so much! It solved the problem. It's astonishing how Java is regressing that such settings need to be configured.

**Comment by ly269nva** [comment]
Charset.defaultCharset():UTF-8
file.encoding property:UTF-8
native.encoding property:null
sun.jnu.encoding property:UTF-8
stdout.encoding property:UTF-8
sun.stdout.encoding property:UTF-8
I also have this problems on netbeans20,jdk8,win11, i write System.out.println("png压缩完成"); it can output chinese in 'Test Results' tab, but Output garbled text in ‘Output’ tab. And no matter how I configure it in netbeans.exe, it doesn't work，example: netbeans_default_options="*** -J-Dfile.encoding=UTF-8 -J-Dsun.jnu.encoding=UTF-8 -J-Dnetbeans.output.encoding=UTF-8 -J-Dconsole.encoding=UTF-8 -J-Dsun.stdout.encoding=UTF-8 -J-Dstdout.encoding=UTF-8 -J-Dstderr.encoding=UTF-8 -J-Dmaven.opts=-Dfile.encoding=UTF-8 -J-Ddefault.charset=UTF-8 -J-Dclient.encoding.override=UTF-8"

**Comment by ly269nva** [comment]
The method of increasing system environment variables what named JAVA_TOOL_OPTIONS is indeed effective, why can't it be configured in Netbeans?
增加系统环境变量JAVA_TOOL_OPTIONS的方式确实有效，为啥netbeans中就配置不了呢？

**Comment by olivalpaulino** [comment]
I've already tried within the NetBeans configuration file, restarted the service, restarted the computer, and it doesn't work that way. However, configuring the environment variable works, as I show in the video. The reason why it works via environment variable and not directly in NetBeans is still unclear.

**Comment by duoduobingbing** [comment]
@olivalpaulino 
The reason is that the changed encoding has to be set for the IDE itself (e.g. via `netbeans.conf`) **and** for the project (e.g. under `exec.vmArgs` in the "Run" action for the specific project). 

`JAVA_TOOL_OPTIONS` gets picked up by both (the individual project and the IDE), so it works.
