### ISSUE TITLE
Autocompletion for PHP Attributes 

### ISSUE THREAD

**Issue by SebNetbeans** [apache/netbeans#4300]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Hello,

Just a simple question. Is it possible to activate autocompletion for
PHP Attributes in Netbeans 14 ?

For an attribute like this :

```
#[Attribute]
final class MaxLength(int $maxLength) { ... }
```

And use it like this :
```

#[MaxLength(40)] // <-- Autocomplete here !
private string $test;
```

I didn't find any documentation on this trick.

Thank you !

Sébastien

### How to reproduce

![autocompletion](https://user-images.githubusercontent.com/108365806/176608660-c259c6d1-65c8-4112-a666-c624bb7e3493.png)

Not test in an earlier version

### Did this work correctly in an earlier version?

No

### Operating System

Linux Ubuntu

### JDK

OpenJDK 64-Bit Server VM 17.0.3

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
NetBeans currently does not support code completion.
Support added in #2640 supports basic editing and formatting.

**Comment by m7md3omr** [comment]
I ve reported a bug couple of days ago about auto-compelete crushes

**Comment by stollr** [comment]
Great news. Thank you :-)
