### ISSUE TITLE
CSS hex color support with alpha

### ISSUE THREAD

**Issue by excolo-rick** [apache/netbeans#4304]
### Description

CSS RGBA color support includes the #RGBA/#RRGGBBAA (https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color) format for deinition, and major browsers have supported it for half a decade or more.

Netbeans' CSS validator objects to this format.

Please add support to the CSS validator.

### Use case/motivation

Using CSS in a project, and use of *-color: #RRGGBBAA is flagged as "unexpected charactes found," giving warnings where none is relevant.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment]
@excolo-rick please have a look at #4964 this should fix this issue. If you need a prebuild binary I referenced a build there.
