### ISSUE TITLE
CSS position:sticky support

### ISSUE THREAD

**Issue by excolo-rick** [apache/netbeans#4305]
### Description

The CSS position property allows for a value of `sticky`. Major browsers have supported this for up to a decade.

Netbeans' CSS validator objects to this value.

Please add support to the CSS validator.

### Use case/motivation

Using CSS in a project, and use of `position: sticky` is flagged as "unexpected charactes found," giving warnings where none is relevant.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment]
Fix was merged via #4480
