### ISSUE TITLE
CSS: min-width: auto => Unexpected character(s) "auto" found

### ISSUE THREAD

**Issue by JackTrapper** [apache/netbeans#4312]
### Apache NetBeans version

Apache NetBeans 14

### What happened

For the CSS styling:

    min-width: auto;

NetBeans reports that `auto` is invalid:

![image](https://user-images.githubusercontent.com/4681474/176925548-9cb53dfa-ead8-4597-beb3-aed9ea9f3794.png)

> Unexpected character(s) "auto" found.

The `min-width` can have the value `auto`:

- https://developer.mozilla.org/en-US/docs/Web/CSS/min-width

So it shouldn't be identified as an error.

Bonus Reading
------------

- https://bz.apache.org/netbeans/show_bug.cgi?id=271414

### How to reproduce

Create a `.css` file, and declare:

```
img {
    min-width: auto;
}
```

### Did this work correctly in an earlier version?

No

### Operating System

Microsoft Windows [Version 10.0.19044.1766]

### JDK

Eclipse Adoptium jdk-17.0.3.7-hotspot

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Reproducible.
Thanks for your report.

**Comment by matthiasblaesing** [comment]
@JackTrapper please have a look at https://github.com/apache/netbeans/pull/4964 this should fix this issue. If you need a prebuild binary I referenced a build there.
