### ISSUE TITLE
Netbeans11 to Netbeans14 upgrade crash at startup

### ISSUE THREAD

**Issue by RGeorgy** [apache/netbeans#4319]
### Apache NetBeans version

Apache NetBeans 14

### What happened

After Upgrading from Netbeans 11 to Netbeans 14 it first mentioned 3 module files that need to be updated. That modules were not listed as problematic. 
After upgrading the modules Netbeans14 does not start again - it sets the lock . but stops ...
Restarting not possible
Uninstalling and reinstalling Netbeans 14 does not recover from this situation. 
My old Netbeans 11 is still running so far ...
The old Nebeans 11 was running under Java 8. Before installing Netbeans 14 I upgraded to JDK 17

### How to reproduce

Update to JDK17
Install Netbeans 14
When asked to update some modules - I did this.
Restarting Netbeans 14.
In the splash screen it reads loading modules. It shortly shows starting modules - it crashes - no Netbeans window can be seen any more.
The netbeans lock is set. So Retry fails with corresponding message
[20220702112635.log](https://github.com/apache/netbeans/files/9032826/20220702112635.log)
[20220702120332.log](https://github.com/apache/netbeans/files/9032827/20220702120332.log)
.

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 11

### JDK

OpenJDK17U-jdk_x64_windows_hotspot_17.0.3_7.msi

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

always - still there ...

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
clear the config folder and start NB, but this time, don't import old config or modules.

folder should be here according to your log:
`C:\Users\Erazer2019\AppData\Roaming\NetBeans`

out of curiosity, what modules did you import?

**Comment by RGeorgy** [comment]
Deleting all files in the USER\AppData\Roaming\Netbeans\14 - gave me a new chance to start Netbeans 14 new...
Before that I deleted some more files in USER\.... Netbeans\14 directory ... I do not know if this is also necessary ...

**Comment by neilcsmith-net** [comment]
This is likely caused by importing old nb-javac modules now that that has been included in the IDE in somewhat different form. The alternative way to import your old config into a new install is to go to `Tools / Options` and click on the `Import` button.

**Comment by RGeorgy** [comment]
> 

Sorry mbien just seen - thanks so much ...
I imported
     org.netbeans.libs.oracle.jsparser
org.netbeans.modules.nbjavac
org.netbeans.modules.nbjavac.api
org.netbeans.modules.nbjavac.impl

**Comment by mbien** [comment]
> org.netbeans.modules.nbjavac
> org.netbeans.modules.nbjavac.api
> org.netbeans.modules.nbjavac.impl

thats what I thought. The namespace changed at some point, thats why it tried to import nb-javac which is already there, preinstalled with a much newer version. You weren't the first which had this issue.
