### ISSUE TITLE
Bug in the application (Unexpected exception)

### ISSUE THREAD

**Issue by zahwaalmira** [apache/netbeans#4320]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

I just got these notifications and that leads me here
![WhatsApp Image 2022-07-01 at 11 48 01 PM](https://user-images.githubusercontent.com/99079504/176998244-4e3c4537-1a3f-48bb-b775-90d45e4323a9.jpeg)
![WhatsApp Image 2022-07-01 at 11 47 44 PM](https://user-images.githubusercontent.com/99079504/176998257-916d6280-cc3c-485e-bee3-9f0d6f580c0e.jpeg)
![image](https://user-images.githubusercontent.com/99079504/176998301-50a3b584-839e-4e06-9d96-7a07c6621c41.png)

  <exception>
    <message>java.lang.NullPointerException</message>
    <frame>
      <class>org.netbeans.modules.gradle.GradleModuleFileCache21$CachedArtifactVersion</class>
      <method>&lt;init&gt;</method>
      <line>143</line>
      <file>${netBeansDir}modules/org-netbeans-modules-gradle.jar</file>
    </frame>

![image](https://user-images.githubusercontent.com/99079504/176998362-a4422baf-ad11-4878-b6aa-4102f1b11e25.png)
![image](https://user-images.githubusercontent.com/99079504/176998412-2b7bd85f-9d5c-4ec4-847d-3c703c2bc79e.png)

### How to reproduce

i dont know which project caused that error

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 11 64bit

### JDK

9

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

just this time

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
I think we have fixed this for NetBeans 14.
