### ISSUE TITLE
Bad version of nbm-maven-plugin on export package generated

### ISSUE THREAD

**Issue by tbw777** [apache/netbeans#4326]
### Apache NetBeans version

Apache NetBeans 14

### What happened
ITS VERY IMPORTANT TO FIX THIS, BECOUSE BUILD IS FAILED FROM "THE BOX"

![image](https://user-images.githubusercontent.com/15821889/177047379-d623b738-ce3d-4e31-876c-2dfb640e5054.png)

When using menuitem "Export package" NB generate :
![image](https://user-images.githubusercontent.com/15821889/177047428-49ac2fc2-e696-464d-8973-3cdcbbd582d6.png)

instead of 

![image](https://user-images.githubusercontent.com/15821889/177047433-cb9a8a7d-b559-4481-93e5-5dd67075e5d9.png)

1. bad version (old as i understand)
2. duplicate plugin definition
3. compile is broken after this operation. This resolving by delete bad plugin declaration and move config to first instance:

![image](https://user-images.githubusercontent.com/15821889/177047499-cdeb06e8-6acc-4f6f-ad74-7bcda6f097e1.png)

### How to reproduce

Press "Export package" on any new modul

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10 21H1

### JDK

17.0.1; Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
@ebarboni this issue is fixed, right?

**Comment by tbw777** [comment]
fixed
