### ISSUE TITLE
Recovering files

### ISSUE THREAD

**Issue by mamistryo** [apache/netbeans#4330]
### Apache NetBeans version

Apache NetBeans 14

### What happened

I accidentally deleted all my folders and files and I need help recovering / retrieving it.
I opened a new file / project on Netbeans and it happened to be the folder where ALL my important documents are stored.
So I decided to delete the "project" and when I did it also gave me the options to delete (source) which I clicked yes to
not knowing what it was and now all my folders are gone, is there a way to retrieve it? It wasn't showing in my Recycle Bin.
Does Apache Netbeans have a "recycle bin" of it's own? I had googled how to restore it, it says I should try "History, and retrieve"
however that option isn't working or available. Using Apache Netbeans 12.6

Thanks, Ani.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Apache Netbeans 12.6

### JDK

HTML5

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
deleting files in NetBeans means they are deleted in the file system, they won't be moved to the recycle bin. NetBeans keeps some file history, but only for files you edit within NetBeans, if the first action you took is to delete the file there won't be any history.

There are ways to recover some deleted files from disk if they haven't been overwritten yet, but that depends on the file system and NetBeans won't help you with that.

Don't click delete unless you mean it. Use decentral versioning systems like git and do automated backups.
