### ISSUE TITLE
JakartaEE Auto complete of @Named Managed Beans not working in Netbeans 14

### ISSUE THREAD

**Issue by bercolax** [apache/netbeans#4338]
### Apache NetBeans version

Apache NetBeans 14

### What happened

I have created a Maven built JakartaEE 9 web application in Netbeans 14. Other things are working fine. But in the JSF page, I am not able to see  the EL auto complete displaying the list of @Named beans. As the packages have been renamed jakarta (replacing javax), may be the changes must be done in the related modules to list the @jakarta.inject.Named annotated Java classes in the EL autocomplete. 
The navigation from the EL in the JSF page to the Java source code of the jakarta.inject.Named annotated Java classes is also not happening.

### How to reproduce

- Create a brand new JakartaEE 9 based Maven web app
- Create a simple @jakarta.inject.Named annotated backing bean with @Named(value="demoBean") with just 1 function
- In the JSF create EL #{  and then in the auto complete you dont see demoBean being listed.

### Did this work correctly in an earlier version?

No

### Operating System

Ubuntu 20+, Windows 11 

### JDK

JDK 11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time 

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by grantleyT** [comment]
same problem. NB 13 and 14 if you hard code el link in it works fine, but will not display. Using Payara Community server, followed their Jakarta EE 9 tutorial where the same el worked perfectly on IntelliJ platform. If you just import Javax.inject.Name it displays correctly in NB.

**Comment by bercolax** [comment]
I guess in the NB plugin must do a Search and Replace - javax by jakarta and publish this as an add on plugin for those who want to work with Jakarta EE 9 onwards.

**Comment by javierllorente** [comment]
I can still reproduce this issue with NetBeans 15 and 16-rc1.

**Comment by grantleyT** [comment]
Same here, I tried it last night with the Jakarta 9.1 compatible Glassfish
Server.
Still no luck!

**Comment by bercolax** [comment]
Incase we can get involved and help, kindly let me know. Will be happy to get involved. We can have two jars for related plugin. Users working can uninstall the javax.xxx plugin and install the jakartaee.xxx plugin. 
- If any user wishes to work on older versions they can have two versions of Netbeans like Netbeans 15 for jakartaee and Netbeans 14 for javax.xx based.

**Comment by juneau001** [comment]
I had done some work on this issue earlier this year but the PR was not submitted in time for release.  I need to perform a diff against the latest code and my working branch to try and determine what is still causing this issue.  Will try to get this done soon.  Sorry for the delay.

**Comment by grantleyT** [comment]
Ok, thanks for the update.

**Comment by bercolax** [comment]
> I had done some work on this issue earlier this year but the PR was not submitted in time for release. I need to perform a diff against the latest code and my working branch to try and determine what is still causing this issue. Will try to get this done soon. Sorry for the delay.

Thanks for the reply and the update.

**Comment by king-martinien** [comment]
hello, I have the same problem (cannot detect CDI beans in xhtml files ). i'm using Netbeans 14 and jakartaEE 10 with the compatible eclipse glassfish server.

**Comment by king-martinien** [comment]
> hello, I have the same problem (cannot detect CDI beans in xhtml files ). i'm using Netbeans 14 and jakartaEE 10 with the compatible eclipse glassfish server.

Now i have downloaded Netbeans 17 and the problem is still there.

**Comment by OnElectric** [comment]
Hi, the only way I have been able to use autocompletions in jsp is by adding the javax.servlet-api library with java 11.
Does anyone know another way? Since for everything to be correct when we compile jsp, we must remove that library so that it uses jakarta instead of javax.
Thank you

**Comment by AmilMammadli** [comment]
in netbeans 17 and jdk 20, autocomplete does not work between <%%> in jsp file, please help

**Comment by apapamarkou** [comment]
Still have this issue. MacOsx , Windows, Linux Netpeans 14, 16, 17.

**Comment by bercolax** [comment]
Installed Netbeans 19 and verified that the issue has been fixed. Thanks a lot.
