### ISSUE TITLE
org.netbeans.external:org-apache-commons-lang3 not availabe for RELEASE140

### ISSUE THREAD

**Issue by gdm-tts** [apache/netbeans#4339]
### Apache NetBeans version

Apache NetBeans 14

### What happened

The depenency `org.netbeans.external:org-apache-commons-lang3` is not found when upgrading a maven-based RPC application to RELEASE140 from RELEASE130.
The dependency is required by the module `org.netbeans.modules.java.lsp.server`.

My search in PRs found that the commons-lang3 library was updated for NB 14 ([see PR 3776](https://github.com/apache/netbeans/pull/3776)), but I failed to see how the dependency must be declared now.

### How to reproduce

Create a new NetBeans Platform-based application built using Maven.
In the application pom.xml add the following dependency:
```
<dependency>
    <groupId>org.netbeans.external</groupId>
    <artifactId>org-apache-commons-lang3</artifactId>
    <version>${netbeans.version}</version>
</dependency>
```

It works when netbeans.version=RELEASE130.

A [search in Maven Central](https://search.maven.org/artifact/org.netbeans.external/org-apache-commons-lang3) confirms that RELEASE140 is not present.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

N/A

### JDK

N/A

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by ebarboni** [comment]
https://repo1.maven.org/maven2/org/netbeans/api/org-netbeans-modules-java-lsp-server/RELEASE140/org-netbeans-modules-java-lsp-server-RELEASE140.pom

show usage of <dependency>
<groupId>org.apache.commons</groupId>
<artifactId>commons-lang3</artifactId>
<version>3.12.0</version>
<classifier/>
</dependency>

and not <dependency>
    <groupId>org.netbeans.external</groupId>
    <artifactId>org-apache-commons-lang3</artifactId>
    <version>${netbeans.version}</version>
</dependency>

You should adapt your pom we try to use the artefacts from the maven central more than the one in external
