### ISSUE TITLE
Error with new Ant JavaFX FXML project

### ISSUE THREAD

**Issue by garawaa** [apache/netbeans#4346]
### Apache NetBeans version

Apache NetBeans 14

### What happened

new project from file->new project->java with ant->javafx->javafx fxml application template gives error when executing. same project creating in nb13 works normally.

### How to reproduce

file->new project->java with ant->javafx->javafx fxml application
From project view right click on the created project and run it

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

windows 10

### JDK

1.8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ebresie** [comment]
What version of ant, Java, and JavaFX were in use?  Platform?  Did you have Fx plug-in installed?

**Comment by neilcsmith-net** [comment]
What error?  Please provide some specifics.

Also, NetBeans 14 is not officially supported running on JDK 8.

You're probably better looking at using JavaFX with Maven or Gradle support and JDK 11+.

**Comment by garawaa** [comment]
my java version is 1.8. There are no such errors in nb13.

**Comment by lkishalmi** [comment]
Correct how?

**Comment by neilcsmith-net** [comment]
@garawaa nothing has changed in the templates between NB13 and NB14.  Unless you can provide details - log of the errors, etc. - so that we can actually look if there's a problem elsewhere, then this issue will be closed as unactionable.
