### ISSUE TITLE
Netbeans 14 bug 2

### ISSUE THREAD

**Issue by garawaa** [apache/netbeans#4347]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Java swing application: free design layout doesn't work

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

windows 10

### JDK

1.8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
can not preproduce
