### ISSUE TITLE
'call hierarchy' from base class does not work anymore

### ISSUE THREAD

**Issue by sijskes** [apache/netbeans#4366]
### Apache NetBeans version

Apache NetBeans 14

### What happened

'call hierarchy' 'search from base class' option does not function anymore, when clicking 'call hierarchy' on a method of a implementation of an interface. 

### How to reproduce

clicking 'call hierarchy' on a method of a implementation of an interface. 

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### JDK

multiple

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

    /**
     * right-click 'call hierarchy' should show calls to method1 from base class.
     * (when this options is enabled in the 'Java Call Hierachy' window, filter icon menu.)
     *
     * works on:
     * Apache NetBeans IDE 11.0 (Build incubator-netbeans-release-404-on-20190319)
     * Java: 11.0.15; OpenJDK 64-Bit Server VM 11.0.15+10-Ubuntu-0ubuntu0.20.04.1
     *
     * works on:
     * Product Version: Apache NetBeans IDE 12.0
     * Java: 11.0.15; OpenJDK 64-Bit Server VM 11.0.15+10-Ubuntu-0ubuntu0.20.04.1
     *
     * does not work on:
     * Product Version: Apache NetBeans IDE 13
     * Java: 17.0.3; OpenJDK 64-Bit Server VM 17.0.3+7-Ubuntu-0ubuntu0.20.04.1
     *
     * does not work on:
     * Product Version: Apache NetBeans IDE 13
     * Java: 11.0.15; OpenJDK 64-Bit Server VM 11.0.15+10-Ubuntu-0ubuntu0.20.04.1
     *
     * does not work on:
     * Product Version: Apache NetBeans IDE 14
     * Java: 17.0.3; OpenJDK 64-Bit Server VM 17.0.3+7-Ubuntu-0ubuntu0.20.04.1
     */

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by sijskes** [comment]
other users report from dev list: 

I also have this problem on Mac M1 with self-built NB14.

**Comment by sijskes** [comment]
[callbug.zip](https://github.com/apache/netbeans/files/9092026/callbug.zip)

minimal example for demonstrating bug.

**Comment by mbien** [comment]
@sijskes  thanks for the detailed report and the reproducer. I just tested it and could make it work on 12.2, while 12.3+ is where it stopped. Sounds like a git bisection for a rainy day.

**Comment by sdedic** [comment]
I would set this to "In progress" as it was the way how one would express willingness to spend one's time on an issue but sadly this is not a JIRA or other _real_ task tracking system. 

I did some adjustments to Call Hierarchy recently that could potentially affect NB 14, but definitely not 12.3 or 13.0, but still +- I should remember how that think works.

**Comment by sijskes** [comment]
[callbug2.zip](https://github.com/apache/netbeans/files/9113415/callbug2.zip)
updated with derived from abstract class, multiple derivation from concrete class.

**Comment by sijskes** [comment]
> @sdedic wip label is set. I could run a bisection between 12.2 and 12.3 if that helps.
> 
> edit: well the bisect wasn't successful. The version range requires nb-javac and it wants to download it but the download does not work.

I cant comment on the buildprocess, but i tried running 11.0 with nb-java disabled and that still works. (i only removed var/cache in between restarts).

**Comment by sdedic** [comment]
I have good news ... and obviously bad news. The good news is that the culprit is probably known.
It seems that implementation of the Call Hiearchy assumes that javac `Trees.getPath()` will return a TreePath for an Element that was *not part of the compilation unit(s) for which the `JavaSource` was created*. This was true for **older nbjavac** implementations, but not for the "generated" nbjavac, which we started to ship with NB13.

And the bad news is that the fix may be little tougher.

**Comment by mbien** [comment]
> I have good news ... and obviously bad news. The good news is that the culprit is probably known. It seems that implementation of the Call Hiearchy assumes that javac `Trees.getPath()` will return a TreePath for an Element that was _not part of the compilation unit(s) for which the `JavaSource` was created_. This was true for **older nbjavac** implementations, but not for the "generated" nbjavac, which we started to ship with NB13.
> 
> And the bad news is that the fix may be little tougher.

i am actually running a bisect right now and can confirm that it ever only worked with nb-javac installed (no matter what JDK version NB is running on). I am not done yet but my current guess is that it will fail as soon as manually-maintained nb-javac becomes jackpot-generated nb-javac, which is essentially identical to plain javac except its language level.

**Comment by sdedic** [comment]
See https://cwiki.apache.org/confluence/display/NETBEANS/Differences%3A+nb-javac -- "Recompleting symbols from sources"

**Comment by mbien** [comment]
12 full rebuilds later (and manually installing nb-javac every time ;)) i can confirm that c1d0699b401d1580e62f7ec6a76aa80021d1af27 of #3206 is indeed the commit causing the regression.
