### ISSUE TITLE
CSS: position: sticky => Unexpected character(s) "sticky" found

### ISSUE THREAD

**Issue by JackTrapper** [apache/netbeans#4368]
### Apache NetBeans version

Apache NetBeans 14

### What happened

For the CSS styling:

    position: sticky;

NetBeans reports that `sticky` is invalid:

![image](https://user-images.githubusercontent.com/4681474/178590533-70357460-8f1e-4428-b9ae-87bdb0dca04d.png)

> Unexpected character(s) "sticky" found.

The `position` can have the value `sticky`:

- https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky_positioning

So it shouldn't be identifier as an error.

### How to reproduce

Create a `.css` file, and declare:

```
img {
   position: sticky;
}
```

### Did this work correctly in an earlier version?

No

### Operating System

Microsoft Windows [Version 10.0.19044.1766]

### JDK

Eclipse Adoptium jdk-17.0.3.7-hotspot

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Chris2011** [comment]
Hey @JackTrapper please make sure that your issue wasn't created earlier, next time because there was already one: #4305
Closing this as duplicate.
