### ISSUE TITLE
Navigator: JavaScript async private function not marked as private

### ISSUE THREAD

**Issue by lbuchs** [apache/netbeans#4371]
### Apache NetBeans version

Apache NetBeans 14

### What happened

javascript private class members (starting with #) are not marked as private in the navigator if the function is async.

### How to reproduce

Example: 

    class test {
        #var;

        // private
        #test1() {}
        async #test2() {}

        // public
        test3() {}
        async test4() {}

        // static private
        static #test5() {}
        static async #test6() {}

        // static public
        static test7() {}
        static async test8() {}
    }

Navigator: 
![grafik](https://user-images.githubusercontent.com/37619779/178758135-9d44afcf-d0f2-42d8-ac30-61b90e36fd35.png)

`#test2` and `#test6` are not marked as private. `#test5` is marked as private but not static.

### Did this work correctly in an earlier version?

No

### Operating System

Windows 11

### JDK

Runtime: Java(TM) SE Runtime Environment 17.0.1+12-LTS-39

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
@lbuchs could you please have a look at the PR #5677, which should fix this problem?

To test a prebuild binary is available from the checks page.

Checks summary: https://github.com/apache/netbeans/actions/runs/4457762337
Direct link to download: https://github.com/apache/netbeans/suites/11654862465/artifacts/605360507
