### ISSUE TITLE
"Find usages" on a PHP class constructor does not find uses of alias classes

### ISSUE THREAD

**Issue by dezlov** [apache/netbeans#4382]
### Apache NetBeans version

Apache NetBeans 14

### What happened

"Find usages" on a PHP class constructor does not find uses of alias classes.

For example, is we have `use Bar as Foo`, finding uses of `Bar` constructor will find `new Bar()` but not `new Foo()`.

### How to reproduce

```php
use Bar as Foo;

class Bar
{
	public function __construct()
	{
	}
}

$foo = new Foo();
$bar = new Bar();

var_dump($foo);
var_dump($bar);
```

Try to find usages of `__construct()`.

The results show only 2 usages found on these lines:

* `public function __construct()`
* `$bar = new Bar();`

The usage on this line is not shown in the results:

* `$foo = new Foo();`

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10 64-bit

### JDK

OpenJDK 11.0.15 64-bit

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Bug is reproducible.
Thanks for your report.

**Comment by dezlov** [comment]
@junichi11 I noticed that you do a lot of work on the PHP side for NetBeans. I was wondering if you could have a look at this issue?

**Comment by junichi11** [comment]
@dezlov I'll try to have a look at it later but I can't promise anything.
