### ISSUE TITLE
It is possible to right-click on a placeholder "Loading, please wait" in the history view.

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#4394]
### Apache NetBeans version

Apache NetBeans 14

### What happened

When you click on "Load next 30 days" in the history view, the placeholder "Loading, please wait" appears. You can right-click on it and call the context menu, which logically should not be the case.

### How to reproduce

In the video, the placeholder appears for a short period of time, but you can still have time to click on it.

https://user-images.githubusercontent.com/9607501/179468467-704a2509-a6cb-4ffa-89ff-e5b3cf60fbae.mp4

### Did this work correctly in an earlier version?

No

### Operating System

Debian GNU/Linux 10 (buster)

### JDK

OpenJDK 64-Bit Server VM 11.0.15+10-post-Debian-1deb10u1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
you have to be a fast clicker to reproduce this. but yeah, there probably shouldn't be a context menu there :)

**Comment by mbien** [comment]
change made it into 15 rc2 https://lists.apache.org/thread/qw4sd9kqy3c1lftwhl61ftpkcqcd6m0f
