### ISSUE TITLE
Every Java breakpoint is a multi breakpoint

### ISSUE THREAD

**Issue by lkishalmi** [apache/netbeans#4415]
### Apache NetBeans version

Apache NetBeans 15 release candidate

### What happened

Just updated to 15-rc1 today and it seems If I put a breakpoint to a Java file it instantly becomes a multi-breakpoint. 
![image](https://user-images.githubusercontent.com/1381701/180146582-751b88d6-a441-44b8-b7b6-b604de62a90c.png)

### How to reproduce

Put a breakpoint in a Java class.

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Ubuntu 22.04

### JDK

JDK17

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
I tried various variations of setting breakpoints but can't replicate this with the rc1 binary zip.  Any interesting logging?  Replicate with clean userdir and cachedir?

**Comment by lkishalmi** [comment]
Tested a bit further. It does not happen with clean user-dir, just with migrated ones. Still testing.

**Comment by lkishalmi** [comment]
Well, find out that it only happens when the Groovy cluster is enabled as the new Groovy Debugger support is eager to add additional Breakpoints into Java files.
Testing further if I could find a fix.

**Comment by lkishalmi** [comment]
Most likely caused by #4153 as the following registration was missing earlier: https://github.com/apache/netbeans/blob/487686125c370140bc39cc8f1d598783f187fdf5/groovy/groovy.debug/src/org/netbeans/modules/groovy/debug/GroovyBreakpointAnnotationListener.java#L42

@entlicher Probaly we shall make that AnnotationListener smarter.

**Comment by neilcsmith-net** [comment]
Thanks @lkishalmi - verified. Having multiple breakpoints also disables the menu for breakpoint properties.  Adding high priority - don't think we can release NB15 with this.

**Comment by lkishalmi** [comment]
I'm working on the fix. It was kind of easy to avoid double registration on Java classes, though there is a bug in the debugger core that prevents breakpoint registration in Groovy files. Fixing that bug, it seems both Truffle and Groovy breakpoints are created.
Now Truffle and Groovy are clashing. I hope I can sort it out soon.
