### ISSUE TITLE
Gradle Projects Test Sources do not see the main code.

### ISSUE THREAD

**Issue by lkishalmi** [apache/netbeans#4418]
### Apache NetBeans version

Apache NetBeans 15 release candidate

### What happened

Create a new gradle library project. Open the LibraryTest.java in the new project. It does not see the Library class.

### How to reproduce

Create a new gradle library project. Open the LibraryTest.java in the new project. It does not see the Library class.

#4406 seems to be similar, though it was filed for NetBeans 14. I've tested the scenario above and it is good in NetBeans 14.

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Ubuntu 22.04

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
#4406 was filed since 14.0.301 was released, so could be the same issue?  It's closer in code to NetBeans 15, and we don't have a way to differentiate in the issue reports.

**Comment by adamoutler** [comment]
This affects me too. My workaround was to use maven build helper to add extra sources to the project.  Any chance of backport to 14 or just wait for the fix in 15?

**Comment by lkishalmi** [comment]
@adamoutler It shall work in NetBeans 14 standard distribution. Are you using the recently updated VS Code plugin?

**Comment by adamoutler** [comment]
No.  I'm using the Netbeans 14 64bit app.

**Comment by neilcsmith-net** [comment]
@adamoutler if you're using Maven, please open a separate issue.

**Comment by adam-waldenberg** [comment]
> No. I'm using the Netbeans 14 64bit app.

Please check out;

https://github.com/apache/netbeans/issues/4823#issuecomment-1311941783
