### ISSUE TITLE
NetBeans does not completely exist after a Gradle build has been done.

### ISSUE THREAD

**Issue by lkishalmi** [apache/netbeans#4419]
### Apache NetBeans version

Apache NetBeans 15 release candidate

### What happened

This could be a bug in Gradle 7.5 actually. So if the user executed/loads a Gradle project which would end up starting a Gradle daemon, then it would keep a non-daemon thread running inside NetBeans JVM. That prevents NetBeans to stop cleanly and keeps the JVM floating around.

Stopping the gradle daemons with ```gradle --stop``` would close NetBeans.

(This is not the first time, Gradle left a thread open.)

### How to reproduce

1. Create/Open a Gradle project.
2. Build the Gradle Project
3. Close NetBeans. 
4. Check the processes, NetBeans JVM shall be around

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Ubuntu 22.04

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
little existential crisis for NetBeans :)

**Comment by lkishalmi** [comment]
Interesting...
I cannot reproduce this with 15-rc2.
@mbien Would you care to test this for me? Thank you!

**Comment by mbien** [comment]
@lkishalmi when i close NB (build from #4456, which should be based on delivery) after going through the steps i get the popup
"exiting the IDE will terminate the following processes: Process - Build (gradleproject1:app)"

When i press exit or wait long enough it will exit fine. The gradle daemon is still left. But this is expected right? It will close itself after a while i suppose.

```
jps
43602 GradleDaemon
43835 Jps
```

**Comment by lkishalmi** [comment]
Tested several times with 15-rc3 as well. Could not reproduce anymore. That's good!
