### ISSUE TITLE
A java.lang.NullPointerException exception has occurred. However, the system should continue working without further problems. Click Show Details for the stack trace.

### ISSUE THREAD

**Issue by poollook** [apache/netbeans#4423]
### Apache NetBeans version

Apache NetBeans 14

### What happened

A java.lang.NullPointerException exception has occurred.
However, the system should continue working without further problems.
Click Show Details for the stack trace.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

windosw 10

### JDK

18

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

A java.lang.NullPointerException exception has occurred.
However, the system should continue working without further problems.
Click Show Details for the stack trac[e]([url](url)).

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
closing due to insufficient info in the report
https://netbeans.apache.org/participate/report-issue.html
