### ISSUE TITLE
Missing space (typo) in PHPStan section

### ISSUE THREAD

**Issue by asafm7** [apache/netbeans#4426]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Missing space (typo) in PHPStan section, after the word "path".

Screenshot attached:
![3BwHjLX0tS](https://user-images.githubusercontent.com/14274769/180463369-bdf1c667-bc39-4930-8252-57ad5902340e.png)

### How to reproduce

Visit the section

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 

### JDK

Not relevant 

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Thanks for your report.

I've created fix PR.

**Comment by KacerCZ** [comment]
Fix was merged and will be part of NetBeans 15.
