### ISSUE TITLE
DebuggerManagerAdapter

### ISSUE THREAD

**Issue by quantrpeter** [apache/netbeans#4434]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Hi, my project is trying to register DebuggerManagerAdapter via [org.netbeans.api.debugger.LazyDebuggerManagerListener](https://gitlab.com/quantr/toolchain/netbeans-riscv/-/blob/master/src/main/resources/META-INF/debugger/org.netbeans.api.debugger.LazyDebuggerManagerListener) but is never fire, in the log console nothing come out. May I know how to trace this bug please?
thanks

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

mac

### JDK

18.0.1.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
You might want to look at https://bits.netbeans.org/14/javadoc/org-netbeans-api-debugger/org/netbeans/spi/debugger/DebuggerServiceRegistration.html as used at https://github.com/apache/netbeans/search?q=debuggerserviceregistration
