### ISSUE TITLE
Apache NetBeans freezes at start

### ISSUE THREAD

**Issue by ZenyaIse** [apache/netbeans#4451]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Apache NetBeans freezes at start just after installation (seems to not able to build GUI). Tried different versions (13, 14), clearing cache, rebooting, reinstalling. Nothing helped. Version 11 works well.

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10

### JDK

1.8.0_211

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
have you tried using a supported JDK?

**Comment by ZenyaIse** [comment]
Manually installed required version of JDK, set netbeans_jdkhome option to the new JDK and it works.
Thanks!

**Comment by mbien** [comment]
awesome :)
