### ISSUE TITLE
Syntax error in php7.4 on php8.1 readonly keyword

### ISSUE THREAD

**Issue by pluk77** [apache/netbeans#4457]
### Apache NetBeans version

Apache NetBeans 14

### What happened

The php version in my project is set to 7.4, yet I get a syntax error related to a php8.1 keyword (readonly), specifically in my 'use' and 'namespace' statement. This should not happen as it is not a reserved keyword in <8.1

### How to reproduce

Set php version to 7.4
Add the following statements in a PHP file

```php
namespace Src\BaseEntity\ReadOnly;

use Src\BaseEntity\ReadOnly\SisterEntity;
```

### Did this work correctly in an earlier version?

Apache NetBeans 12.4

### Operating System

windows

### JDK

1.8.0_302; OpenJDK 64-Bit Server VM 25.302-b08

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Have not tried on Netbeans > 12.4 or 13, just migrated from 12.4 to 14

Could have been introduced as part of https://github.com/apache/netbeans/pull/3360 

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by junichi11** [comment]
I've already fixed it: #4037
