### ISSUE TITLE
Update libjunixsocket to 2.5.x - dylib fails notarization

### ISSUE THREAD

**Issue by neilcsmith-net** [apache/netbeans#4460]
The x86_64 version of the libjunixsocket 2.4.0 native library is compiled against macOS SDK 10.8. A minimum of SDK 10.9 is required for notarization.  Without notarization, macOS installers cannot be produced.  AFAIK this is fixed in version 2.5.0, compiled against SDK 10.14, although there is now 2.5.1.

https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues

cc @matthiasblaesing - any concerns elsewhere if updated?

**Comment by matthiasblaesing** [comment]
I'll prepare an update shortly.

**Comment by neilcsmith-net** [comment]
@matthiasblaesing thanks. If you can handle update that's great, or I can have a look tomorrow. Mainly wanted to check you didn't have concerns.

Unfortunately looks like this regressed in 2.4.0 - had been fixed once in 2.3.1 https://github.com/kohlschutter/junixsocket/pull/76

**Comment by matthiasblaesing** [comment]
So I prepared an update. While the version number indicated, that it is an API compatible change, it is in fact not and the docker.api module was broken. I tested the updated library on linux and could connect with my SSH agent and I checked the disassembled code of JSch and there the non-deprecated version of the socket address generation was used. This should be ok.

**Comment by matthiasblaesing** [comment]
If anyone tries to rebuild the sig file, you get flooded with exceptions as sigtest failes to parse the class files. While looking into this, I noticed, that to my analysis sigtest just does not follow the JVMS and reads the wrong parts of the class file when RuntimeInvisibleTypeAnnotations are read. sigtest needs to be fixed or replaced.
