### ISSUE TITLE
IDE copy and paste reports "Not a valid class"

### ISSUE THREAD

**Issue by BruceKHaddon** [apache/netbeans#4463]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Any attempt to use copy to copy a file (java source or other) leads to :"Copy is not a valid class" when pasting. It used to be possible to copy and paste any file (completed or incomplete class or other kind of file). Now it will not copy and paste even compiled and correct classes. This functionality should be general and allow the copying of any file in the project (and apply a sequence number if pasted to the same package).

### How to reproduce

Select any file (class or otherwise)
Select "copy" from the edit menu or the pop-up menu.
Select a package for a destination.
Select "paste" from the edit menu or the pop-up menu.

### Did this work correctly in an earlier version?

Apache NetBeans 12.4

### Operating System

Windows 10 Pro, 21H2, 64-bit, build 19044.1826

### JDK

OpenJDK jdk-18.0.1.1 Apache download 64-bit

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Thanks for the report.  If there is a relevant stack trace from the error message or `View / IDE log` please add.

I've just tried to replicate, and seen this once.  After the first attempt, paste had a sub-menu with refactor copy option.
