### ISSUE TITLE
New Gradle project creates just empty folder

### ISSUE THREAD

**Issue by garawaa** [apache/netbeans#4464]
### Apache NetBeans version

Apache NetBeans 14

### What happened

new gradle java project creates just empty folder.

### How to reproduce

File -> new project -> java with gradle -> java application

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

windows 10

### JDK

1.8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Anything useful in `View / IDE log` or error messages?  Please try with a later JDK too - running on JDK 8 is not officially supported.

**Comment by lkishalmi** [comment]
You might experience the following issue #4387.

**Comment by lkishalmi** [comment]
Please test it on NetBeans 15. Repoen it if the issue still happens.
