### ISSUE TITLE
Website tutorial on modules missing images

### ISSUE THREAD

**Issue by brutzman** [apache/netbeans#4491]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Tutorial page is missing images.  Inspecting src links didn't reveal an easy fix.

* NetBeans Platform Plugin Quick Start
* https://netbeans.apache.org/tutorials/nbm-google.html

### How to reproduce

Visiting tutorial page reveals broken image links.

The image links worked previously (long ago) but relevant subdirectory might not have transitioned to apache, not sure...

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10

### JDK

OpenJDK 18.0.2

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Module tutorials seem essential to health of NetBeans platform but not well supported.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ebresie** [comment]
This is likely an issue associated with the https://github.com/apache/netbeans-website content.

I'm assuming it may relate to this one https://github.com/apache/netbeans-website/blob/master/netbeans.apache.org/src/content/tutorials/nbm-google.asciidoc

Assume the images may be available in an older version here https://github.com/apache/netbeans-website/tree/asf-site/content/tutorials/images 

But if I'm not mistaken the above asciidoc seems to point to for example images/nbm-googlebar/new-project-0.png.

Assume need 
(1) applicable images need to be moved into a "nbm-googlebar" subfolder and/or 
(2) "version specific" file names needs to be adjusted where applicable to align to current images (i.e. without "version identifiers) in some way.

**Comment by ebresie** [comment]
After further review, the folder does exist already with the proper names so there may be an issue when publishing the page to the asf-site branch of the netbeans-website content.

**Comment by brutzman** [comment]
Wondering if first performing a manual push of the missing images might at least make the tutorial repeatable?

**Comment by mbien** [comment]
images got restored recently on the above mentioned page, closing
