### ISSUE TITLE
Refactoring error

### ISSUE THREAD

**Issue by Muinighin** [apache/netbeans#4504]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Attempted to refactor rename a class field. Instead of refactoring, I received the attached error message. Log file also supplied.
![image_2022-08-15_101241935](https://user-images.githubusercontent.com/37768133/184608766-ff958d52-952a-49ed-b5a5-52abf37942ac.png)
[messages.log](https://github.com/apache/netbeans/files/9336233/messages.log)

### How to reproduce

Attempted to refactor rename field 'instrument' in simple class Message to 'receiver'. Tried renaming to different name and restarting Netbeans, both produced the same error.

![image_2022-08-15_101650261](https://user-images.githubusercontent.com/37768133/184609463-36e4c5b0-0962-4262-8df8-e6ff5614818a.png)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 Home Version	21H2  OS build	19044.1889 Experience	Windows Feature Experience Pack 120.2212.4180.0

### JDK

OpenJDK 18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Refactoring usually works without problem.

Product Version: Apache NetBeans IDE 14
Java: 18.0.1; OpenJDK 64-Bit Server VM 18.0.1+10
Runtime: OpenJDK Runtime Environment 18.0.1+10
System: Windows 10 version 10.0 running on amd64; UTF-8; en_GB (nb)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
this was likely fixed in https://github.com/apache/netbeans/pull/7153 (NB 22)
