### ISSUE TITLE
Code completion not working in default switch case

### ISSUE THREAD

**Issue by icojb25** [apache/netbeans#4511]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Firstly, I'm not sure if this is specific to Spring Boot projects. 

I have a simple Spring RestController which passes method arguments through a switch statement. If I try to access a public static inner class field as a method or return parameter in the 'named' cases, this works, but neither the goto nor autocomplete functionality works when trying to access the inner class fields in the 'default' case of the switch statement. 

Ctrl click to go to source origin (the class def) also does not work in the default case, although this works for the other switch cases. 

### How to reproduce

1) Start new Spring boot project with starter-web enabled
2) build out a new RestController with a switch statment in the body
3) Attempt to access a public inner static class variable in the statement block of the 'default' switch case block, it will not work. 

NB Update - this is not specific to Spring Boot, it appears to happen in standard projects as well. 

```java
public class Mavenproject1
{
  public String method1(String variable)
      {
  
          switch (variable)
          {
              case "one":
              {
                  return Mavenproject1.RspCodes.ONE;
              }
              
              case "two":
              {
                  return Mavenproject1.RspCodes.TWO;  // <------- code completion WORKS here
              }
              
              default: 
              {
                  return Mavenproject1.  // <---- code completion appears to BREAK here
              }
          }
      }
      
      public static class RspCodes
      {
               public static final String ONE = "one";
               public static final String TWO = "two";
      }

}
```

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Win 10 Home

### JDK
IDE is running on: OpenJDK 11.0.14.1
Porject is running on: Oracle JDK 1.8_201

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Building with built in Maven
Oracle 1.8 (201) JDK x64

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by icojb25** [comment]
Clearing the cache does not seem to fix the problem

**Comment by neilcsmith-net** [comment]
Please try running the IDE on JDK 11 or higher and verify the problem still occurs.  JDK 8 is no longer a supported option for running the IDE on.  You can still choose JDK 8 under Java Platforms for projects.

You said this can be reproduced with a "standard" Maven project.  Please provide a minimal reproduce project and upload a zip here - thanks!

**Comment by icojb25** [comment]
Hi @neilcsmith-net - thanks for your response. I've uploaded something below. 

Re: the JDK - yes, I fixed the bug report - the project is running on JDK 8, but the IDE is running on AdoptOpenJDK 11. I have amended the report above. 

[mavenproject1.zip](https://github.com/apache/netbeans/files/9349383/mavenproject1.zip)

**Comment by neilcsmith-net** [comment]
Thanks.  Unfortunately, I cannot reproduce with that project - all works fine here.

**Comment by icojb25** [comment]
Hmmm, ok, thanks @neilcsmith-net is there any other info that would be helpful (where would I find it?)? I have reproduced on x2 projects (prod - Spring app, and test project above). 

See from the screenshot the static inner class is not suggested. 

![Capture](https://user-images.githubusercontent.com/37830404/184848235-0dcd2445-3831-4f7a-85d3-b81b82d8d258.PNG)

**Comment by mbien** [comment]
can you update your snippet so that it is a self contained reproducer? There is no static inner class anywhere.

**Comment by icojb25** [comment]
Sorry, I realise I was actually running NB13, not 14 as previously stated. This doesnt happen on NB14 so I guess we could close this, even though I expect it could be confirmed on 13 using the test case above. Apologies for the red herring.

**Comment by mbien** [comment]
I see. Well, don't forget to upgrade to NB15 in a few weeks ;)
