### ISSUE TITLE
Links in output window stacktraces do not work (when they point to JDK code)

### ISSUE THREAD

**Issue by maffe** [apache/netbeans#4516]
### Apache NetBeans version

Apache NetBeans 14

### What happened

The links in stacktraces to JDK code do not work with JDK 9+.

### How to reproduce

Run any code causing an exception in JDK code in a Maven project, for example:

```
package com.acme.bugs.netbeans;

import java.io.FileNotFoundException;
import java.io.FileReader;

public class StacktraceLink {
    public static void main(final String[] args) throws FileNotFoundException {
        new FileReader("nonexistent");
    }
}
```

Output:
```
--- exec-maven-plugin:3.0.0:exec (default-cli) @ Test ---
Exception in thread "main" java.io.FileNotFoundException: nonexistent (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at com.acme.bugs.netbeans.StacktraceLink.main(StacktraceLink.java:10)
```

Clicking on a link starting with `java.base/` (or any other Java module) does not open the file and a message `Source file not found for "FileReader"`/`Source file not found for "FileInputStream"` appears in the status bar.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 64-bit

### JDK

OpenJDK 18.0.2 Windows x64

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Always happens with JDK 9+.

NetBeans is running on OpenJDK 18.0.2 and the project uses an OpenJDK 18.0.2 Maven toolchain. (Maven istself is running on Java 8, but that shouldn’t matter.)

NetBeans found the sources when adding the JDK 18.0.2 platform and these files can be opened in the Debugging tab when using the debugger. The links do not work even when the matching JDK file is opened.

I believe the links worked earlier when using Java 8 or older (without the module system).

The links work with own code and Maven dependencies (if the source JAR is present).

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
Thanks for the detailed report. Could reproduce it on latest master too (basically NB 15).

**Comment by mbien** [comment]
btw as workaround you could paste the stack trace into the windows -> debugging -> analyze stack trace window. 

It works from there.

**Comment by neilcsmith-net** [comment]
So looks like this code and the regex it uses need updating to be module aware - https://github.com/apache/netbeans/blob/master/java/maven/src/org/netbeans/modules/maven/api/output/OutputUtils.java#L172

See also regex in StackAnalyzer https://github.com/apache/netbeans/blob/master/java/java.navigation/src/org/netbeans/modules/java/stackanalyzer/StackLineAnalyser.java#L57

Would be good to have this in one place, but if not at least kept in sync?  Anywhere else analyzing stack traces?

**Comment by mbien** [comment]
@neilcsmith-net there are multiple issues here I believe. If you set a breakpoint at https://github.com/apache/netbeans/blob/cf48b1fd9a97a8294c10b99fa00ad488f5837206/java/maven/src/org/netbeans/modules/maven/api/output/OutputUtils.java#L186 you see that the cp does not include the active JDK. So it doesn't find anything even if the parsing works.

This seems to be the case no matter if the project has a module info or not.

'packageName' a few lines above the breakpoint is incorrect too if a module is in the trace line.

**Comment by mbien** [comment]
opening JDK links already didn't work on NB 8 + JDK 8 which indicates that it was most likely never implemented for maven projects. Going to take a look how to get the active jdk of a project and see how to proceed from there.

I already couldn't figure out how to get the project JDK info when I wrote #4802, lets give it another try.

**Comment by neilcsmith-net** [comment]
@mbien yes, both are broken.  I would guess lack of `ClassPath.BOOT` in the response at https://github.com/apache/netbeans/blob/master/java/maven/src/org/netbeans/modules/maven/api/output/OutputUtils.java#L244 ?

The stack trace analyzer doesn't work correctly here either, obviously, as it's just using the global classpath info, so always going to give the running JDK.

**Comment by errael** [comment]
> figure out how to get the project JDK info

Reminds me of what's going on sorting out gradle projects and which jdk... with https://github.com/apache/netbeans/pull/5052

**Comment by mbien** [comment]
forgot to post here that #5091 is pending and should fix the issue encountered here. dev build is linked from the PR. Would be good if someone could confirm that this issue is fixed.

**Comment by maehem** [comment]
Michael, 

I downloaded and ran the dev build in the link for #5091 and it appears to work for me on OSX 12.5.1.  Both stack trace links links  into the JDK and my own code seem to be working when I click them in the output window.

Thank you for making this work!   I look forward to seeing this in NB17.


mark

**Comment by mbien** [comment]
@maehem awesome, thanks a lot for verifying!
