### ISSUE TITLE
Auto-correct messes up JavaDoc

### ISSUE THREAD

**Issue by blakemcbride** [apache/netbeans#4542]
### Apache NetBeans version

Apache NetBeans 14 & 15-rc4.

### What happened

NetBeans was pointing out an error in my JavaDoc.  It offered to correct it.  I accepted.  It then messed up the JavaDoc.  See the two attached files
![pic1](https://user-images.githubusercontent.com/6467584/187002664-1c1ac1f1-6e66-4424-b824-9a4475192b7c.png)
![pic2](https://user-images.githubusercontent.com/6467584/187002666-d27ce819-21cf-4b73-a5e1-f3d1769fb583.png)
.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Fedora Linux

### JDK

8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Yes, same issue - missed this report.  You can see the space between the first two sentences being removed, which is part of the issue.

@blakemcbride please verify with 19-rc4 linked at #6225 and request reopening this if you still see the issue.
