### ISSUE TITLE
need to update maven-war-plugin for maven web application using jdk17

### ISSUE THREAD

**Issue by menny68** [apache/netbeans#4552]
### Apache NetBeans version

Apache NetBeans 14

### What happened

building a project of type maven web application using jdk 17 source level 17 got the following error

.... Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.3:war failed: Unable to load the mojo 'war' in the plugin 'org.apache.maven.plugins:maven-war-plugin:2.3' ...

### How to reproduce

create new project
type = maven web application
application server glassfish 6
javaee version = jakarta ee8 web

set code source level 17
target version 17

build the project

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

ubuntu 20.04

### JDK

openjdk 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

work around bump maven-web-plugin to version 3.3.2 in pom.xml

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.2</version>
                <configuration>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                </configuration>
        </plugin>

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
NB17 will have maven hints which annotate outdated dependencies #5009

**Comment by OndroMih** [comment]
While #5969 is in draft mode, there's a fix in the currently used archetype https://github.com/juneau001/jakartaee10-archetype.

**Comment by OndroMih** [comment]
The fix in the currently used archetype is now released: https://mvnrepository.com/artifact/io.github.juneau001/webapp-jakartaee10/1.1.0

We can upgrade it while waiting for the new archetype

**Comment by asbachb** [comment]
@OndroMih  I'd suggest to do a PR to update the used artifact for now so that this get included into NB19. Can you prepare one?

If the new NetBeans internal solution (aka #5969) is ready, we'd just override that change.

**Comment by OndroMih** [comment]
> @OndroMih I'd suggest to do a PR to update the used artifact for now so that this get included into NB19. Can you prepare one?
> 
> If the new NetBeans internal solution (aka #5969) is ready, we'd just override that change.

NB19 targets an August release, right? I can prepare a PR for that but I can't get to it sooner than in a week or 2.

**Comment by OndroMih** [comment]
Here's the PR to update the current achetype: https://github.com/apache/netbeans/pull/6201
