### ISSUE TITLE
Incorrect warning "The global variable "this" is not declared"

### ISSUE THREAD

**Issue by ViktorKarev** [apache/netbeans#4568]
### Apache NetBeans version

Apache NetBeans 14

### What happened

I found a strange warning in a javascript file.
[test.js.zip](https://github.com/apache/netbeans/files/9452986/test.js.zip)
![view](https://user-images.githubusercontent.com/95738309/187447776-d4ee3884-b6be-4d9d-a3aa-8f12bfe045da.png)

### How to reproduce

Open file in Apache NetBeans.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 7

### JDK

java version "1.8.0_341" Java(TM) SE Runtime Environment (build 1.8.0_341-b10) Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Chris2011** [comment]
Reproducable.

**Comment by qmegas** [comment]
I guess it's duplicate of #4213

**Comment by matthiasblaesing** [comment]
Please have a look at the reference PR. That should fix the problem. A nightly build is available from the CI/CD summary page:

https://github.com/apache/netbeans/actions/runs/4646997912

or directly:

https://github.com/apache/netbeans/suites/12111203659/artifacts/638179968
