### ISSUE TITLE
Support RingoJS project

### ISSUE THREAD

**Issue by va0dl914** [apache/netbeans#4575]
### Description

Add RingoJS project support and no longer show errors on RingoJS sources (update the parser to support RingoJS syntax).

### Use case/motivation

Currently only NodeJS supported for JS. There is RingoJS too and especially it's part of the Java ecosystem.

### Related issues

Don't know!

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Chris2011** [comment]
The JS parser should be up to date with latest NetBeans 14 thanks to @matthiasblaesing . Please give us more information, also a sample project where you have problems with. Thx.

**Comment by va0dl914** [comment]
> The JS parser should be up to date with latest NetBeans 14 thanks to @matthiasblaesing . Please give us more information, also a sample project where you have problems with. Thx.

There currently no RingoJS project. For JS either it's an HTML app or NodeJS app. So you have to use one of these project types for your Ringo code but they are not really suited. Ringo is based RhinoJS which in turn based on the JVM. You can't write sth like this without errors: `var log10 = java.lang.StrictMath.log10(1517.19234);`

https://ringojs.org/documentation/java_integration/

**Comment by Chris2011** [comment]
It is not just the project template, also you asked for update the parser to support RinogJS syntax. I just had a quick look at https://ringojs.org/ and just saw simple JS syntax also for ES6 everything is up to date. So if ringo uses a different syntax by mixing JS and Java together etc. yes that needs to be implemented. but also java.lang.strictMath.log10 is still a valid and native JS syntax. Not Ringo specific. Just that maybe it shows you "java" is not defined. But that means that the global java object here is just not defined but it is not about the parser itself.

**Comment by Chris2011** [comment]
@va0dl914 as a workaround, you can add this on top of your JS file `/* global java */` and the warning will go away if that helps and also other object, that are not declared. You also have a hint/fix on the marked object.

**Comment by botic** [comment]
This issue should target "Rhino support" and not "RingoJS support": Rhino is the underlying JavaScript engine of multiple JavaScript runtimes. RingoJS is just a runtime on top of Rhino. So if someone wants to write JS for RingoJS, he/she is writing for Rhino's JavaScript implementation.

**Comment by Chris2011** [comment]
Afaik, NetBeans dropped the support for an older JavaScript engine, but I can't remember, whether it was Rhino or Nashorn. @jtulach or @matthiasblaesing can help here maybe.

**Comment by matthiasblaesing** [comment]
There is nothing stopping you writing nashorn/rhino compatible JS with NetBeans. There might be to little hints, that point out unsupported features in rhino, but JS is JS.

If people want to improve the situation:

1.) actually use the support and try to pin-point-problems, I'm willing to help, just not do the work. (Syntax/Feature filtering)
2.) make it possible to support `importPackage` and `importClass` (and maybe the (AFAIK!) deprecated default java import) with code completion based on either the system JDK or the surrounding java project (which provides a classpath).

Both of these things are doable - come to the mailinglist and ask if you want to try.

See:
- https://netbeans.apache.org/participate/submit-pr.html#contributing-code
- https://netbeans.apache.org/community/mailing-lists.html#dev
