### ISSUE TITLE
NetBeans main window title bar should match system theme on Mac OS

### ISSUE THREAD

**Issue by timboudreau** [apache/netbeans#4577]
### Description

If you use the dark theme on Mac OS, the bright white title bars of Java applications stick out like a sore them.

Fortunately, there is a simple system property fix that could be added to the default `netbeans.conf` with no effect on other platforms:

```
-J-Dapple.awt.application.appearance=system
```

will cause Java windows to pick up the theme set for the rest of the desktop and color window decorations to be consistent with them.

### Use case/motivation

NetBeans not to look like an alien on a dark-theme Mac OS desktop

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by ctipper** [comment]
One line fix, surely closing this issue would take less than 6 months?
