### ISSUE TITLE
Click the Class of JDK, cannot open the source of Java Platform

### ISSUE THREAD

**Issue by pizirun** [apache/netbeans#4581]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Have added the JAR/Fold of JDK src.zip file, while Clicking the Class, such as String, in Editor, there's Exception message in the Notifications view, and coud not open the added the source code of String.

### How to reproduce

1. added the JAR/Fold of JDK src.zip file
2. Create a project, Clicking the Class, such as String, of JDK  in Editor,
3. there's Exception message in the Notifications view, and coud not open the added the source code of String.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 20.04.5 LTS  System: Linux version 5.15.0-46-generic running on amd64; UTF-8; en_US (nb)

### JDK

Java: 17.0.4; OpenJDK 64-Bit Server VM 17.0.4+8-Ubuntu-120.04 Runtime: OpenJDK Runtime Environment 17.0.4+8-Ubuntu-120.04

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
> added the JAR/Fold of JDK src.zip file

That doesn't work for anything JDK 8+.  The sources should be picked up automatically.  Are you using the distribution JDK?  If so, have you installed the source package?
