### ISSUE TITLE
Evaluate Expressions Control Fails when double quotes are entered

### ISSUE THREAD

**Issue by cbm64chris** [apache/netbeans#4583]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Run a project in debug, hit a breakpoint. Run any valid java command in the expression control. Move the beginning of the line and type a double quote. Typing no longer functions in the control although the editor and other functions are unaffected. Closing the evaulate expression control does nothing to re-enable. Staring a new debugging session does not help. Only restarting NetBeans returns the functionality.

### How to reproduce

https://user-images.githubusercontent.com/20171342/188417391-038b8276-a0f3-46e6-b5c7-5900c7e76732.mov

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS 12.5

### JDK

Zulu 18.32.11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Not reproducible with simple project in NB14 or NB15 here on Ubuntu - same JDK.

**Comment by mbien** [comment]
I tried with NB22 and can also not reproduce it. When i put a `"` in front of the expression and press evaluate I notified that the expression isn't valid:

![image](https://github.com/apache/netbeans/assets/114367/b14f3c84-6eff-4ec9-abc4-4ec12a740522)

closing for now, feel free to reopen if this is still a problem and you have more info / an idea how to reproduce it.
