### ISSUE TITLE
Netbeans 14 Gradle 7.4 project load problems

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#4585]
### Apache NetBeans version

Apache NetBeans 14

### What happened

* We consistiently see these warnings on root project and sub-project loads:
```
Cannot load: <subproject path>
```
* Where the reason involves Gradle 7.4
* Projects are set in Netbeans to use the project `gradlew` version: 7.2 
  * Which is set in the Gradle tab of the options panel
* It is evidently a problem with larger implications as projects report errors and such even following successful builds
* Gradle when run from the command line is always successful.

See also
* #4554
* #4239
which seem to be related to these problems.

### How to reproduce

* Set-up a Gradle project using `gradlew` and Gradle v7.2
* Open project in netbeans
* Clear user and netbeans gradle caches (or begin with a clean install)
* Load and build projects

You should be seeing these warnings on sub-project loads:
```
Cannot load: <subproject path>
```
* Where the explaination involves Gradle 7.4
* Our projects all use the same Gradle version 7.2 which is set in the Gradle options panel

### Did this work correctly in an earlier version?

Apache NetBeans 12.4

### Operating System

Ubuntu 22.04.1 LTS

### JDK

Zulu18.30+11-CA

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
As @lkishalmi mentioned elsewhere, Gradle 7.2 does not support JDK 18 - https://docs.gradle.org/current/userguide/compatibility.html 

Also, please specify if the JDK you're using on the CLI and/or in the project properties differs from the one running the IDE.

**Comment by lkishalmi** [comment]
BTW. NetBeans 15 is going to put a warning badge on the project in such configurations, and would propose some ways to fix the issue.
