### ISSUE TITLE
Unit test on single file is converted to integration test

### ISSUE THREAD

**Issue by mlvtito** [apache/netbeans#4587]
### Apache NetBeans version

Apache NetBeans 14

### What happened

I noticed that my Netesta plugin does not work anymore with Netbeans 14.
Each time it tries to apply `ActionProvider.COMMAND_TEST_SINGLE`, the action is replaced by the new `COMMAND_INTEGRATION_TEST_SINGLE`.

### How to reproduce

I use Netesta plugin to automatically trigger unit tests on a single file

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Ubuntu

### JDK

1.8, 11, 17 & 18

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

I have done some debugging, so I can tell where the problem occurs. 

In the class `DefaultReplaceTokenProvider`, in the method `isIntegrationTestTarget`, the variable `targetFiles` can be also empty (and not only `null`)

In this case, the `allMatch` method of the stream return `true` whereas there are no files.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Looks like it should perhaps be using [extractFileObjectsfromLookup](https://github.com/apache/netbeans/blob/master/java/maven/src/org/netbeans/modules/maven/execute/DefaultReplaceTokenProvider.java#L86), although the extra check for empty would be good.  Feel free to file a PR.

Also, looks like your plugin should really be fixed to pass FileObject.

**Comment by hemantsoni42** [comment]
@neilcsmith-net  can you please assign me this issue.
I already solve fork this and solved the issue.

**Comment by hemantsoni42** [comment]
Fixed Unit test on single file is converted to integration test #4587 #5381

**Comment by hemantsoni42** [comment]
@neilcsmith-net thank you sir for your help
I once again go through the code and file a different PR after adding an extra check.

**Comment by neilcsmith-net** [comment]
This should be fixed in 18-rc3. Please test when that is available next week.
