### ISSUE TITLE
Missing Linux installer

### ISSUE THREAD

**Issue by mossroy** [apache/netbeans#4593]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Unlike with Netbeans <=14, Netbeans 15 does not provide a linux installer

### How to reproduce

https://netbeans.apache.org/download/nb15/ provides installers only for windows and mac
https://netbeans.apache.org/download/nb14/ (for Netbeans 14) provides an installer for linux, too

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Ubuntu 22.04

### JDK

OpenJDK 64-Bit Server VM (build 17.0.4+8-Ubuntu-122.04, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I did not find anything obviously related in the changelog from https://github.com/apache/netbeans/releases/tag/15

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by geertjanw** [comment]
Linux users: use the binary zip, Snap, or our community installers (there is a .deb without JDK too), https://www.codelerity.com/netbeans/. This has been discussed on dev@ a little while back. Linux installer is a little broken and no-one has fixed it yet.
