### ISSUE TITLE
The context menu supports the open in explorer、open in terminal and copy path function

### ISSUE THREAD

**Issue by AndyLuke** [apache/netbeans#4601]
### Description

As a basic function that is used with a very high frequency, it is still not available today, which is regrettable. I know that there are already relevant plug-ins, but I think this should be a necessary function of an excellent ide. I hope to add this function in future versions.

### Use case/motivation

[![nb-20220908095802.png](https://i.postimg.cc/V68rvLGx/nb-20220908095802.png)](https://postimg.cc/WD5bfjP8)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Chris2011** [comment]
The actions, that you pointed to are coming from the plugin, where I'm the current maintainer of: https://github.com/Chris2011/QuickOpener-NetBeans so yes I'm definitely with you. The plugin does a bit more if you check the readme of the project and I think not everything is needed and not prepared enough to add it into the core (refactoring, cleanup, etc.) So yes it could be possible to maybe copy code into the core or reuse some code parts and create them from scratch which is also possible. Atm I have not enough time for doing this, but I like the idea and think of it. Thx for interesting in this.

**Comment by matthiasblaesing** [comment]
"Open in Terminal" and "Open in system" are now in core as of NB20.
