### ISSUE TITLE
Impossible to create a Maven Web application for Jakarta EE 9.1

### ISSUE THREAD

**Issue by richard-grin** [apache/netbeans#4605]
### Apache NetBeans version

Apache NetBeans 15 release candidate

### What happened

Windows 11
NetBeans 15
Impossible to create a Java with Maven - Web Application, Server GlassFish Server 6.2.5, Jakarta EE 9.1
Menu File > New Project > Java with Maven > Web Application.

Server: GlassFish Server 6.2.5
Java EE Version: Jakarta EE 9.1 Web.

Click on Finish.

In the Notifications Zone, an "Unexpected Exception" appears. The error message:

java.lang.IllegalStateException: **No archetype defined for profile 9.1-web in class org.netbeans.modules.maven.j2ee.ui.wizard.archetype.J2eeArchetypeFactory$WebArchetypes**; check whether all possible <Profile, Archetype> pairs have been added
    at org.netbeans.modules.maven.j2ee.ui.wizard.archetype.BaseJ2eeArchetypeProvider.getArchetypeFor(BaseJ2eeArchetypeProvider.java:135)
    at org.netbeans.modules.maven.j2ee.ui.wizard.archetype.J2eeArchetypeFactory.findArchetypeFor(J2eeArchetypeFactory.java:79)
    at org.netbeans.modules.maven.j2ee.ui.wizard.EEWizardIterator.instantiate(EEWizardIterator.java:102)
    at ...
    ... 

### How to reproduce

Launch NetBeans 15.
Menu File > New Project > Java with Maven > Web Application.
Server: GlassFish Server 6.2.5
Java EE Version: Jakarta EE 9.1 Web.
Click on Finish.

In the Notifications Zone, an "Unexpected Exception" appears. The error message:

java.lang.IllegalStateException: No archetype defined for profile **9.1-web** in class org.netbeans.modules.maven.j2ee.ui.wizard.archetype.J2eeArchetypeFactory$WebArchetypes; check whether all possible <Profile, Archetype> pairs have been added
    at org.netbeans.modules.maven.j2ee.ui.wizard.archetype.BaseJ2eeArchetypeProvider.getArchetypeFor(BaseJ2eeArchetypeProvider.java:135)
    at org.netbeans.modules.maven.j2ee.ui.wizard.archetype.J2eeArchetypeFactory.findArchetypeFor(J2eeArchetypeFactory.java:79)
    at org.netbeans.modules.maven.j2ee.ui.wizard.EEWizardIterator.instantiate(EEWizardIterator.java:102)
    at ...
    ... 

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Windows 11

### JDK

Java: 17; OpenJDK 64-Bit Server VM 17+35-2724 

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time.
The creation of a Maven Web Application for Jakarta EE 8 worked in NetBeans 13. I didn't try NetBeans 14.

Afterwards, it is not possible to create a new project, of any type (even a simple Java project with Maven). I must restart NetBeans to be able to create a simple Java project with Maven.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ricardojonathanromero** [comment]
the same problem here

**Comment by geertjanw** [comment]
Probably 9.1 isn't supported yet, can you verify @juneau001 ?

**Comment by juneau001** [comment]
I have confirmed that it is not working properly.  I looked at the code and it seems like the archetype for 9.1 is not configured properly.  This will require a patch/update to resolve.  CCing @pepness on this issue.

**Comment by HamiltonNCIrl** [comment]
Could you possibly provide instructions on how to apply this update, please? I'm lost here. Thanks.

**Comment by sysmat** [comment]
Same here

**Comment by Teddy-1024** [comment]
Same problem here.

**Comment by ronan-crcdc** [comment]
Same issue with fresh install of Netbeans 15
