### ISSUE TITLE
PHP code format - no new line after last method

### ISSUE THREAD

**Issue by zeleznypa** [apache/netbeans#4611]
### Description

To be able to setup the PSR-12 compatible auto-format, I have to add one empty line „after function“

<img width="1075" alt="Snímek obrazovky 2022-09-10 v 14 40 38" src="https://user-images.githubusercontent.com/1191472/189483963-cd865bac-06a9-460c-85c8-618705fbc8cf.png">

But the PSR don't want to have blank line before the class closing curly bracket.

### Use case/motivation

I want to have code auto-formatted in PSR-12 compatible way.

Current result:
```php
class Foo
{
    public function bar() {
        // some code
    }

    public function baz() {
        // some code
    }

}
```

Expected result:
```php
class Foo
{
    public function bar() {
        // some code
    }

    public function baz() {
        // some code
    }
}
```

### Are you willing to submit a pull request?

I want to, but I'm not a Java developer

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
It seems that setting blank lines "Before Class End" is only able to add more blank lines if its value is greater than blank lines "After Fields" or "After Function".
Similar case is also for blank lines "After Class Header" in combination with blank lines "Before Fields" and "Before Function".

So proposal seems to be that settings for class start and end should have higher priority than the other settings.
Right?

**Comment by zeleznypa** [comment]
@tmysik Thanks so much ❤️

**Comment by tmysik** [comment]
@zeleznypa Not me, I just clicked the Merge button ;)

@junichi11 is the right guy to thank to, he is implementing all the PHP support in NetBeans (not only) these days. Thanks a lot, Junichi!

**Comment by zeleznypa** [comment]
@junichi11 Thanks much to you also :)

**Comment by junichi11** [comment]
You're welcome :)
