### ISSUE TITLE
PHP code suggestion from generated class properties

### ISSUE THREAD

**Issue by zeleznypa** [apache/netbeans#4612]
### Description

The PHP 8 introduced generated class properties defined in constructor like:

```php
class Foo {
    public function __construct(
        public Bar $bar,
        protected Baz $baz
    ){}

    protected function doSomething(): void
    {
        $this->bar->magic($this->baz->property);
    } 
}
```

instead of old one:

```php
class Foo {
    public Bar $bar;

    protected Baz $baz
    public function __construct(Bar $bar, Baz $baz)
    {
        $this->bar = $bar;
        $this->baz = $baz;
    }

    protected function doSomething(): void
    {
        $this->bar->magic($this->baz->property);
    } 
}
```

### Use case/motivation

When the code is written old way,  the code suggestion in the `doSomething` method after I wrote `$this->bar` or `$this->baz` or when I press there the shortcut for the „Show code completion popup“ display the popup with available properties and methods.

Unfortunately when the code is written in new way format, the popup is empty. 

### Are you willing to submit a pull request?

I want to, but I'm not a Java developer

### Code of Conduct

Yes

**Comment by junichi11** [comment]
I can't reproduce it.
Could you write an exact example code to reproduce it?

```
Product Version: Apache NetBeans IDE 15
Java: 11.0.16; OpenJDK 64-Bit Server VM 11.0.16+8-post-Ubuntu-0ubuntu120.04
Runtime: OpenJDK Runtime Environment 11.0.16+8-post-Ubuntu-0ubuntu120.04
System: Linux version 5.15.0-50-generic running on amd64; UTF-8;
```

**Comment by zeleznypa** [comment]
@junichi11 Strange. Now when I tried to isolate the example, situation not happen on the same environment.
I'm closing the request.
