### ISSUE TITLE
PHP `$this`, `static` and `self` return type

### ISSUE THREAD

**Issue by zeleznypa** [apache/netbeans#4613]
### Description

When I use `@return static` in PhpDoc or `public function foo(): static`, the NetBeans works well also with code suggestion.

But unfortunately some of third-party code like one of the most frequent framework Laravel use `@return $this` which mean the same like `static`, but NetBeans don't understand it.

There is also the return type `self` which mean nearly the same, but the NetBeans also  don't understand it.

### Use case/motivation

I want to have working code suggestion also when I use the third party code :)

### Are you willing to submit a pull request?

I want to, but I'm not a Java developer

### Code of Conduct

Yes

**Comment by junichi11** [comment]
Could you write an example code, steps to reproduce, and actual&expected results?
e.g. 
```php
// example code
```
#### Steps to reproduce
1.
2.
3.

#### Actual result
something

#### Expected result
something

**Comment by zeleznypa** [comment]
It looks like that it is already fixed.
