### ISSUE TITLE
PHP Formatting: No space between 'AND !$var'.

### ISSUE THREAD

**Issue by NotherGithubAccount** [apache/netbeans#4635]
### Apache NetBeans version

Apache NetBeans 15 release candidate

### What happened

`if ($a AND !$b)` formats to `if ($a AND!$b)`. It works correctly with &&, the behavior is the same with OR and ||.

When checking the "Unary Operator" box in Tools -> Options -> Editor -> Formatting for PHP and spaces, the result is
`($a AND ! $b)`
While that works as advertised, imho there should always be a space after AND/OR.
 

### How to reproduce

Create corresponding test code and select source->format.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian 11 5.18.0-0.deb11.4-amd64

### JDK

OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb11u1)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Afaik, always.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by junichi11** [comment]
Reproducible. Thanks!

**Comment by NotherGithubAccount** [comment]
Thanks for the quick fix!

**Comment by junichi11** [comment]
You are welcome :)
