### ISSUE TITLE
High cpu utilization on IDLE

### ISSUE THREAD

**Issue by kresoSusec** [apache/netbeans#4650]
### Apache NetBeans version

Apache NetBeans 15

### What happened

High cpu utilization on IDLE when netBeans is minimalized. 
in more details: when mouse cursor is in active project part and when you go to browser or some other application cpu usage on my pc go to 30% and don't come back to 0%. 
If i right click mouse on active script in netBeans cpu goes back to 0%., or if i click on menu 
cpu goes back to 0%; 
Demonstration video link:
https://app.box.com/s/7k9d4ip13n126nfzc6ia1d17v1xs43co

I have found this article with same problem: ,and here is the solution
netBeans developers-please fix this problem.
https://codeutility.org/netbeans-8-2-high-cpu-usage-without-any-reason-stack-overflow/

### How to reproduce
Here is selfsampler3471503817174232889.npss file for download
https://app.box.com/s/npoztpbfhqm7ocs4hhecuetdtagkw4fx

if this is a normal behavior of new version of NetBeans?, then  send me a message on 
kresosusec.suec1@gmail.com
I have use before netBeans 8.2 and i didn't have that problem with high cpu usage on idle when netBeans is minimalized 
Demonstration video link:
https://app.box.com/s/7k9d4ip13n126nfzc6ia1d17v1xs43co

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10

### JDK

Java: 1.8.0_161; Java HotSpot(TM) 64-Bit Server VM 25.161-b12

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

https://app.box.com/s/7k9d4ip13n126nfzc6ia1d17v1xs43co

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
Well, actually instead of ScreenShots you could actually send real data on what NetBeans is doing, by enabling Self profiling. There is a Profile the IDE button right to the memory gauge. You can start the profiling there, later on you can stop that and export the snapshot. Compress that and attach it to this issue.

**Comment by kresoSusec** [comment]
Is there any video tutorial or any kind of tutorial on how to do that? I do not know how to export and compress snapshot. I like the IDE but its annoying to hear fan noise in background when you don't do anything.
In oracle versions of program there is no that problem. 
I am planning to switch to Eclipse if that problem contain to exist in next update. 
lkishalmi can you tell me what to do to have normal CPU usage? I have try netBeans on 2 computers and on both of them there is a same problem with high CPU usage. Try it by yourself. Open netBeans and leave cursor in area where you write code, minimize it and cpu will go to 30%. It go back to 0% when you right click on coding area.

**Comment by lkishalmi** [comment]
Well, for me it is 0.02% to 0.2% when the cursor is blinking in the Editor.

I have 4 computers around, all of them has similar utilization. I'm using Ubuntu though.

Well, exporting the performance snapshot is not a rocket science. That's literally the first icon on the selfsampler, with the tooltip: `Export IDE snapshot...`. It seems compression is not necessary. Just attach that file here.

**Comment by kresoSusec** [comment]
I have made video for you:  
https://app.box.com/s/a2z7arpc4uejhst2sqw1n61zi4u3grqd  
Please watch it, and replay . Thanks 
Krešimir Sušec

**Comment by lkishalmi** [comment]
Well, could have mentioned that you are working with PHP. Normally we assume that you use NetBeans for Java development.

So my best guess, the PHP parser got into some loop, constantly parsing your code in the background. In order to fix that the PHP people may need the aforementioned performance snapshot, and probably the source code you are working on.

Also changing your code could make the PHP parser eventually happy and stop consuming your CPU.

**Comment by kresoSusec** [comment]
I have made this video with opened default 
HTML5 project with 0% of my code, so you can see that is not related to my code or PHP. Its problem with netBeans 15 on windows 10 
https://app.box.com/s/7k9d4ip13n126nfzc6ia1d17v1xs43co

**Comment by lkishalmi** [comment]
Well, I do not need another proof of that you have a problem with the CPU usage of NetBeans. I believe you.

What can't elude my mind is that you already took two videos an not one performance snapshot, what was requested. Do you think anyone could tell where is the CPU spending time upon your video? More specifically than it is NetBeans?

**Comment by lkishalmi** [comment]
Just to present. The Self profiler would give detailed information like this:
![image](https://user-images.githubusercontent.com/1381701/191357700-092aa6a2-0e61-40ea-8a90-7cd1ff74ebe6.png)

**Comment by kresoSusec** [comment]
can you please make tutorial with steps in details what i need to do. 
For example:
1. click on this,.
2. now klick here, etc. 
I really like the ide, and i want to fix this problem.
I don't have any idea how to get information's you need to solve the problem. 
I will do what i need to do , but i need your help to do that.,So please write some instructions.
Thanks

**Comment by lkishalmi** [comment]
This is how you take a performance snapshot.

https://user-images.githubusercontent.com/1381701/191654781-25259278-23ae-4938-9305-bc8c4fad6522.mp4

**Comment by kresoSusec** [comment]
In my case when i stop self Profile i receive a message about 

![slika1](https://user-images.githubusercontent.com/113850461/191872468-9f4cf5b7-148d-4988-b465-63560f87e087.png)

![slika2](https://user-images.githubusercontent.com/113850461/191872472-40406a46-2d35-4704-9f01-b8428fe26d1f.png)

Here is selfsampler3471503817174232889.npss file, maybe you can decode it 

https://app.box.com/s/npoztpbfhqm7ocs4hhecuetdtagkw4fx

**Comment by lkishalmi** [comment]
You need to have the Java functionality enabled to be able to load the file:
![image](https://user-images.githubusercontent.com/1381701/191896713-0d5101bc-b2a0-4009-b903-5e517d2e820e.png)

From here it seems the IDE spend the most time doing something with native support of accessibility. Maybe screen reader, virtual keyboard or something like that.

I've seen this, the sympthom look similar, though really old and totally unrelated besides talking about `com.sun.java.accessibility.AccessBridge`

**Comment by lkishalmi** [comment]
@kresoSusec is there any progress on this one?

**Comment by kresoSusec** [comment]
> @kresoSusec is there any progress on this one?
Nothing new. Thanks for cooperation on this  problem Ikishalmi. I hope next version of net Beans will not have that problem.

**Comment by lkishalmi** [comment]
Well it is surely not a NetBeans issue, So we can't fix it. It is related to the assistive technologies in use, and maybe the price you are using them has to be paid by CPU cycles.

**Comment by kresoSusec** [comment]
do you have any suggestion what i need to disable, to have normal CPU usage?

**Comment by kresoSusec** [comment]
> do you have any suggestion what i need to disable, to have normal CPU usage?
> 
> On this version of netBeans by Oracle i don't have any problems with high CPU usage.
Only on Apache versions
 ![netBeans](https://user-images.githubusercontent.com/113850461/193589874-46e0d0c0-0303-4852-acfd-7059e15c5ceb.png) i am using netBeans 8.2 and i dont have that problem.
> 
> ![moje postavke](https://user-images.githubusercontent.com/113850461/193601825-8bb51883-12c0-4ece-a357-2747533e25b8.png)
> 
> this is how i have my setting in windows

**Comment by lkishalmi** [comment]
OMG. That Java release is more than 4.5 years old! Could you install a more recent one Like JDK 17, or if you really need JDK 8, than use a more recent one.

https://foojay.io/almanac/java-17/

**Comment by kresoSusec** [comment]
> OMG. That Java release is more than 4.5 years old! Could you install a more recent one Like JDK 17, or if you really need JDK 8, than use a more recent one.
> 
> https://foojay.io/almanac/java-17/

Thanks
