### ISSUE TITLE
/bin/sh:行1: /home/deepin/Toochain/arm-2009q1/bin/arm-none-linux-gnueabi-g++: 没有那个文件或目录

### ISSUE THREAD

**Issue by 652436962** [apache/netbeans#4660]
### Apache NetBeans version

Apache NetBeans 15

### What happened

netbean 15 add cross compile ,build  

/bin/sh:行1: /home/deepin/Toochain/arm-2009q1/bin/arm-none-linux-gnueabi-g++: no such file or directory

netbean 14  is ok

### How to reproduce

netbean 14  is ok

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

deepin linux

### JDK

flatpak include

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by 652436962** [comment]
this is ok in netbean14  and  i'd  add in 14 is ok 
netbean 15  add cross compile  is no  such file or dirctory

**Comment by mbien** [comment]
i don't really know what this means but we don't provide the flatpak packages
