### ISSUE TITLE
NetBeans output build panel distorts UTF-8 Java file names

### ISSUE THREAD

**Issue by epliskin** [apache/netbeans#4669]
### Apache NetBeans version

Apache NetBeans 15

### What happened

My Maven Java project includes some classes with non-ascii names. Suppose I place some error in one of this files and start build in IDE. Then NetBeans console displays error messages with distorted file names. Messages look like what you can see opening UTF-8 text file with wrong "windows-1251" encoding.

The Maven log in separate file (maven install > log) contains correct  filenames in UTF-8 encoding but in the NetBeans output build panel those error messages look corrupt.

The problem is specific to JDK 17 (with netbeans_jdkhome="C:\Program Files\Java\jdk-17" in netbeans.conf file) as opposed to JDK 15. When I set "netbeans_jdkhome" to JDK 15 then error messages in the NetBeans output build panel display correct UTF-8 class names.

The "netbeans_default_options" in my "netbeans.conf" file includes "-J-Dfile.encoding=UTF-8" clause. 
The Windows environment variable JAVA_TOOL_OPTIONS is set to "-Dfile.encoding=UTF-8".

### How to reproduce

I believe the problem is easily reproducible with non-ascii Java class name containig some invalid identifier for example.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

OpenJDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Can you try setting `sun.stdout.encoding=UTF-8` (or from JDK 19  `stdout.encoding=UTF-8`) instead. See also #4396 and https://bugs.openjdk.org/browse/JDK-8284778

**Comment by epliskin** [comment]
Confirm the problem resolved by adding "-J-Dsun.stdout.encoding=UTF-8" clause to the "netbeans_default_options" key in "netbeans.conf" file. Thank you!

**Comment by neilcsmith-net** [comment]
Thanks for the confirmation.  Glad to know it's working for you.
