### ISSUE TITLE
[PHP] No IDE hint for promoted properties with @mixin

### ISSUE THREAD

**Issue by terax6669** [apache/netbeans#4683]
### Apache NetBeans version

Apache NetBeans 15

### What happened

NetBeans fails to provide hints for promoted properties in a child property when introduced via `@mixin`.
![image](https://user-images.githubusercontent.com/19204073/192149508-795a5244-1f09-4067-8c53-e98e1bf755e2.png)

### How to reproduce

```php
<?php

/**
 * @property-read Data $data
 */
class IdeHelperDataContainer
{
}

/**
 * @mixin IdeHelperDataContainer
 */
class DataContainer
{
}

class Data
{
	public function __construct(
		public readonly array $foo,
	) {

	}
}

$container = new DataContainer();
$data = new Data([]);

$container->data; // works
$container->data->foo; // no ide hint!
$data->foo; // works
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Pro 22000.978

### JDK

OpenJDK 19.0.0 (from Chocolatey)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Only when using `@mixin`.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by terax6669** [comment]
Still happening on NetBeans 16.

**Comment by junichi11** [comment]
Reproducible. Thanks for your report.

BTW, Need not "Still happening on NetBeans **." because it does not happen anything if anyone does not work on it.
