### ISSUE TITLE
[PHP] Parser syntax error - accessing a const array value

### ISSUE THREAD

**Issue by terax6669** [apache/netbeans#4684]
### Apache NetBeans version

Apache NetBeans 15

### What happened

![image](https://user-images.githubusercontent.com/19204073/192149986-01daa5c7-37f9-48c0-a36d-536827081c49.png)

### How to reproduce

```php
<?php

class Foo
{
	public $bar = 'Bar';
}

class Bar {
	const FOOBAR = ['Bar' => 'tada!'];
}

$foo = new Foo;

var_dump($foo->bar::FOOBAR[$foo->bar]);
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Pro 22000.978

### JDK

OpenJDK 19.0.0 (from Chocolatey)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

AFAIK this syntax never worked in NetBeans.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by junichi11** [comment]
Reproducible. Thanks!
