### ISSUE TITLE
jdk 17 can´t run on NetBeans IDE 12

### ISSUE THREAD

**Issue by JSantamania** [apache/netbeans#4693]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

I´m using netbeans IDE 12.
Was using jdk 14 but some problem need --enable:preview a jar doesn´t run on other version of jdk
I´ved installed jdk 17 and it produce good jar than can run on other machines. But NetBeans' run command doesn´t run neither debug command.  

### How to reproduce

Install NetBeans
Install jdk 14
make a program with java jdk 14 (any one with Ant)
install jdk 17
assign jdk17 as plattform to the program you made
NetBeans produce good jar, that run correctly on console, but you can´t run inside NetBeans neither "run" command nor "debug" command. Netbeans remains on silent and give me a notification of "silent"
Windows 10
NetBeans IDE 12

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

window 10

### JDK

first jdk 14, needs --enable:preview. Now jdk17 

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Ever 

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
Well, NetBeans 12, will never support Java 17. Try to use NetBeans 15.

Also try to describe in more details what is your problem along with `--enable-preview`, note, that it is `--enable-preview` not `--enable:preview`!

I could not reproduce this behavior with `--enable-preview` and NetBeans 15, with JDK 17 using an Ant based project.

**Comment by JSantamania** [comment]
Thanks, I'll true NerBeans 15
Regards

Jesús
________________________________

**Comment by JSantamania** [comment]
Thanks,  jdk17 with NetBeans 15 work fine.

Regards,

De: Laszlo Kishalmi ***@***.***>
Enviado el: martes, 27 de septiembre de 2022 1:09
Para: apache/netbeans ***@***.***>
CC: JSantamania ***@***.***>; Author ***@***.***>
Asunto: Re: [apache/netbeans] jdk 17 can´t run on NetBeans IDE 12 (Issue #4693)


Well, NetBeans 12, will never support Java 17. Try to use NetBeans 15.

Also try to describe in more details what is your problem along with --enable-preview, note, that it is --enable-preview not --enable:preview!

I could not reproduce this behavior with --enable-preview and NetBeans 15, with JDK 17 using an Ant based project.
