### ISSUE TITLE
Project marked as unloadable but will compile using command line mvn

### ISSUE THREAD

**Issue by snelliga** [apache/netbeans#4698]
### Apache NetBeans version

Apache NetBeans 15

### What happened

I upgraded to netbeans 15, changed from SVN to GIT, and imported modified sources from a third party.
We are using the freeware version of Mule and all the Mule projects are flagged as [unloadable].
Opening the pom, the pom does not flag any lines in error.
if attempt to build from command line, it works.
Netbeans is configured to use maven 3.6.3
Default JDK is JDK11
global Execution Options are:
-gs C:\users\XXXXXXXX\.m2\settings.xml -s C:\users\XXXXXXXX\.m2\settings.xml

Attached is one of the pom files pom.xml renamed as pom.txt

[pom.txt](https://github.com/apache/netbeans/files/9665661/pom.txt)

### How to reproduce

Create a maven project and paste the attached pom file into the project.

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10 64 bit

### JDK

Netbeans running under java 1.8.0_231 -- Mule compile would be using amazon-corretto-11.0.6.10.1-1-windows-x64-jdk\jdk11.0.6_10

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
any exceptions in the log?

**Comment by neilcsmith-net** [comment]
You say that the default JDK is JDK 11 and that you're running NetBeans under JDK 1.8.  Default JDK where?  Note that NetBeans does not officially support running on JDK 8 any more, and some things may be missing, although it's unlikely the cause of this.

Curious that the shared file has a parent POM called `Pom.xml` - wonder if that's causing an issue?

**Comment by mbien** [comment]
we can't really investigate this without the parent pom. If you can reduce it to a minimal reproducer feel free to reopen or file another issue.
