### ISSUE TITLE
Gradle setting wrong NetBeans jdk version

### ISSUE THREAD

**Issue by errael** [apache/netbeans#4704]
### Apache NetBeans version

Apache NetBeans 15

### What happened

![11-18](https://user-images.githubusercontent.com/20450427/193150941-b82e9b94-f47e-4c15-91ee-cd302af7cea3.png)

This issue probably originates from some gradle behavior. Gradle 6.8.x limits sourceCompatibility and targetCompatibility to 18; using compilerArgs bigger numbers can be passed to the compiler.

Looking at the attached png, I'm guessing that NetBeans is told that the project is at 18. Shouldn't it allow the compilerArgs override the 18 as far as NetBeans is concerned?

I'm openning this in the hopes that NB-16 will use the correct jdk version.

### How to reproduce

Can provide project if that's needed.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux harmony 5.19.0-76051900-generic #202207312230166078056622.04~9d60db1

### JDK

openjdk version "11.0.2" 2019-01-15

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by errael** [comment]
@lkishalmi, perhaps you have some insight into this. I have no idea how gradle tooling informs the IDE of the source version.

**Comment by neilcsmith-net** [comment]
Have you tried a daily build?  NetBeans 15 only supports up to Java 18 anyway.

**Comment by lkishalmi** [comment]
Well, we ask Gradle what is the source/target java version on each source set. We do not really analyze the command line options. It is merely reported back to the IDE (which uses that to detect `--enable-preview`)

Gradle 7.5 officially supports Java up to version 18 as a runtime.

**Comment by errael** [comment]
(ahhhh, and I was just getting ready to test it on a dev build)

> Gradle 7.5 officially supports Java up to version 18 as a runtime.

That's not really the issue. And I have some projects that use gradle 6.8.3. I have code, "switch pattern matching with case when", in a grail built project that compiles from NetBeans. I'm using frgaal.

You confirm that with NB-16 the wrong jdk version will be given to the nbjavac/editor.

Would you entertain a patch that if it finds a "--source","<version>" in the compiler args it uses that version to inform NetBeans?

**Comment by lkishalmi** [comment]
Well, I'd leave the fun of creating a patch for you. I'm occupied elsewhere.

https://github.com/apache/netbeans/blob/62a9953d4d5e27dc4b530b72e08d934c7098c59d/java/gradle.java/src/org/netbeans/modules/gradle/java/api/GradleJavaSourceSet.java#L137
the corresponding compiler args are also available in this class.
