### ISSUE TITLE
Task categories at bugrtacking dashboard with cyrillic symbols does not load properly after restart

### ISSUE THREAD

**Issue by 6PATyCb** [apache/netbeans#4732]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Task categories at bugrtacking dashboard with cyrillic symbols does not load properly after IDE restart. 
Before restart IDE:
![image](https://user-images.githubusercontent.com/33724393/193782687-be80be65-47a1-4039-a292-8dccee9eae78.png)
After restart:
![image](https://user-images.githubusercontent.com/33724393/193783058-0828bc28-964b-48e5-b800-111cc29908f9.png)

### How to reproduce

Just create task category with name "тест" and restart IDE. It will lost it after restart. 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

Oracle jdk 14, x64

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I was try to look at sources and I think issue at step when category name converted to name store file in ide/bugtracking/src/org/netbeans/modules/bugtracking/tasks/cache/DashboardStorage.java.
On read file step executed decodeURL func https://github.com/apache/netbeans/blob/694f319b068d33bb812274d1232fc79e264ca5ff/ide/team.commons/src/org/netbeans/modules/bugtracking/commons/TextUtils.java#L213 which work correctly only with two-digit character codes:
https://github.com/apache/netbeans/blob/694f319b068d33bb812274d1232fc79e264ca5ff/ide/team.commons/src/org/netbeans/modules/bugtracking/commons/TextUtils.java#L222
but cyrillic symbols after encodeUrl func contains three digits. for example 'testй' -> 'test%439.c'

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
hmm. wondering why `java.net.URLDecoder` wasn't used there.

would be good to:
 - add a test to https://github.com/apache/netbeans/blob/master/ide/team.commons/test/unit/src/org/netbeans/modules/bugtracking/commons/TextUtilsTest.java which shows that this breaks
 - replace the impl in `TextUtils` with `URLEncoder`/`Decoder` (or find the reason why it wasn't used in the first place ;))

adding good-first-issue label

**Comment by 6PATyCb** [comment]
>     * add a test to https://github.com/apache/netbeans/blob/master/ide/team.commons/test/unit/src/org/netbeans/modules/bugtracking/commons/TextUtilsTest.java which shows that this breaks

I would try to do this tests, but i don't have experience to compile full IDE. Is it possible make it only for bugtracking module? 
This [link](https://netbeans.apache.org/wiki/DevFaqModulePatching.asciidoc) is not contain information about compilation.

Is a good practice - making tests who will fails testing step because errors is not fixed yet?

**Comment by mbien** [comment]
let me think about this. The URL encoded String is used as file name. This isn't optimal because this could hit the file name length limit on windows (which is still 255 chars I believe).

`тест` would be encoded to `%D1%82%D0%B5%D1%81%D1%82` using `java.net.URLEncoder`. Which means that `тесттесттесттесттесттесттесттесттесттесттест` would break the limit. Maybe this is long enough? :)

> I would try to do this tests, but i don't have experience to compile full IDE. Is it possible make it only for bugtracking module?

You have to build netbeans once via command line (https://github.com/apache/netbeans#building-netbeans).
After that, simply open the bugtracking module in NetBeans and you can build and test it like a normal project.


> Is a good practice - making tests who will fails testing step because errors is not fixed yet?

if we end up using `java.net.URLEncoder/Decoder` we won't need more tests because this would test JDK code. But to answer the question: I believe it would be best to add a test which demonstrates the issue to the same commit which fixes the issue.

**Comment by 6PATyCb** [comment]
> Base64 encoding would be better suited for this most likely, its more compact and doesn't have the dot problem.
> edit: probably have to use Base32 due to case insensitivity of some file systems.

You are right about probably length limitation. As alternative Base64/32 might be better create one mapping file like `categories.map` with json or some another format that associates a category name with a category body file and all body files will be named by increment algorithm (category1.c, category2.c ... categoryN.c)? Or another opinion - since all the categories required for the dashboard together we could read all the files ending in `.c` from the directory and recover the category names from their bodies. This will allow you not to think about encodings and file lengths.

Also, we must not forget after fix with replace to another serialize format we receive new issue with backward capability of old saved files. 

> You have to build netbeans once via command line (https://github.com/apache/netbeans#building-netbeans).
After that, simply open the bugtracking module in NetBeans and you can build and test it like a normal project.

Thanks for the advice, I'll try to do it

**Comment by mbien** [comment]
agreed. The methods are also unfortunately public API of the module, so we can't really remove them or change the encoding.

Thats why I decided to use java.net.URLEncoder for now. This fixes this particular issue here, without changing API or file compatibility. It has the disadvantage of being a bad encoder for file names, but this would be another issue - at least it should works.

**Comment by 6PATyCb** [comment]
I was create pool request [#4751](https://github.com/apache/netbeans/pull/4751) with test.
