### ISSUE TITLE
Test results window does not display results

### ISSUE THREAD

**Issue by maffe** [apache/netbeans#4734]
### Apache NetBeans version

Apache NetBeans 15

### What happened

The test results window does not show up automatically when selecting “Test” in a project’s context menu. After opening it via Window → IDE Tools → Test Results, it stays empty even when running the tests again.

### How to reproduce

Create a new Maven project and select “Test” in its context menu.

### Did this work correctly in an earlier version?

Yes but I don’t know the version.

### Operating System

Windows 10 64 Bit

### JDK

19

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Saljack** [comment]
I have the same issue. I think it is connected somehow to surefire maven plugin. 
This is my output:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.something.SomeTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.61 s - in org.something.SomeTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by michaelajr** [comment]
Tested on Intel Mac and all is fine - Test Results window pops open and is populated with test results.

Tested on a Mac with Apple silicone... and I get a blank Test Results window (have to manually open it).

Maybe another issue with native build like with the profiler.

**Comment by maffe** [comment]
#7113 did not fix this issue for me, but I noticed the problem goes away when I remove `--color always` from the Maven Global Execution Options in NetBeans.
