### ISSUE TITLE
one pluggin cannot install

### ISSUE THREAD

**Issue by LOND-HO13** [apache/netbeans#4747]
### Apache NetBeans version

Apache NetBeans 15

### What happened

The plugin cannot be installed when JDK 14 is used to boot NetBeans 11.3 because unpack200 was deprecated in JDK14.

¿How can I solve this error?, since I have jdk 19 and I get this error

### How to reproduce

java.io.IOException: error=2, No such file or directory at java.base/java.lang.ProcessImpl.forkAndExec(Native Method) at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319) at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250) at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) Caused: java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/bin/unpack200" (in directory "/Users/xxxxx/Library/Application Support/NetBeans/11.3/modules"): error=2, No such file or directory at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) [catch] at org.netbeans.updater.ModuleUpdater.unpack200(ModuleUpdater.java:567) at org.netbeans.updater.ModuleUpdater.unpack(ModuleUpdater.java:465) at org.netbeans.updater.ModuleUpdater.run(ModuleUpdater.java:117)

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

windows

### JDK

19

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Anything else

frecuently

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
start with JDK 11 or select a unpack200 implementation when the warning dialog shows up.

you can set the `netbeans_jdkhome` property in your etc/netbeans.conf to your JDK 11 folder, this is used to start NetBeans with.
