### ISSUE TITLE
Close whole documents list at once

### ISSUE THREAD

**Issue by mbien** [apache/netbeans#4760]
_Originally posted by @6PATyCb in https://github.com/apache/netbeans/issues/4710#issuecomment-1272557189_

When too much files is opened I like to use `documents list` format for manage it:
![image](https://user-images.githubusercontent.com/33724393/194762879-ea2250c6-222e-429d-8f59-c1b70390c588.png)

but in that format would be good to have close button to group of documents:
![image](https://user-images.githubusercontent.com/33724393/194763097-3fa38dee-932c-4e11-a956-de12cda764b7.png)

**Comment by Richard7111** [comment]
Hello, can you assign me this issue and help me navigate a little in the project?

**Comment by Richard7111** [comment]
Hello @mbien, can you assign me this issue and help me navigate a little in the project?

**Comment by mbien** [comment]
hi @Richard7111

sure. Take a look at `platform/core.multitabs`.

you could set a breakpoint here:
https://github.com/apache/netbeans/blob/1a9b29d627a0f343837dc053b56e8de32d6ff689/platform/core.multitabs/src/org/netbeans/core/multitabs/impl/ButtonPopupSwitcher.java#L445-L456

Don't try to close editor tabs with unsaved changes since this can cause issues.

how to build NetBeans and work with modules was recently answered here.
https://github.com/apache/netbeans/discussions/4664#discussioncomment-3756079

**Comment by Richard7111** [comment]
Hello, I am not able to find how to create documents list where should I look for this feature. Google was no help. Could you please help me?

**Comment by Richard7111** [comment]
Hello @6PATyCb, I am not able to find how to create documents list, where should I look for this feature. Google was no help. Could you please help me?

**Comment by troizet** [comment]
Choose menu Tools -> Options -> Appearance -> check "Sort opened documents list by project".
Then open several projects.

**Comment by 6PATyCb** [comment]
> Hello @6PATyCb, I am not able to find how to create documents list in the IDE, where should I look for this feature. Google was no help. Could you please help me?
> 
> EDIT: Managed to find it.

Hi! Take a look at @troizet comment
