### ISSUE TITLE
CSS: Show documentation (ctrl+shift+space) displays incorrect documentation

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#4778]
### Apache NetBeans version

Apache NetBeans 15

### What happened

It looks like the documentation search for the display is not done by the full word, but by a few characters before the caret. Also the search is done for partial matches.

### How to reproduce

https://user-images.githubusercontent.com/9607501/195260539-1a57f8af-9b6a-42bd-8d17-83595b851a16.mp4

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian 10, Ubuntu 20.04.4 LTS

### JDK

OpenJDK 64-Bit Server VM 11.0.16+8-post-Ubuntu-0ubuntu120.04, OpenJDK Runtime Environment 11.0.16+8-post-Debian-1deb10u1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

The issue is similar to #4494.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
@troizet please have a look at the referenced PR, which should fix the issue. A testbinary is available there if needed.

**Comment by troizet** [comment]
@matthiasblaesing Tried a test build. Everything works great. Thank you!

**Comment by matthiasblaesing** [comment]
@troizet thanks for checking!
