### ISSUE TITLE
PHP hint for Empty Heading when content of tag supplied by PHP variable

### ISSUE THREAD

**Issue by brandpeter** [apache/netbeans#4804]
### Apache NetBeans version

Apache NetBeans 15

### What happened

At its simplest, _`<?php $title = 'something';?><h1><?php echo $title?></h1>`_ in a PHP file reports the error 'Empty Heading'.
Looks valid to me.

### How to reproduce

Paste above code into a PHP file, and open it in NetBeans editor.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 64bit

### JDK

SE 16

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by junichi11** [comment]
I can't reproduce it.

![nb-gh-4804](https://user-images.githubusercontent.com/738383/198271045-fbdc48cc-2fa4-48f5-ac38-eda40c268073.png)
```
Product Version: Apache NetBeans IDE 15
Java: 11.0.16; OpenJDK 64-Bit Server VM 11.0.16+8-post-Ubuntu-0ubuntu120.04
Runtime: OpenJDK Runtime Environment 11.0.16+8-post-Ubuntu-0ubuntu120.04
System: Linux version 5.15.0-52-generic running on amd64; UTF-8;
```

**Comment by KacerCZ** [comment]
Tried it in NetBeans 17 and I was not able to reproduce the error.
