### ISSUE TITLE
High CPU usage for NetBeans Linux with C/C++ project.

### ISSUE THREAD

**Issue by darwinte** [apache/netbeans#4807]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Project files has ~300k total files. C/C++ indexing shows ~69k files parsing. High CPU usage takes ~40 minutes.

Profiling shows:

FileSystemWatchService	16,086 ms (100%)	15,830 ms (100%)
sun.nio.fs.LinuxWatchService$Poller.run ()	16,086 ms (100%)	15,830 ms (100%)

### How to reproduce

Easily reproducible.  Request for more info like logs, etc.

### Did this work correctly in an earlier version?

Apache NetBeans 12.5

### Operating System

Ubuntu 22.04.1 LTS

### JDK

openjdk 11.0.16 2022-07-19

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by darwinte** [comment]
![Screenshot_20221017_115327](https://user-images.githubusercontent.com/1226154/196260281-09e99054-5c6e-46fa-8ebf-279973aada79.png)

**Comment by lkishalmi** [comment]
Are you using the C++ Lite support or the one from NetBeans 8.2?

**Comment by darwinte** [comment]
> Are you using the C++ Lite support or the one from NetBeans 8.2?

I am using NetBeans 8.2. C++ Lite can't debug I think.  Now I have switched to CLion and is pretty set and content.
