### ISSUE TITLE
False positive on "The collection is only added to, never read" when collection is declared 'final'

### ISSUE THREAD

**Issue by hbitteur** [apache/netbeans#4824]
### Apache NetBeans version

Apache NetBeans 15

### What happened

A collection declared as `final` can be added to and read from, and the program works correctly of course.
However Netbeans flags this collection with the warning "_**The collection is only added to, never read**_"!
See the simple example below.

### How to reproduce

```
public void test ()
{
    final List<String> myList = new ArrayList<>(); // Line 1, warning here
    myList.add("FooBar"); // Line 2, where addition is done

    for (String str : myList) { // Line 3, where reading is done
        System.out.println(str);
    }
}
```
Netbeans flags line 1 with the warning message: "_The collection is only added to, never read_"
Warning is wrong, since the collection is read on line 3.
This false warning disappears when `final`  is removed on line 1.

It disappears also if line 2 (addition) is removed.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

Windows 10, 64 bits

### JDK

17.0.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Should be fixed in 16. Release candidate available at #4815 if you want to test.
