### ISSUE TITLE
Wizard "New Entity Classes from Database" does not work with Payara (version 16 RC1) - Jakarta EE 9.1

### ISSUE THREAD

**Issue by richard-grin** [apache/netbeans#4827]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

I arrive directly on the second step of the wizard and no Datasource is displayed, so I have to give up. Instead of "Data source", "Please wait.." is displayed, and I waited a very long time. Yet I can connect to the database from the entry "Databases" of the Services tab of NetBeans. 

The server is Payara Server Community 6.2022.1 Alpha 4. This problem does not happen with GlassFish 6.2.5.

### How to reproduce

Create a Maven Web project for Jakarta EE 9.1. 
Launch the wizard "New Entity Classes from Database".
 I arrive directly on the second step of the wizard and no Datasource is displayed so I have to give up. Instead of "Data source", "Please wait.." is displayed, and I waited a very long time. Yet I can connect to the MySQL 8.0.25 database from the entry "Databases" of the Services tab of NetBeans. 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Family 64-bit, version 21H2

### JDK

11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

It happens every time.
Related to #3813.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by richard-grin** [comment]
I have just tried the final version of Payara 6.2022.1 and now it works a little better. No longer the message "Please wait...". In fact, the problem is now exactly the same as it is described in the issue https://github.com/apache/netbeans/issues/3813.

**Comment by richard-grin** [comment]
I don't know if I must open a new issue.
I have just tested this functionality with NetBeans 17 RC1 and Payara 2023.1.
It works better. The only remaining problem is that the generated entities use the "javax" namespace instead of the "jakarta" one.

**Comment by neilcsmith-net** [comment]
cc @jGauravGupta any thoughts?  Sticking NB17 label on this to track in case there's a fix to bring in.

**Comment by matthiasblaesing** [comment]
There is a fix proposed in #6129. Please check if that fixes your case. A dev build of that is available from the checks page of the PR:

https://github.com/apache/netbeans/actions/runs/5403767470

or directly via

https://github.com/apache/netbeans/suites/13930633639/artifacts/775835473
