### ISSUE TITLE
Namespace "javax" used in generated code for a Jakarta 9.1 application (instead of jakarta)

### ISSUE THREAD

**Issue by richard-grin** [apache/netbeans#4828]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

If a wizard is used to generate classes, "javax" is used instead of "jakarta".
For example, with the wizard "New Entity Classes from Database" or "New Session bean", or "New Entity".

### How to reproduce

Create a new Maven Web project for Jakarta 9.1 and launch a wizard.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Family 64-bit, version 21H2

### JDK

11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by richard-grin** [comment]
Perhaps, in this period of transition between the 2 namespaces, it would be easier to propose 2 types of code generation and the user will choose one?

**Comment by matthiasblaesing** [comment]
There is a fix proposed in #6129. Please check if that fixes your case. A dev build of that is available from the checks page of the PR:

https://github.com/apache/netbeans/actions/runs/5403767470

or directly via

https://github.com/apache/netbeans/suites/13930633639/artifacts/775835473
