### ISSUE TITLE
Debugger views only show a single "DN" column and no rows

### ISSUE THREAD

**Issue by nmatt** [apache/netbeans#4831]
### Apache NetBeans version

Apache NetBeans 15

### What happened

When debugging Java code (Maven project), the debugger views like Variables, Watches, Breakpoints and Call Stack show no content, and only a single column with heading "DN", see this screenshot:

![image](https://user-images.githubusercontent.com/7593340/197074600-135986fc-cfe8-4564-b46d-34a59e2b552f.png)

This also affects the popup display for variables in the source code when expanding the popup view via "+": 

Obviously, this makes debugging almost impossible.

### How to reproduce

Start a debugging session (e.g. Debug File or Debug Test File) and stop at some break point. Look at the various debug views.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

Windows 10

### JDK

JDK 8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

The same projects work without issues in NetBeans 12.2. Prior configuration was imported into NetBeans 15 from 12.2.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
never saw that happening before. More info would be needed to reproduce this. I am debugging a maven project right now actually.

btw NB is supported on JDK 11, 17 and "current at release".

**Comment by nmatt** [comment]
@mbien: I retried with JDK 11.0.16.1 (current version), same behavior.

**Comment by nmatt** [comment]
Ok, the culprit the BinEd plugin in version 0.2.3: https://github.com/exbin/bined-netbeans-plugin/issues/15
The newer version 0.2.4 from 12/10/2022 seems to solve the issue, however the NetBeans plugin portal still provides version 0.2.3 by default. One has to download and install version 0.2.4 manually.
