### ISSUE TITLE
JSX React fragment syntax (empty tag) generates warnings throughout the fragment but is correct and proper JSX nomenclature.

### ISSUE THREAD

**Issue by BrianHCombes** [apache/netbeans#4832]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Within the ReactJS development environment where HTML/JSX is normal in a JS file, NetBeans is interpreting fragment syntax as unexpected while expecting a "jsx_indentifier" per the warning message. See screenshot.

![JSX_Indentifier-problem- 2022-10-20 231431](https://user-images.githubusercontent.com/21314458/197117714-3a1d00cd-b90f-4070-9a16-b6cce2c410ff.jpg)

### How to reproduce

The trouble starts at the '<>' and ends at the '</>'
Simply paste this code into your IDE, running the code not needed:

import React from '../react_nodes/react';
import { Outlet, Link } from '../react_nodes/react-router-dom';

const Layout = () => {
  return (
         
    <> 
          <div>
          <Link to="/"><button>Home</button></Link>
          <br /><br />
          </div>
            
          <div>
          <Link to="/blogs"><button>Blogs</button></Link>
          <br /><br />
          </div>  
            
          <div>
          <Link to="/contact"><button>Contact for thee</button></Link>
          </div>            
        

      <Outlet />
    </>
  )
  
};

export default Layout;

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Pro

### JDK

Java: 18.0.1.1; Java HotSpot(TM) 64-Bit Server VM 18.0.1.1+2-6

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Happens at all times this syntax is encountered.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by BrianHCombes** [comment]
BTW, I get around it by replacing empty tags with a filler like '<React.StrictMode>' or simply '<div>' but it does create an unneeded DOM node.

**Comment by Chris2011** [comment]
Reproducable. Thx for the info.

**Comment by matthiasblaesing** [comment]
@BrianHCombes thank you for the report. Could you please check the referenced PR whether that fixes your usecase (and that of #5149)? A nightly build is available from the CI/CD summary page:

https://github.com/apache/netbeans/actions/runs/4589486775

or via this link:

https://github.com/apache/netbeans/suites/11974020321/artifacts/628316307

Thank you.
