### ISSUE TITLE
Gradle won't load project in NetBeans-16rc1

### ISSUE THREAD

**Issue by errael** [apache/netbeans#4847]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Attached zip file has trivial projects that demo the problem

Running `NB-master, Oct 19 just after freeze` under NB-15 debugger

Open lib - resolve problem

Observe:       
```
    Cannot load: /.../lib
    Could not run build action using
        /home/err/.gradle/wrapper/dists/gradle-6.8.3-bin
            /7ykxq50lst7lb7wx1nijpicxn/gradle-6.8.3
```
On the System, there is:

```
        /home/err/.gradle/wrapper/dists/gradle-6.8.3-bin
            /7ykxq50lst7lb7wx1nijpicxn/gradle-6.8.3/bin/gradle
```

Right click lib - select build, `BUILD SUCCESSFUL`

Still has PrimingBuildRequired and Resolve still fails; Cannot load

**NOTE: There are two smallish bugs in NB-15, mentioned in the "How to reproduce" section; since can't open on 16...**

### How to reproduce

Steps are shown above, to reiterate

1. jar -xf _attached-zip-file_, 3 projects: lib,app,compose
[gradle-projects-compose.zip](https://github.com/apache/netbeans/files/9847401/gradle-projects-compose.zip)
2. open lib, resolve doesn't work, see above

### This is what happens on NB-15 (with two small bugs)

**=== problem 1 (minor problem)**

0. tar -x projects
1. clean userdir/cachedir
2. Open app,lib - trust yes, resolve problem
3. Observe lib resolves, not app.
4. Attempt to resolve app, Does not resolve app, no error indication or output.
5. Do app > build, see expected error
       Execution failed for task ':compileJava'.
       > Could not resolve all files for configuration ':compileClasspath'.
          > Could not find play:lib:1.0.0.
   Resolve should show this rather than failing silently
6. Execute task lib publishToMavenLocal
7. Now app resolves as expected.

Only problem is that step 4 does not show an error (which can be seen by manually running build as in step 5)

**=== problem 2**

With all problems resolved,
right click on app, "SetMainProject" does not appear in context menu.

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Linux harmony 5.19.16-76051916-generic #202210150742~1666053244~22.04~cf07008 SMP PREEMPT_DYNAMIC Tue O x86_64 x86_64 x86_64 GNU/Linux

### JDK

openjdk 11.0.2 2019-01-15

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Doesn't seem specific to the project setup you shared.  Happens just with `lib` and with any project set up to use Gradle 6.8.3.

cc @lkishalmi @sdedic for comment.  Marked high and with NB16 milestone for now, but feel free to re-assess.

**Comment by lkishalmi** [comment]
```
Failed to notify build listener. 'java.util.Optional org.gradle.api.internal.plugins.PluginRegistry.findPluginForClass(java.lang.Class)'
```
Well we should be careful when using internal Gradle classes.

**Comment by errael** [comment]
> ```
> Failed to notify build listener. 'java.util.Optional org.gradle.api.internal.plugins.PluginRegistry.findPluginForClass(java.lang.Class)'
> ```
> 
> Well we should be careful when using internal Gradle classes.

Off topic of nb-16 fix, but how about an issue/discussion to consider not running Gradle with NB directly? Could the Gradle daemon be used to gather the info that NB needs?

**Comment by neilcsmith-net** [comment]
@sdedic download it? Or possibly compile it?  If you want to go down a rabbit warren :smile: https://issues.apache.org/jira/browse/LEGAL-570

**Comment by sdedic** [comment]
Never mind; I think I've found a way how to generate gradle wrapper by gradle (that is available, otherwise all CI gradle tests would be failing).

**Comment by matthiasblaesing** [comment]
@sdedic you indicate, that you found a solution, if the need arises, that NetBeans external dependencies mechanism can download from arbitrary https locations:

https://github.com/apache/netbeans/blob/9445a566c595a6c7573e3478e3073c3e15eda05f/extide/libs.gradle/external/binaries-list#L18

That way an offline build will still work if the binary is cached once. We should not stretch this to wide, but gradle is already using it to download the tooling-api and gradle itself.

**Comment by errael** [comment]
Fixed running
```
 hg glog -r .
@    changeset:   9067:9197022e1aed
|\   bookmark:    delivery
~ ~  tag:         tip
     tag:         upstream/delivery
     parent:      9066:94426cc5a858
     parent:      9060:dca4cb74f460
     user:        Neil C Smith <neilcsmith@apache.org>
     date:        Tue Oct 25 11:31:46 2022 +0100
     summary:     Merge pull request #4808 from lkishalmi/languages.antlr-4
```
