### ISSUE TITLE
CSS: Hint "unknown property" is displayed, in case the css property is written in uppercase letters.

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#4861]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

Hint "unknown property" is displayed, in case the css property is written in uppercase letters.

![image](https://user-images.githubusercontent.com/9607501/197937097-86b7609a-5e8f-4694-9e97-23063a9a25df.png)

### How to reproduce

Write the css property in uppercase letters.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian 10

### JDK

OpenJDK Runtime Environment 11.0.16+8-post-Debian-1deb10u1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
@troizet could you please have a look at the referenced PR? It should fix this issue and a test build is available there.

**Comment by matthiasblaesing** [comment]
@troizet thanks for checking!
