### ISSUE TITLE
Can't activate Tools > Plugins > Installed > Tools

### ISSUE THREAD

**Issue by errael** [apache/netbeans#4866]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

Automatic module activation activates parts of "non-detail" broad plugin group. This leads to situations where a user can neither acitvate nor deactivate the plugin group; somewhat confusing. The user is forced into the "show details" realm.

Turns out this isn't just about automatic activation. The tools module consists of, according to it's documentation,
```
Modules installed: Gradle Editor Support, Gradle Projects Distributions, Ant
```
But manually activating tools with the Plugins dialog, or having it automatically activated by Options Dialog, only activates Ant.

Don't know if this is a tools only problem, or a generic problem with _Uber Plugins_.

And, starting with a clean userdir/cachedir
```
Tools > Options > Java > Gradle
```
does not activate Gradle, it shows a blank pane. **This seems like a bug**. Interestingly, if you then do
```
Tools > Options > JavaDebugger
```
And go back to `Gradle`, the gradle pane is now active.

So one way to activate gradle, without opening a gradle project, is too first look at `JavaDebugger` options.

### How to reproduce

**Manually Activating Tools has problems**

0.  Start with clean userdir/cachedir
1.  Tools > Plugins > Installed > Checkmark Tools
2.  Click Activate, Click Activate, Click Finish
    Observe Plugins > Tools is not shown as active.
4.  Checkmark Tools
    Observe Activate Button is not enabled
    Observe Deactivate Button is not enabled
3.  Checkmark Show Details
    Observe
    Search: Ant; Ant-Tools is Active
    Search: Gradle; Gradle Editor Support, Gradle Projects Distributions are not active

Activating Tools should have activate all 3 things listed in its `Modules installed` (I think).

**Automatic Activation by Options Dialog**

0.  Start with clean userdir/cachedir
1.  Tools > Options > Java > Gradle
    Observe blank pane
2.  click Cancel to dismiss Options
3. Tools > Plugins > Installed
    Observe Tools is not active
4.  Checkmark Tools
    Observe Activate Button is not enabled
    Observe Deactivate Button is not enabled

Going to Gradle options should activate Gradle tools.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux harmony 5.19.16-76051916-generic #202210150742~1666053244~22.04~cf07008 SMP PREEMPT_DYNAMIC Tue O x86_64 x86_64 x86_64 GNU/Linux

### JDK

openjdk version "11.0.2" 2019-01-15 OpenJDK Runtime Environment 18.9 (build 11.0.2+9) OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Can replicate. Come across this testing builds and RCs quite often. Ergonomics can be a PITA sometimes (it's actually better behaving here than when we shipped nb-javac separately!). Clicking on another tab (eg. Maven) and back in options fixes the blank pane by enabling Java SE - assume something also due to location of options panel registration in extide cluster?  cc @lkishalmi

**Comment by lkishalmi** [comment]
Hmm, both the `gradle.editor` module (new in this release) and the `gradle.dists` are eager modules, which should mean they are loaded if all of their dependencies are loaded. There might be a glitch in the feature enablement code somewhere.

The easy workaround would be to have these modules as regular and add them as a dependency in the `gradle.kit` module. I'm going to create a PR for that.
