### ISSUE TITLE
No high resolution icon (png)

### ISSUE THREAD

**Issue by javierllorente** [apache/netbeans#4881]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

netbeans.icns is 512 x 512 pixels whereas netbeans.png is 32 x 32 pixels. This low resolution makes it look blurry on KDE.

### How to reproduce

Unzip the binary zip and head to netbeans/nb/. There you will see that netbeans.png is low-res. 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

openSUSE Tumbleweed / KDE Plasma

### JDK

OpenJDK 17.0.4

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
We have high resolution frame icons, which are picked up fine by Gnome.  Any idea what KDE is doing differently and where it's picking the low resolution icon from?

**Comment by javierllorente** [comment]
Where are those high resolution icons in the binary zip? I thought netbeans.png was picked for the taskbar, hence my pull request.
Even if KDE is picking the low resolution icon, don't we need a high resolution one for creating a .desktop file (affects any DE)?

**Comment by neilcsmith-net** [comment]
They're inside `core.startup` so of less use for a desktop file - https://github.com/apache/netbeans/tree/master/platform/core.startup/src/org/netbeans/core/startup

I think an SVG might be a better option in a desktop file?  Although possibly with a PNG option.  Depends if you're installing them or providing a file path.  I think they need to be added alongside the existing icon in NetBeans distribution though.

There's a fixed up SVG and a 48x48 PNG in NBPackage used for creating DEB, etc. - https://github.com/apache/netbeans-tools/tree/master/nbpackage/src/main/resources/org/apache/netbeans/nbpackage  The SVG needed proportions fixing and comments removing to work properly on Gnome.  I have a feeling that the XDG spec says a 48x48 icon is the minimum that must be provided if installing as icons, hence the DEB provides that plus SVG.

**Comment by javierllorente** [comment]
I also think that a SVG would be a better option. Perhaps we could include https://github.com/apache/netbeans/blob/master/nbbuild/javadoctools/siteresource/apache-netbeans.svg in the binary zip?

The [Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) recommends a 48x48 icon;
"So, you're an application author, and want to install application icons so that they work in the KDE and Gnome menus. Minimally you should install a 48x48 icon in the hicolor theme."

**Comment by lkishalmi** [comment]
The "old" Linux installer created a desktop file with a lo-res icon.

The Snap distribution has the 512x512 png, that looks fine.

**Comment by neilcsmith-net** [comment]
@javierllorente I had difficulties with Gnome not loading that SVG, tracked to issues with the license header, which is why the NBPackage SVG is different from that one. Would need to validate what works across OS.

@lkishalmi see things like #4776 - it would be useful to have higher quality icons bundled in the zip.
