### ISSUE TITLE
Start Page Size and Startup Dialog have shrunk 

### ISSUE THREAD

**Issue by ebresie** [apache/netbeans#4889]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

On Startup, the dialog use to look like
![image](https://user-images.githubusercontent.com/370894/198884587-e48f7881-9d6e-410b-b4bb-258dd6194d53.png)

But with Netbeans 16-rc2 it looks like
![image](https://user-images.githubusercontent.com/370894/198884616-e2f5a509-4d81-4c28-9de9-0c8ec03c4c55.png)

On the Start Page, the size of the content has changes (on the left is Netbeans 15, on the right is Netbeans 16-rc2)
![image](https://user-images.githubusercontent.com/370894/198884128-52bc811e-b722-4e61-9a31-b81f637b6c62.png)

### How to reproduce

Startup NetBeans 15, see the Startup dialog and the Start Page
Startup NetBeans 16-rc2, see the Startup Dialog and the Start Page window.

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Windows 11

### JDK

openjdk version "11.0.12" 2021-07-20

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

May be related to similar startup issues like

- https://github.com/apache/netbeans/issues/3910 
- https://github.com/apache/netbeans/issues/4288

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ebresie** [comment]
The About dialog also seems to have some sizing issues as well.

For 15
![image](https://user-images.githubusercontent.com/370894/198885582-ec486b71-169b-4d19-bf67-766b792bdfd1.png)

For 16-rc2 
![image](https://user-images.githubusercontent.com/370894/198885538-f921155a-b3c2-4054-a286-6337b8212149.png)

**Comment by ebresie** [comment]
In the New Project, it also appears to impact size of the dialogs

![image](https://user-images.githubusercontent.com/370894/198886030-6b9aa77c-3dea-439e-9b0b-458880f821fd.png)

**Comment by ebresie** [comment]
Not sure if this is a behavior relative to the screen size as this is high resolution like

![image](https://user-images.githubusercontent.com/370894/198886196-82fda08f-1947-45cd-97e8-a5d70d432849.png)

**Comment by ebresie** [comment]
Initially, the etc/netbeans.conf file has no netbeans_jdkhome set by default which seemed to leverage JDK 8 version.  It seems to be leveraging Java 8.  When setting this to netbeans_jdkhome  to a Java 11 JDK this seems to help resolve this.

Does NetBeans 16 now require Java 11 to run?

**Comment by neilcsmith-net** [comment]
Officially NetBeans has required Java 11 since NetBeans 13!  I'd recommend using JDK 18 to run the IDE on.  At least, that fixed a bunch of HiDPI issues I'd seen elsewhere.

**Comment by neilcsmith-net** [comment]
I'm also curious the Windows launcher is finding JDK 8 without anything in netbeans.conf - doesn't find Java 11+.

**Comment by ebresie** [comment]
Not sure if this is relevant, but 

- The Windows Java control panel Java...VIew finds only the Java 8 JRE present, 
- There was no "JAVA_HOME" set so it may be looking via the path
- The "Oracle" "javapath" was present earlier in the path (as well as other versions), so maybe this has something to do with how ["Oracle" deals with javapath](https://stackoverflow.com/questions/49540325/which-jre-does-c-programdata-oracle-java-javapath-java-exe-use)

**Comment by eirikbakke** [comment]
Yeah, this is a HiDPI scaling issue on Java 8 vs. Java 11; not a NetBeans version issue. Java 8 did not support HiDPI scaling on Windows, and so instead, Windows tries to do its own compatibility mode thing, which doesn't work very well. The solution is to run the NetBeans IDE on a newer Java version. (You can still associate your individual projects with Java 8 if desired.)
