### ISSUE TITLE
No more option for creating an EJB singleton in the wizard that creates an EJB

### ISSUE THREAD

**Issue by richard-grin** [apache/netbeans#4892]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

In a Jakarta EE Web application, the previous versions of NetBeans allowed to create an EJB singleton with New > Session Bean. It is no longer the case.
It would be nice to have it back.

### How to reproduce

Create a Maven Jakarta EE Web application.
Right click on the application and choose New > Session Bean. No radio button for Singleton.
I join 2 snapshots: with a previous version and with the current beta version.

![current](https://user-images.githubusercontent.com/3168639/199059301-ae003309-208f-4192-850e-cadcd4606465.png)
![previous](https://user-images.githubusercontent.com/3168639/199059399-72bfd2c4-53dd-4395-b117-3fe23ee26763.png)

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Windows 11 Family 64-bit, version 21H2

### JDK

11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

It is not a big problem but I don't understand why this option was removed.
I reported other errors in this wizard that creates an EJB and perhaps it is not difficult to add this option back in the same time.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by richard-grin** [comment]
Are there any plans to fix this and other Jakarta EE 9.1 issues in the final NetBeans 16 release? Or are the fixes planned for a later release?

**Comment by neilcsmith-net** [comment]
> Are there any plans to fix this and other Jakarta EE 9.1 issues in the final NetBeans 16 release?

Not in NB16, sorry - see [dev@ mail thread](https://lists.apache.org/thread/m4ok1nnk4dt44kgycf5s64b3vwtj0xrc). Hopefully fixes can happen in the NB17 timeframe.

**Comment by richard-grin** [comment]
Thanks Neil for this important information. It is a big problem for me 
because I have a training course scheduled for a month from now, but I 
understand it is not easy to fix all these issues.

Richard

Le 11/11/2022 à 11:06, Neil C Smith a écrit :

**Comment by richard-grin** [comment]
This issue is still in NetBeans 17 RC1.

**Comment by richard-grin** [comment]
Planned in the final version of NetBeans 17?

**Comment by neilcsmith-net** [comment]
If it's not in by now then almost certainly not, sorry.
