### ISSUE TITLE
Toolbars Git->create tag

### ISSUE THREAD

**Issue by plavv** [apache/netbeans#4914]
### Description

In toolbar is absent Git->create tag.
In customize toolbars, I can not add item Git->create tag.
Please, add Git->create tag in toolbar.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Not sure if it should be enabled by default, but if it's not addable by customization then that would be good to look at.

**Comment by plavv** [comment]
Сan you add the button(Git-tag) in the next release?
