### ISSUE TITLE
Unable to build c/c++ EFL (Enlightenment Foundation Libraries) project

### ISSUE THREAD

**Issue by RubbleMonkey** [apache/netbeans#4925]
### Apache NetBeans version

Apache NetBeans 15

### What happened

I started a new c project using the c/c++ plugin (NOT the CPPLite kit plugin), and added the required pkg-config command using the "Add PkgConfig Library" option in the project properties menu. After a number of warnings regarding the <Elementary.h> header the build failed. I tried gcc and clang and neither worked. If I invoke the compiler directly it builds just fine, but if you try to use make on the project makefile directly if fails the same way.

### How to reproduce

The problem is reproducible by making any test application using the EFL libraries and then trying to build it. I have attached my exported test project:
[EFL_test.zip](https://github.com/apache/netbeans/files/9945034/EFL_test.zip)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux - OpenSUSE Leap 15.4 x86_64

### JDK

OpenJDK 11.0.16

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

I attached the build error:
[build_log.txt](https://github.com/apache/netbeans/files/9945046/build_log.txt)

If you need any additional information I would be happy to help!

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Thanks for the report.  The C/C++ plugin is not part of the Apache NetBeans project, so we can't do anything about issues with it directly.

This code may be released by Apache NetBeans in future.  Perhaps @vieiro has an update, thoughts on workaround, or ideas where help might be useful?

**Comment by vieiro** [comment]
Hi @neilcsmith-net ,
I have very little idea about the CPPLite functionality. I think @jlahoda is the author and may shed more light into the issue.

**Comment by RubbleMonkey** [comment]
Since it is a problem with the old 8.2 plugin and it's not part of the Apache NetBeans project, would it be more helpful to close this issue and open a feature request to opensource the 8.2 c/c++ plugin? It would be a real shame to see such a useful plugin go unmaintained.

**Comment by neilcsmith-net** [comment]
@vieiro yes, this is with the old C/C++ code, not CPPLite.  Are you still looking at updating and bringing that back into NetBeans?  If this particular issue is not still relevant to the work, please close it, thanks!

@RubbleMonkey there is a branch here with the code already (it was always open-source, and was donated) - it's just not in a releasable state. https://github.com/apache/netbeans/tree/cnd

**Comment by RubbleMonkey** [comment]
@neilcsmith-net thanks! I'll have to check that out!
