### ISSUE TITLE
Netbeans 15 crashes when i change language

### ISSUE THREAD

**Issue by iarts** [apache/netbeans#4935]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Netbeans 15 crashes when i change language on mac air m2 2022

### How to reproduce

just open netbeans and change the language e.g from english to greek

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

mac OS ventura 13.0

### JDK

Java: 11.0.13; Java HotSpot(TM) 64-Bit Server VM 11.0.13+10-LTS-370

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
I'd guess that would be JDK specific. Do you have other information logs/crash dump?

**Comment by mbien** [comment]
closing since no response
