### ISSUE TITLE
PHP interpreter doesn't work with spaces

### ISSUE THREAD

**Issue by BrandonWill** [apache/netbeans#4940]
### Apache NetBeans version

Apache NetBeans 15

### What happened

PHP Interpreter does not work correctly if there are spaces.

Example not working:
![image](https://user-images.githubusercontent.com/949047/200662911-f677c4f5-717c-41d8-85e2-43cb4b16017a.png)

Example working:
![image](https://user-images.githubusercontent.com/949047/200662755-025559e9-a939-49e6-9c92-8caaf6200902.png)

### How to reproduce

On Windows, copy and paste your PHP folder and try to point to it in NetBeans settings. Any spaces will cause the "PHP interpreter must be a valid file." error

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows

### JDK

Microsoft JDK 11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
I was not able to reproduce the issue in NetBeans 17.
Tried both Windows and Linux.
Message "PHP interpreter must be a valid file" appeared only when file did not exist.
