### ISSUE TITLE
Improve padding size in the "Options" dialog

### ISSUE THREAD

**Issue by bykka** [apache/netbeans#4973]
### Description

The "Options" dialog does not look polished and one of the problems is that components have different padding sizes.
Or sometimes does not have padding at all.

- different padding
![image](https://user-images.githubusercontent.com/489997/202186090-4b9a62e0-1ce9-4043-8de7-0f416a98492d.png)
![image](https://user-images.githubusercontent.com/489997/202187637-e0c45e06-1bd8-4986-8dc0-95b8c8eca5b7.png)
![image](https://user-images.githubusercontent.com/489997/202187849-5c3acfae-3d3f-4857-8b4b-65710bfd5f35.png)
![image](https://user-images.githubusercontent.com/489997/202188287-e156df68-9259-4d5b-bf1a-3dd334d1284d.png)
- no top padding
![image](https://user-images.githubusercontent.com/489997/202186339-5b37ce2f-af31-4436-b9b6-cde7cda3b55b.png)
- different padding
![image](https://user-images.githubusercontent.com/489997/202186543-66499e9d-115f-417d-acb4-07e17c3df0e5.png)
![image](https://user-images.githubusercontent.com/489997/202187083-8251f64c-3a16-4895-96bd-eefebaa1dc5d.png)
- no bottom padding and unnecessary resize bar
![image](https://user-images.githubusercontent.com/489997/202186851-cdfe5f76-d205-4652-bd12-476aaf9c327f.png)
- different top padding
![image](https://user-images.githubusercontent.com/489997/202187509-f5a67367-1386-4fae-9333-38718f973269.png)

### Use case/motivation

Would to see a consistent design for all tabs of the "Options" dialog.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Some good points made (except possibly for the resize bar - actually found myself needing that this week).  Stuck `good first issue` on it, as it might be an interesting issue for a new contributor with good visible outcomes.

**Comment by mbien** [comment]
what look and feel are you using? FlatLaf won't render many of the borders on the screenshots which makes this issue less visible. In some situations adding padding without borders might leave too large gaps (e.g I don't think the hints tab needs more padding in the north with FlatLaf since there is no border).

NB16 should have a more consistent looking hints tab (with all its option panels) #4906.

**Comment by bykka** [comment]
Windows L&F
![image](https://user-images.githubusercontent.com/489997/202390949-88ed2219-dcd0-4d20-9eb1-7239473940cd.png)

**Comment by mbien** [comment]
right. FlatLaf became the default on all systems a few releases ago. We mostly pay attention that everything is working well on the default.

But fixes for other look and feels are of course welcome too as long they don't affect the default. Most of the layout issues you marked do also apply to FlatLaf.

**Comment by mbien** [comment]
gradle options cleanup: #5274

**Comment by mbien** [comment]
@bykka #5625 should fix this + more. A dev build will appear on the summary page of the PR workflow.
