### ISSUE TITLE
no library found for namespace http://omnifaces.org/ui

### ISSUE THREAD

**Issue by NicolaIsotta** [apache/netbeans#4976]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

Since omnifaces 3.0, omnifaces taglib are not recognized by the IDE.

### How to reproduce

Create java / jakarta EE (at least 8) web project. 
Add omnifaces 3 (if java/jakarta EE 8) or 4 (if jakarta EE >= 9) dependency
Create xhtml page and add `xmlns:o="http://omnifaces.org/ui"` to the namespaces declaration
![omnifaces](https://user-images.githubusercontent.com/18428155/202250672-d27ab467-8beb-489f-9af9-88087eba373e.jpg)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

Java: 11.0.13; Java HotSpot(TM) 64-Bit Server VM 11.0.13+10-LTS-370

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Related:
https://github.com/omnifaces/omnifaces/issues/489
https://github.com/omnifaces/omnifaces/issues/442
https://issues.apache.org/jira/browse/NETBEANS-3611
https://issues.apache.org/jira/browse/NETBEANS-3150

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by NicolaIsotta** [comment]
Ok find the cause.
In ConfigManager, jakarta ee taglibs are not handled:
https://github.com/apache/netbeans/blob/67393d2c6d8dc52aadb3477ac86b40bfc2dc4fef/enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/facelets/mojarra/ConfigManager.java#L1062-L1153
Solution:
- add mojarra-4.0 as an external module (I don't really know how to do this)
- refactor the code in the ConfigManager by calling the new mojarra function `DbfFactory.getSchema(ServletContext servletContext, String documentNS, String version, String localName)`:

https://github.com/eclipse-ee4j/mojarra/blob/b9f62a28133b639a1f1d1f23de02fc7027e8aa23/impl/src/main/java/com/sun/faces/config/manager/DbfFactory.java#L320-L331

Any hint on how to go on?

**Comment by morvael** [comment]
Related to this (perhaps) is lack of support for new non-URL URNs for JSF 4.0:
![jsf4](https://user-images.githubusercontent.com/1133953/210590859-af78ea71-8ece-4d31-a47f-8ef650922c20.png)
See https://github.com/jakartaee/faces/issues/1553

And I think related to that is the inability to load facelet 4.0 taglib (also "No library found" error):
```
<facelet-taglib version="4.0"
                xmlns="https://jakarta.ee/xml/ns/jakartaee"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-facelettaglibrary_4_0.xsd">
                ...
```

**Comment by LouisCollet** [comment]
Same situation in NB 17rc3
What makes Jakarta EE unusable for Jakarta Faces 4.0
Are we to understand that NB no longer supports JSF?

**Comment by geertjanw** [comment]
You are to understand that NB supports everything you provide support for at github.com/apache/netbeans.

**Comment by LouisCollet** [comment]
Hi everybody,

I am a basic java developer and certainly unable to participate in the development of NB. 

I would like to continue to evolve and use Jakarta EE... and especially Jakarta Faces 4.0.

In no way, my message is a criticism, but a cry for help!

Have a nice day ¡

Louis

**Comment by geertjanw** [comment]
Appreciated, thanks, @LouisCollet.

**Comment by fcorneli** [comment]
Tried out NetBeans version 17-RC3. Unfortunately this issue is still present.
On a Java EE 8 project NetBeans does not recognize `xmlns:p="http://primefaces.org/ui"`, i.e., red all over the place. Same remark for a Quarkus project using JSF.

On a Jakarta EE 10 project NetBeans does not recognize `xmlns:h="jakarta.faces.html"`, but there `xmlns:p="http://primefaces.org/ui"` is OK.
Could somebody have a look at this before version 17? Such basic functionality should not get broken.

**Comment by fcorneli** [comment]
Strange, version 17 still has this issue, but a build from master not...
