### ISSUE TITLE
Missing Open Actions in DataSystem API Platform Applications

### ISSUE THREAD

**Issue by twothorns** [apache/netbeans#4981]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Upgraded from Netbeans 12 to 15 (and JDK 1.8 to 19) and now the Open actions are missing from the File menu on builds of pre-existing and new 'Java with Ant' platform applicatrions using the DataSystem API.

### How to reproduce

Create the vanilla application from the 'File Type Integration Turorial' (https://netbeans.apache.org/tutorials/60/nbm-filetype.html).  This will create a File Type application with no way of opening a file.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

Windows 10 version 10.0 running on amd64

### JDK

JDK-19.0.1

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
any exceptions in the log? Try starting your application on JDK 11 and check for java module system warnings. Those warnings are errors on more recent JDKs.

https://dev.java/learn/strong-encapsulation-(of-jdk-internals)/

It often helps to not upgrade several major versions at once - this rarely works out of the box.
