### ISSUE TITLE
Git diff "Local to Revision" does not allow to select the revison, only the branch

### ISSUE THREAD

**Issue by scsynergy** [apache/netbeans#4983]
### Apache NetBeans version

Apache NetBeans 15

### What happened

When I right-click on a project or any file therein and select "Git" -> "Diff" -> "Diff to ..." -> "Local to Revision" I can select the branch I want to diff but not the revision I want to diff against - instead the dialog closes immediately when I click on a branch.

Up to and including Netbeans 14 after selecting the desired branch another dialog would open where all the revisions of that branch were displayed and I could select the exact revision I want to diff against.

This second dialog (see attached file for screenshot) does not open up, instead the dialog with the branches just closes when I select a branch.

### How to reproduce

When I right-click on a project or any file therein and select "Git" -> "Diff" -> "Diff to ..." -> "Local to Revision" I can select the branch I want to diff but not the revision I want to diff against - instead the dialog closes immediately when I click on a branch.

Up to and including Netbeans 14 after selecting the desired branch another dialog would open where all the revisions of that branch were displayed and I could select the exact revision I want to diff against.

This second dialog (see attached file for screenshot) does not open up, instead the dialog with the branches just closes when I select a branch.
![netbeans-bug-screenshot](https://user-images.githubusercontent.com/11332162/202645135-4bf24507-c9c5-43c3-b7f6-885d129d59dd.png)

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Debian 11 bullseye

### JDK

OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
I just tried it and it worked with NB 15. I could select a specific hash and diff against it. Check the logs if you see any git related exception.

as workaround, you can also change the revision later once the diff window is open (upper right combo box).

There are also at least two other ways how to diff: you can simply press the history button on any file and you are in a diff view or use the git -> show history to see a full file history diff.

**Comment by scsynergy** [comment]
The Log-File in ~/.netbeans/15/var/log/messages.log does not seem to show any related exception (I cannot attach the file: "Something went really wrong, and we can't process that file. Try again."

I attached a screenshot with the upper right combo box of the diff window which only shows branches to choose from, not revisions and the "Select" entry only opens up a dialog within which I may select a branch but never a specific revision.

Unless I am too stupid to understand the UI, the "show history" does not allow to diff two different branches, but only within the one branch?

![Screenshot_20221121_141040](https://user-images.githubusercontent.com/11332162/203064719-ad2f3ae0-60b7-4493-8382-d2dbd189ecc6.png)
).

![Screenshot_20221121_142111](https://user-images.githubusercontent.com/11332162/203065691-1829d680-e12a-4462-9c6a-b3b92ebfc2ce.png)

I also attached a screenshot made with Netbeans 14 to show how the dialog looks there.
![netbeans14-screenshot](https://user-images.githubusercontent.com/11332162/203066222-94600c69-67de-4dc2-a797-69dbe3b60f84.png)

**Comment by mbien** [comment]
> the "show history" does not allow to diff two different branches, but only within the one branch?

you are right, I think I looked at the wrong window when I replied.

The problem is that when following your steps the window does open up for me:

![diff-to](https://user-images.githubusercontent.com/114367/203135334-daa822e8-ba84-4b3a-b31b-996432b152ec.png)

and once the `Select` and then `Diff` is pressed, it is possible to open the same window again in the diff view scrolling down and selecting:
![diff-again](https://user-images.githubusercontent.com/114367/203135475-08624222-f3a6-4def-9b28-1177042415b9.png)


we have to diff our workstations to figure out what is going on here :) Have you tried it with a different project?

**Comment by scsynergy** [comment]
It happens with all projects not just for me but also for all of my colleagues.
No related exception in ~/.netbeans/15/var/log/messages.log.
No notification within Netbeans itself.

**Comment by scsynergy** [comment]
The same bug occurs on Netbeans 16, too.

**Comment by scsynergy** [comment]
Ah, yes, that worked - such a simple solution. Thank you very much!
