### ISSUE TITLE
Cannot run Chrome

### ISSUE THREAD

**Issue by TheToma** [apache/netbeans#4987]
### Apache NetBeans version

Apache NetBeans 15

### What happened

When I hit run with chrome with netbeans connector selected I keep getting the error "Cannont run C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" I also get this error when I go to the help tab and select "Online Docs and Support" and "Report Issue". Oddly enough is I click on "Keyboard Shortcut Card" it opens a new tab in Chrome just fine. If Microsoft Edge is selected as my default browser it will run, but who wants to use Edge?!?

### How to reproduce

Have Netbeans 15 and Netbeans connector installed on Windows 10.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

JDK 18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by ebresie** [comment]
The NetBeans Connector does seem to be a little dated as details on the page show as "Version 1.1.5 Updated September 9, 2015" 

Not sure if this is related but without [NetBeans Connector](https://chrome.google.com/webstore/detail/netbeans-connector/hafdlehgocfcodbgjnpecfajgkeejnaa?hl=en ) installed, the first time I selected "Chrome" in the Tools...Option...General...Web Browser, on the same panel, the "Proxy Setting" had "Use System Properties" set.  I set (in my environment) to "No Proxy" and selected the Help...Online Doc and it seemed to open up.

**Comment by ebresie** [comment]
For reference, using Windows 11, with Netbeans running on Java 11

**Comment by ebresie** [comment]
Is this associated with netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins in the codebase?  

When attempting to build there are a number of "deprecation warnings" 

Ignoring source, target and bootclasspath as release has been set
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:32: warning: [deprecation] ExternalProcessBuilder in org.netbeans.api.extexecution has been deprecated
import org.netbeans.api.extexecution.ExternalProcessBuilder;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:33: warning: [deprecation] InputReaderTask in org.netbeans.api.extexecution.input has been deprecated
import org.netbeans.api.extexecution.input.InputReaderTask;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:34: warning: [deprecation] InputReaders in org.netbeans.api.extexecution.input has been deprecated
import org.netbeans.api.extexecution.input.InputReaders;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:32: warning: [deprecation] ExternalProcessBuilder in org.netbeans.api.extexecution has been deprecated
import org.netbeans.api.extexecution.ExternalProcessBuilder;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:33: warning: [deprecation] InputReaderTask in org.netbeans.api.extexecution.input has been deprecated
import org.netbeans.api.extexecution.input.InputReaderTask;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:34: warning: [deprecation] InputReaders in org.netbeans.api.extexecution.input has been deprecated
import org.netbeans.api.extexecution.input.InputReaders;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:32: warning: [deprecation] ExternalProcessBuilder in org.netbeans.api.extexecution has been deprecated
import org.netbeans.api.extexecution.ExternalProcessBuilder;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:33: warning: [deprecation] InputReaderTask in org.netbeans.api.extexecution.input has been deprecated
import org.netbeans.api.extexecution.input.InputReaderTask;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:34: warning: [deprecation] InputReaders in org.netbeans.api.extexecution.input has been deprecated
import org.netbeans.api.extexecution.input.InputReaders;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:32: warning: [deprecation] ExternalProcessBuilder in org.netbeans.api.extexecution has been deprecated
import org.netbeans.api.extexecution.ExternalProcessBuilder;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:33: warning: [deprecation] InputReaderTask in org.netbeans.api.extexecution.input has been deprecated
import org.netbeans.api.extexecution.input.InputReaderTask;
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:34: warning: [deprecation] InputReaders in org.netbeans.api.extexecution.input has been deprecated
import org.netbeans.api.extexecution.input.InputReaders;

C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:99: warning: [deprecation] ExternalProcessBuilder in org.netbeans.api.extexecution has been deprecated
            Process process = new ExternalProcessBuilder(executable)
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:103: warning: [deprecation] InputReaderTask in org.netbeans.api.extexecution.input has been deprecated
            InputReaderTask task = InputReaderTask.newTask(
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:103: warning: [deprecation] InputReaderTask in org.netbeans.api.extexecution.input has been deprecated
            InputReaderTask task = InputReaderTask.newTask(
C:\git\netbeans\webcommon\extbrowser.chrome\src\org\netbeans\modules\extbrowser\plugins\chrome\LinkListener.java:104: warning: [deprecation] InputReaders in org.netbeans.api.extexecution.input has been deprecated
                    InputReaders.forStream(process.getInputStream(),

**Comment by vieiro** [comment]
Closing this one if favor or #6601
