### ISSUE TITLE
"Click to change this {license|template}" not working

### ISSUE THREAD

**Issue by jwoehr** [apache/netbeans#4988]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Creating a new PHP file produces this:
```
<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */
```
Clicking has no effect.

### How to reproduce

1. Create a PHP file.
2. Click on the text which represents the link.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

```
Linux pop-os 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux
```

### JDK

```
$ java --version openjdk 11.0.17 2022-10-18 OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04) OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
```

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by JoachimRohde** [comment]
You need to hold the CTRL-key while clicking. If you don't know this the text is a bit misleading.

**Comment by mbien** [comment]
going to assume that the ctrl+click worked -> closing
