### ISSUE TITLE
Possible to hide, remove, or override Help button on Platform Applications?

### ISSUE THREAD

**Issue by tmulle** [apache/netbeans#5003]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Not really a bug, so feel free to move this ticket to another location.

Since we can't use JavaHelp in the Platform Applications we build with NetBeans, is it possible to remove/hide the Help button?

The reason I ask is that if we decide to use NetBeans for our commercial application we are going to get customer issues because they see a help button but it doesn't work.

So, we would like to do either of the following:

a) Hide the help button
b) Get Java Help integration working again (I know it's a license issue which is why it's not there)
c) Have the help button enabled but be able to override the functionality to open a remote website with HTML documentation being hosted. This way we can use the Help button in all the places it automatically shows up but bring the customer to our hosted documentation.

Thanks!

### How to reproduce

Click on any Help button and nothing will happen.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mac OS

### JDK

JDK11+

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
b) and c) are already achievable in a platform application.  For c) look at https://bits.netbeans.org/dev/javadoc/org-openide-util-ui/org/openide/util/HelpCtx.Displayer.html

**Comment by trixon** [comment]
For a) I use
System.setProperty("netbeans.winsys.no_help_in_dialogs", "true");
as per https://bits.netbeans.org/dev/javadoc/org-openide-windows/architecture-summary.html

**Comment by tmulle** [comment]
Thanks everyone, I think we'll use option A and then add a new menu item for Help Contents like the NetBeans IDE does.
I'll close this issue now..

Just out of curiosity, are there any detailed instructions on how to get JavaHelp reintegrated in a Platform Application using the external jars?
