### ISSUE TITLE
[PHP] Coalescing operator is formatted as ternary operator

### ISSUE THREAD

**Issue by noelma** [apache/netbeans#5011]
### Apache NetBeans version

Apache NetBeans 15

### What happened

When I format my PHP 7+ code
Coalescing operators are aligned as ternary operators

#### Currently
![Capture d’écran du 2022-11-27 09-48-36](https://user-images.githubusercontent.com/10517497/204126628-cbb62e01-d71e-4bb2-bdcf-05dc16726f48.png)

#### Goal
![Capture d’écran du 2022-11-27 09-56-54](https://user-images.githubusercontent.com/10517497/204126942-4c959b4a-51d8-4fdd-bdf8-f4b62713018d.png)

Or separate into 2 packing option :man_shrugging:  :
- coalescing operator
- ternary operator

### How to reproduce

- In `Tools` > `Options` > `Editor` > `Formatting` > `PHP(Wrapping)`
- Use `Always` for the `Ternary Operator` option
  ![fen](https://user-images.githubusercontent.com/10517497/204127621-a0539df1-d9cc-4b06-b234-917218e72eed.png)
- And `Apply`
- Insert the following code in a PHP file:
  ```php
  <?php

  $data = [
      'key_1' => 10,
      'key_2' => 100,
  ];

  $tenaryOperator = isset($data['key_1']) ? $data['key_1'] : 'default';

  $coalescingOperator = $data['key_1'] ?? 'default';
  ```
- Apply formatting

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Linux version 5.15.0-53-generic running on amd64

### JDK

18.0.2-ea; OpenJDK 64-Bit Server VM 18.0.2-ea+9-Ubuntu-222.04; Private Build

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by junichi11** [comment]
Reproducible. Thank you for your report!
