### ISSUE TITLE
Some Gradle Projects can't be Loaded due to NotSerializableException

### ISSUE THREAD

**Issue by lkishalmi** [apache/netbeans#5015]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

I've tried to open the `netbeans-website/netbeans.apache.org` the IDE reports a  notification that it cannot be open due to NotSerializableException on `tasks.propertyValues`

### How to reproduce

1. Clone https://github.com/apache/netbeans-website
2. Open the netbeans.apace.org project in it

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Ubuntu 22.04 and 22.10

### JDK

Java 17

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by sdedic** [comment]
Will fix by tomorrow to get to the patch release. Thanks.
