### ISSUE TITLE
[PHP] Error for octal numbers with prefix in php8.1

### ISSUE THREAD

**Issue by noelma** [apache/netbeans#5026]
### Apache NetBeans version

Apache NetBeans 15

### What happened

In PHP 8.1, it is possible to write octal numbers with the explicit prefix `0o`.
https://wiki.php.net/rfc/explicit_octal_notation
https://www.php.net/manual/en/migration81.new-features.php#migration81.new-features.core.octal-literal-prefix

This new octal prefix causes a syntax error
![Capture d’écran du 2022-11-28 21-57-56](https://user-images.githubusercontent.com/10517497/204380503-72e079a3-e81e-4080-8173-0d7d03220f4c.png)
![Capture d’écran du 2022-11-28 21-58-03](https://user-images.githubusercontent.com/10517497/204380516-be44795a-7541-4d4d-be16-5ed078909699.png)

### How to reproduce

- In `Properties` > `Sources` > `PHP Version`,
- Select `PHP 8.1`,
- Insert the following code in a PHP file:
  ```php
  <?php
  
  // PHP ^8.0
  if(016 === 14) {
      echo "016 in octal equals 14 in decimal\n";
  }
  // PHP 8.1+
  if(0o16 === 14) {
      echo "0o16 in octal numbers with the explicit 0o prefix equals 14 in decimal\n";
  }
  ```

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Linux version 5.15.0-53-generic running on amd64

### JDK

18.0.2-ea; OpenJDK 64-Bit Server VM 18.0.2-ea+9-Ubuntu-222.04; Private Build

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Reproducible.
This wasn't part of PHP 8.1 support in https://github.com/apache/netbeans/pull/3463

**Comment by junichi11** [comment]
Fixed.
