### ISSUE TITLE
async method with super call: Error "Expected an operand but found super"

### ISSUE THREAD

**Issue by lbuchs** [apache/netbeans#5030]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Netbeans marks valid JavaScript code as invalid, when awaiting a super call in a async function.

### How to reproduce

1. Create a javascript file with following content:

```
class Foo {
    async baseMethod() {
        return 10;
    }
}

class Bar extends Foo {
    async extendedMethod() {
        let i = await super.baseMethod();
        console.log(i);
    }
}

x = new Bar();
x.extendedMethod();
```
Netbeans will show a syntax error:

```
Expected an operand but found super
      let i = await super.baseMethod();
        
----
(Alt-Enter shows hints)
```

Project Setting for Javascript ECMA Version is: _ES.Next (Experimental)_, but the error is reproducible with every version.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

Java(TM) SE Runtime Environment 17.0.1+12-LTS-39

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
This will also be fixed by #5677
