### ISSUE TITLE
PHP - Highlight calling deprecated method

### ISSUE THREAD

**Issue by zeleznypa** [apache/netbeans#5043]
### Description

When the code contain calling a method on the class, that is marked as `@deprecated`, it will be useful to highlight this as warning same like `Wrong param name` for example

<img width="1099" alt="Snímek obrazovky 2022-12-03 v 9 50 55" src="https://user-images.githubusercontent.com/1191472/205432752-0c98d65a-3a96-4008-93ff-04a3257a15e0.png">

The `@deprecated` can be in the phpDoc on the method or also on the whole class/interface.

### Use case/motivation

I would like to be informed, that I'm calling something, that is deprecated and will be removed or changed in the future.
Sometimes the `@deprecated` phpDoc also contain an useful information about how to change the current code.

### Are you willing to submit a pull request?

I want to, but I'm not a Java developer

### Code of Conduct

Yes

**Comment by Chris2011** [comment]
I would prefer to strike through them as we already know this feature. What do you think? @zeleznypa 
<img width="286" alt="image" src="https://user-images.githubusercontent.com/795658/205465818-87042a0a-509c-447d-a5b6-67198e139d1b.png">

This is more consistent in my opinion.

**Comment by zeleznypa** [comment]
@Chris2011 Any variant of highlighting this will be nice.

**Comment by troizet** [comment]
You can enable this feature in Options -> php -> Annotations -> Resolve Deprecated Elements.

**Comment by zeleznypa** [comment]
@troizet Thanks much, it is what I'm looking for.
