### ISSUE TITLE
Go to File -> Search by folder is broken

### ISSUE THREAD

**Issue by mokraemer** [apache/netbeans#5055]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

if you open the dialog "Go To File"
you can select "Search by folders" but the result is always empty.

My assumption about this function would be, it lists the files found by the name of the given folders. But even if you have a folder "test" with 10 files in it. And type "test" and select "Search by Folders" you always get "<No Files Found>"

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mageia 8 (Linux)

### JDK

openjdk 11.0.17 2022-10-18 LTS

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Chris2011** [comment]
It is working but it seems very slow:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/795658/206273061-36afe641-1529-47ca-880e-c2053c430813.png">

**Comment by mokraemer** [comment]
I think, I totally misunderstood this search type. I thought it could be used to open files by part of the folder (package) names:
e.g. if your tree is
main/modules/tree/item/base.js
you could just type "tree" to get all files from main/modules/tree

since, if you enable "Search by folders" and type
*base
it still finds "main/modules/tree/item/base.js" while base is no folder name.

I was hoping, to get a method to easily open files from a package, as the files themselves are named "base".

**Comment by mokraemer** [comment]
ok, I found, what "search by folder" is used for.
If you have output, e.g. by a debugger and get the full path, you can simply paste the full path in that field and open that file.
If the checkbox is not selected, that would not work.

**Comment by mokraemer** [comment]
Since packages, namespaces, modules or what ever you call them are integrated, the file names are now shorter and the folders may contain part of the relevant information.
See e.g. https://www.php-fig.org/psr/psr-4/

Sure, one can navigate in tree, but this is quite "slow", as you have to open many folders - I assume you encounter the same, and find it more easy by typing filenames to open files.

**Comment by mbien** [comment]
oh didn't know this dialog existed, learned something new. (I always used ctrl+o aka go-to-type or do a ctrl+f search on a folder)

so not broken after all? Should we close it?

**Comment by mokraemer** [comment]
that feature is not broken - right, but can we improve it, so searching a folder - not searching the path - would be possible too?

If I have the full path (with line no from a tool), I really don't need a "search dialog" - just a "open this file".

**Comment by Chris2011** [comment]
For this feature request, please create a new feature request ticket and add explicit step by step instrctions, what you would like to see in NetBeans. With examples etc. Also check other IDEs/editors for UX to see how they do it and how NetBeans can improve it too.
