### ISSUE TITLE
[JS] Codecompletion: Inheritance support

### ISSUE THREAD

**Issue by mokraemer** [apache/netbeans#5056]
### Description

If you use inheritance in JS, e.g.:
```
class A{
	y(){
		
	}
}

class B extends A{
	  x(){
		
	}
}

let xx=new B();
```

And then type "xx." netbeans just finds "x()" and not "y()"

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Chris2011** [comment]
For me it is working with latest NetBeans 15: 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/795658/206271354-13becffd-ce4a-473d-86ae-45b9495c7952.png">

Can you please a bit more specific, maybe there is some other case, where this is not working.

**Comment by mokraemer** [comment]
strange, in one project it works, but not in another one. I'm going to check what is the difference between those.

**Comment by matthiasblaesing** [comment]
Completion for inherited members works in projects, but not outside it. If I'm not mistaken this makes sense, as in the working case the parent completion comes from the JS Index. However the indexer only files contained in a project, not outside it.

**Comment by mokraemer** [comment]
I cannot reproduce the issue; I' going to close it.
