### ISSUE TITLE
Remove abandon cache folder not cleaning up

### ISSUE THREAD

**Issue by ebresie** [apache/netbeans#5069]
### Apache NetBeans version

Apache NetBeans 16

### What happened

In Windows environment, a number of previous versions of netbeans have been installed over time and cleaned up.

In the "%USERPROFILE%/AppData/Local/Netbeans/Cache" folder there is a folder which includes previously removed (i.e. Netbeans 14) while nothing else shows in other folder 

On startup with a newer version, the mismatch of the abandoned cache folder causes the below notification to show

![image](https://user-images.githubusercontent.com/370894/206912677-2049a554-9f32-4a80-9b2e-8495512abe8e.png)

When selecting to turn on janitor cleanup, the abandon cached folder remains and does not get removed as expected.

### How to reproduce

On windows in the "%USERPROFILE%/AppData/Local/Netbeans/Cache" folder, have an abandon netbeans cache folder.
Startup newer Netbeans,
Wait for Cleanup notification to occur.
Select to cleanup
Restart Netbeans
Cleanup notification will occur again 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

JDK 11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Occurs at startup following initial initialization and notification appears.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ebresie** [comment]
Notification looks like the following:

![image](https://user-images.githubusercontent.com/370894/209848498-a411aa4f-7198-4f53-bfdb-7fac0b88f20e.png)

**Comment by ebresie** [comment]
Assuming this is somewhere in the Janitor project (org.netbeans.modules.janitor package)

**Comment by ebresie** [comment]
For reference here is 
![image](https://user-images.githubusercontent.com/370894/209977719-0a3c0e1d-0d31-4540-a443-ec2b1c772e85.png)

Here is the cache folder setup which is triggering the "cache" mismatch
![image](https://user-images.githubusercontent.com/370894/209977926-af57bd1c-ab54-46c0-afdf-bfafc048a7c1.png)

**Comment by lkishalmi** [comment]
Let's see if this would work better: https://github.com/apache/netbeans/pull/6148

**Comment by mbien** [comment]
i assume this is now working fine on windows since NB 19
