### ISSUE TITLE
[PHP] Intersection types is not highlighted nor clickable on function return type and property type

### ISSUE THREAD

**Issue by the-liquid-metal** [apache/netbeans#5072]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Netbeans already able to validate and highlight class name in context of intersection types. All accepted position: function argument type, function return type, property type are fine. Unfortunately this did not happen to interface. There are:
- missing validation and highlighting on function return type and property type.
- missing validation on function argument type.

### How to reproduce

```php
<?php
class Class1 {}
class Class2 {}
interface Iface1 {}
interface Iface2 {}

// displayed highlight: all accept null
// missing highlight: [none]
// displayed error: null and 2nd Class1
// missing error: 2nd Iface1
function funcX(Class1 & Class2 & Iface1 & Iface2 & null & Class1 & Iface1 $arg1) {
    echo $arg1;
}

// displayed highlight: Class1 and Class2
// missing highlight: Iface1 and Iface2
// displayed error: null and 2nd Class1
// missing error: 2nd Iface1
function funcY($arg1): Class1 & Class2 & Iface1 & Iface2 & null & Class1 & Iface1 {
    echo $arg1;
}

class Class3 {
    // displayed highlight: Class1 and Class2
    // missing highlight: Iface1 and Iface2
    // displayed error: null and 2nd Class1
    // missing error: 2nd Iface1
    public Class1 & Class2 & Iface1 & Iface2 & null & Class1 & Iface1 $prop1;
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

Java: 14.0.1; Java HotSpot(TM) 64-Bit Server VM 14.0.1+7 Runtime: Java(TM) SE Runtime Environment 14.0.1+7

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Reproducible.
Thanks fro your report.

**Comment by KacerCZ** [comment]
During testing I also found out, that "Find Usages" does not find all usages of `Iface1` and `Iface2`.

**Comment by KacerCZ** [comment]
PR #5534 fixes reported errors.
