### ISSUE TITLE
[PHP] Explicit octal integer literal detected as error

### ISSUE THREAD

**Issue by the-liquid-metal** [apache/netbeans#5075]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Explicit octal integer literal detected as error

### How to reproduce

```php
$oct = 0o123456; // error
$oct = 0o123_456; // error
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

Java: 14.0.1; Java HotSpot(TM) 64-Bit Server VM 14.0.1+7 Runtime: Java(TM) SE Runtime Environment 14.0.1+7

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by troizet** [comment]
Duplicate #5026
