### ISSUE TITLE
[PHP] Not relevant enum methods must produce error

### ISSUE THREAD

**Issue by the-liquid-metal** [apache/netbeans#5086]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Not relevant enum methods must produce error

### How to reproduce

```php
enum Suit: string {
  case Hearts = 'H';
  case Diamonds = 'D';
  case Clubs = 'C';
  case Spades = 'S';

  // already correct error message display
  public function __construct($param) {
    echo "__construct";
  }

  // this statement must display error
  public function __destruct() {
    echo "__destruct";
  }

  // this statement must display error
  public function __set($arg1, $arg2) {
    echo "__set";
  }

  // this statement must display error
  public function __get($arg1) {
    echo "__get";
  }

  // OK
  public function __call(string $name, array $args) : mixed {
    echo "__call";
  }

  // OK
  public static function __callStatic(string $name, array $arguments): mixed {
    echo "__callStatic";
  }
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

Java: 14.0.1; Java HotSpot(TM) 64-Bit Server VM 14.0.1+7 Runtime: Java(TM) SE Runtime Environment 14.0.1+7

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Similar to #5094, just more forbidden method names.

**Comment by KacerCZ** [comment]
According to PHP documentation there are more magic methods not allowed in enums.
These methods are `__isset`, `__unset`, `__sleep`, `__weakeup`, `__serialize`, `__unserialize`, `__toString`, `__set_state`, `__clone` and `__debugInfo`.

Links:
* https://www.php.net/manual/en/language.enumerations.object-differences.php
* https://www.php.net/manual/en/language.oop5.magic.php

**Comment by KacerCZ** [comment]
PR was merged and will be part of NetBeans 17.
