### ISSUE TITLE
[PHP] Enum must not use trait which requires property

### ISSUE THREAD

**Issue by the-liquid-metal** [apache/netbeans#5093]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Since enum most not has property, using trait which requires property is forbidden.

### How to reproduce

```php
<?php
trait TWithProp {
    public function setProp() {
        return $this->prop;
    }
}

trait TWithoutProp {
    public function getValue() {
        return 10;
    }
}

enum Suit1: string {
  use TWithProp;  // this statement must display error
  use TWithoutProp; // OK
  case Hearts = 'H';
  case Diamonds = 'D';
  case Clubs = 'C';
  case Spades = 'S';
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

Java: 14.0.1; Java HotSpot(TM) 64-Bit Server VM 14.0.1+7 Runtime: Java(TM) SE Runtime Environment 14.0.1+7

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Your first trait does not contain any property.

I verified, that NetBeans 16 and also version from master correctly display error if enum contains property declaration or uses trait with property.

**Comment by the-liquid-metal** [comment]
NB correctly recognize declared properties.

Look at line-4 and line-7: the property declared/accessed dinamically.
run successfully at compile time, error at runtime as long as those methods are not called.
