### ISSUE TITLE
[PHP] Enum is missing autocompletion "name" item for instance context

### ISSUE THREAD

**Issue by the-liquid-metal** [apache/netbeans#5102]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Enum has builtin readonly property: ```name``` and ```value```. Unfortunately, ```name``` is missing in autocomplete, specifically in instance context.

### How to reproduce

```php
<?php
enum Suit: string {
  case Hearts = 'H';
  case Diamonds = 'D';
  case Clubs = 'C';
  case Spades = 'S';
}

echo Suit::Hearts->value . "\n"; // OK
echo Suit::Hearts->name  . "\n"; // MISSING

$card = Suit::Diamonds;
echo $card->value . "\n"; // OK
echo $card->name  . "\n"; // MISSING
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

Java: 14.0.1; Java HotSpot(TM) 64-Bit Server VM 14.0.1+7 Runtime: Java(TM) SE Runtime Environment 14.0.1+7

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Reproducible.
Thanks for your report.

**Comment by KacerCZ** [comment]
PR #4966 fixes this issue.
