### ISSUE TITLE
CSS: Parsing error "unexpected token SASS_FORWARD" in LESS file

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#5104]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Parsing error "unexpected token SASS_FORWARD" in LESS file.

### How to reproduce

- create a LESS file
- write `@forward: 'test';`

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian 10

### JDK

11.0.16; OpenJDK 64-Bit Server VM 11.0.16+8-post-Debian-1deb10u1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
Please check the referenced PR. A testbuild is available there. I'd appreciate a review/test.

**Comment by troizet** [comment]
@matthiasblaesing I tried a test build. Everything works. Thank you!
