### ISSUE TITLE
Netbeans 16 is suspended in Linux Ubuntu Studio 22.04

### ISSUE THREAD

**Issue by paul-e-king** [apache/netbeans#5146]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Netbeans 16 was installed in Ubuntu Studio 22.04 running a KDE Plasma desktop. No errors were reported from the installation. The method used was to download the .deb package from the Apache site, and run "sudo dpkg -i" to install it.

When the "netbeans" command was run by clicking the icon, execution was suspended indefinitely, and had to be killed using a kill -HUP signal.

When "netbeans" was run from a command line, the following warnings were noted from standard error:
```
Script started on 2022-12-24 11:16:26-05:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="106" LINES="30"]
rivendell $ netbeans
Detected KDE; adding awt.useSystemAAFontSettings=on
WARNING: package com.apple.eio not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/usr/lib/apache-netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
^C
rivendell $ exit

Script done on 2022-12-24 11:17:50-05:00 [COMMAND_EXIT_CODE="0"]
```
Once again, execution was suspended indefinitely, and this time the execution could be stopped using Control+C.

At no time did I see a GUI.

Paul

### How to reproduce

1. Use a machine running Debian or an Ubuntu variant, with KDE Plasma as the desktop
2. Download and install the .deb for Apache Netbeans 16 from the Apache Netbeans website.
3. Install under BASH using ```sudo dpkg -i apache-netbeans_16-1_all.deb```
4. Find the icon under your Application Launcher menu (type "netbeans" with the menu open), click on the Netbeans icon.
5. Notice an increase in system activity briefly, then nothing. (netbeans is suspended)
Alternative steps
4. Run netbeans from bash
5. Again, nothing will happen, but assure yourself that it is loaded with: ```ps ax|grep netbeans``` in a bash console.
6. Find the PID, then run ```kill -HUP nnn``` where nnn is the PID of netbeans

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux (Ubuntu Studio 22.04)

### JDK

19.0.1 OpenJDK

### Apache NetBeans packaging

Third-party package

### Anything else

The packaging was a *.deb, provided by the Apache Netbeans website. Since a package manager was required to open it that was not provided by Apache, I am saying that dpkg is 3rd party for that reason.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
does the zip distribution work?

**Comment by lkishalmi** [comment]
You may also take a ThreadDump from the process in order to see what is blocking the execution. May also try with a different LTS JDK (17, or 11)

**Comment by neilcsmith-net** [comment]
What is the content of `~/.netbeans/16/var/log/messages.log`?

What is the output of `apt list --installed "*openjdk*"`?
