### ISSUE TITLE
Operand error on adding Comments in JSX block

### ISSUE THREAD

**Issue by BrianHCombes** [apache/netbeans#5149]
### Apache NetBeans version

Apache NetBeans 16

### What happened

When adding standard JSX format comments in a JSX block when developing in ReactJS an operand/syntax error occurs. 

Proper comment form is as follows:  {/* This is a comment */}.

This causes line error markers that clutter up the code space. 

![Comment Errors - Screenshot 2022-12-25 230246](https://user-images.githubusercontent.com/21314458/209509766-9a4f71e2-7924-470d-b354-d89040dd8eca.jpg)

This does not affect run time. It's simply a IDE environment issue.

### How to reproduce

Simply create a code block of JSX.

Add a comment line like so: {/* comment */}

You should see this causes numerous error markers on numerous lines. However, the code will run fine.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Pro

### JDK

Java: 18.0.1.1; Java HotSpot(TM) 64-Bit Server VM 18.0.1.1+2-6

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by locness3** [comment]
Same issue. What source file should be looked into?

**Comment by BrianHCombes** [comment]
On 2023-03-19 3:19 pm, locness3 wrote:

> Same issue. What source file should be looked into?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>

Any ReactJS source file having a JSX block within. Standard comment 
protocol is treated as an error within the JSX block. Technically, the 
JSX block is the HTML within the ReactJS file which is a JS file by 
format. It's all a ReactJS thing.

Best Regards,

Brian H. Combes
President / Chief Engineer
Tarp Tie Down Company
Email: ***@***.***
Phone/Text: 303-919-2307

Links:
------
[1] 
https://github.com/apache/netbeans/issues/5149#issuecomment-1475402667
[2]

**Comment by locness3** [comment]
I'm talking about the source cpde of NetBeans.

**Comment by BrianHCombes** [comment]
On 2023-03-20 3:54 am, locness3 wrote:

> I'm talking about the source code of NetBeans.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>

Ah,

Project properties are:

Netbeans source configuration is PHP 7.4 with UTF-8 encoding and running 
PHP Built-in web server.

This for development of HTML web pages.

Best Regards,

Brian H. Combes
President / Chief Engineer
Tarp Tie Down Company
Email: ***@***.***
Phone/Text: 303-919-2307

Links:
------
[1] 
https://github.com/apache/netbeans/issues/5149#issuecomment-1475921863
[2]

**Comment by locness3** [comment]
OK, I'm just trying to find which part of NetBeans's source code handles hints for JSX.
