### ISSUE TITLE
The maven pom has a multi-level dependency problem

### ISSUE THREAD

**Issue by nvdsl** [apache/netbeans#5169]
### Apache NetBeans version

Apache NetBeans 16

### What happened

When importing mvave projects, dependency calculation is incorrect for some projects.

### How to reproduce

The maven pom has a multi-level dependency problem, but the maven plugin of eclipse does not have this problem. There are some problems with pom.xml calculation in META-INF of other jars or referenced projects. The experience of netbean is much better now. Thank you for your efforts.

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

window 10

### JDK

jdk17

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

none

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by ebresie** [comment]
Can any example of the problem be provided?  Either an example pom or point to a project where this may occur?

**Comment by ebresie** [comment]
Is this related to transient dependencies or only those defined in the pom?

**Comment by mbien** [comment]
would need more details, closing
