### ISSUE TITLE
Javascript Modules: export Keyword disables hightlighting within classes

### ISSUE THREAD

**Issue by NReib** [apache/netbeans#5184]
### Apache NetBeans version

Apache NetBeans 16

### What happened

While browsing JS Modules with exported classes, there is no Highlighting within a directly exported class. Also the methods of that class do not show in the navigator.

### How to reproduce

```// this does not show in navigator / highlighting does not work
export class test {
	method(param){
		param;
	}
};

// this shows in navigator / highlighting works
class test2{
	method(param){
		param;
	}
}

// no highlighting, Go to declaration does not work
export {test2};
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mageia 8 (Linux)

### JDK

javac 11.0.17

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
@NReib could you please check the referenced PR and/or the dev build available from the CI/CD summary page:

https://github.com/apache/netbeans/actions/runs/4658661222

or directly via:

https://github.com/apache/netbeans/suites/12134425195/artifacts/639862034

**Comment by NReib** [comment]
Thank you for the fix, sadly, I was on vacation. I suppose the feature does not require further testing?

**Comment by matthiasblaesing** [comment]
@NReib no problem. NetBeans 18 is reaching its freeze date. Testing is always appreciated and double checking, that the issue is indeed fixed at least confirms the fix.
