### ISSUE TITLE
[PHP] Match operator formatting with arrays is broken

### ISSUE THREAD

**Issue by NReib** [apache/netbeans#5186]
### Apache NetBeans version

Apache NetBeans 16

### What happened

If the value of a match arm is an array, NB does not format it well.

### How to reproduce

Before:
```
<?php
match(123){
	'test' => [
		'key' => 'val',
		],
};
?>
```

After Alt+Shift+F:
```
<?php
match(123){
	'test' => [
'key' => 'val',
	],
};
?>
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mageia 8 (Linux)

### JDK

openjdk version "11.0.17" 2022-10-18 LTS

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Reproducible.
Thanks for your report.
