### ISSUE TITLE
Add PHP to HTML5 project

### ISSUE THREAD

**Issue by sainirman** [apache/netbeans#5190]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Unable to add PHP files to an HTML5 project.

### How to reproduce

Create an HTML5 project and try adding a PHP file.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

19.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Chris2011** [comment]
For this we have a PHP project, where you can also have JS files, HTML, CSS, Twig, whatever you want. At the end, you can add an empty file and name it "Foo.php". This should work.

**Comment by sainirman** [comment]
> For this we have a PHP project, where you can also have JS files, HTML, CSS, Twig, whatever you want. At the end, you can add an empty file and name it "Foo.php". This should work.

I am aware about the existing PHP project, however imagine a case where you have a huge project completely made as an HTML project and you only have to add minor PHP code to it. In such case it is not feasible to make the project completely again as a PHP project even if it just means copy and pasting. I am looking to add a PHP file to my already existing HTML project and creating an empty file with a .php extension doesn't work.

**Comment by Chris2011** [comment]
Of course it is working:

![image](https://user-images.githubusercontent.com/795658/210785403-9b6defe6-72f0-46c9-9630-6f5cced01327.png)

If it is not working for you, please help us to identify the problem.

**Comment by matthiasblaesing** [comment]
No reply in ~9months, closing.
