### ISSUE TITLE
VSNetBeans build fails on java.mx.project missing tag in build.xml

### ISSUE THREAD

**Issue by MartinBalin** [apache/netbeans#5196]
### Apache NetBeans version

Apache NetBeans 16

### What happened

VSNetBeans builder failed at https://ci-builds.apache.org/job/Netbeans/job/netbeans-vscode/1389/consoleText
at bottom there is following error:
```
-checkout-graalvm:
     [exec] Cloning into 'graal'...
     [exec] warning: Could not find remote branch vm-20.3.0 to clone.
     [exec] fatal: Remote branch vm-20.3.0 not found in upstream origin

BUILD FAILED
/home/jenkins/workspace/Netbeans/netbeans-vscode/java/java.mx.project/build.xml:30: exec returned: 128
```
Checking https://github.com/oracle/graal git repo there is no [`vm-20.3.0`](https://github.com/apache/netbeans/blob/6e18d439dbcf608714abe1f5b855900db9fd6216/java/java.mx.project/build.xml#L34) tag nor branch. Similarly there is also a reference to mx branch [`5.279.0`](https://github.com/apache/netbeans/blob/6e18d439dbcf608714abe1f5b855900db9fd6216/java/java.mx.project/build.xml#L44) at the same build.xml.
The failure happened with build #1389, VSIX itself is built.

### How to reproduce

See the build on jenkins https://ci-builds.apache.org/job/Netbeans/job/netbeans-vscode/1389/

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

ubuntu jenkins builder

### JDK

JDK11

### Apache NetBeans packaging

Apache VSNetBeans for VSCode

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by jtulach** [comment]
> someone pruned the tags in the public repository (?)

Unbelievable! OracleLabs guys should provide a justification why they believe removing tagged releases is a good practice. @MartinBalin why did that happen?

Thanks for the #5199 fix - that shall be enough until some _clever mind_ decides to rewrite whole history or the repository...

**Comment by jtulach** [comment]
According to [slack discussion](https://graalvm.slack.com/archives/CNBFR78F9/p1673178311692809?thread_ts=1673177767.964889&cid=CNBFR78F9) the missing tag is back:

> this is a bug and is going to be fixed....
> .... The bug is fixed and deployed, the missing tags  are now avail ...
> The tags are back online and we've made sure this cannot happen again. Sorry for the inconvenience! 

Thank you. The (development) world seems to be a consistent place again.

**Comment by mbien** [comment]
if its back online as the quote says and also there to stay we should probably revert #5199 again - or at least then when the next time the version is bumped.

**Comment by mbien** [comment]
the same issue just resurfaced, the tags and branches appear to be gone again:
https://github.com/apache/netbeans/pull/7468#issuecomment-2166392424
