### ISSUE TITLE
Deprecated 'main' property is used by run-single

### ISSUE THREAD

**Issue by swpalmer** [apache/netbeans#5267]
### Apache NetBeans version

Apache NetBeans 16

### What happened

The run single file action injects a runSingle task that references a Gradle property that was deprecated in Gradle 7.5

Running with  '--warning-mode all --stacktrace' the result is:
```
The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.5/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main for more details.
at org.gradle.api.tasks.JavaExec.setMain(JavaExec.java:427)
at org.gradle.api.tasks.JavaExec_Decorated.setMain(Unknown Source)
at org.netbeans.modules.gradle.tooling.NetBeansRunSinglePlugin.lambda$addTask$2(NetBeansRunSinglePlugin.java:85)
```

### How to reproduce

Using Gradle 7.5 or later and running a single file via the context menu will reproduce the problem.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS 13.2

### JDK

JDK 17.0.05

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
closing since the PR was merged
