### ISSUE TITLE
Folder ... is already used as Netbeans project

### ISSUE THREAD

**Issue by evgeniy-dammer** [apache/netbeans#5273]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Hello, I have a problem with opening ntop/ntopng project. 
Actually, I followed this guide https://fossies.org/linux/ntopng/doc/README.netbeans.pdf
When I specify the folder with the project, I get an error "Folder /mnt/49c9b955-8511-4b53-81ef-82e3d0259fed/projects/ntopng is already used as Netbeans project" as on attached screenshot. Many people suggest deleting the nbproject folder in the project folder as a solution to this problem. But there is no nbproject folder inside the project folder.
I have installed different versions of NetBeans - 12 and 16. Also I have uninstalled and reinstalled NetBeans several times. I deleted the ~/.cache/netbeans/ cache. But the error persists.

### How to reproduce

1) File -> New Project -> C/C++ -> C/C++ Project with Existing Sources -> Next button
2) In "New Project" window specify a path "/path/ntopng" to project folder in field named "Specify the folder that contains existing sources"
3) At the bottom of this window the error "Folder "/mnt/49c9b955-8511-4b53-81ef-82e3d0259fed/projects/ntopng" is already used as Netbeans project"  appears

![Screenshot from 2023-01-11 12-11-53](https://user-images.githubusercontent.com/57175456/211757292-8e3939e0-7efa-42b7-87ea-d2f081bf8abc.png)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 22.04

### JDK

JDK 1.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
@mbien well, strictly speaking it's in the repository, just not in the main branch - https://github.com/apache/netbeans/tree/cnd

**Comment by mbien** [comment]
> @mbien well, strictly speaking it's in the repository, just not in the main branch and not in a releasable state (yet?!) - https://github.com/apache/netbeans/tree/cnd

yes i know about that branch

**Comment by neilcsmith-net** [comment]
Going to close this as `won't fix` for now.  We can't support CND from 8.2, and if the diverged CND branch here is brought back to life, that will probably require new issues and info.
