### ISSUE TITLE
PHP: Generates the return type boolean instead of bool for a function in phpDoc

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#5284]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Generates the return type `boolean` instead of `bool` for a function in phpDoc.
Php does not have a built-in `boolean` type: https://www.php.net/manual/en/language.types.intro.php
Also see the warning under "Scalar Types": https://www.php.net/manual/en/language.types.declarations.php

### How to reproduce

- Create a function that returns `true` or `false`:
```php
function test() 
{
    return true;
}
```
- Generate a phpDoc comment
- The `@return` tag was received with the wrong return type:
```php
/**
 * 
 * @return boolean
 */
function test() 
{
    return true;
}
```

instead of:
```php
/**
 * 
 * @return bool
 */
function test() 
{
    return true;
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian 10

### JDK

OpenJDK 64-Bit Server VM 11.0.16+8-post-Debian-1deb10u1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Reproducible.
Thanks for your report.
