### ISSUE TITLE
Netbeans plugin "Base IDE" not getting activated

### ISSUE THREAD

**Issue by blf-drishti** [apache/netbeans#5289]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Suddenly I noticed I didn't get the tool that had options "source" and "history" and I didn't see the option we see when seeing history to select which versions we are comparing like "local", "git", etc. 
Upon searching a bit on StackOverflow I came across a solution to reactivate the plugin "Base IDE" but neither the "activate" nor "deactivate" or "uninstall" button is enabled for it. It feels like this plugin is not activated currently but I haven't been able to activate or deactivate it.

### How to reproduce

Go to "tools">"plugins"> "installed" and select "Base IDE" plugin (that is click on the checkbox next to it). This is in Netbeans 16.

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

ubuntu

### JDK

11 openJdk Oracle

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This was working in 16 a while ago. This issue I noticed recently only

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
The `Base IDE` disabled buttons is replicated on a properly working IDE.  I can think of a couple of reasons that might be the case.  Try selecting the `Show details` checkbox and look at what plugins are activated in the Base IDE category.

It might be better to try with a clean userdir and/or reinstall.
