### ISSUE TITLE
css feature :has does not recognize pseudo classes

### ISSUE THREAD

**Issue by mokraemer** [apache/netbeans#5303]
### Apache NetBeans version

Apache NetBeans 16

### What happened

just add 
body:has(#aCheck:checked) {
  background-color:red;
}

this is marked as syntax error, but this is valid. has can contain any selector, even pseudo classes

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mageia 8 (Linux)

### JDK

java-11-openjdk-11.0.17.0.8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
@mokraemer please have a look at the referenced PR and test it. If you need a prebuild binary, it is available from the CI summary or from this direct link: https://github.com/apache/netbeans/suites/10786014570/artifacts/542201388

**Comment by mokraemer** [comment]
downloaded the referenced dev build.
It looks good for me. No more complains about the syntax.

Thanks!

**Comment by matthiasblaesing** [comment]
@mokraemer thanks for the test. I merged a slightly updated version, based on review.
