### ISSUE TITLE
Freezing program upon apply settings change

### ISSUE THREAD

**Issue by snowwolf212** [apache/netbeans#5321]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Hello. I came across a software bug with NetBeans. When I go into “Tools” > “Options” > “Editor” > and then I make changes from here… once I hit apply the whole program freezes and I can’t continue without forcing the program to shutdown with the task manager. Does my bug make sense to you? I was hoping you guys can fix this glitch. I’m running windows 11.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

JKD 19

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Which changes?!  Without knowing what you're trying to change when it hangs it's hard to help.  Or is this with _any_ change?

**Comment by snowwolf212** [comment]
Any changes I make from that settings window. As soon as I hit apply. The screen freezes.

Do you want me to make a video of it to show you???? I can do that for you.



________________________________

**Comment by neilcsmith-net** [comment]
Possibly.  Also check the userdir (location in About window) and look for the `var/log/messages.log` file.  Check if there's anything that seems related at the end and share here.  Thanks!

**Comment by snowwolf212** [comment]
The following is in the folder you mentioned me to go to. Did you want me to send you a copy of those files?  From: Neil C SmithSent: Tuesday, January 24, 2023 8:35 AMTo: apache/netbeansCc: snowwolf212; AuthorSubject: Re: [apache/netbeans] Freezing program upon apply settings change (Issue #5321) Possibly. Also check the userdir (location in About window) and look for the var/log/messages.log file. Check if there's anything that seems related at the end and share here. Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by neilcsmith-net** [comment]
@snowwolf212 please use the GitHub UI to respond - we're getting a bunch of HTML in your email replies that makes them less than useful!
