### ISSUE TITLE
Netbeans Incorrect Code Format for Java Source

### ISSUE THREAD

**Issue by kemperalves** [apache/netbeans#5323]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Today netbeans formatted my code erroneous, I converted the code to a simple sample with same structure and then the code continue to be wrong formatted.

### How to reproduce

1 - Create a new java project with a main class.

2 -Make your main function above:

```java

    public static void main(String[] args) throws Exception {

        List<String> myList = new ArrayList<>();

        for (String s : myList) {
            if (!s.isBlank()) {

                switch (s.substring(0, 1)) {
                    case "T":
                        System.out.println("T");
                        break;
                    case "N":                               
                                try {
                        System.out.println(Long.valueOf(s));
                    } catch (Exception ex) {
                        throw new Exception("FIRST ERROR MESSAGE");
                    }
                    break;
                    case "F":
                                    try {
                        System.out.println(new BigDecimal(s));
                    } catch (Exception ex) {
                        throw new Exception("ANOTHER ERROR MESSAGE");
                    }
                    break;
                    case "M":
                                    try {
                        System.out.println(new BigDecimal(s));
                    } catch (Exception ex) {
                        throw new Exception("OPS, MORE ONE ERROR MESSAGE");
                    }
                    break;
                    case "D":
                        throw new Exception("THIS VALUE CAN NOT BE USED");
                    case "L":
                                try {
                        System.out.println(Boolean.valueOf(s));
                    } catch (Exception ex) {
                        throw new Exception("THIS VALUE IS NOT A BOOLEAN");
                    }
                    break;
                }
            }
        }

    }


```

3 - Click in Source / Format or type the keyboard shortcut

And then, the code is formatted but, incorrect. the try blocks is not aligned, the breaks statements not aligned too.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS 13.1 (22C65), Darwin 22.2.0, MacBookPro18,3, MKGP3LL/A

### JDK

JDK 18, zulu

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by kemperalves** [comment]
The try blocks is not aligned and the blocks with these tyrs the break statement is wrong too.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/27026273/213455648-385443d4-8c1f-49f3-b431-d550465a3b13.png">

**Comment by neilcsmith-net** [comment]
Can replicate.  Only seems to be if the `try` directly follows the `case` statement.

**Comment by keshavcodex** [comment]
Hey, i am new here can I take this issue?

**Comment by BradWalker** [comment]
Hey @keshavcodex , yes you can "take" it.

As we are mostly volunteers here, there are a few people paid to work on Netbeans I believe, your efforts would be welcome. I'm confident we would welcome a fix if you proposed something.

**Comment by neilcsmith-net** [comment]
I'd forgotten about this little annoyance.  Putting a milestone on it as something to track for NB19.

@keshavcodex go for it! :+1: Anyone can open a PR for NetBeans - you don't need anyone's permission or to be assigned to work on something, and as Brad said, your efforts would be welcome.
