### ISSUE TITLE
Can't make git push

### ISSUE THREAD

**Issue by antoniodiego** [apache/netbeans#5326]
### Apache NetBeans version

Apache NetBeans 16

### What happened

The authorization are failing while i'm trieng to make a git push

### How to reproduce

Go to Team -> Push. Type the credentials. Click next

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

JDK 18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

It appers no messages showing what error happened. The screen simple repeats. 

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by antoniodiego** [comment]
With me it not works.

I put the same credentials I use to login on GitHub.

What shoud be at the credentials fields ?

Also, why credentials need to be asked ? Using the NetBeans integrated or a system terminal it isn't prompted 

Isn't there a way to skip the credentials entry?

**Comment by neilcsmith-net** [comment]
> I put the same credentials I use to login on GitHub.

GitHub doesn't support that. You need to setup a token.

See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by antoniodiego** [comment]
Creating a token worked

Thanks
