### ISSUE TITLE
Open folder on system file explorer

### ISSUE THREAD

**Issue by antoniodiego** [apache/netbeans#5327]
### Description

I think it should be good to open project foldes at system file explorer (Like the Windows Explorer on Windows). 
Several time we want to make it, but we need to find manually the folder throug the system explorer, what seems to be annoying.

### Use case/motivation

Do right click on the folder, select Show at system explorer option

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
candidate for a https://github.com/apache/netbeans/labels/good%20first%20issue, the open-in-terminal action could be used as potential blueprint.

https://github.com/apache/netbeans/blob/master/ide/dlight.terminal/src/org/netbeans/modules/dlight/terminal/action/OpenInTerminalAction.java

**Comment by neilcsmith-net** [comment]
Thanks @mbien - I removed the triage label but forgot to comment!

This would be a good improvement, but the action to use is probably already there https://github.com/apache/netbeans/blob/master/platform/core.ui/src/org/netbeans/core/ui/sysopen/SystemOpenAction.java  It might just be a case of referencing in two extra places - folders and the project actions.  I actually think it would be better if that action was available on _all_ files too.

**Comment by mbien** [comment]
@neilcsmith-net good to know, that is even better!

There is also a somewhat related usecase where you want to copy the path of a file or folder and paste it somewhere into your code, PR or shell etc. I think this could be solved by updating the properties UI (right click -> properties) to contain an easily copyable path. Only mentioning this here since I think to remember that there was a proposal to solve this via an action too, analog to SystemOpenAction.

**Comment by NicolaIsotta** [comment]
I use this plugin: https://github.com/lbruun/netbeans-explore-in-os

**Comment by mbien** [comment]
@NicolaIsotta thanks for the info. Added the plugin-available label.

**Comment by Chris2011** [comment]
We also have this one: https://github.com/Chris2011/QuickOpener-NetBeans it is a fork from another one which is dead. I think those stuff, what is already in this plugin like Open in system terminal (not in NetBeans), open in file explorer (Project, folder, also on selected file, copy file path and open in default app (like in an other editor) should be part of NetBeans core. I also wanted to spend this code but I dunno, whether we still need permissions from the original developer.
