### ISSUE TITLE
"Fix Import" omits a class when its class name with prefix is already used

### ISSUE THREAD

**Issue by frkinta** [apache/netbeans#5330]
### Apache NetBeans version

Apache NetBeans 16

### What happened

In the example bolow, when editing`myClass`, if you try to fix import by hitting "Ctrl+Shift+I", the editor will not propose to add the missing class : `use Test\Services\ApiService;`. 
This happen even when imported class are in different namespaces

### How to reproduce

```PHP
<?php

namespace Test\Services;

class ExtendedApiService{};
```
```PHP
<?php

namespace Test\Services;

class ApiService{};
```

```PHP
<?php

namespace Test;

use Test\Services\ExtendedApiService;

class myClass
{

    public function __construct(
        private ExtendedApiService $ExtendedApiService,
        private ApiService $ApiService,            
    )
    {
    }

}


```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

ubuntu 22.04

### JDK

OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04) OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by junichi11** [comment]
Reproducible. Thank you for your report!
