### ISSUE TITLE
Unable to connect to the NetBeans Distribution

### ISSUE THREAD

**Issue by tarcisioreis** [apache/netbeans#5345]
### Apache NetBeans version

Apache NetBeans 16

### What happened

This is the error message that appears when trying to update the plugins home screen:

"Unable to connect to the NetBeans Distribution because of sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targe"

### How to reproduce

To reproduce the error you have to install the platform, when entering the ide click on "Activate Features", the plugin screen will appear, in the Updates tab, just click on the check for updates button
![endscreen](https://user-images.githubusercontent.com/7525518/213942246-3afa2940-d2ae-44d4-9d5f-0613361f2f5f.png)
![screen1](https://user-images.githubusercontent.com/7525518/213942250-b18c7b2a-7785-4779-b4d2-1c1c66cf645b.png)
![screen2](https://user-images.githubusercontent.com/7525518/213942252-dcf3eeaa-7724-431a-b858-fc260e797ecb.png)
![screen3](https://user-images.githubusercontent.com/7525518/213942253-8a5886dc-9a20-4605-947c-be3843a57108.png)

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

Windows 8.1 64 bits

### JDK

jdk1.8.0_91

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Minimum JDK for NetBeans 13+ is JDK 11.  Minimum JDK for Let's Encrypt is also higher than that - https://letsencrypt.org/docs/certificate-compatibility/

Please test with a recent JDK and see if you can still reproduce?  Closing for now.

**Comment by tarcisioreis** [comment]
How do I adjust this in my netbeans installed with JDK 8 according to the print I sent. I await instructions to correct this.

**Comment by neilcsmith-net** [comment]
@tarcisioreis please try with a supported JDK.
