### ISSUE TITLE
PHP: ctrl+shift+space displays documentation for an empty line

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#5347]
### Apache NetBeans version

Apache NetBeans 16

### What happened

ctrl+shift+space displays documentation for an empty line

### How to reproduce

- create a new php file
- set the caret on the empty line
- press `Ctrl + Shift +Space` or click `Source -> Show documentation`.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian 10

### JDK

OpenJDK 64-Bit Server VM 11.0.16+8-post-Debian-1deb10u1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Reproducible in NetBeans 17.
