### ISSUE TITLE
CSS: bad handling of colons in class names

### ISSUE THREAD

**Issue by NicolaIsotta** [apache/netbeans#5351]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Netbeans does not handle css classes correctly if they contain colons (maybe other special chars too). I discovered this while using [primeflex](https://github.com/primefaces/primeflex).
In particular:

- css class suggestion should not contain the escape char before the colon
- there's a warning "Class xxx not found" if the class contains a colon

### How to reproduce

Include primeflex css in your webpage ( https://unpkg.com/primeflex@3.3.0/primeflex.css ).

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64; Cp1252; it_IT (nb)

### JDK

11.0.13; Java HotSpot(TM) 64-Bit Server VM 11.0.13+10-LTS-370

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

![image](https://user-images.githubusercontent.com/18428155/214053783-dd1dfead-1af3-4cca-946b-0e4487bc13fc.png)
![image](https://user-images.githubusercontent.com/18428155/214054239-1902a2c3-102e-4bf1-a950-cd10f557c78f.png)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment]
@NicolaIsotta could you please test this nightly build:

https://github.com/apache/netbeans/suites/11531466195/artifacts/596675121

It can be accessed from the latest checks run:

https://github.com/apache/netbeans/actions/runs/4408188233

The PR description:

**Comment by NicolaIsotta** [comment]
Hi @matthiasblaesing , I've tested the nightly build.
Suggestions work:
![image](https://user-images.githubusercontent.com/18428155/225256713-61b75a3f-15a9-458d-8dca-86d6f002fe1b.png)
Bu there's still the class not found warning:
![image](https://user-images.githubusercontent.com/18428155/225257047-f773abf7-19c5-4505-a33d-cd342eda9816.png)

**Comment by NicolaIsotta** [comment]
I found out why, there are 3 possible cases:

- css in the project folder and link targets the local css: everything (suggestion and check) works
- css in the project folder, link targets remote css: suggestions work but greyed out, check does not work
- no local css, link targets remote css: nothing works (even though the css appear in the "Remote Files" node)

but I do not think the remote css problem has something to do with this PR. Might be another issue.

**Comment by matthiasblaesing** [comment]
@NicolaIsotta thanks for the update. Yes the remote CSS issue is a different one (I think I already saw a corresponding issue). I plan to let this wait until the weekend and if noone intervenes, I'll merge then.
