### ISSUE TITLE
PHP: Guessing return type for function in documentation is not displayed correctly

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#5355]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Guessing return type for function in documentation is not displayed correctly

### How to reproduce

 - write a code
```php
function test(bool $a) {
    if ($a) {
        return 1;
    } else {
        return 'string';
    }
}

test(true);
```

- set the caret to `test` and press `Ctrl + Shift + Space` or click `Source -> Show documentation`
- the documentation will show `stringint` instead of `string | int` as the return type

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian 10

### JDK

OpenJDK 64-Bit Server VM 11.0.16+8-post-Debian-1deb10u1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by KacerCZ** [comment]
Reproducible.
Thanks for your report.
