### ISSUE TITLE
PHP: Unable to find declaration of interface for instanceof operator

### ISSUE THREAD

**Issue by qmegas** [apache/netbeans#5371]
### Apache NetBeans version

Apache NetBeans 16

### What happened

When using **instanceof** operator against the interface the Netbeans can't find the declaration of that interface (right click on interface name and choose Navigate -> Go To Declaration). However it works fine for classes.

I guess that IDE looking for the class only, however it should work fine with instances too. Reference to PHP documentation: https://www.php.net/manual/en/language.operators.type.php#example-124

### How to reproduce

Simple code to reproduce

```php
interface Foo
{
	public function test();
}

class Bar implements Foo
{
	public function test()
	{
		echo 1;
	}
}

$a = new Bar();

if ($a instanceof Bar) { //Do find declaration
	$a->test();
}

if ($a instanceof Foo) { //Can't find declaration
	$a->test();
}
```

If you Ctrl+Click on `Bar` in `$a instanceof Bar` line, the cursor will jump to `Bar` class declaration. However if you do the same for `Foo` interface, it won't work.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

16.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by junichi11** [comment]
Reproducible. Thank you for your report!!
