### ISSUE TITLE
PHPDoc works only partially for class variables (ex: string vs array)

### ISSUE THREAD

**Issue by tanzanite777** [apache/netbeans#5375]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Netbeans seemingly fails to parse class variable PHPDoc if it is 'array' type. Consequently, code completion and inspection (hold control key and hover - i believe it is the default binding) cannot show the content of the PHPDoc block comment.

Works correctly with everything else i can think of.

### How to reproduce

Create a php project (8.1) with this file:

```
<?php declare(strict_types=1);

class Test {
  /**
   * This text will show up correctly. Works with any other type, except array, that i can think of - not just 'string'.
   * @var string
   */
  static string $works;

  /**
   * This PHPDoc block comment is completely ignored and this text will not show up anywhere.
   * @var array
   */
  static array $snafu;
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

System: Windows 10 version 10.0 running on amd64; UTF-8; en_US (nb)

### JDK

Java: 18; Java HotSpot(TM) 64-Bit Server VM 18+36-2087

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

100% reproducible.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by troizet** [comment]
Similar behavior for the intersection type. 
I can make a fix for the intersection type and a workaround for the array, but I can't make the correct tests until #5426, #5427 are fixed.
