### ISSUE TITLE
PHP: Extra space after ternary operator in method call

### ISSUE THREAD

**Issue by KacerCZ** [apache/netbeans#5380]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Formatting ternary or null-coalescing operator inside method call adds extra space after expression and before closing parenthesis.

### How to reproduce

Create file with following contents:
```php
<?php

var_dump($a);
var_dump($a ? 1 : 2);
var_dump($a ?? null);
```
- Check option in formatting for PHP language Spaces > Within Parenthesis > Method / Function Call
- Reformat code twice
- There are two spaces before closing parenthesis instead of only one.

Actual result:
```php
<?php

var_dump( $a );
var_dump( $a ? 1 : 2  ); // <- Extra space before )
var_dump( $a ?? null  ); // <- Extra space before )
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 22.10

### JDK

OpenJDK 17.0.5

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by terax6669** [comment]
@junichi11 This has been untouched for almost a year, nobody is assigned to the issue.
I checked and this bug still exists in current versions.

**Comment by junichi11** [comment]
> Are you willing to submit a pull request?
Yes

So, nobody assign to it.

@KacerCZ I'll take over it if you don't fix it.

**Comment by KacerCZ** [comment]
@junichi11 I was investigating the issue but don't know how to fix it, so I didn't assign it to myself.

Only thing I found out, that there are probably some extra formatting tokens after ternary and null-coalescing operators, which cause the issue by adding extra space.

**Comment by junichi11** [comment]
OK, I'll assign this to me.
