### ISSUE TITLE
Netbeans dont Support WildFly 27

### ISSUE THREAD

**Issue by dyegocarmo** [apache/netbeans#5407]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Try to add WildFly 27 on Netbeans 16 and you get no imports of jakartaee.* to your project

### How to reproduce

Try to add WildFly 27 on Netbeans 16 and you get no imports of jakartaee.* to your project

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows

### JDK

JDK17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by emaphis** [comment]
Try Netbeans 17 RC2
https://ci-builds.apache.org/job/Netbeans/job/netbeans-TLP/job/netbeans/job/release170/11/artifact/

**Comment by neilcsmith-net** [comment]
See #5324 for NetBeans 17 release candidates.

**Comment by dyegocarmo** [comment]
No, doest work.;..
i try to use last RC and the WildFly 27 libs (of javartaee.*) are no import to use...

**Comment by dyegocarmo** [comment]
The basic problems is:
The netbeans not import the jakarta ee libs from wildfly27 dir.

**Comment by mbien** [comment]
this doesn't sound like a Wildfly specific issue. This sounds more like #4828

when I create a new web project using WF 27 and select Jakarta EE 10 I see the `jakarta.*` namespace in the new project template using NB 17rc3.

**Comment by asbachb** [comment]
@dyegocarmo could you validate if this issue is still persistent in NetBeans 18 so that we can close the issue.

**Comment by dyegocarmo** [comment]
Still... Doest work.

Em seg., 19 de jun. de 2023 14:31, Benjamin Asbach ***@***.***>
escreveu:

**Comment by asbachb** [comment]
It's not really clear what's the problem here.

I'm able to:
* Add Wildfly 27.0.1 in NetBeans 18
* Deploy a Jakarta EE application

So please add some more instructions, screenshots about the problem.

**Comment by dyegocarmo** [comment]
Doest Work!
Widlfly libs doest show....
you cannot add a session bean !
try!

**Comment by dyegocarmo** [comment]
![image](https://github.com/apache/netbeans/assets/60780092/f81919cd-818c-4e73-8f29-cb78e7dfd728)

**Comment by dyegocarmo** [comment]
![image](https://github.com/apache/netbeans/assets/60780092/a25915a8-65c4-42e3-8572-7bcb82d7b262)

**Comment by dyegocarmo** [comment]
![image](https://github.com/apache/netbeans/assets/60780092/5c8b8b40-34aa-4ff0-bfe0-214f0f9f4f04)

**Comment by dyegocarmo** [comment]
![image](https://github.com/apache/netbeans/assets/60780092/8703f764-2d32-4c0e-91c5-1a16efcb04da)
