### ISSUE TITLE
PHP: The intersection type specified in the phpDoc tag is rendered incorrectly 

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#5426]
### Apache NetBeans version

Apache NetBeans 16

### What happened

The `BaseClass&BaseInterface` intersection type specified in the phpDoc tag is displayed as `BaseClass|BaseInterface`.

### How to reproduce

 - write a code
```php
class newPHPClass {
    
  /**
   * Text
   * @var BaseClass&BaseInterface
   */
  public $test;
  
  /**
   * Text
   * 
   * @param BaseClass&BaseInterface $a
   * @return BaseClass&BaseInterface
   */
  public function test($a)
  {
  }
}
```

 - use autocomplete or `Ctrl + hover` to display the documentation.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 20.04.5 LTS

### JDK

OpenJDK 64-Bit Server VM 11.0.17+8-post-Ubuntu-1ubuntu220.04

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by junichi11** [comment]
Reproducible. Thank you for your report!
