### ISSUE TITLE
Go to Declaration is not working in .XHML JSF file  

### ISSUE THREAD

**Issue by IbrahimMSoliman** [apache/netbeans#5428]
### Apache NetBeans version

Apache NetBeans 16

### What happened

in XHML file (JSF jakarta.faces-4.0.0 ), autocomplete and "Go to Declaration" are not working when we use @Named (import jakarta.inject.Named;) while it is working with (import javax.inject.Named;).

### How to reproduce

1- create new web application (Jakarta ee9 or 10 with Netbeans 17RC3), 
2-create new XHTML File.
3-create new ManagedBean:
import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Named;

@Named
@SessionScoped
public class Test implements Serializable
{
private String name;
//create Setter/Getter for variable "name"
}
4-in XHML add #{test.name}
5-CTRL+ click on test to open "Test.java" file.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 Pro

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by m1kryn** [comment]
Hello,

Just confirming that I see this in Jakarta EE 10 and NetBeans 18 as well. 

Thanks,

Mike

**Comment by asbachb** [comment]
This was fixed with #6160
