### ISSUE TITLE
Please add "break on error" for PHP

### ISSUE THREAD

**Issue by ErikKrause** [apache/netbeans#5434]
### Description

xdebug supports break on error, warning, notice
See https://bugs.xdebug.org/view.php?id=711
Could this be implemented in netbeans? Works in VSCode...

### Use case/motivation

If a runtime error occurs, which would also causes an E_WARNING, E_NOTICE etc. error, it should be possible to break code execution on the line which caused the error.

### Related issues

didn't find any

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by tanzanite777** [comment]
This and more has also been supported for eons in Eclipse PDT. While warnings / errors you can make breakpoints yourself for (via the callback) - doing that for exceptions is impossible (so, there is no workaround). This is highly desirable for debugging as currently one can only set breakpoints in uncaught exception handler callback which is after stack unroll that destroys the error context - making breakpoints there fairly pointless.

So, i would like the "break on error" of the OP to be interpreted to also include the typical exception options.

**Comment by ErikKrause** [comment]
Is this anywhere on the roadmap? I consider this an essential feature, and I wonder why this hasn't been implemented long ago.
