### ISSUE TITLE
Found a bug in NetBeans

### ISSUE THREAD

**Issue by FongmwUM** [apache/netbeans#5451]
### Apache NetBeans version

NetBeans 12.5

### What happened

[bug log.txt](https://github.com/apache/netbeans/files/10683037/bug.log.txt)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Edition	Windows 11 Home Single Language Version	21H2 Installed on	‎28/‎05/‎2022 OS build	22000.1455 Experience	Windows Feature Experience Pack 1000.22000.1455.0

### JDK

Java 16

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Are you using NetBeans 16 or NetBeans 12.5?  If the latter, please update to a current version.  This is possibly a bug that was fixed.  Although the section of the log from `View / IDE log` would be useful.

Please also describe what you were doing when you experience the exception.  This is not enough information to proceed with.

**Comment by lkishalmi** [comment]
Well, I think the JDK is Java 16 and NetBeans is 12.5.

As @neilcsmith-net said, please use Apache NetBeans 16.

**Comment by asbachb** [comment]
```
<record>
  <date>2023-02-08T15:36:01</date>
  <millis>1675841761744</millis>
  <sequence>1029</sequence>
  <level>700</level>
  <thread>155</thread>
  <message>UI_USER_CONFIGURATION</message>
  <key>UI_USER_CONFIGURATION</key>
  <catalog>org.netbeans.modules.uihandler.Bundle</catalog>
  <param>Windows 10, 10.0, amd64</param>
  <param>Java HotSpot(TM) 64-Bit Server VM, 16.0.2+7-67, Java(TM) SE Runtime Environment, 16.0.2+7-67</param>
  <param>Apache NetBeans IDE 12.5</param>
  <param></param>
  <param>java.util.ConcurrentModificationException at java.util.ArrayList.forEach</param>
  <param>&lt;Please provide a description of the problem or the steps to reproduce&gt;</param>
  <param>*********</param>
</record>
```
