### ISSUE TITLE
Ubuntu 22.04 black screnn in first window

### ISSUE THREAD

**Issue by andrerezendebr** [apache/netbeans#5459]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Netbeans runs with black screen on Ubuntu 22.04, unable to see buttons and menus. I tested installing several different versions of OpenJDK up to 8 and even tested the netbeans 12 version. Ubuntu running in a recent virtualbox machine zero installation.

![Captura de tela 2023-02-09 163105](https://user-images.githubusercontent.com/10235465/217918315-e3727831-81ba-4b10-aa10-373ecc460c47.png)

### How to reproduce

Install netbeans dowloaded, apt or snap.

![Captura de tela 2023-02-09 163105](https://user-images.githubusercontent.com/10235465/217918255-8c4c5bc1-4c2a-4cd5-8cab-1e1f5d11db23.png)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 22.04

### JDK

OpenJDK 11

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Anything else

Doesn´t run nebeans installade by apt, snap, instalation script o zip file

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lalo-mx** [comment]
Have you tested with JDK 11?

**Comment by andrerezendebr** [comment]
Yes

Enviado do Yahoo Mail no Android 
 
  Em qui., 9 9e fev. 9e 2023 às 17:18, Eduardo ***@***.***> escreveu:   


Have you tested with JDK 11?

**Comment by neilcsmith-net** [comment]
Try the latest NetBeans with a recent JDK (ideally 17+) and share the log output.

Do you know if it's running X or Wayland in there?

**Comment by lkishalmi** [comment]
Well the attached picture says, that you are trying NetBeans 9.0 most probably using a zip or installer version, not the Snap Package. Remove the old NetBeans installation, and use at Least JDK 11, JDK 17+ preferred.

**Comment by asbachb** [comment]
Closing due to no further response. If the issue still persists with the suggested solutions feel free to reopen.
