### ISSUE TITLE
Version of JPA for Jakarta EE10 is 3.1, not 3.0

### ISSUE THREAD

**Issue by richard-grin** [apache/netbeans#5472]
### Apache NetBeans version

Apache NetBeans 17 release candidate

### What happened

In a Maven Web project genarated by NetBeans, the version for persistence.xml should be 3.1, not 3.0.

### How to reproduce

Create a new Maven Web project with NetBeans 17 RC1. The attribute of the tag persistence is 3.0. The same for the attribute xsi:schemaLocation.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Family 64-bit, version 21H2

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by asbachb** [comment]
This needs to be fixed in the used archetype.

see https://github.com/juneau001/jakartaee10-archetype/blob/main/src/main/resources/archetype-resources/src/main/resources/META-INF/persistence.xml

/cc @juneau001

**Comment by richard-grin** [comment]
Finally, I am not sure that it is required to modify the version, according to [https://github.com/jakartaee/persistence/issues/372](url)

**Comment by asbachb** [comment]
@richard-grin So from my understanding `NetBeans` creates the correct `persistence.xml` as there's no dedicated version per JPA release.

So I'd suggest to close the issue.
