### ISSUE TITLE
Not able to add Server

### ISSUE THREAD

**Issue by Ankit8572** [apache/netbeans#5494]
### Apache NetBeans version

Apache NetBeans 16

### What happened

i am not able install server and server in my project whenever I try to install sever on my project it shows Not a valid GlassFish Server installation. But Glassfish Server are already on the file location. 

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

window 11

### JDK

8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
would be good to try again on JDK 11 and NetBeans 17 which should be available in a week or two and report back with more details if it is still failing.

**Comment by mbien** [comment]
closing due to no response.
