### ISSUE TITLE
Changing language on mac netbeans quits unexpectedly, versions 12,6 and 13

### ISSUE THREAD

**Issue by Gil9091e10** [apache/netbeans#5506]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Netbeans closes unexpectedly when the keyboard language is changed, for example, if netbeans is executed, the keyboard language is in English. Netbeans later opens, the keyboard language is changed to Spanish, it closes unexpectedly.

It has happened to me using the 12.6 versions, I upgraded to version 13 thinking that it was an issue of version 12.6 but it still gives the same problem

### How to reproduce

- open netbeans
- Change keyboard language

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

MAC OX

### JDK

Java 11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
NetBeans 17 will be available in a week or two, lets check if its reproducible there, otherwise we can close this.
