### ISSUE TITLE
Failure on Refactor Move

### ISSUE THREAD

**Issue by ericjs** [apache/netbeans#5508]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Attempting a Refactor move operation throws an error suggesting I file a bug report:

Module Java Refactoring threw java.lang.IllegalStateException: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.getThrownTypes()" because "tree.meth.type" is null. Please report a bug against Java Refactoring module and attach your var/log/messages.log.

Attaching dump files suggested by messages in log
[Archive.tar.gz](https://github.com/apache/netbeans/files/10748706/Archive.tar.gz)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux, OpenSuse Tumbleweed, kernel 6.1.4-1-default x86_64

### JDK

openjdk 17.0.5 2022-10-18

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Every time.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ericjs** [comment]
Ok, with the broken test classes removed so as not to be in the picture, I still run into this error with renames. Everything built with no errors before attempting the move, including the class mentioned in the log. Again attaching log and dump.

[Archive (2).tar.gz](https://github.com/apache/netbeans/files/10750570/Archive.2.tar.gz)

**Comment by mbien** [comment]
sounds like the same as #3725
