### ISSUE TITLE
JSF Code Completition not work with jakarta 9.x or higher version

### ISSUE THREAD

**Issue by AngeloRubens** [apache/netbeans#5522]
### Apache NetBeans version

Apache NetBeans 17

### What happened

When setting the jakarta version from 8 to 9 in pom.xml the autocompletion in xhtml page doesn't work. The suspect is from jakarta 8 to jakarta 9 change the name space from javax.* to jakarta.*

### How to reproduce

Create a maven web project with jakarta 9.
Create a xhtml page
If you write #{application.} after dot press ctrl+space, the autocompletition but not suggest any completition.

Otherwise if you repeat the same steps but with jakarta 8 api, it's works fine. 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

all

### JDK

all

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by LouisCollet** [comment]
I have the same issue
see also https://github.com/apache/netbeans/issues/5470 
Have a nice day !

**Comment by rohandbhatte** [comment]
Using NB 17 and the issue persist. Making it hard to build application with new 

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="jakarta.faces.html"
      xmlns:f="jakarta.faces.core">

But autocomplete works with 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

**Comment by apapamarkou** [comment]
> However, the old names spaces allow us to enable the auto-completition.
Is this a workaround of yours or you just use the old versions?

**Comment by javierllorente** [comment]
Duplicate of #4828

**Comment by matthiasblaesing** [comment]
NB 19 got much improved Jakarta namespace support, given that the issue referenced as duplicate is resolved, this is also resolved.
