### ISSUE TITLE
Netbeans is ignoring my anti-aliased desktop font settings

### ISSUE THREAD

**Issue by localdevjs** [apache/netbeans#5526]
### Apache NetBeans version

Apache NetBeans 16

### What happened

I'm using Kubuntu 22.10, just upgraded to netbeans 16. My font settings in KDE have anti-aliased fonts turned off, and I've also updated "/etc/fonts/conf.d/" to have anti-aliasing turned off there.

Netbeans runs and shows anti aliased fonts in both the UI and the code editor.

I expect all fonts everywhere to be pixelated and ugly the way they should be on low dpi screens ;)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 22.10

### JDK

Several versions of oracle jdk

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Line 208 of the "netbeans" startup script explicity mentions KDE and overriding font settings using "useSystemAAFontSettings=on". This seems badly incorrect to me. I've set it back to "off" but that only fixes the source code editor, the rest of the UI is still using those blurry, headache inducing fonts.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by localdevjs** [comment]
Perhaps instead of forcing anti aliased fonts on the few of us who have an accesibility issue with anti-alisaed fonts on low dpi screens (it causes blurry eyes and headaches after 10 mins), maybe we can have a setting in the netbeans options that simply toggles the setting on or off everywhere (ui + code editor).

**Comment by mbien** [comment]
well. Nobody expected that there is a valid use case for having font AA turned off these days :)

The reason why the launcher script is handling this for KDE specifically was discussed in #5161. Short version is that the JDK doesn't provide good defaults on KDE still.

**Comment by neilcsmith-net** [comment]
Also #5161 is in NB17, so hopefully the results might still be a little better there.  It should be released in the next few days, but there's always the last release candidate at https://github.com/apache/netbeans/discussions/5324
