### ISSUE TITLE
Fix All Import suggesting unused import (wicket-bootstrap-extensions)

### ISSUE THREAD

**Issue by r1gm** [apache/netbeans#5537]
### Apache NetBeans version

Apache NetBeans 16

### What happened

When using Fix Import Feature

![image](https://user-images.githubusercontent.com/12691031/220011605-20df46f3-0eee-4ddc-8e8a-d9c20add4ae7.png)

this import suggestion always come out.

![image](https://user-images.githubusercontent.com/12691031/220011815-d9ddf239-fbe6-4b8e-81bf-212f1f8ada30.png)

### How to reproduce

See What happened

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

No

**Comment by mbien** [comment]
this would need a minimal reproducer. It is not clear what is wrong there.

**Comment by r1gm** [comment]
[ImportTestCase.zip](https://github.com/apache/netbeans/files/12309071/ImportTestCase.zip)

Hi, hope this help.

**Comment by mbien** [comment]
Thanks. So its ant-project specific and only happens in the test project when the language level is set to JDK 9+.

Interestingly, it does not offer the import if it has something else to fix. If i remove the BigDecimal import and use the action it will work fine, the second invocation will offer this weird class.
