### ISSUE TITLE
Possibly Incorrect Warning

### ISSUE THREAD

**Issue by CElliott316** [apache/netbeans#5544]
### Apache NetBeans version

Apache NetBeans 16

### What happened

The subroutine signature 'private static final returnType XXX()' evokes the warning 'private method XXXX is declared final'.  In an article published years ago, the reader was told that declaring a procedure final enabled the compiler to apply some optimizations that it could not OW make.  As far as I recall, there was no restriction on what methods could be made final.

### How to reproduce

```java
public final class SR {
  public static void main(String[] args) {
    sayHello();
  }
  private static final sayHello(){  // Putting the cursor on the underline evokes the warning
    System.out.println("Hello");
 }
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Microsoft Windows [Version 6.3.9600] = Windows 8.1, Pro, 64-bit

### JDK

Jdk-17.0.2, Wndows, X86

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
hi @CElliott316,

you sure you didn't forget the method return type?
`private static final sayHello() {`
->
`private static final void sayHello() {`

**Comment by CElliott316** [comment]
It is working correctly now:  None of my method declarations are underlined with a thin, sorta red line that displays a warning about private and final being an invalid signature combination.  Thanks for all your hard work.

 

Charles Elliott
