### ISSUE TITLE
Try with resources with "var" formatted with extra space before "var"

### ISSUE THREAD

**Issue by rturner-edjuster** [apache/netbeans#5546]
### Apache NetBeans version

Apache NetBeans 16

### What happened

This is almost the same issue as https://github.com/apache/netbeans/issues/3720.

When Java code is automatically formatting a try-with-resources statement, if the resource is specified with the type `var` instead of a specific type, an additional space is injected before the `var` keyword.

### How to reproduce

With a clean install of NetBeans 16 on MacOS 13.1, with the default Java code formatting settings (no changes to defaults after install, and no importing of previous version settings), and using a "new file", and no existing project:

1. Create a new Java file:
2. Replace all code with the following:
```
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class NewClass {

    public void test() throws IOException {
        try (var br = Files.newBufferedReader(Paths.get("test"))) {

        }
    }
}
```
3. Select "Format" from the "Source" menu and the code will be reformatted as:
```
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class NewClass {

    public void test() throws IOException {
        try ( var br = Files.newBufferedReader(Paths.get("test"))) {

        }
    }
}
```

Note the additional space in `try ( var`.

If you replace `var` with `BufferedReader`, the problem does not occur.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

Mac OS X version 13.1 running on aarch64; UTF-8; en_CA (nb)

### JDK

18.0.2; OpenJDK 64-Bit Server VM 18.0.2+9-FR

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by rturner-edjuster** [comment]
@neilcsmith-net I will also try with version 17 when the release is made available for general download -- seems imminent based on voting thread. I will provide an update here once I've done that.

**Comment by neilcsmith-net** [comment]
@rturner-edjuster we're just waiting for the webpages to be updated now.  The downloads are already published on ASF infrastructure at https://downloads.apache.org/netbeans/netbeans-installers/17/  And the community installers are also up at https://www.codelerity.com/netbeans/

**Comment by rturner-edjuster** [comment]
Looks like this issue is resolved in v17. My test case above, along with testing it on other code seems to work as expected. Closing.

**Comment by neilcsmith-net** [comment]
Thanks for confirmation @rturner-edjuster Strange, though!  Should have been fixed in NB16, and I'm not sure anything else changed in that code. Mind you, updated nb-javac could have fixed it, as that was the original cause of the issue anyway.
