### ISSUE TITLE
Install to drive other than C:\

### ISSUE THREAD

**Issue by jeffythedragonslayer** [apache/netbeans#5547]
### Description

Can there please be a way to install NetBeans on a Windows letter drive other that C?  I bought a new drive because I was out of disk space but can't install NetBeans on it.  Apache-NetBeans-16-bin-windows-x64.exe doesn't let me choose.

### Use case/motivation

I just want to install Netbeans

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
Try the community installers at https://www.codelerity.com/netbeans/ The Windows installer there should hopefully support this OK - it's built with NBPackage and InnoSetup.  And you'll get NetBeans 17 already.

No-one seems to be working on the NBI installers, and there are a bunch of issues with them including this.  Personally I'd like to see us move to NBPackage there too, as we already have for Linux packages.  The JDK-less option needs some work on the launcher ideally first though.
