### ISSUE TITLE
osx GPU usage

### ISSUE THREAD

**Issue by FlorianBruckner** [apache/netbeans#5555]
### Apache NetBeans version

Apache NetBeans 16

### What happened

I am on a MacBook Pro, the latest x86 one. But this has been an issue for me for years, also on previous MBP models and with all versions of NetBeans back to at least 8.2.

At times the infamous "kernel_task" kicks in. This usually indicates that the machine is too hot. For years I have learned to live with this issue never really made the connection that NetBeans, in any version, actually contributes to this significantly, but it is not obvious. When monitoring the CPU, while NetBeans can consume quite some CPU cycles, it has never been that of an outlier compared to other processed.

I recently added a nice tool that shows various system metrics: cpu usage, temperatures but also power consumption details. What you should know beforehand is that, in order to get a bit more runtime out of my mac before it got too warm, I modified the system to always use the iGPU. But you could observe the same behavior with the discrete GPU built into the machine.

The metric to watch for is the GPU power consumption. Without nebeans being open, power consumption on the GPU is about two watts:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/2104853/221095722-445cbd15-5e51-4bd6-bc1d-611055a25c91.png">

When Netbeans is doing "something", GPU power consumption raises to up to 20 watts:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/2104853/221095913-5e1ef735-09b9-43de-bb8f-5d80fb224835.png">

I believe to have tracked it down to the status component - when this is showing activity, GPU power consumption jumps to 20W:
![image](https://user-images.githubusercontent.com/2104853/221096176-b0d1d7ab-1b8f-42fc-a795-ac4906afc99f.png)

Minimizing the Netbeans window and power consumption drops to the baseline again. Just having another window on top of Netbeans doesn't change power consumption.

Just as an observation, back in the days when Netbeans could run with either Java6 or Java8 (this must have been 7.2), performance of Netbeans (especially graphics) have been excellent with Java6, but seriously degraded with Java8, especially on large displays. It may be related, but not necessarily.

### How to reproduce

On your mac:
(1) install stats
(2) configure it to show temperatures and power consumption
(3) Start netbeans
(4) observe power consumption of GPU
(5) Let Netbeans do something, like running an application
(6) observe power consumption of GPU

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

OSX

### JDK

java 8, 11, 17 (all amazon corretto)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
Well, try to change the Look and Feel and see if that makes any difference. Check the native Mac Look and Feel.

**Comment by FlorianBruckner** [comment]
Just tried, it was using the Mac Look and Feel and I switched to Metal - CPU power consumption has not changed.

**Comment by FlorianBruckner** [comment]
This may actually not be a Netbeans issue, but a Swing one.

I have been using this piece of sample code here:

https://docs.oracle.com/javase/tutorial/uiswing/examples/components/ProgressBarDemoProject/src/components/ProgressBarDemo.java

This is as basic as it will get and I really cannot believe what I am seeing here.

The progress bar is created with a range from 0 to 100:
        progressBar = new JProgressBar(0, 100);

It starts eating GPU as soon as the value is not 0 or 100. The power drawn from the CPU according to the tool I am using depends on the size of the JFrame. When the JFrame is just tiny, my GPU consumption delta is about 3 watts from baseline. when the JFrame is maximized, the delta is up to 17 watts.

While looking at power consumption, the task to update progress was not running, so the application was basically idle.

I have been running this on latest Java 8 (i know, ancient), but as this correlates to Netbeans GPU power consumption across 8, 11 and 17 I guess this may be unrelated to the Java version being used.

As I said, I am very confused by this result and would ask someone to verify these findings. It may very well be something specifc for my machine or the way I am doing measurements.

**Comment by FlorianBruckner** [comment]
I should add that I am seeing this just in GPU power consumption and not in activity monitor GPU usage.

**Comment by DevCharly** [comment]
Don't have a MBP with a discrete GPU. Seems not occur with the iGPU.

I wonder whether this effect also occurs with FlatLaf?

You could also try a different JDK distro to exclude the possibility that something is wrong in amazon corretto.

**Comment by FlorianBruckner** [comment]
I am pretty convinced now that what I am seeing is not caused by NetBeans.

It appears to be caused by implementation details in AquaProgressBarUI. In the version I looked at, it starts a timer when the progress is not 0 or 100% and does a JComponent.repaint() for each timer iteration. By contrast, the BasicProgressBarUI does this only when the progress is indeterminate. I guess AquaProgressBarUI does this beause the progress bar used to have a sort of "glowing" effect in the past, this may be a leftover from this.

The repaint() then appears to be causing "something" in the OGL render pipeline that, under certain conditions that I do not understand, causes to put load on the GPU. Interestingly, this is not shown in Activity Monitor as GPU usage, just the power consumption goes up. Which I would say is correct looking at temperatures measured by the machine and my lap temperature sensor.

So, not a NetBeans issue and thus closing here.
