### ISSUE TITLE
Git missing password textbox

### ISSUE THREAD

**Issue by quantrpeter** [apache/netbeans#5563]
### Apache NetBeans version

Apache NetBeans 17

### What happened

missing password textbox for git

<img width="573" alt="image" src="https://user-images.githubusercontent.com/50471577/221359586-f9a962d9-9225-4ec0-ad5f-3f6dee7f1c87.png">

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

MacOS Montetry 12.6.3 (21G419)

### JDK

"19.0.2" 2023-01-17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
please provide steps to reproduce this issue
