### ISSUE TITLE
Maven fails to build project

### ISSUE THREAD

**Issue by KoviBilumina** [apache/netbeans#5571]
### Apache NetBeans version

Apache NetBeans 17

### What happened

I'm running NetBeans with Java 11:

Product Version: Apache NetBeans IDE 17
Java: 11.0.16; OpenJDK 64-Bit Server VM 11.0.16+8
Runtime: OpenJDK Runtime Environment 11.0.16+8
System: Linux version 5.19.0-32-generic running on amd64; UTF-8; sl_SI (nb)
User directory: /home/gregor/Apps/netbeans/USERDIR/170
Cache directory: /home/gregor/Apps/netbeans/CACHEDIR/170

I also have a Maven project that still uses Java 1.7. When I try building it I get:
cd /home/gregor/tmp/MilkyWay.default/MilkyWay-util; JAVA_HOME=/home/gregor/Apps/java/170 M2_HOME=/home/gregor/Apps/java/maven/363 /home/gregor/Apps/java/maven/363/bin/mvn --batch-mode --batch-mode install
Error injecting: org.netbeans.modules.maven.event.NbEventSpy
java.lang.TypeNotPresentException: Type org.netbeans.modules.maven.event.NbEventSpy not present

Whole Exception in attached bug.log file.
[bug.log](https://github.com/apache/netbeans/files/10841608/bug.log)

### How to reproduce

I'm not sure how.

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

Ubuntu 22.04.2 LTS

### JDK

11.0.16; OpenJDK 64-Bit Server VM 11.0.16+8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

I've been using the same user and cache directories as with NetBeans 16.

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Looks related to #5548 Not sure if there's a workaround for NB17?  cc/ @mbien

**Comment by mbien** [comment]
This issue will likely "fix" itself since NB 18 will bundle a javac which is based on JDK 20 which doesn't support 1.7 anymore - so it won't work due to other reasons :)

You could try to set `-T 1` as maven flag which should trigger the fallback mode of the output window and might make it work in NB 17 at least.

**Comment by KoviBilumina** [comment]
Using `-T 1` did fix the issue.
So what you are saying that after the end of May I won't be able to use NetBeans for my projects? At least the ones based on Java 1.7.

**Comment by mbien** [comment]
You would have to use an older version of NetBeans for projects which use JDKs which are end of life, or upgrade to a supported version - JDK 8 will stay a while.

https://inside.java/2022/09/26/quality-heads-up/ more info about JDK 20 dropping support for 7

**Comment by mbien** [comment]
I forgot to mention: NB 18 will also likely bundle maven 3.9+, which also doesn't support 1.7 anymore.

good to see that the workaround is working, closing this issue
