### ISSUE TITLE
Exception while running Maven project

### ISSUE THREAD

**Issue by kovica** [apache/netbeans#5584]
### Apache NetBeans version

Apache NetBeans 17

### What happened

I have a Maven project based on Java 1.7. Running a class with main method produces Exception. Whole stack trace is in bug.log file.
[bug.log](https://github.com/apache/netbeans/files/10859924/bug.log)

### How to reproduce

Have a Maven based Java 1.7 project and run class with main method

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

Ubuntu 22.04.2 LTS

### JDK

11.0.16; OpenJDK 64-Bit Server VM 11.0.16+8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

`-T 1` that you see when running Maven is because of #5571

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
the world moved on. The java compiler and maven 3.9 dropped support for EOL Java 7.
