### ISSUE TITLE
PHP heredoc parsing crashes editor

### ISSUE THREAD

**Issue by fglueck** [apache/netbeans#5585]
### Apache NetBeans version

Apache NetBeans 17

### What happened

The code parsing in a complex heredoc works wrong.
If inside a heredoc a method call with a second here/nowdoc parameter the parser/syntax highlighter will hang/crash.

### How to reproduce

Use follow code:

```
   <?php
    echo <<<HTML
      <span><label for="{$from}">{$this->caption[$key]}</label>
        {$this->element()->select("bp{$postfix}", $this->get_opt($value), $value)->label($this->caption[$key]??'', $this->title[$key]??'')->on('change', <<<'X'
				 ... some code ....
                 X)}
      </span>
      HTML;
```

This is a extract with reduced code. If you change <<<'X' to <<<X it is the same behaviour. But with " or ' it works.

If you open the code as file, you can see the last line (HTML;) will have a wrong color. Not the same then the opening <<<HTML.

The editor is now not usable ( after HTML; ), You can't edit code with wrong syntax highlighting. So be carefull.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

18.0.1.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Product Version: Apache NetBeans IDE 17
Updates: NetBeans IDE is updated to version [NetBeans 8.2 Patch 2](http://wiki.netbeans.org/NetBeans8.2PatchesInfo)
Java: 18.0.1.1; Java HotSpot(TM) 64-Bit Server VM 18.0.1.1+2-6
Runtime: Java(TM) SE Runtime Environment 18.0.1.1+2-6
System: Windows 10 version 10.0 running on amd64; UTF-8; de_DE (nb)

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Reproducible. Thank you for reporting it.

**Comment by junichi11** [comment]
@fglueck Can you create a simple example that can run?

**Comment by junichi11** [comment]
#### Simple reproducible example:

```php
<?php

class T {

    public function test(): string {
        return "test method";
    }

    public function test2($param): string {
        return $param . PHP_EOL;
    }
}

$t = new T();
echo <<< HTML
    <span>{$t->test()}</span>
    {$t->test2(<<< X
        something 
        something
    X)}
    HTML;
```
