### ISSUE TITLE
Problem creating and loading a new project with Gradle v8

### ISSUE THREAD

**Issue by JNightRide** [apache/netbeans#5610]
### Apache NetBeans version

Apache NetBeans 17

### What happened

When I create a new gradle v8 project, the project is created, however it doesn't load the project itself, throwing the following message "**Could not run build action using connection to Gradle install...**"

![Captura de pantalla de 2023-03-04 20-44-59](https://user-images.githubusercontent.com/97632588/222972893-ad12edba-d7d0-45ae-92f9-04923c53e8d4.png)

Tampoco se puede resolver con la opción "**Resolve Project Problems**".

![Captura de pantalla de 2023-03-04 20-45-25](https://user-images.githubusercontent.com/97632588/222973147-cf922373-76e0-4a74-a8c0-0c15fbca34fb.png)

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

Linux - Debian Bullseye v11.6

### JDK

OpenJDK - 11.0.18 2023-01-17

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

**Comment by lkishalmi** [comment]
Raised a PR for netbeans-tools repo: https://github.com/apache/netbeans-tools/pull/62

Once merged, I'd roll out another Snap package, so this one would be fixed.
