### ISSUE TITLE
Unexpected java.lang.IllegalArgumentException: Key contains code point U+0000

### ISSUE THREAD

**Issue by BruceKHaddon** [apache/netbeans#5633]
### Apache NetBeans version

Apache NetBeans 17

### What happened

[messages.log](https://github.com/apache/netbeans/files/10924329/messages.log)

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

Windows 10 Pro, version 21H2, build 19044-2694, Intel i7 x64 16.0 GB

### JDK

openjdk-19.0.1_windows-x64_bin.zip

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time when run, but not when run in debug.

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
```
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.apache.tools.ant.module.bridge.impl.BridgeImpl$PostRun
java.lang.IllegalArgumentException: Key contains code point U+0000
	at java.prefs/java.util.prefs.AbstractPreferences.get(AbstractPreferences.java:291)
	at org.apache.tools.ant.module.api.IntrospectedInfo$3.load(IntrospectedInfo.java:681)
	at org.apache.tools.ant.module.AntSettings.getCustomDefs(AntSettings.java:119)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl$PostRun.run(BridgeImpl.java:443)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```
looks like there are invalid characters in a config file, the exception is in JDK code, this comment explains it:
https://github.com/openjdk/jdk/blob/f813dc71836e002814622fead8a2b0464b49c83a/src/java.prefs/share/classes/java/util/prefs/AbstractPreferences.java#L118-L123

**Comment by BruceKHaddon** [comment]
Michael,

Do you have any idea which config file? It must be the same file in both 16 and 17.

NetBeans 15 did not show this problem, and when I first saw this in 16 I uninstalled that and reinstalled 15. The problem was still not there in 15, but was there again when I changed back to 16.
I had hoped the problem was just with 16, but it persists in 17, so it must be some config file that came with 16 and has been carried forward to 17.

Regards,  Bruce


________________________________
Dr. Bruce K. Haddon
1506 Chambers Drive<https://www.google.com/maps/search/1506+Chambers+Drive?entry=gmail&source=g>
+1 303/499 6240
Boulder, CO 80305-7002
***@***.******@***.***>

"Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."—Henri Poincare

**Comment by mbien** [comment]
I don't know unfortunately, but a similar issue was posted here: #5147

**Comment by BruceKHaddon** [comment]
Michael,

Yep! The same issue, exactly.

I have installed every release of NetBeans since 3.0, and this issue only started with 16.

Regards, Bruce


________________________________
Dr. Bruce K. Haddon
1506 Chambers Drive<https://www.google.com/maps/search/1506+Chambers+Drive?entry=gmail&source=g>
+1 303/499 6240
Boulder, CO 80305-7002
***@***.******@***.***>

"Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."—Henri Poincare

**Comment by mbien** [comment]
well, resetting the config will solve the problem for you, but I would be curious if it is again the same file which is corrupted, or if it is just a random anomaly.

Could be worth trying to scan all property files for that code point

**Comment by lkishalmi** [comment]
Were you using JDK 8 as NetBeans Runtime recently?

You may be seeing: [NETBEANS-3284](https://issues.apache.org/jira/browse/NETBEANS-3284)

**Comment by BruceKHaddon** [comment]
Laszlo,

Not since Java 9 was released.

But it seems worth a try. Which “userdir” would that be?

Regards, Bruce
