### ISSUE TITLE
NetBeans IDE processes do not terminate, and cannot be cancelled.

### ISSUE THREAD

**Issue by BruceKHaddon** [apache/netbeans#5634]
### Apache NetBeans version

Apache NetBeans 17

### What happened

On any execution of a project (run, debug, javadoc) the process does not end. The only way to end the processes is to close the IDE.
![Screenshot 2023-03-08 123855](https://user-images.githubusercontent.com/102705941/223826246-c1546764-b5b2-47d1-b589-d60f4c3ef28f.jpg)
![Screenshot 2023-03-08 123855](https://user-images.githubusercontent.com/102705941/223826279-b4a8e4ea-178f-4e90-9a11-6f6687e7450a.jpg)
![Screenshot 2023-03-08 123628](https://user-images.githubusercontent.com/102705941/223826297-e895fc89-3d01-4952-9399-bfdce77e5070.jpg)

### How to reproduce

Compile and run anything.

This problem was not present in NetBeans 15 but was/is present in NetBeans 16 and 17

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Windows 10 Pro, version 21H2, build 19044-2694, Intel i7 x64 16.0 GB

### JDK

openjdk-19.0.1_windows-x64_bin.zip

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time.

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
what is the exception?

**Comment by BruceKHaddon** [comment]
Michael,

There is no exception. The processes just keep adding up as they are run, and when the attempt is made to select and cancel them, nothing happens when clicking on the x (the entry does not go away, and the process is still there).

The only way to terminate those processes is to exit NetBeans, then answer the question (twice) of do you want to terminate these processes.

Regards, Bruce


________________________________
Dr. Bruce K. Haddon
1506 Chambers Drive<https://www.google.com/maps/search/1506+Chambers+Drive?entry=gmail&source=g>
+1 303/499 6240
Boulder, CO 80305-7002
***@***.******@***.***>

"Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."—Henri Poincare

**Comment by mbien** [comment]
I mainly asked since I see a red error notification on the screenshot you posted.

What happens if you kill your program by pressing the stop button in the output window?

**Comment by BruceKHaddon** [comment]
Michael,

That red error notification is the one from the other report submitted (the one with the “unexpected error”) for which I forwarded the log file.

Clearing that notification has no effect on the “processes-still-running” issue.

Regards, Bruce

BTW, do you have idea of when the copy-and-paste issue will be fixed. I teach and am forever attempting to copy snippets from code to emails and other documentation, or the other round, or trying to copy-and-paste class files from one project to another (the workaround for this last one is to use “Copy” in “Refactor”). Copy-and-paste of code within NetBeans is OK.


________________________________
Dr. Bruce K. Haddon
1506 Chambers Drive<https://www.google.com/maps/search/1506+Chambers+Drive?entry=gmail&source=g>
+1 303/499 6240
Boulder, CO 80305-7002
***@***.******@***.***>

"Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."—Henri Poincare

**Comment by mbien** [comment]
i see, thanks, so you say stopping your program via the stop button on the output window does also not work?

regarding the copy and paste issue:
we don't have enough contributors who use windows, I don't even have windows installed anywhere right now. This issue is also not always reproducible - so I can't really say when someone will start another attempt to fix it.

but going through old mails, e.g https://lists.apache.org/thread/0r9qm9rkmvl6nxs5zcyr4145xrfwbbq3

you could try setting:
`-J-Dorg.netbeans.NbClipboard.level=FINEST`
or
`-J-Dnetbeans.slow.system.clipboard.hack=false `
or
`-J-DTopSecurityManager.disable=true`
to your netbeans.conf and check if it has any effect.

**Comment by lkishalmi** [comment]
Sad but true, the best workaround for the Copy+Paste issue is  not using Windows.

**Comment by BruceKHaddon** [comment]
Dear Laszio,

Not a solution.

I teach, and 99% of my students use a Windows-based laptop.

I sometimes get a student using a Mac (with MacOS) and only one time in
a decade have I had a student using Linux on a desktop machine. This is
because students are both beginners, and quite usually of very modest means.
Students also take other courses, where the tools and programs they need are
Windows-based so there is no way for me to ask students to acquire another
machine, and learn to use some Unix-derived system (that takes more
understanding than they have when starting in the computing world).

So, by saying, “not using Windows,” is virtually equivalent to saying, “don’t
use NetBeans.” Do not get me wrong. I have used many IDE’s, and in fact at
one time was an evangelist for NetBeans when employed by Sun
Microsystems. It is probably the easiest to learn of all the “industrial grade”
IDEs. (But even working for Sun, the “enemy” of Microsoft, demonstrations
of NetBeans were most often made on Windows machines, at the request
of potential customers—who may have been only later converted to Solaris.)

So, the copy-and-paste problems cannot be regarded as a non-issue by
dismissing the world’s use of Windows! I regard such a suggestion as being
unresponsive. You may have intended the response to be humor, but it
is a serious problem for serious users (and probably future proponents
of the use) of NetBeans.

Regards, Bruce K. Haddon

p.s. Why is Windows the problem? I have many other applications that work
quite well using copy-and-paste on Windows, and I also have Java applications
of my own that use the JDK copy-and-paste software, and they also work exactly
as expected. Is NetBeans trying to do something clever (like caching) with
copy-and-paste? It really is a mystery (and it is a more recent phenomenon).

________________________________
Dr. Bruce K. Haddon
1506 Chambers Drive<https://www.google.com/maps/search/1506+Chambers+Drive?entry=gmail&source=g>
+1 303/499 6240
Boulder, CO 80305-7002
***@***.******@***.***>

"Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."—Henri Poincare

**Comment by mbien** [comment]
@BruceKHaddon I don't think the "switch to linux/mac" was actually meant seriously (but please switch to linux :)). Point is: nobody of us uses it which means the motivation is low to fix this and there are extra steps involved to even reproduce it.

NB is developed in the open and relies on contributions, any dev on windows can take a look at it and open a PR. I also linked a thread where users/devs tried narrow down the problem and recommended JVM options. So have you tried those?

Also, lets not derail this issue completely. This is issue is not about copy and paste.

**Comment by lkishalmi** [comment]
Well, I've said workaround and sad. Members of the team put considerable amount of time/effort, trying to figure out how to fix that. We have failed so far.

Surprisingly adding: `-J-Dorg.netbeans.NbClipboard.level=FINEST` to the command line was the most stable way to avoid the problem. I guess it's a weird timing issue between the OS and the JVM.

**Comment by BruceKHaddon** [comment]
Laszlo,

My apologies. I guess I am sensitive to the Windows/Non-Windows issue.

As mentioned, I worked for Sun in various roles, mostly customer-facing, and consequently as a matter of course had to use Windows, although I did have Solaris as an alternative boot on my laptop (rarely used). This was at a time when the official Sun (McNealy) policy was that having Windows on a Sun-provided machine was (theoretically) a firing offense. Prior to working for Sun, I had used Windows, VAX VMS, Solaris, Unix 7, IBM OS, plus at least 4 OS’s that I had written or supported myself (as well as several other lesser-known operating systems), so apart from the convenience these days of using Windows and the needs of my students, I am reasonably agnostic to the debates, other than getting annoyed when getting mixed into such debating situations.

Anyway, I shall try the command line suggestion.

Thanks for the support,

Bruce

**Comment by neilcsmith-net** [comment]
> Point is: nobody of us uses it which means the motivation is low to fix this and there are extra steps involved to even reproduce it.
> 
> NB is developed in the open and relies on contributions, any dev on windows can take a look at it and open a PR.

With the risk of taking this further off-topic, this is not entirely true!  I'm certainly motivated to fix, both for NetBeans and platform applications, and have tried to look at and reproduce this on numerous occasions.  I have _never_ managed to reproduce following any of the steps outlined.  Any dev on Windows looking and opening a PR isn't realistic right now.  @BruceKHaddon let's continue and follow up on the dev@ list or on #3962

**Comment by neilcsmith-net** [comment]
Which build system are you using?  I see the exit dialog after building or running Gradle projects on Linux.  But only once, and I don't see the progress handles still active during use of the IDE.  I suspect this might be partly caused by the Gradle daemon process(es) but I haven't managed to confirm that completely - killing the Gradle daemon does sometimes stop the dialog from appearing.

**Comment by ibrayock** [comment]
I have the same issue with both Netbeans 17 & 18. Any update on this issue ? 
Thanks

**Comment by BruceKHaddon** [comment]
Yes, indeed. This issue causes me to have to reboot NetBeans after about 20-30 invocations
of build, clean and build, run, or debug. Even if a process is manually terminated, it stops
running, out the process still exists and is listed when NetBeans is closed.

I have students using NetBeans. I cannot explain this behavior to them. This is in
urgent need of fixing.

On a similar note, the reported problems with copy and paste are also a problem
for students. If I give them a snippet to use, they cannot copy and paste that into
any project, nor can they copy and paste a snippet to email me with a question.
I have other Java programs (of my own) that use the clipboard, and they work.
The problem appears to lie completely with NetBeans.


________________________________
Dr. Bruce K. Haddon
1506 Chambers Drive<https://www.google.com/maps/search/1506+Chambers+Drive?entry=gmail&source=g>
+1 303/499 6240
Boulder, CO 80305-7002
***@***.******@***.***>

"Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."-Henri Poincare

**Comment by ibrayock** [comment]
I am not using Netbeans as a student but for an application based on Netbeans Platform. Any update would be more than welcome.

**Comment by neilcsmith-net** [comment]
@BruceKHaddon @ibrayock this issue is still labelled `pending-response` because a number of questions that have been asked have not been answered as yet.

**Comment by Chris2011** [comment]
> Which build system are you using? I see the exit dialog after building or running Gradle projects on Linux. But only once, and I don't see the progress handles still active during use of the IDE. I suspect this might be partly caused by the Gradle daemon process(es) but I haven't managed to confirm that completely - killing the Gradle daemon does sometimes stop the dialog from appearing.

What about this one?

**Comment by Chris2011** [comment]
My two cents here, sometimes the cancel button works, sometimes not. Doesn't matter what I did. Sometimes it is the Background Scanning progress. Sometimes it is the Git Refresh Indices and sometimes others. All of them shows the dialog "You will be canceling it, do you want to?" And when I hit cancel sometimes nothing happens. I didn't dive deep into it but the only solution for me was just restart NetBeans and hoping that this is not coming back again. If it is a fresh start from my Laptop everything works fine, after hours work working than it happens. I will try to find more info for it.

**Comment by ibrayock** [comment]
> Which build system are you using? I see the exit dialog after building or running Gradle projects on Linux. But only once, and I don't see the progress handles still active during use of the IDE. I suspect this might be partly caused by the Gradle daemon process(es) but I haven't managed to confirm that completely - killing the Gradle daemon does sometimes stop the dialog from appearing.

I am using Windows 10 Enterprise (x64) with maven 3.8.1.

**Comment by ibrayock** [comment]
> My two cents here, sometimes the cancel button works, sometimes not. Doesn't matter what I did. Sometimes it is the Background Scanning progress. Sometimes it is the Git Refresh Indices and sometimes others. All of them shows the dialog "You will be canceling it, do you want to?" And when I hit cancel sometimes nothing happens. I didn't dive deep into it but the only solution for me was just restart NetBeans and hoping that this is not coming back again. If it is a fresh start from my Laptop everything works fine, after hours work working than it happens. I will try to find more info for it.

For me, the stop button is never working. I have to close Netbeans and start again

**Comment by BruceKHaddon** [comment]
Folks,

If it helps, my configuration is:

Product Version: Apache NetBeans IDE 17
Java: 19.0.1; OpenJDK 64-Bit Server VM 19.0.1+10-21
Runtime: OpenJDK Runtime Environment 19.0.1+10-21
System: Windows 10 version 10.0 running on amd64; UTF-8; en_US (nb)
User directory: C:\Users\bkh\AppData\Roaming\NetBeans\17
Cache directory: C:\Users\bkh\AppData\Local\NetBeans\Cache\17

The problem of a process not terminating is seen whether JavaFX is
enabled or not.

When a compile or running program terminates, the progress bar
stops showing "progress", but a running process remains.

It is possible to cause an executing compile or running program by use of the
the X button on the progress bar (bottom right), and get the pop-up asking
whether you want to cancel, and with a Yes answer, the execution stops, but
there is still left a running process.

When NetBeans is closed, the warning of these running processes appears
in a pop-up with the processes listed. If the "Exit IDE" button is used,
the NetBeans window disappears, but leaves another pop-up with a repeat of the
same request, see below.

***@***.***


________________________________
Dr. Bruce K. Haddon
1506 Chambers Drive<https://www.google.com/maps/search/1506+Chambers+Drive?entry=gmail&source=g>
+1 303/499 6240
Boulder, CO 80305-7002
***@***.******@***.***>

"Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."-Henri Poincare

**Comment by neilcsmith-net** [comment]
@BruceKHaddon there are at least 3 possible build systems in NetBeans for Java (and I'm assuming these are Java projects).  Please confirm what build system you're using, and ideally share one of the projects to this issue, as well as how it was created (wizard type, etc.). Also check `View / IDE log` and see if there's anything peculiar in there when the processes are stuck.  Thanks!

**Comment by BruceKHaddon** [comment]
Neil,

The build system is Ant.

The most recent log files are attached (what is "peculiar" in this context).

I have a number of projects where I run the compiled classes as programs outside
the IDE. These terminate quite normally.


________________________________
Dr. Bruce K. Haddon
1506 Chambers Drive<https://www.google.com/maps/search/1506+Chambers+Drive?entry=gmail&source=g>
+1 303/499 6240
Boulder, CO 80305-7002
***@***.******@***.***>

"Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."-Henri Poincare

**Comment by BruceKHaddon** [comment]
Neil,

Project that behaves as described (export file attached).


________________________________
Dr. Bruce K. Haddon
1506 Chambers Drive<https://www.google.com/maps/search/1506+Chambers+Drive?entry=gmail&source=g>
+1 303/499 6240
Boulder, CO 80305-7002
***@***.******@***.***>

"Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."-Henri Poincare

**Comment by mbien** [comment]
> Doesn't matter what I did. Sometimes it is the Background Scanning progress. Sometimes it is the Git Refresh Indices and sometimes others. ... And when I hit cancel sometimes nothing happens. 

well this isn't useful since those task have completely different implementations. The task has to support cancellation. The button is just a button which tells the task to cancel. Cancelling a thread is always a best effort situation, you can interrupt it if it is blocking on IO or locks and when its not you hope that it runs into the next `if (cancelled) return` check. Thats it.

Cancelling a process, like a different JVM is again a completely different situation. So please be concrete here or nobody will be able to investigate this issue.

```java
public class Mavenproject2 {

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setSize(200, 200);
        frame.setVisible(true);
    }
}
```
I ran this on linux as maven project on JDK 20, pressed the stop button, closed NetBeans and everything shut down no questions asked.

**Comment by mbien** [comment]
> The build system is Ant.

thanks. just repeated the same test above in an ant project and it did work too. Is this a windows specific issue?

**Comment by mbien** [comment]
> Project that behaves as described (export file attached).

@BruceKHaddon this is not a mailing list, it is an issue tracker, we won't see any files.

**Comment by BruceKHaddon** [comment]
The program was a simple "Hello, World!" (one print statement) just to
show that the complexity of the project is not the issue.

**Comment by neilcsmith-net** [comment]
@BruceKHaddon I cannot replicate with either the ASF or Codelerity (community) installer using the default Ant project on Windows 11.  That's why the logs or actual project might be useful.  You can attach files to issues and comments in the GitHub UI.  You can't do it via email, and please don't reply to issues via email as it spams comments with a lot of useless text.

Can you also see if the community installer works for you.  That bundles a local JDK for the IDE, and I'm curious whether that also replicates what you're seeing on your system.

**Comment by ibrayock** [comment]
> @ibrayock OK, as you said you're using the platform I suspect it's still related to https://lists.apache.org/thread/6l3tg4brq4522gcmc956jjtj855p6710 Do you have the JavaFX support enabled in Tools / Plugins, or are you running the IDE on a JDK with that included? Also try excluding the html4j libraries from the platform application.
> 
> I'm not sure if this is the same as the original report, as it's very RCP specific.

I didn't have JavaFx support enabled in Tools / Plugins. I enabled it but still the same issue. I am using openJDK 17.0.7 with JavaFx included. There is no html4j dependency on my platform application. 
The issue is still existing

Thanks

**Comment by neilcsmith-net** [comment]
@ibrayock have you specifically excluded html4j from the platform as covered in that thread?

**Comment by ibrayock** [comment]
@neilcsmith-net Executing a dep tree with maven or looking under "Dependencies" drop-down list on Netbeans doesn't show any html4j dependency so I don't know where to exclude it since it's not there in the first place.

**Comment by BruceKHaddon** [comment]
[1060_01_ZAHelloWorld.zip](https://github.com/apache/netbeans/files/11748718/1060_01_ZAHelloWorld.zip)
[messages.log](https://github.com/apache/netbeans/files/11748720/messages.log)
[messages.1.log](https://github.com/apache/netbeans/files/11748746/messages.1.log)
[messages.2.log](https://github.com/apache/netbeans/files/11748767/messages.2.log)

Here are the files that I tried to send by email  (cannot use email in the 21st century?)
The sif file is a Netbeans export file with just a "Hello, World" program. On my machine, it
has the same behavior as all other projects (processes not terminating completely).

**Comment by neilcsmith-net** [comment]
@BruceKHaddon looking at the log I suspect this might be related to #5633 given the stack trace of that error in your log. There are lots of other messages around the classpath that seem suspect too. Have you tried the suggestion from that issue and deleted the userdir and cachedir (or renamed if you want to backup the configuration)?

**Comment by neilcsmith-net** [comment]
@BruceKHaddon you could also take a look at https://github.com/apache/netbeans/issues/6076#issuecomment-1593391874 and whether following that process fixes things for you.

**Comment by BruceKHaddon** [comment]
Michael,

Thank you for finding (and fixing) this problem (I have been restarting NetBeans
4 or 5 times a day to clean up non-terminating processes).

Have you any idea which release will have this bug-fix included?

Regards Bruce


________________________________
Dr. Bruce K. Haddon
1506 Chambers Drive<https://www.google.com/maps/search/1506+Chambers+Drive?entry=gmail&source=g>
+1 303/499 6240
Boulder, CO 80305-7002
***@***.******@***.***>

"Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."-Henri Poincare

**Comment by mbien** [comment]
the change does not fix the root of the issue since it is not known how the config files are getting corrupted on windows. It adds defensive measures to prevent the import of corrupted files into the next NB version and handles property files with invalid keys a bit better in some cases.

But to answer the question: the change should be in NB 19

You could reset the netbeans config which should fix this issue too.
