### ISSUE TITLE
No 17 version on 17 version

### ISSUE THREAD

**Issue by tbw777** [apache/netbeans#5639]
### Apache NetBeans version

Apache NetBeans 17

### What happened

1. New NB application
2. Go to module step 3
3. You cant select 17 version from [maven central](https://repo1.maven.org/maven2)

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

windows 10

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

![image](https://user-images.githubusercontent.com/15821889/223986127-f86f9710-b697-457b-96e8-71083399ad9a.png)
![image](https://user-images.githubusercontent.com/15821889/223986721-f3d84ab5-93e1-44b2-8b01-f8d03da7e66d.png)
![image](https://user-images.githubusercontent.com/15821889/223986822-c993c2fd-9870-449a-87eb-07e546abfcb5.png)

### Are you willing to submit a pull request?

No

**Comment by ebarboni** [comment]
I cannot reproduce. I have the RELEASE170 listed

**Comment by tbw777** [comment]
i have deinstalled 16nb before

**Comment by mbien** [comment]
the list is taken from maven central. Next time your index updates it should be in the list.
