### ISSUE TITLE
Error: Could not find or load main class

### ISSUE THREAD

**Issue by Jana2Shata** [apache/netbeans#5656]
### Apache NetBeans version

Apache NetBeans 17

### What happened

I used NetBEans on a previous Windows-enabled laptop, and it worked just fine. However, when I tried to install it on another Windows-enabled laptop too (using the absolute same steps), and created a new project (containig nothing but a "Hello World!" print statement), it keeps showing an error message when trying to run it: 
Error: Could not find or load main class
Command execution failed.

And when trying to build it:
No sources to compile

I tried renaming the package, renaming the class, selecting the main class from properties and creating a new main class but none of that worked.

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Windows11

### JDK

jdk1.8.0

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by wwilsonn91** [comment]
I can't reproduce this myself.

Did you structure the class correctly?
Is the package properly declared?
Is the "hello world" print instruction contained within a main method? ("public static void main(String[] args)" or "public static void main(String... args)"? Is such a method even declared?

**Comment by Jana2Shata** [comment]
First of all, thank you for helping!
And yes, everything is as you mentioned.  However, it appeared to be a problem related to the path. I changed the default source folder location and it somehow worked perfectly.
Again, thank you.

احصل على Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
