### ISSUE TITLE
"Open Project" does not work - no response, error reported

### ISSUE THREAD

**Issue by Herbert246** [apache/netbeans#5687]
### Apache NetBeans version

Apache NetBeans 17

### What happened

First a new simple "Hello World" project was created.
When trying to open an existing project nothing happens, an error is reported.
[messages.log](https://github.com/apache/netbeans/files/11015981/messages.log)
Perhaps the messages.log helps.

### How to reproduce

After starting Netbeans and opening 1 project, no other project can be opened - just no response when clicking the icon or typing the shortcut.
An error is reported immediately (see attached message.log).
[messages.log](https://github.com/apache/netbeans/files/11016040/messages.log)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Product Version: Apache NetBeans IDE 17 Java: 17.0.4.1; Java HotSpot(TM) 64-Bit Server VM 17.0.4.1+1-LTS-2 Runtime: Java(TM) SE Runtime Environment 17.0.4.1+1-LTS-2 System: Windows 11 version 10.0 running on amd64; Cp1252; de_AT (nb) User directory: C:\Users\Herbert\AppData\Roaming\NetBeans\17 Cache directory: C:\Users\Herbert\AppData\Local\NetBeans\Cache\17

### JDK

17.0.4.1; Java HotSpot(TM) 64-Bit Server VM 17.0.4.1+1-LTS-2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

The problem started after opening a larger number of projects (more than 30).
I closed the all but this did not help.
Even installing other versions of Netbeans did not help.
I previously uninstalled the old version and deleted the folders in the AppData directory.

### Are you willing to submit a pull request?

Yes

**Comment by neilcsmith-net** [comment]
Looking at the log, this seems to be a bug in the JDK.  Seems similar to eg. https://github.com/skylot/jadx/issues/1628

Can you try adding `-J-Djava.util.Arrays.useLegacyMergeSort=true` to the default options in `netbeans.conf` (or adding as an argument in the launch shortcut) and see if that fixes things.

**Comment by Herbert246** [comment]
I added -J-Djava.util.Arrays.useLegacyMergeSort=true to the default options in netbeans.conf and now it works as it should!
