### ISSUE TITLE
Java debug no longer works

### ISSUE THREAD

**Issue by OS4** [apache/netbeans#5691]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Selecting debug or run on a Java project no longer works. I've tried several OpenJDK and Oracle JDK platforms. Selecting run or debug does absolutely nothing.  

I notice that the indication of a file containing a main function has also disappeared, but don't know if this is related.

Product Version: Apache NetBeans IDE DEV (Build dev-c3d96a0a7209daf8d5c0ee963a3f1aae1a9c775c)
Java: 18.0.2-ea; OpenJDK 64-Bit Server VM 18.0.2-ea+9-Ubuntu-2
Runtime: OpenJDK Runtime Environment 18.0.2-ea+9-Ubuntu-2
System: Linux version 6.1.15-2-liquorix-amd64 running on amd64; UTF-8; en_GB (nb)
User directory: /home/owen/.netbeans/dev
Cache directory: /home/owen/.cache/netbeans/dev

### How to reproduce

Right click on a Java project and select Debug or Run

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

Ubuntu 22.10 on Intel i7 64 bit

### JDK

openjdk version "18.0.2-ea" 2022-07-19

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Occurs every time

### Are you willing to submit a pull request?

Yes

**Comment by lkishalmi** [comment]
Need more info. I could not reproduce this behavior.
