### ISSUE TITLE
Bug in Comments Block in Maven File

### ISSUE THREAD

**Issue by PortfolioDavidStump** [apache/netbeans#5715]
### Apache NetBeans version

Apache NetBeans 17

### What happened

If you have the following Code in your Maven File:
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgs>
                        <arg>--enable-preview</arg>
                    </compilerArgs>
                </configuration>
            </plugin>

And you try to comment this out using Block Comment as follows:

            
The Block Comment is disabled after the double dash in the arg statement so everything from enable-preview onwards becomes 'live' and makes the POM unprocessable by MAVEN.

The Resolution is to remove the -- from the Argument and the Block Comment works as expected and the POM file is processable again.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mac OS Monterey Version 12.6.3

### JDK

Oracle JDK 20 (jdk-20+36)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Replicable every time.

### Are you willing to submit a pull request?

No

**Comment by PortfolioDavidStump** [comment]
Should have added same problem also occurs with single In-Line Comment e.g.

 - Everything from enable-preview onwards becomes 'live'.

**Comment by mbien** [comment]
this is no bug, this is how the maven pom parser works. You get the exact same error from the command line:
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /tmp/mavenproject1/pom.xml: in comment after two dashes (--) next character must be > not e (position: END_TAG seen ...<compilerArgs>\n                    <arg>--e... @19:29)  @ line 19, column 29
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/tmp/mavenproject1/pom.xml) has 1 error
[ERROR]     Non-parseable POM /tmp/mavenproject1/pom.xml: in comment after two dashes (--) next character must be > not e (position: END_TAG seen ...<compilerArgs>\n                    <arg>--e... @19:29)  @ line 19, column 29 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
```
