### ISSUE TITLE
a way to disable tooltips inside the source editor

### ISSUE THREAD

**Issue by notzed** [apache/netbeans#5719]
### Description

When selecting a function variant for auto-completion a single-line toolip is shown above the current entry line, which purportedly shows the current argument bolded as the parameters are filled out.

I would like this to be able to be disabled, or significantly altered in implementation such as moving it to the status line at the bottom of the window.

### Use case/motivation

This behaviour is **infuriating**!  It partially covers up the 2 preceding lines of source which usually provide context for the function call so interferes with the coding process.

I never read it and I find myself pressing ESC hundreds of times a day, sometimes hundreds of times an hour, to be able to read the sourcecode it hides or simply to remove the visual distraction.

To access the information it is supposed to present I rather active the auto-complete popup manually afterwards.

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
hi @notzed 

this tooltip?


![param-tooltip](https://user-images.githubusercontent.com/114367/227808040-cf6a0522-cdd5-4182-8843-0d0128e945b5.png)

(ctrl+p)?

**Comment by notzed** [comment]
Sorry for the delay, yeah that's the one but I use C-SPACE to show the completion thing and docs.

Anyway I got so sick of it I finally wrote a patch for it:

https://github.com/apache/netbeans/pull/5897

**Comment by notzed** [comment]
Well I suppose that isn't quite the one, it's the one that shows just the selected method and it's current argument.

e.g.

![pain](https://user-images.githubusercontent.com/51409789/235269236-4781f27d-32eb-4d28-a02d-4177abbb4016.png)

@mbien : Sorry I tried to link the bug as per the example in [1] but that's obviously incorrect, and it's been so long i forgot how did it last time.

[1] https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74681408

**Comment by mbien** [comment]
@notzed all good. I linked the PR with the issue. I am not sure if you can even do that without having commit rights.

@Chris2011 sorry, I don't know what you are talking about :). The tooltip shows overloaded methods which are applicable to the context (based on which parameters are already set and where your cursor is).

**Comment by Chris2011** [comment]
Yes but NetBeans in general doesn't show them all at once, they show one implementation and then the hint "+ 8 Overrides" but I dunno which context and in which language support.

**Comment by Chris2011** [comment]
I need to check whether I see the documentation about the "x overrides available." could be that this is from an other IDE.
