### ISSUE TITLE
Support project specific formatting rules for Yaml 

### ISSUE THREAD

**Issue by stollr** [apache/netbeans#5726]
### Description

Currently one cannot define project specific formatting rules for Yaml:
![grafik](https://user-images.githubusercontent.com/1118790/227900641-7870ded8-ae43-41d8-8cca-a45686118302.png)

It would be nice if this could be added.

### Use case/motivation

Sompe projects use 4 spaces and some use 2 spaces for indentation.

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
yaml supports no formatting atm, see https://github.com/apache/netbeans/issues/4539

closing as duplicate
