### ISSUE TITLE
After attempting to get the maven index an error occurs, indexing fails and then restarts.

### ISSUE THREAD

**Issue by dat-linux** [apache/netbeans#5727]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Maven indexing starts, then throws an error, then restarts. 

### How to reproduce

Run Netbeans fresh. 

Create a new Netbeans Application project.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 20.04

### JDK

11

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Occurs every time. Maven indexing repeats and fails.

LOG: [https://pastebin.com/Cgp3isGJ](https://pastebin.com/Cgp3isGJ) 

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
looks like you have not sufficient storage to extract the index. Either in temp or in the netbeans cache.

NetBeans 18 will disable indexing completely in a low storage situation #5655 and also add more settings for the indexing features #5646.

**Comment by dat-linux** [comment]
I had 40GB space available. I monitored the disk, and it was nowhere near full at any time.

**Comment by dat-linux** [comment]
If you disable indexing it renders creating a Netbeans Application project (which is my goal) incapable.

**Comment by dat-linux** [comment]
/tmp is not on a partition, there is only one partition aside from root, and it has 40GB space available. I ran a clean on all temp files and folders and it makes no difference.

**Comment by dat-linux** [comment]
I'm using openJDK this is not "Ubuntu's build", it's just hosted in their repo.

**Comment by neilcsmith-net** [comment]
> Running it as non root would not permit access to /tmp in any case.

That's not true with a standard setup.  What capacity is left on `/tmp`?  IIRC Maven index extraction currently uses `/tmp` as well as the cache location.

> I'm using openJDK this is not "Ubuntu's build", it's just hosted in their repo.

That was a joke!  Have had multiple issues with the Ubuntu packages of OpenJDK in the past.

**Comment by dat-linux** [comment]
Not sure why it needs to do this, maven is supposed to be a convenience where you declare a dependency in the pom and maven downloads it as you need it.

**Comment by neilcsmith-net** [comment]
> /tmp is not on a partition, there is only one partition aside from root, and it has 40GB space available.

That implies that `/tmp` is _not_ on the partition with 40GB space available?!

**Comment by dat-linux** [comment]
Downloading, and then having to update a 2GB index (that unzips to goodness knows what size) every week is really inefficient.

**Comment by dat-linux** [comment]
I told you already /tmp is not on a separate partition.

**Comment by dat-linux** [comment]
It also takes a long time, like over ten minutes, and often stalls.

**Comment by mbien** [comment]
it doesn't download the whole index every week. That is done only once.

**Comment by neilcsmith-net** [comment]
> I told you already /tmp is not on a separate partition.

No, you said you had one partition _aside_ from root, and that has 40GB of space.  You did not say how much space was on the root partition, which is where I assume from what you said where `/tmp` is.

> If you disable indexing it renders creating a Netbeans Application project (which is my goal) incapable.

Just tested this.  Run through the wizard and use the `dev-SNAPSHOT` version for the NetBeans version.  Then open up the POM in the parent project and change `netbeans.version` to the required version, eg. `RELEASE170` for the latest.  Clean and build the parent project, then run the app project.

**Comment by mbien** [comment]
just as side note: linux does not have to put tmp on a physical partition to limit its size, tmp can be a simple file. I have 750GB free on home and tmp is set to 20GB - its not a partition in my case either.

Fact is that the JDK thinks you are running out of space somewhere which causes the index extraction to reset. The only two locations relevant for indexing is your tmp folder and the netbeans cache folder which is `/home/.cache/netbeans/17` in your case.

**Comment by dat-linux** [comment]
The project creation does not complete because it stalls on the indexing.

**Comment by mbien** [comment]
so, indexing shouldn't restart anymore
 - on failure, indexing will be disabled and has to be manually enabled again in the options
 - index size is now about half of the original size, and can be further reduced by enabling filtering #5922
 - since NB 19 will be able to use the latest maven-indexer library, we have more control over where files land. I changed it to download to temp, but extract directly to the cache folder. Not quite sure if this is a good idea but we will see.
 - some upstream optimizations are still pending, see comment https://github.com/apache/netbeans/issues/5809#issuecomment-1586041418

closing this issue. All this should appear for NB 19, most of it is testable via dev builds: https://github.com/apache/netbeans/#download

**Comment by mesykkor** [comment]
On Linux /tmp may be an in-RAM tmpfs, you may check by running mount (and grepping 'tmp'). You can also see how much RAM was allocated.
After several attempts to beat it by using a TMP, TMPDIR etc, I found how to pass to the IDE a JVM property:
**./netbeans -J-Djava.io.tmpdir=/var/tmp**
If there is enough space there it should work, just now downloading there....
