### ISSUE TITLE
"Forward" and "Back" actions binding to Mouse4 and Moune5 buttons

### ISSUE THREAD

**Issue by brainbreeze** [apache/netbeans#5728]
### Description

As with many other software, I expect the extra mouse keys (on the side) (Mouse4 and Mouse5) to mean back/forward.

### Use case/motivation

I look forward to being able to bind additional mouse buttons to certain actions. Or that the Mouse4 and Mouse5 mouse buttons will direct the courses forward/backward.
**This is normal and expected.**
This is much faster when inspecting a project.
Significantly faster than Ctrl+Alt+Left, Ctrl+Alt+Right, or other unexpected custom options.

### Related issues

Archived request with status "New":
https://bz.apache.org/netbeans/show_bug.cgi?id=70961

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Yes, would really like to see this myself.  I've opened a PR.  And yes, it's using the Keymap .. but so are the mouse wheel actions!

There should be a dev build from the PR soon, and some testing of the defaults would be appreciated.

**Comment by neilcsmith-net** [comment]
The dev build to test this is available at https://github.com/apache/netbeans/actions/runs/6150432871?pr=6434
