### ISSUE TITLE
[JS] Incorrect warning on class property declaration

### ISSUE THREAD

**Issue by qmegas** [apache/netbeans#5740]
### Apache NetBeans version

Apache NetBeans 17

### What happened

See example code:

```js
class Test {
	var1 = 123;
	var2 = this.var1;
}
```

On line 3 NetBeans show warning `The global variable "var1" is not declared`, however that is absolutely correct code, and varaible "var1" is the property of `Test` class.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

16.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
@qmegas please check PR #5995, which should fix this issue. A test build is available from the PR summary page:

https://github.com/apache/netbeans/actions/runs/5100679715

or directly via: 

https://github.com/apache/netbeans/suites/13194152319/artifacts/718900999

**Comment by qmegas** [comment]
@matthiasblaesing Confirm the fix
