### ISSUE TITLE
Plugin not building java project through proxy

### ISSUE THREAD

**Issue by FaiyazMujawar** [apache/netbeans#5771]
### Apache NetBeans version

Apache NetBeans 17

### What happened

I'm trying to use Apache Netbeans Java extension to run a spring boot application, with my machine protected by a VPN. When trying to run the application, I get the following error:
```
Warning: Maven is configured for a proxy 10.24.19.83:8080, but the system does not require a proxy for network connections. Proxy settings should be removed from user gradle.properties.
Update Maven configuration ?
```

The project is maven based and not on gradle.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windpws 10 Enterprise

### JDK

OpenJDK 17.0.1

### Apache NetBeans packaging

Apache VSNetBeans for VSCode

### Are you willing to submit a pull request?

No

**Comment by sdedic** [comment]
Please verify the connectivity at the moment the message appears. Google DNS address (8.8.8.8) is used with `ProxySelector` to detect a possible proxy. Also please look into the logfile for a possible error - from the description it seems that proxy was not detected, although it should be.

Ignore the message part with `gradle.properties` -- I've made a copypaste bug when copying messages from gradle to maven support, this should be already fixed now.
