### ISSUE TITLE
NbEventSpy : Unsupported major.minor version 52.0, creating Java Maven Enterprise Project with JDK 17 Jakarta 10 Glassfish 7.0.3

### ISSUE THREAD

**Issue by MauroBelardi** [apache/netbeans#5772]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Creating a new Java Maven Enterprise Project, I obtain:

Error executing Maven.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting: public void org.apache.maven.eventspy.internal.EventSpyDispatcher.setEventSpies(java.util.List)
  at ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  while locating org.apache.maven.eventspy.internal.EventSpyDispatcher

1 error
      role: org.apache.maven.eventspy.internal.EventSpyDispatcher
  roleHint: 
Caused by: Unable to provision, see the following errors:

1) Error injecting: public void org.apache.maven.eventspy.internal.EventSpyDispatcher.setEventSpies(java.util.List)
  at ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  while locating org.apache.maven.eventspy.internal.EventSpyDispatcher

1 error
Caused by: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.TypeNotPresentException: Type org.netbeans.modules.maven.event.NbEventSpy not present
  at ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  while locating org.apache.maven.eventspy.EventSpy annotated with @com.google.inject.name.Named(value=ide)

1 error
Caused by: Type org.netbeans.modules.maven.event.NbEventSpy not present
Caused by: org/netbeans/modules/maven/event/NbEventSpy : Unsupported major.minor version 52.0

### How to reproduce

Try to create a new Maven project "mavenproject1" from NetBeans 17 GUI: File > New Project... > Java with Maven > Enterprise Application > NEXT > GlassFish Server (v. 7.0.3) + Jakarta EE 10 + default (Create EJB Module, Create Web App Module, mavenproject1-ear > Finish

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 Pro, v. 22H2, build 19045.2728, Windows Feature Experience Pack 120.2212.4190.0

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Installer: Codelerity / Gj IT packages (https://www.codelerity.com/netbeans/), Windows (x86_64), https://github.com/codelerity/netbeans-installers/releases/download/v17-build1/Apache-NetBeans-17.exe

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
I can't reproduce the NbEventSpy problem. Class version 52 is Java 8, so I am not sure what is going on there. Have you changed something in the maven settings? E.g are you using a different maven version than the bundled one?

However, there is still an issue here since I am getting:
```
Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project mavenproject5: Unable to add module to the current project as it is not of packaging type 'pom' -> [Help 1]
```
the sub-projects can't add themselves to the parent. (tip: for debugging purposes disable "reused output tabs" in maven settings and run the wizard)

**Comment by neilcsmith-net** [comment]
> However, there is still an issue here since I am getting:
> 
> ```
> Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project mavenproject5: Unable to add module to the current project as it is not of packaging type 'pom' -> [Help 1]
> ```

Somehow forgot to comment that I saw that behaviour too when I was labelling / assigning.

**Comment by hello-earth-gh** [comment]
btw just in case someone stumbles on this, for reference, I got this error because were was a JAVA_HOME set to an old Java 7 installation somewhere in environment variables. I created a BAT file to reset it to at least Java 8
