### ISSUE TITLE
PHPunit 10 incompatibility

### ISSUE THREAD

**Issue by Max84** [apache/netbeans#5790]
### Apache NetBeans version

Apache NetBeans 17

### What happened

I'm trying to launch PHPUnit test with Netbeans.
My test works with phpunit 5.7 (yes, it's very old). Work = NetBeans launches the test, finds test, creates report.
With PHPUnit 10, Netbeans doesn't launch test and this error is displayed: Class NetBeansSuite cannot be found in C:\Program Files\NetBeans-17\netbeans\php\phpunit\NetBeansSuite.php

I have the same bug with Netbeans 12.4.

### How to reproduce

Create a PHP project, add a PHPUnit test, add PHPUnit to your NetBeans.
Just take care to phpunit version.
Run the test.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 2016

### JDK

16.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by KacerCZ** [comment]
Reproducible.
Thanks for your report.

Changes in PHPUnit 10 are breaking `NetBeansSuite.php` class for integration.
Method `suite()` is no longer called.

**Comment by KacerCZ** [comment]
Here is related commit: https://github.com/sebastianbergmann/phpunit/commit/36354a9cdc69ecabd20ac505b07541cfdde50aaa

It also added check that passed file defines `TestCase`.

**Comment by Max84** [comment]
@KacerCZ  @junichi11 @neilcsmith-net 
All my thanks for your works!
I'm looking forward to having NB18 :)
