### ISSUE TITLE
Verification in Plugin Portal not working

### ISSUE THREAD

**Issue by jkovalsky** [apache/netbeans#5806]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Plugin verifiers can no longer verify plugins due to an error which prevents the page with plugin verification requests to load. It only displays:

```
An error occurred
An error occurred during execution; please try again later.
No Exception available
```

### How to reproduce

With Plugin Portal Verifier privileges just try to open the link:

[https://plugins.netbeans.apache.org/verification/list](https://plugins.netbeans.apache.org/verification/list)

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

Linux Mint 21.1

### JDK

N/A

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

No

**Comment by jkovalsky** [comment]
@matthiasblaesing, could you please investigate this as soon as possible?

**Comment by geertjanw** [comment]
Confirmed, seeing the same message.

**Comment by matthiasblaesing** [comment]
There is a verification request without associated plugin version. I added a hotfix, that skips that entry, but there are other problems. I'm looking into it.
