### ISSUE TITLE
Unpacking index is extremely slow

### ISSUE THREAD

**Issue by webracer999** [apache/netbeans#5809]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Related bug: https://bz.apache.org/netbeans/show_bug.cgi?id=239915

I have the default value for updating maven index frequency of one week.
Every time it gets updated, the step "unpacking index" takes a lot of time - about 20 minutes. Also the fans are running at full speed.

### How to reproduce

Wait for the next weekly maven index update.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 22.10

### JDK

OpenJDK 20

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
hi @webracer999 

we are working on this, but it will take a bit till it makes it in.

#4999 would be a PR to watch out for. It is likely that we can make the index a bit smaller by using filters and improve extraction time a bit just by updating the dependencies (but this has to wait for now unfortunately).

There will be likely a setting for multi threading which should cut extraction time at least in half on most systems (my old i7 6700k extracts in 6 mins with that change). However, if you are having problems with spinning fans now, multi threading will make it worse (they will spin shorter though). Notebooks aren't that good for sustained load.

NB 18 will provide a setting to disable remote index extraction, while allowing to keep local .m2 scanning enabled (which is super fast). This might work pretty well for a lot of use cases. #5646 shows a screenshot of the new settings.

**Comment by webracer999** [comment]
Thank you @mbien for the information!

BTW I have an "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" (`/proc/cpuinfo`) and 16 GB RAM. My Thinkpad is 3 years old but I think it's not the worst hardware setup today.

I wasn't sure if it's still a known problem, because I found no issue on GitHub. So thank you for your detailed reply!

**Comment by mbien** [comment]
so, 4999 is merged (for NB 19). #5922 would be next. The workflow should produce a dev build linked from the summary page. Feel free to give it a try.

The initial indexing runs at about 5.5mins on my workstation with multi threading enabled (download not included, subsequent index updates are faster of course). But if you are traveling with your notebook I would turn indexing off once the initial index is built - everything will still work, just not quite up2date. If you forget, canceling indexing will pause it for a while (currently 2h).

There is now also a way to add a date cutoff filter for artifact information, aka: student mode (since who uses old libraries anyway)

**Comment by webracer999** [comment]
Thanks, I have tried the current master branch.
I can confirm that all of the CPU cores are being used. Initial indexing took about 14 minutes.
If I remember correctly, it took about 30 minutes in NB 17. But ...
It is difficult for me to measure. I have to use a stopwatch and keep an eye on the indexing status. Is there another way? Then I could give you a better statement.

But still, I think multithreading for indexing is a good thing. So I do not know if we need exact times.

**Comment by mbien** [comment]
> It is difficult for me to measure. I have to use a stopwatch and keep an eye on the indexing status. Is there another way? Then I could give you a better statement.

NB will print the total time spent to the log, but this includes download unfortunately which makes it not very useful for benchmarks. Both, download and extraction is done in maven-indexer which is not NB code, so I can't easily add more logging there. (would be nice, but is low prio for now - sorry)

some updates:
#5922 is now also merged which cuts index size almost in half

there are two upstream PRs pending:
https://github.com/apache/maven-indexer/pull/318 (should speed up incremental updates significantly)
https://github.com/apache/maven-indexer/pull/317 (some smaller optimizations)

**Comment by webracer999** [comment]
> NB will print the total time spent to the log, but this includes download unfortunately which makes it not very useful for benchmarks. Both, download and extraction is done in maven-indexer which is not NB code, so I can't easily add more logging there. (would be nice, but is low prio for now - sorry)

OK, thanks - it's not perfect, but a lot better than watching and stopping manually. :) I understand that's low prio for logging.

Thanks for the other info/updates!

**Comment by webracer999** [comment]
> [exec] INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: Indexing of central took 664,02s.

It took about 11 minutes for indexing for my system with master branch.

**Comment by webracer999** [comment]
NetBeans 18:
> INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: Indexing of central took 1284,06 s.

-> Master branch takes half the time. Thanks so far. :)

**Comment by mbien** [comment]
planning to close this issue with #6089 which should make incremental updates significantly faster as last piece of the puzzle.

**Comment by webracer999** [comment]
Yes, you can close this issue.
Thank you very much for your work!
