### ISSUE TITLE
not working properly. Buffering and not showing and working many more features like Build and run project, Add Glassfish Server etc 

### ISSUE THREAD

**Issue by ankush123github** [apache/netbeans#5833]
### Apache NetBeans version

Apache NetBeans 17

### What happened

not working properly. Buffering and not showing and working many more features like Build and run project, Add Glassfish Server etc 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows

### JDK

1.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by matthiasblaesing** [comment]
It is unclear what is the problem you are describing. I looks like you are unsatisfied with lots of things, but to help you need to identifiy the problem, describe what you see, and what you expect.
