### ISSUE TITLE
Compile on save not working

### ISSUE THREAD

**Issue by giusdiluca** [apache/netbeans#5839]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Hello,

while coding with Netbeans 17 it would be useful the IDE to compile on save the java  class modified.
Even if I have the check "Compile on save" on the project turned on, the class file is not compiled/update in the target folder after an edit/save of the interested java source file.

Could you please advise on that?

Many thanks
Giuseppe.

### How to reproduce

Create a maven java project, a java source file into it. 
Turn on the "Compile on save" option on the project.
Edit the java file and look that the class file is not updated into the target directory of the project unless you do a full build of the project.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

RedHat 7.7

### JDK

Java: 11; OpenJDK 64-Bit Server VM 11+28

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
I cannot reproduce this with 17 or 18-rc1 with a simple one file Maven project.  However we do have at least one duplicate report. Could you also try 18-rc1 see #5849 .  Let's ensure we still have the problem!

**Comment by lkishalmi** [comment]
Closing as no response in the last 6 months.
