### ISSUE TITLE
MacOS L&F in dark mode: Labels are hard to read

### ISSUE THREAD

**Issue by michbarsinai** [apache/netbeans#5861]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Opened NB 18 rc-1 on a Mac while in Dark mode. Using Mac OS X Look and feel. The labels on the trees are using white text (because of the system's dark mode) but the backgrounds are light (not brought from the system?). As a result, the text is hard to read.

![image](https://user-images.githubusercontent.com/1938468/233496059-ef338ea4-8acc-4d0d-8d09-ce9b72ed7e8b.png)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mac OS X 13.3.1 (22E261)

### JDK

openjdk 20 2023-03-21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Thanks for the report.  Please try FlatLaf Cupertino as an alternative.  FlatLaf is the default and recommended IDE look and feel.

**Comment by ctipper** [comment]
FWIW macos Aqua always does this, it was never adapted to dark mode. I don't know what solution is, I migrated my apps two years ago, it's to do with Aqua being integrated into JDK and Oracle's priorities.

**Comment by iajn** [comment]
Might be stating the obvious but the change was probably introduced by https://github.com/apache/netbeans/pull/5732 so if you  still want to use the Mac OS X look & feel like it was before you'd have to remove the -J-Dapple.awt.application.appearance=system option from the netbeans.conf file.

**Comment by DevCharly** [comment]
@iajn thanks for the hint. You're right. Just tested it.

The option `-J-Dapple.awt.application.appearance=system` affects colors in some components in "Mac OS X" look.

Should we revert PR #5732 for NB 18 ?

**Comment by neilcsmith-net** [comment]
> Should we revert PR #5732 for NB 18 ?

Well, that also fixed #4577 

IMO, this should stay - priority should be the default look and feel.

**Comment by DevCharly** [comment]
> IMO, this should stay ...

👍

If people use macOS dark mode, then they probably also use a dark L&F instead of the light "Mac OS X" L&F.
