### ISSUE TITLE
PHP - Latte templates plugin - Wrong escaping string parameter (syntax highlight)

### ISSUE THREAD

**Issue by zeleznypa** [apache/netbeans#5862]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Netbeans plugin for `latte` syntax show an error when the string parameter contains an escaped apostrof character.

<img width="555" alt="Snímek obrazovky 2023-04-21 v 8 12 03" src="https://user-images.githubusercontent.com/1191472/233554500-554a239e-c71f-4e02-b8ae-002c4e77dda8.png">

### How to reproduce

In the PHP Netbeans enable / install the built-in plugin (`tools > plugins > installed > Latte templates`)

<img width="889" alt="Snímek obrazovky 2023-04-21 v 8 15 05" src="https://user-images.githubusercontent.com/1191472/233555406-a3588fdc-ec8b-47ee-8cbe-767a2c9818d3.png">

Create new file `test.latte` and put the following code

```latte
<p>{_'text that contains an escaped \' character'}</p>

<p>{_'text that not contains an escaped problematic character'}</p>
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mac OS X version 10.16 running on x86_64; UTF-8; cs_CZ (nb)

### JDK

14.0.2; Java HotSpot(TM) 64-Bit Server VM 14.0.2+12-46

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

I want to, but I'm not a Java developer

**Comment by junichi11** [comment]
Reproducible. Thanks for reporting it.

**Comment by junichi11** [comment]
Documentation: https://latte.nette.org/en/tags#toc-translation

**Comment by zeleznypa** [comment]
@junichi11 Many thanks
