### ISSUE TITLE
gitignore shading not working on long name directories?

### ISSUE THREAD

**Issue by MarkRS-UK** [apache/netbeans#5874]
### Apache NetBeans version

Apache NetBeans 17

### What happened

A directory with a long name (40 characters) appears, in the project list, to be excluded from my git repository, although it isn't (the directory and its subdirectories and files have been included in both my local and remote [GitLab] repositories).

It is shown in the list as grey (excluded) rather than white (included).

This is the only directory structure in my project with such a long name.  All other directories and files in the project are correctly marked in the project list.

### How to reproduce

In a project with a git repository make a subdirectory with a short name and under it one with a long name (I don't know at what length this breaks down).

Use the usual entries in .gitignore to include the long named directory, eg

```
!/root/shortname
/root/shortname/*
!/root/shortname/name_at_least_forty_characters_in_length
```
Look at the projects list.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux Fedora 37

### JDK

java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
ok, closing
