### ISSUE TITLE
PHP: Documentation for methods and properties is not displayed when Ctrl + Shift + Space is pressed

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#5881]
### Apache NetBeans version

Apache NetBeans 18 release candidate

### What happened

Documentation for methods and properties is not displayed when `Ctrl + Shift + Space` is pressed

### How to reproduce

```php
class TestClass
{
    public $property;

    public function testFunction()
    {
    }
}

$test = new TestClass();

$x = $test->property;

$test->testFunction();
```
Case 1:
  - set the caret to `$test->property^` or `$test->testFunction^`
  - press `Ctrl + Shft + Space`
  - the documentation is displayed

Case 2:
  - set the caret to `$test->prop^erty` or `$test->testFun^ction`
  - press `Ctrl + Shft + Space`
  - documentation will not be displayed

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Debian 10

### JDK

OpenJDK Runtime Environment 11.0.18+10-post-Debian-1deb10u1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

The reason seems to be that the anchor is not calculated correctly
https://github.com/apache/netbeans/blob/a56df8c75784ea61c41c5e54f9d0dfd6d96a0ac5/php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion.java#L361-L364

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
cc/ @junichi11 can you take a look as this has been reported as a regression in 18-rc1 from 17 and see if it's something to address before release? Thanks!

**Comment by junichi11** [comment]
I'll look at it ASAP. Thanks!

**Comment by junichi11** [comment]
Reproducible. Thank you for reporting it. I'll fix it ASAP.

**Comment by troizet** [comment]
@junichi11 Tried rc2. Everything works. Thank you!

**Comment by junichi11** [comment]
Great to hear that. Thank you for your verification!
