### ISSUE TITLE
Netbeans is not working (flatpak)

### ISSUE THREAD

**Issue by ChrisToumparis** [apache/netbeans#5905]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Netbeans just shows white screen and close itself !

this is the only thing that appears in terminal:
Detected KDE; use explicit setting for font antialiasing (-J-Dawt.useSystemAAFontSettings=on)
WARNING: package com.apple.eio not in java.desktop

The normal version work good though

### How to reproduce

1) Open Konsole
2) Type: flatpak install flathub org.apache.netbeans
3) Type: flatpak run org.apache.netbeans

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

OpenSUSE Tumbleweed

### JDK

11

### Apache NetBeans packaging

Third-party package

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
we don't manage the NetBeans flatpak packages. Does the zip distribution of NB 18rc2 work for you?

**Comment by neilcsmith-net** [comment]
Please report at https://github.com/flathub/org.apache.netbeans/issues  Thanks!
