### ISSUE TITLE
support for CSS at-rule: @layer

### ISSUE THREAD

**Issue by lbuchs** [apache/netbeans#5918]
### Description

Netbeans should support CSS layers: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
At the moment there are errors occurring in a CSS file if you use layers.

### Use case/motivation

CSS Layers are now supported in every major browser. https://caniuse.com/mdn-css_at-rules_layer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
A fix is proposed as part of #6451. Please check it. Test builds are available:

- From the checks summary page: https://github.com/apache/netbeans/actions/runs/6190122968
- Or directly: https://github.com/apache/netbeans/suites/16181456062/artifacts/924240381
