### ISSUE TITLE
Javascript syntax parser: import.meta.url not recognised

### ISSUE THREAD

**Issue by excolo-rick** [apache/netbeans#5919]
### Apache NetBeans version

Apache NetBeans 17

### What happened

A javascript function call with `import.meta.url` as a parameter gets interpretted by the syntax formatter as an out-of-place `import` statement. This shows the js file as containing an error, even though it doesn't.

### How to reproduce

In a javascript file:
`(() => {})(import.meta.url);`

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Window 11

### JDK

18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mobegoulm** [comment]
Hi there, is this still on progress? Trying to develop a javascript/vue application on NetBeans and it shows many of exactliy this kind of errors.

**Comment by alexstanciu-1** [comment]
Hello,

import.meta.url / import.meta.resolve is the only way to solve some `path` issues.

Please prioritize this !

Thank you

**Comment by matthiasblaesing** [comment]
@alexstanciu-1 @excolo-rick @mobegoulm please check the changes proposed in #7211. These add support for the meta properties and code completion. 

A nightly build is available from the checks page: https://github.com/apache/netbeans/pull/7211/checks (see artifacts dropdown) or directly: https://github.com/apache/netbeans/suites/22276568166/artifacts/1372776118.

Please test that build it is available for the next 5 days.

**Comment by alexstanciu-1** [comment]
Hello
Thank you !

I have downloaded and tested 

Looks Ok! 

Regards,
Alex

**Comment by matthiasblaesing** [comment]
@alexstanciu-1 thanks for testing. I'll let the PR stay a few more days and test this some more in reality and will then merge. The fix will be in NB22.
