### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by maya667** [apache/netbeans#5920]
### Apache NetBeans version

Apache NetBeans 17

### What happened

<img width="960" alt="Annotation 2023-05-06 145436" src="https://user-images.githubusercontent.com/132763155/236630516-1b85ebcd-aee6-4a52-82a3-17b4d838e03d.png">

la palette a soudainement disparu , quand je veux rajouter un bouton ou autre cela m'indique une erreur sans pour autant me decrire l'erreur

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

jdk 20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by junichi11** [comment]
Please write in English.
Please give it an appropriate title. (please don't write just "bug")
