### ISSUE TITLE
NB 17 not detecting PHP Syntax Errors

### ISSUE THREAD

**Issue by impulsionjl** [apache/netbeans#5932]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Hi,

Upgraded from 11.2 today. And what a bad idea was it.

NB 17 not showing PHP syntax errors on save. 

- I first imported settings from 11.2;
- Then I uninstalled both;
- Then I reinstalled NB 17;
- Then I deleted local and roaming directories;

Computer rebooted for each step.

Netbeans still doesn't warn if there is syntax errors in php files. Impossible to work in these conditions.

It was working on any netbeans versions I had until now.

### How to reproduce

Something weird I've noticed. If i check anything in options->editor->hints->php then apply, it will highlights errors again. Then, on next file, again, it's not detecting errors.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

W11

### JDK

20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by impulsionjl** [comment]
[test.webm](https://github.com/apache/netbeans/assets/41991093/640584d7-e78f-44de-aaf5-ddb3cbe6c4f6)

**Comment by neilcsmith-net** [comment]
Please share any relevant parts of the IDE log - `View / IDE Log`.

Does the background scanning of projects in the video finish or is it stuck?

Please try 18-rc3 if you can - #5849 

cc/ @junichi11

**Comment by impulsionjl** [comment]
Thank you for replying.

I'll try 18. Meanwhile, few lines of log while opening, and editing, then check settings in options->hints:


Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 510,0MB maximum 8152,0MB
Non heap memory usage: initial 7,3MB maximum -1b
Garbage collector: G1 Young Generation (Collections=18 Total time spent=0s)
Garbage collector: G1 Old Generation (Collections=0 Total time spent=0s)
Classes: loaded=11179 total loaded=11179 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 34?186?883?072
INFO [null]: Total physical memory 34?186?883?072
INFO [org.netbeans.modules.php.editor.parser.GSFPHPParser]: Parsing of big PHP files enabled: false (max size: 5?000?000)
INFO [org.netbeans.ui.metrics.php]: Existing PHP project opened [frameworks: ].
INFO [null]: Last record repeated 2 more times.
INFO [org.netbeans.ui.metrics.projects]: USG_PROJECT_OPEN
INFO [null]: Last record repeated 2 more times.
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 0 ms.
INFO [org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater]: Resolving dependencies took: 33 ms
INFO [org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater]: Complete indexing of 0 binary roots took: 0 ms
INFO [org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater]: Indexing of: jar:file:/C:/Program%20Files/NetBeans-16/netbeans/php/docs/phpsigfiles.zip!/phpstubs/phpruntime/ took: 227 ms (New or modified files: 0, Deleted files: 0) [Adding listeners took: 0 ms]
INFO [org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater]: Indexing of: nbfs://nbhost/SystemFileSystem/PHP/RuntimeLibraries/ took: 38 ms (New or modified files: 0, Deleted files: 0) [Adding listeners took: 0 ms]
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.XMLDataObject@1bd74e49[MultiFileObject@2bb3ccea[Actions/Help/master-help.xml]]
INFO [org.netbeans.editor.BaseKit]: Null Action.NAME property of action org.netbeans.modules.groovy.editor.actions.FixImportsAction@62632e64
INFO [org.netbeans.modules.mercurial]: version: null
WARNING [org.netbeans.modules.options.editor.keymap.EditorBridge]: The action org.netbeans.modules.jshell.editor.RunScriptAction@65f27b17 doesn't provide short description, using its name.
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.BrokenDataShadow@529e70e5[MultiFileObject@bd35a0[Keymaps/NetBeans/D-BACK_QUOTE.shadow]]
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.BrokenDataShadow@28be2b4d[MultiFileObject@59dc9c6[Keymaps/NetBeans/OS-B.shadow]]
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.BrokenDataShadow@529e70e5[MultiFileObject@bd35a0[Keymaps/NetBeans/D-BACK_QUOTE.shadow]]
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.BrokenDataShadow@28be2b4d[MultiFileObject@59dc9c6[Keymaps/NetBeans/OS-B.shadow]]
INFO [org.netbeans.modules.subversion]: Finished indexing svn cache with 0 entries. Elapsed time: 0 ms.
log4j:WARN No appenders could be found for logger (nu.validator.source.LocationRecorder).
log4j:WARN Please initialize the log4j system properly.
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.netbeans.modules.cpplite.debugger [1.10 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.cpplite.editor [1.9 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.cpplite.project [1.9 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.cpplite.kit [1.9 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
INFO [org.netbeans.modules.git.status]: GitInterceptor.refreshTask: Scanning in progress, trying again in 10?000ms
WARNING [org.netbeans.modules.options.editor.keymap.EditorBridge]: The action org.netbeans.modules.jshell.editor.RunScriptAction@65f27b17 doesn't provide short description, using its name.
INFO [org.netbeans.modules.git.status]: GitInterceptor.refreshTask: Scanning in progress, trying again in 10?000ms

**Comment by impulsionjl** [comment]
And also a bunch of 

Adding a fold that is identical with another previously added fold from the same FoldManager is not allowed.
Existing fold: [tags] E2 <166462,167710>, desc='<.../>', hash=0x419dc53c, [166462, 167710] {166463, 167709}; FoldManager: org.netbeans.modules.csl.editor.fold.GsfFoldManager@26e62774
     New fold: [tags] E2 <166462,167710>, desc='<.../>', hash=0x7ef0a216, [166462, 167710] {166463, 167709}; FoldManager: org.netbeans.modules.csl.editor.fold.GsfFoldManager@26e62774

**Comment by junichi11** [comment]
@impulsionjl 
> Does the background scanning of projects in the video finish or is it stuck?

Which one?
Maybe, errors are not shown until the background scanning has finished.

> I'll try 18. Meanwhile, few lines of log while opening, and editing, then check settings in options->hints:

Are errors shown?
There are no strange logs for PHP.

> Then I deleted local and roaming directories;

Please check them again. (Help > About: user directory and cache directory)

**Comment by impulsionjl** [comment]
@junichi11
@neilcsmith-net 

Thank you for replying.

Opening projects seems stucked indeed. And I've noticed that it looks like happening with heavy projetcs (containing lots of files, including bunch of assets).

So I closed heavy projects, restarted IDE with 2 light projetcs. It opened projects, scanned background and checked for external changes: and then, when there is none progress bars pending, it seems it's working normally.

Nice to have this clue, thanks to you, but now how I can deal with heavy projects ? Should I limit the scan to certain extensions ? (Im not using github inside netbeans, so i don't need to check for changes on images, and assets). Or is this scan already limited to scripts and then what do you suggest ? I must insist on the fact that these heavy projects never "crashed" earlier versions of netbeans i've used (and i use it since 15 years). Im used to work with a bunch of projects opened, jumping from one to another.

**Comment by impulsionjl** [comment]
![100pcscan](https://github.com/apache/netbeans/assets/41991093/d613c21d-6926-4e84-af72-c72ed8c36aef)

100%, but not finishing and so errors are not highlighted (for all opened projects even if it's scanning one particular other project than the edited file)

**Comment by junichi11** [comment]
Unfortunately, I can say only "Please try to wait until it disappears" because I don't have a heavy project to reproduce it...

**Comment by impulsionjl** [comment]
@junichi11 and I did wait.... and indeed, finally the tasks were done (like 6-8 hours later, for one project). I thought it was just stuck on % value, but actually it did finish. You never edit on only one file at time, so I'm wondering if community would considere if it's possible to maintain basic syntax error detection without to finish scanning everything.  So I can close this, but improvable in next versions, i think. Thank you for paying attention
