### ISSUE TITLE
IDE finds an error if casting a variable in arrow function

### ISSUE THREAD

**Issue by 15god** [apache/netbeans#5933]
### Apache NetBeans version

Apache NetBeans 17

### What happened

![image](https://github.com/apache/netbeans/assets/117515234/7e5abf35-bc79-4238-83d2-c1abcba563a9)
I initiated a new laravel project through composer, but IDE started showing error in pre-generated function. If i remove casting, red squiglies disappear.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Win 10

### JDK

JDK 20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Please also write an example code to reproduce it. (not only the image)

**Comment by junichi11** [comment]
Reproducible. The cause is not an arrow function expression but an instanceof expression.

### Example code

```php
<?php
class Example {}
$test = "Example";
$a = new Example();
$boolean = $a instanceof ((string) $test); // error
var_dump($boolean);

```

Thank you for reporting it.
