### ISSUE TITLE
Excecution stops/shutdown after breakpoint step

### ISSUE THREAD

**Issue by marcello1960** [apache/netbeans#5940]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Suddenly (until yesterday no problems were encountered), after stopping on any breakpoint and following the step command, the program:

- crashes in the absence of a shutdown_function
- execute the shutdown_function if this has been set

The problem occurred with version 13, I installed version 17 but it persists
![2023-05-12 13_38_36-Window](https://github.com/apache/netbeans/assets/60887242/18ceca54-4d51-430d-84e2-1d38be75bb7c)

### How to reproduce

.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64; Cp1252; it_IT (nb)

### JDK

VM 15.0.1+9-18

### Apache NetBeans packaging

Apache NetBeans platform

### Anything else

I'm not sure how much I answered about the packaging in the previous question

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Could you write details with your exact steps?

e.g. 
#### Example code

```php
// example code
```

#### Steps to reproduce
1.
2.
3.

#### Actual result
something

#### Expected result
something

**Comment by marcello1960** [comment]
Thanks Junichi, in the meantime I updated Xdebug from version 2.9.8 to 3.1.6 and everything started working again, both in NetBeans version 17 and in 13.
