### ISSUE TITLE
Find Usages probably shouldn't separately report multiple usages from same line

### ISSUE THREAD

**Issue by janicki** [apache/netbeans#5953]
### Description

If I try Find Usages on say ObjectX, then every instance of "ObjectX x = new ObjectX()" will be listed twice in the results... Once for each usage of ObjectX.  While technically correct, it would probably be nicer (99% of the time?) to just coalesce repeated lines into one.

### Use case/motivation

It just seems redundant to list the same lines twice.  Even though each resulting match highlights a different part of the line in each result, I think it would be more useful to highlight both parts in one result.

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
I don't really see the benefit to deduplicate results of "find usages". A usage is a usage, no matter how the code is formatted - if a method is called 3 times I would expect 3 results in that list. Selecting individual results will jump the cursor to the right place, deduplication would remove information and complicate things.

The result will also depend on what you had selected, this is for the `JFrame` class:
![image](https://github.com/apache/netbeans/assets/114367/3d132b5c-9bea-49f4-88f2-022e261eb286)

this would be for the `JFrame()` constructor which shows only one hit:
![image](https://github.com/apache/netbeans/assets/114367/fe411060-a8d7-4cb0-bf8b-6f9729b33673)
