### ISSUE TITLE
Laravel detect

### ISSUE THREAD

**Issue by Guilherme-fagundes** [apache/netbeans#5965]
### Description

When using larabel, the blade template is not supported, and the facades options do not appear in the controllers. I believe this could be implemented or improved

### Use case/motivation

I want netbeans to be on the same level as phpstorm

### Are you willing to submit a pull request?

No

**Comment by Chris2011** [comment]
For blade there is a plugin for this: https://github.com/haidubogdan/netbeans-php-blade-plugin we should treat this like other PHP frameworks to add blade support just if we enable this framework. But this should be part of a laravel plugin.

**Comment by parallels999** [comment]
It would be great if it had full laravel support

**Comment by Chris2011** [comment]
@parallels999 someone needs to define what full laravel support means. If you want to help to make Apache NetBeans better, please form a document what helps all of us to dive into it. As I mentioned above there is already a plugin for this, with good support (I guess) please test it and make tickets at the other repo if it is related to the plugin.

**Comment by parallels999** [comment]
The plugin only handles `blade` files, for example, on laravel there is view paths point separated `view('root.folder.blade_file'`)
There is no `Ctrl + Click`, no folder autocomplete, for that path, because it is only an string for netbeans
The blade plugin does a great job with these types of paths, but only on blade directives on a blade file
![image](https://github.com/apache/netbeans/assets/109294935/c5372b24-707f-4d02-9bf7-6e079d48291a)
>please form a document what helps all of us to dive into it

That would be the main problem, I don't think anyone has enough knowledge to do it. If I had more knowledge I would be happy to do it.

**Comment by parallels999** [comment]
`CTRL + Click` 
![use](https://github.com/apache/netbeans/assets/109294935/a4bbb4e4-05a0-47ca-a95f-d910b74ba930)
autocomplete paths
![screenshot-view](https://github.com/apache/netbeans/assets/109294935/0f8b74c3-b85f-4fdb-866f-0a56e38accc6)
config paths, there is files with array, so they are array assoc paths [laravel/laravel/config](https://github.com/laravel/laravel/tree/11.x/config)
![screenshot-config](https://github.com/apache/netbeans/assets/109294935/e80457b8-e0f7-4ef7-91d0-9612e0fd61ae)
route paths, laravel has route files, [laravel/laravel/routes](https://github.com/laravel/laravel/tree/11.x/routes)
![screenshot-route](https://github.com/apache/netbeans/assets/109294935/b7456e82-dda3-42e2-a3cd-41265fe525f8)
Translations and translation parameters, [Laravel/laravel/lang/en](https://github.com/laravel/laravel/tree/9.x/lang/en)
![screenshot-trans](https://github.com/apache/netbeans/assets/109294935/a35b8101-88ce-4f52-bd78-3e3662654c9b)

**Comment by Chris2011** [comment]
@parallels999 this would be better to make a discussion ticket. Or, we also have a wiki, just create an account and add a detailed paper there: https://cwiki.apache.org/confluence/display/NETBEANS/Feature+Request+Outlines

**Comment by Chris2011** [comment]
Closing this in favor of this discussion: https://github.com/apache/netbeans/discussions/7231
