### ISSUE TITLE
The code completion function does not work correctly

### ISSUE THREAD

**Issue by dil-it21** [apache/netbeans#5974]
### Apache NetBeans version

Apache NetBeans 17

### What happened

When I'm writing code, I try to autocomplete method names or function calls, but when I press ENTER, instead of autocomplete, even what I had already started to write is deleted, I went to version 17 because something similar happened in version 16 , but instead of deleting what I had written, it would hang and I had to kill the process from the terminal.

![image](https://github.com/apache/netbeans/assets/85707367/0c91400f-f086-49e2-81ed-5df06ab63b7b)

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Ubuntu 18.04, 64 bits

### JDK

11.0.19; OpenJDK 64-Bit Server

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I just use the Dracula for Netbeans theme

### Are you willing to submit a pull request?

Yes

**Comment by junichi11** [comment]
@dil-it21 Please write an example code to reproduce it.

**Comment by mbien** [comment]
closing due to no response. Feel free to reopen if there is a reproducer available and it still is reproducible on a current version of NB.
