### ISSUE TITLE
Wrong CSS errors & hints

### ISSUE THREAD

**Issue by selcox** [apache/netbeans#5975]
### Apache NetBeans version

Apache NetBeans 17

### What happened

The following CSS outputs hints and errors that are not correct.
Especially in responsive design constructs like min(), max() and calc() are
often used. There one overlooks gladly genuine problems.

.hints {
  container-type: size;
  container-name: name;
  user-select: none;
  font-size: min(25px, 26px);
  margin: 0px 0px min(5px, 0.26cqh);
  margin-top: max(2px, 10%);
  aspect-ratio: 146/102;
  hyphenate-character: auto;
  hyphenate-limit-chars: 10;

  --height: 10px;
  height: calc(100% - var(--height));
}

@container name (max-height: 780px) {

}

### How to reproduce

Set the given CSS in a css-file and open it in netbeans.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64; Cp1252; de_DE (nb)

### JDK

15.0.1; Java HotSpot(TM) 64-Bit Server VM 15.0.1+9-18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
A fix is proposed as part of #6451. Please check it. Test builds are available:

- From the checks summary page: https://github.com/apache/netbeans/actions/runs/6190122968
- Or directly: https://github.com/apache/netbeans/suites/16181456062/artifacts/924240381
