### ISSUE TITLE
Unable to create new Java Frontend Application with Maven on macOS aarch64

### ISSUE THREAD

**Issue by davidbitterlich** [apache/netbeans#5985]
### Apache NetBeans version

Apache NetBeans 17

### What happened

I tried to create a new Java Frontend Application project with Maven
Therefore I navigated to the menubar and selected File -> New Project, here I selected Maven and then Java Frontend Application

Since openjfx was not installed before, NetBeans installed it and ran into an issue, so I restarted the IDE. Afterwards I opened NetBeans again and the element was enabled now so I wanted press "Next", but it crashed again. I've found a messages.log which I attached here.
[messages.log](https://github.com/apache/netbeans/files/11553544/messages.log)

### How to reproduce

Simply create a new Java Frontend Application with Maven.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS 13.4 aarch64

### JDK

11.0.19, OpenJDK, aarch64

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I took a look into the messages.log myself and found out that it crashed because it could not load the library /Users/dbitterlich/.openjfx/cache/17/libprism_es2.dylib

I was curious about that circumstance and opened my Terminal. The file exists:

> ls -al ~/.openjfx/cache/17
> total 376
> drwxr-xr-x  4 dbitterlich  staff     128 24 Mai 12:22 .
> drwxr-xr-x@ 4 dbitterlich  staff     128 24 Mai 12:22 ..
> -rw-r--r--  1 dbitterlich  staff   81232 24 Mai 12:22 libprism_es2.dylib
> -rw-r--r--  1 dbitterlich  staff  108176 24 Mai 12:22 libprism_sw.dylib

So I thought about what else could be the cause for this issue and checked if the file is a valid library using file:

> file ~/.openjfx/cache/17/libprism_es2.dylib 
> /Users/dbitterlich/.openjfx/cache/17/libprism_es2.dylib: Mach-O 64-bit dynamically linked shared library x86_64

Obviously we have an x86_64 only library while my machine's architecture is aarch64, so the JDK is also running as aarch64. This is most probably the reason why NetBeans cannot handle the library and unexpectedly crashes.

The crash is that deep that I even cannot reopen the new project wizard dialog again and I am forced to restart the IDE

### Are you willing to submit a pull request?

No

**Comment by rkraneis** [comment]
Would updating the dependencies in the POM help? See https://stackoverflow.com/questions/71630758/problem-with-javafx-and-apple-m1-silicon-chip-and-intellij-error-loading-li for reference.

**Comment by neilcsmith-net** [comment]
cc/ @dukescript @jtulach 

Personally I'd fix this by removing that wizard from the IDE in its entirety, as it's been the cause of so many issues.

**Comment by neilcsmith-net** [comment]
This is probably broken across the board in NB18 right now because of #6004 too.

**Comment by matthiasblaesing** [comment]
@neilcsmith-net I doubt OpenJFX as bundled with NetBeans can currently work on mac OS aarch64. The binaries seem to build for amd64 (aka x86-64).

I'm not a mac user, so don't know how "good" rosetta is, but a setup with an aarch64 JDK and amd64, transcoded, JFX sounds like a broken combination.

From my POV we need to:
a) enhance the module system to enable filtering modules based on supported processor architecture
b) introdocue at least two new OpenJFX wrappers: `libs.javafx.macosx.aarch64` and `libs.javafx.linux.aarch64`

**Comment by neilcsmith-net** [comment]
@matthiasblaesing yes. I added the labels because it's broken on every OS in NB18 right now, and because the wizard should behave nicely and bail out cleanly whenever its assumptions can't be met.

**Comment by matthiasblaesing** [comment]
@davidbitterlich could you please have a look at #6028? That PR is intended to make it possible to run OpenJFX on mac OS on Aarch64. There is a test build available from the PR check summary page:

https://github.com/apache/netbeans/actions/runs/5171203812

or directly via:

https://github.com/apache/netbeans/suites/13362800800/artifacts/730940759
