### ISSUE TITLE
Modal dialog with wrong parent can lock up the application

### ISSUE THREAD

**Issue by rkeen-siemens** [apache/netbeans#5987]
### Apache NetBeans version

Apache NetBeans 17

### What happened

`DialogDisplayerImpl.notify` sets the wrong parent when the currently active window is a modal dialog. When running with [FlatLaf providing window decorations](https://www.formdev.com/flatlaf/window-decorations/#enable_disable_linux) via `setDefaultLookAndFeelDecorated` on Linux, this allows the user to click the previously active modal dialog to bring it to the front due to [JDK-8306001](https://bugs.openjdk.org/browse/JDK-8306001).

### How to reproduce

Start a platform application with the following run before creating any UI (e.g. in an override of `ModuleInstall.validate`):

```java
JFrame.setDefaultLookAndFeelDecorated(true);
JDialog.setDefaultLookAndFeelDecorated(true);
```

Then from within an open model dialog invoke another using `DialogDisplayer.notify` and click the originally open dialog. This dialog will come to the front and if the new dialog is completely hidden there is nothing the user can do but kill the application.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

Yes

**Comment by neilcsmith-net** [comment]
Please check with NetBeans 18 - there have been some changes in this area eg. #5280 Be good to see if the issue is still relevant.

**Comment by rkeen-siemens** [comment]
Thanks for pointing that out @neilcsmith-net, but the change to `DialogDisplayerImpl` was cosmetic and the same issue persists. I'll have a pull request with a fix soon.

**Comment by neilcsmith-net** [comment]
Yes, the changes directly in `DialogDisplayerImpl` were cosmetic, but there were other changes recently in parenting logic that I thought might be relevant.  They at least need to be consistent, and ideally in one place.

There's no need to open an issue if you have a PR ready anyway.  Let's take the conversation there.
