### ISSUE TITLE
Javadoc http server fails to load

### ISSUE THREAD

**Issue by cbm64chris** [apache/netbeans#5990]
### Apache NetBeans version

Apache NetBeans 18 release candidate

### What happened

Right-clicking upon a dependency the View Javadoc context menu option displays;

![image](https://github.com/apache/netbeans/assets/20171342/5f11db97-af5e-4a86-a918-42ca2689507a)

Looking at the IDE log, I'm seeing;
```
java.lang.IllegalStateException: Unable to create the directory [/tomcat.8082] to use as the base directory
	at org.apache.catalina.startup.Tomcat.initBaseDir(Tomcat.java:868)
	at org.apache.catalina.startup.Tomcat.getServer(Tomcat.java:652)
	at org.netbeans.modules.httpserver.HttpServerModule.buildServer(HttpServerModule.java:179)
[catch] at org.netbeans.modules.httpserver.HttpServerModule.initHTTPServer(HttpServerModule.java:109)
	at org.netbeans.modules.httpserver.HttpServerSettings.setRunning(HttpServerSettings.java:206)
	at org.netbeans.modules.httpserver.HttpServerURLMapper.getURL(HttpServerURLMapper.java:146)
	at org.openide.filesystems.URLMapper.findURL(URLMapper.java:115)
	at org.netbeans.modules.extbrowser.URLUtil.getURLOfAppropriateType(URLUtil.java:147)
	at org.netbeans.modules.extbrowser.URLUtil.createExternalURL(URLUtil.java:77)
	at org.netbeans.modules.extbrowser.MacBrowserImpl.loadURLInBrowserInternal(MacBrowserImpl.java:61)
	at org.netbeans.modules.extbrowser.ExtBrowserImpl$1.run(ExtBrowserImpl.java:141)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
```

This is happening for all methods opening Javadoc except when using the Javadoc index search with uses the inbuilt browser.

### How to reproduce

Within a maven java project, include a dependency for which Javadoc exists remotely. Download the Javadoc using the context menu of the dependency, or the top-level Dependencies folder.

Right click upon the dependency when the Javadoc is loaded, indicated by the J in the upper right corner of the dependency icon.

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

macOS 13.1.3 M1 (aarch64)

### JDK

17.0.7 (arm64) "Azul Systems, Inc." - "Zulu 17.42.19"

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This occurs on every occasion over multiple reloads.

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
> On macOS, it seems that user.dir is the root, not the home directory. And creating the Tomcat directory fails 

wow

**Comment by neilcsmith-net** [comment]
Looks like it's broken on Windows too.  Tried with both ASF and Codelerity installers (am building and testing across machines today).  With both, `user.dir` is set to the IDE install location.  Might work for zip in user's personal space, but won't installed in Program Files.

This default is probably a problem on Linux too.  If I run `netbeans` from the CLI while in a none user directory, it fails then too.

We might want to code this to be in the cache folder?

**Comment by mbien** [comment]
> On macOS, it seems that user.dir is the root, not the home directory. And creating the Tomcat directory fails 

it creates an empty folder structure in my case:
```
tree -la tomcat.8082/
tomcat.8082/
└── work
    └── Tomcat
        └── localhost
            └── ROOT
```
cache or tmp are probably both ok for that. Cleanup is probably not required since nothing is in it?

**Comment by neilcsmith-net** [comment]
The workaround on Windows is different (above relies on the fact it's executed as a shell script).  Can edit the Windows shortcut, and add the same property to the end of the Target field.

Noticed it seemed empty, but not what uses might make that not the case, if any.  Also might have to consider if there are any networking restrictions related to the location?

**Comment by mbien** [comment]
would suggest to put it into temp for now `Files.createTempDirectory("nb-tomcat")`.

If its actually something worth caching we can put it into `Places.getCacheSubdirectory("tomcat")`?

**Comment by neilcsmith-net** [comment]
@matthiasblaesing isn't that `user.home` not `user.dir`?!

**Comment by matthiasblaesing** [comment]
Windows:

![image](https://github.com/apache/netbeans/assets/2179736/1fc083b0-9585-4c92-bdb3-b7b6eccccafa)

mac OS:

![image](https://github.com/apache/netbeans/assets/2179736/0a46fa9b-dfd7-4edb-a439-30942573671b)


Key | Description of Associated Value
-- | --
user.home | User's home directory
user.dir | User's current working directory

**Comment by matthiasblaesing** [comment]
NetBeans binary (Zip distribution)  tested on Windows works (i.e. javadoc is opened in browser)

**Comment by neilcsmith-net** [comment]
@matthiasblaesing yes, if the present working directory is user writable then this works. So, as said above, the zip will probably be OK on Windows.

OTOH, try eg. `cd /; netbeans;` with the Linux packages and it doesn't. With your tests above, try running from different a different directory to home.

**Comment by matthiasblaesing** [comment]
Ah f*** ok, I see.

**Comment by matthiasblaesing** [comment]
PR is open. Tested with Windows where I reproduced the problem by running from a directory where I explicitly denied write permissions. With the fix it works.

**Comment by mbien** [comment]
> will build from the PR and verify

@cbm64chris you can also download a dev-build from the build summary page of the PR if you want:
https://github.com/apache/netbeans/actions/runs/5094203872?pr=5993
