### ISSUE TITLE
Terminal can not be launched on MacOS

### ISSUE THREAD

**Issue by vanuatoo** [apache/netbeans#6012]
### Apache NetBeans version

Apache NetBeans 18

### What happened

Terminal does not open in NetBeans

### How to reproduce

1. Launch NetBeans
2. Select from Menu: Window -> IDE Tools -> Terminal

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS Ventura 13.3.1 on M1 MacBook Pro 14 inch

### JDK

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

It happens every time.

messages.log shows the following output

INFO [org.netbeans.modules.dlight.terminal.action.TerminalSupportImpl]: Process exited with the return code:1
INFO [null]: Last record repeated again.
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.XMLDataObject@d17bcb9[MultiFileObject@c7536ae[Actions/Help/master-help.xml]]
WARNING [org.netbeans.modules.options.editor.keymap.EditorBridge]: The action org.netbeans.modules.jshell.editor.RunScriptAction@74254895 doesn't provide short description, using its name.

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
This will need to bump to NB20.  We need a plan for integrating updated binaries here.

cc. @ebarboni - another netbeans-native-* repo candidate?

**Comment by ebarboni** [comment]
maybe yes. for the current native maybe we should migrate some sh, to have the "all" os into the native repo instead windows :p
