### ISSUE TITLE
libjnidispatch-nb.jnilib can't be opened

### ISSUE THREAD

**Issue by vanuatoo** [apache/netbeans#6014]
### Apache NetBeans version

Apache NetBeans 18

### What happened

When launching NetBeans, there are errors. The IDE starts and works fine.

### How to reproduce

1. Launch Netbeans
2. Pop-up dialog appears (set attachment)
3. Press OK on the dialog
4. Same pop-up appears as in the step 2
5. Press OK on the dialog
6. NetBeans starts successfully

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS Ventura 13.3.1 on M1 MacBook Pro 14 inch

### JDK

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else
It happens everytime
<img width="258" alt="Screenshot 2023-06-02 at 13 03 43" src="https://github.com/apache/netbeans/assets/6188902/a30af7c7-c662-40cc-b497-8c5d8eb91881">

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
This is macOS's Gatekeeper in action.  You can run, if I remember correctly, `xattr -r -d com.apple.quarantine <extracted folder>` before running NetBeans.

Or you can use either the ASF macOS installer, or the [Codelerity community installer](https://www.codelerity.com/netbeans/). Both of which are signed and notarized with the hardened runtime.  The community installer includes a local Java 20 JDK as part of the App bundle that is signed and notarized together to make things a little easier.
