### ISSUE TITLE
Improve the feature of "Open In System"

### ISSUE THREAD

**Issue by AndyLuke** [apache/netbeans#6043]
### Description

The long-awaited feature of "Open In System" was finally added in Netbeans 18, after using it, I found that the function is not perfect yet, such as right-click in the editor, there is no menu of "Open In System". In addition, in the right-click menu, sometimes the menu can be found directly, sometimes the menu is in the submenu under the tools, can not be directly found, there is no a unified fixed menu location. By the way, this feature also does not support shortcuts yet. In my opinion, nowadays this feature should be a basic and convenient feature of an IDE or other code editor, but it is obvious that this feature is not convenient enough now.

### Are you willing to submit a pull request?

No

**Comment by AndyLuke** [comment]
Yes, very exact.

**Comment by mbien** [comment]
> Might be nice to add to editor popup too.

editor tab would be a better place for this IMHO. I am still thinking about a good spot to hide "copy path" :)

> I've just set mine to Alt+Shift+S

+1

> sometimes the menu can be found directly, sometimes the menu is in the submenu under the tools

the root folder has the tool sub menu expanded. Not sure if this is a problem though.

**Comment by neilcsmith-net** [comment]
PR hopefully covers all discussed in this issue.
