### ISSUE TITLE
Apache Malfunction

### ISSUE THREAD

**Issue by alexis11111111111** [apache/netbeans#6055]
### Apache NetBeans version

Apache NetBeans 18

### What happened

My apache Netbeans automatically exit on its own after about 5 minutes have try getting the lastest version of apache netbeans but problem still persist.

### How to reproduce

My apache netbeans automatically exit on its own after about 5 minutes have try getting the lastest version of apache netbeans but problem still persist

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 64 bit

### JDK

8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
JDK 8 is not a supported JDK for running the Apache NetBeans IDE.  Please try an up-to-date JDK.  If the problem recurs, open another issue including more information about what you were doing at the time, and if possible attach the log file to the issue.
