### ISSUE TITLE
"Fix imports..." adds statements to wrong place of the document in php files

### ISSUE THREAD

**Issue by thanasis-oob** [apache/netbeans#6056]
### Apache NetBeans version

Apache NetBeans 18

### What happened

After updating the program to the latest version 18, I noticed that the "Fix imports" functionality in a php file, adds the use Classes in wrong places of the file.

### How to reproduce

Case 1
On a new PHP project.
Add some namespaced classes with methods and doc methods.
Call some classes inside a class method, then right click on the file editor area and from the context menu choose the "Fix imports...".
Until previous version "Fix imports..." functionality, detects all non imported classes, shows a popup with the found classes and then adds "use /NamespePath/Class1;" statement after the first  "<?php" and after the namespace statement.

Case 2
create a new php file.
Open a new <?php ?> tag
then write html and mix <?php ?> tags that calls namespaced classes
use the "Fix imports..."
The use statements are added inside the last <?php ?> tag.

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Ubuntu 22.04

### JDK

11.0.19; OpenJDK 64-Bit Server VM 11.0.19+7-post-Ubuntu-0ubuntu122.04.1

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Anything else

before Fix imports..."
```
<?php

/** @var EntityActionManager  $entityActionManager  */
?>
    <?php foreach($scripts as $script): ?>
        <?php if(!AppManager::get()->hasLoadedScript($script)): ?>
            <script type="text/javascript" src="<?= e(asset($script)) ?>"></script>
        <?php endif; ?>
    <?php endforeach; ?>
````

After before Fix imports..."
```
<?php


/** @var EntityActionManager  $entityActionManager  */

?>


    <?php foreach($scripts as $script): ?>
        <?php if(!AppManager::get()->hasLoadedScript($script)): ?>
            <script type="text/javascript" src="<?= e(asset($script)) ?>"></script>
        <?php endif; ?>
    <?php 

use App\Logic\App\AppManager;
use App\Logic\App\EntityActionManager;
endforeach; ?>

````

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
@thanasis-oob Thank you for your report! Could you please provide an example code to reproduce it? I can't reproduce it with your current example code only.

**Comment by thanasis-oob** [comment]
Create a new php project.
Create a folling files under the root dir

App\TestClass1.php
```
<?php

namespace App;

class TestClass1{public static function callMe() {return __CLASS__;}}

```

App\TestClass2.php
```
<?php

namespace App;

class TestClass2{public static function callMe() {return __CLASS__;}}

```

App\TestClass3.php
```
<?php

namespace App;

class TestClass3{public static function callMe() {return __CLASS__;}}

```

App\TestClass4.php
```
<?php

namespace App;

class TestClass4{public static function callMe() {return __CLASS__;}}

```
index.php

```
<?php 

?>
<!DOCTYPE html>
<html>
    <body>
        
        <?php if(1 === 1): ?>
            <?php \App\TestClass1::callMe()?>
        <?php else: ?>
            <?php \App\TestClass2::callMe()?>
        <?php endif; ?>
    </body>
</html>

```

Then open the index.php fro editing from the netbeans and right click somewhere in the editor and choose "Fix Imports.." (Ctrl+Shift+I)

the file is tranformed as below

```
<?php 

?>
<!DOCTYPE html>
<html>
    <body>
        
        <?php if(1 === 1): ?>
            <?php TestClass1::callMe() ?>
        <?php else: ?>
            <?php TestClass2::callMe() ?>
        <?php 

use App\TestClass1;
use App\TestClass2;
endif; ?>
    </body>
</html>

```


Until previous version The file was tranformed as below

```
<?php 

use App\TestClass1;
use App\TestClass2;
?>
<!DOCTYPE html>
<html>
    <body>
        
        <?php if(1 === 1): ?>
            <?php TestClass1::callMe() ?>
        <?php else: ?>
            <?php TestClass2::callMe() ?>
        <?php endif; ?>
    </body>
</html>

```

It happened a similar bug in a Class file with one open php tag (<?php) and namy methods with document comments, but unfortunately I cannot remember how to reproduce it.

**Comment by junichi11** [comment]
@thanasis-oob Reproducible. Thanks!

**Comment by junichi11** [comment]
Reverted "FixImports" changes with #6152 
It should be OK now.
