### ISSUE TITLE
Add support for CSS @supports

### ISSUE THREAD

**Issue by asafm7** [apache/netbeans#6060]
### Description

Add support for CSS @supports

### Use case/motivation

Currently, the use of CSS @supports shows errors

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Support for @supports was added about four years ago. There are explicit tests for @supports in the project:

https://github.com/apache/netbeans/blob/1e494096b524d4c302eb34cca60977ba3955f6df/ide/css.lib/test/unit/src/org/netbeans/modules/css/lib/Css3ParserTest.java#L734-L909

So please add concrete cases, that fail for you.

**Comment by matthiasblaesing** [comment]
A fix is proposed as part of #6451. Please check it. Test builds are available:

- From the checks summary page: https://github.com/apache/netbeans/actions/runs/6190122968
- Or directly: https://github.com/apache/netbeans/suites/16181456062/artifacts/924240381
