### ISSUE TITLE
Formating of "match" expression same as arrays in PHP

### ISSUE THREAD

**Issue by Eugene-Melbourne** [apache/netbeans#6074]
### Apache NetBeans version

Apache NetBeans 18

### What happened

when you formatting PHP code, the match expression is being formatted 

```
match ($type) {
        'integer' => 'a',
        'string' => 'b',
        default => null,
    };
```
    
I think it should be formatted like this

```
match ($type) {
        'integer' => 'a',
        'string'  => 'b',
        default   => null,
    };
```

### How to reproduce

alt + shift + f

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64; UTF-8; en_AU (nb)

### JDK

19.0.1; Java HotSpot(TM) 64-Bit Server VM 19.0.1+10-21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by KacerCZ** [comment]
Formatting of array is configured by option under Alignment > Group Multiline Alignment > Array Initializer.
Formatting of `match` should have individual option.

**Comment by Eugene-Melbourne** [comment]
@KacerCZ , yes, sorry, I was clear enough. I meant to say that the same way as formatting for `array `has an option, there should be an option for `match`. Would you like me to change the initial post/header?

**Comment by KacerCZ** [comment]
@Eugene-Melbourne Yes, this is feature request, so I changed labels.

**Comment by terax6669** [comment]
@junichi11 Nothing happened for almost half a year. Can we add this to a milestone?

Also, is there a checklist for adding support for a new language feature? This should've been part of 8.0 support.
If there is no such checklist may I suggest one be created to avoid such overlooks?

**Comment by junichi11** [comment]
> Nothing happened for almost half a year. Can we add this to a milestone?

I'll work on it when I have time although I can't promise anything. Maybe, it will take some time, I guess.
I have more important issue than this. It's PHP 8.3 support.

> This should've been part of 8.0 support.

No, This is not a required feature. It's an additional feature. (Normal formatting feature should work fine.)

**Comment by Eugene-Melbourne** [comment]
just for the record, the new configuration can be found like this 
`Alignment > Group Multiline Alignment >Match Arm Arrow`
It is working fine
