### ISSUE TITLE
in PHP "?" should be equal to "|null" for typehinting

### ISSUE THREAD

**Issue by Eugene-Melbourne** [apache/netbeans#6075]
### Apache NetBeans version

Apache NetBeans 18

### What happened

when I use typehint like this 

`/** @var ?User $user */`

Netbeans doesn't understand the typehint

but if I do it like this 

`/** @var User|null $user */`

the typehint is being understood by Netbeans, It means that the 
ctrl+space - gives options
and 
ctrl+shift+i - is not trying to delete the "use User"

But for PHP it is the same meaning, either it is "User|null" or " ?User"

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64; UTF-8; en_AU (nb)

### JDK

19.0.1; Java HotSpot(TM) 64-Bit Server VM 19.0.1+10-21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by KacerCZ** [comment]
Reproducible, thank you for the report.

Working example:
```php
function now() {
    /** @var \DateTime|null $now */
    $now = NULL;
    $now->
}
```

Not working:
```php
function now() {
    /** @var ?\DateTime $now */
    $now = NULL;
    $now->
}
```

**Comment by Eugene-Melbourne** [comment]
there is the same problem in regards to the class comments like this 

```
/**
 * @property ?\DateTime $now
 * /
```

should I make a separate ticket for this, or does this ticket covers it?

**Comment by junichi11** [comment]
@Eugene-Melbourne 

> should I make a separate ticket for this, or does this ticket covers it?

Will fix it with this ticket. Please write a whole example code to reproduce it always. Thanks.

**Comment by Eugene-Melbourne** [comment]
@junichi11 

You are right! I should have tried to reproduce it. 
The `@property ?\DateTime $now` is working now in Netbeans18. 
It was not working in the Netbeans 17 along with `@var ?\DateTime`. 
I thought if one is not fixed then the other one is also not fixed. My mistake. Thank you for pushing me to follow the formal procedure.
