### ISSUE TITLE
Allow building with latest JDK without extra setup

### ISSUE THREAD

**Issue by LiamM32** [apache/netbeans#6125]
### Description

Building the latest version with JDK 20 will fail. The README.md admits that this may happen on newer JDK versions. This should be fixed, so that one doesn't need to install an older JDK version just to compile NetBeans.

### Use case/motivation

For `ant build` to run without errors when using JDK 20.

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
The `README` also includes an explanation for this, and instructions for how to build with JDK 20. If you look at the GitHub actions workflows you'll also see how build is being tested on JDK 21 already.

I'm inclined to close this issue, but maybe someone has a thought on an alternative approach?

**Comment by neilcsmith-net** [comment]
@mbien "Gradle is just Ant with slightly better syntax" <sup>TM</sup> :laughing: 

All (half) joking aside, I was under the impression there was a reason this had to be Gradle-based.  If there isn't, then yes, let's get it changed back - Gradle approach to compatibility with newer JDKs is a PITA!
