### ISSUE TITLE
forms designer re-ordering components dragging gone weird

### ISSUE THREAD

**Issue by grandinj** [apache/netbeans#6134]
### Apache NetBeans version

Apache NetBeans 18

### What happened

Dragging not smooth

### How to reproduce

(*) Open Netbeans form designer on a complex form

(*) open the Object navigator

(*) try and drag an item up or down 

(*) Notice that the insertion point is not following the drag point properly, but bouncing around

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Windows 10 version 10.0 running on amd64; Cp1252; en_US (nb)

### JDK

17.0.5; OpenJDK 64-Bit Server VM 17.0.5+8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by DevCharly** [comment]
This is a bug in NB 18 with FlatLaf window decorations on Windows 10/11.

It will be fixed in NB 19. See PR #6142 

As workaround, disable FlatLaf window decorations:

![image](https://github.com/apache/netbeans/assets/5604048/e615a670-a43f-4aec-a106-001a4eba0f01)

**Comment by grandinj** [comment]
@DevCharly Cool, thanks for working on that!
