### ISSUE TITLE
Limit config import to recent versions

### ISSUE THREAD

**Issue by mbien** [apache/netbeans#6135]
NB suggesting config imports from (very) old versions keeps causing new, seemingly unrelated issues. We tried to patch things up before (e.g #4838) and keep patching things (#6094) still but it is overall a fairly risky operation to let users import settings as fragile as the mechanism is.

Not to mention that the only usecase we probably test on a regular basis is to import from N-1.

I suggest to agree to a number, lets say 3 versions from `current` as sliding window and only let NB suggest imports of those versions. The explicit import (via the buttons in the options) should probably still allow everything but maybe have a scary warning on it.

refs:
https://lists.apache.org/thread/s3b83q9z7b86rogc6l57vzgx2hkpbc52
#6076, #5147 #5633, #5634, #3797, #4831 ...

**Comment by neilcsmith-net** [comment]
Agreed!  Have opened a PR to implement as suggested.
