### ISSUE TITLE
Attempting to save out a long string via BigStringCustomEditor results in an error: "Char at 0 is not a character: <char as int>"

### ISSUE THREAD

**Issue by SirIntellegence** [apache/netbeans#6147]
### Apache NetBeans version

Apache NetBeans 18

### What happened

I went to view a long string and, it shows up properly in the debug window, shortened and all, but using the "save to file" button breaks things.

### How to reproduce

See above. TBH, I am mostly making this so I have a bug number to name the branch after.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mac

### JDK

OpenJDK 64-Bit Server VM Temurin-19.0.1+10 (build 19.0.1+10, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I strongly believe it is related to https://github.com/apache/netbeans/issues/4123

### Are you willing to submit a pull request?

Yes

**Comment by neilcsmith-net** [comment]
> TBH, I am mostly making this so I have a bug number to name the branch after.

Please don't open issues for this purpose, as it says in the issue form. Just open a pull request. They use the same numbering system anyway, and it just makes extra work all round.

**Comment by SirIntellegence** [comment]
Ah. My bad. Sorry about that. Apparently I didn't notice that. How would you recommend making branch names in the first place then since you need to open a pull request before you can get the number.

**Comment by mbien** [comment]
> How would you recommend making branch names in the first place then since you need to open a pull request before you can get the number.

@SirIntellegence i do this locally. Branch from latest master and give it some name. Then when I push the branch to my clone the git CLI even posts a link which will directly lead you to the PR page. So the next click opens the PR already.
