### ISSUE TITLE
`Objects.requireNonNull` should disable "Null Pointer Dereference" warnings

### ISSUE THREAD

**Issue by NicolaIsotta** [apache/netbeans#6149]
### Apache NetBeans version

Apache NetBeans 18

### What happened

Using `Objects.requireNonNull` should disable "Null Pointer Dereference" warnings. Instead, it doesn't.

### How to reproduce

```java
public static String myToString(Object object) {
    Objects.requireNonNull(object);
    if (object instanceof Number) {
        DecimalFormat df = new DecimalFormat("#.00");
        return df.format(((Number) object).doubleValue());
    } else {
        return object.toString();
    }
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64; Cp1252; it_IT (nb)

### JDK

11.0.14.1; OpenJDK 64-Bit Server VM 11.0.14.1+1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

![null warning](https://github.com/apache/netbeans/assets/18428155/6470fe7e-e4e9-4306-96de-3b02be74788b)

if `Objects.requireNonNull(object);` is replaced by `if (object == null) throw new NullPointerException();` the warning disappears.

### Are you willing to submit a pull request?

No

**Comment by asbachb** [comment]
Here's an additional test for `NPECheckTest` to prove the problem:

```java
    public void testObjectsRequireNonNull() throws Exception {
        HintTest.create()
                .input("package test;\n"
                        + "import java.util.Objects;\n"
                        + "public class Test {\n"
                        + "  public String test(Object obj) {\n"
                        + "    Objects.requireNonNull(obj);\n"
                        + "    if (obj instanceof Number)\n"
                        + "      return \"\";\n"
                        + ""
                        + "    return obj.toString();\n"
                        + "  }\n"
                        + "}")
                .run(NPECheck.class)
                .assertNotContainsWarnings("7:15-7:23:verifier:Possibly Dereferencing null");
    }
```
