### ISSUE TITLE
Composer vendor name containing a dot or an underscore is not accepted

### ISSUE THREAD

**Issue by ChristianJohn-Softwareentwicklung** [apache/netbeans#6192]
### Apache NetBeans version

Apache NetBeans 18

### What happened

While setting up composer in options, my vendor name throws a note 
Vendor is not valid (only lower-case letters and "-" allowed). 
I am able to save my settings, but when do a composer init the option window is open again.

![image](https://github.com/apache/netbeans/assets/59682676/70c563ca-dd71-4a4f-b54d-55afbf967ccc)

### How to reproduce

Go to options, PHP, Composer. 
Set a vendor name like my-vendor.com

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

1.8.0_131; Java HotSpot(TM) 64-Bit Server VM 25.131-b11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Refering to https://getcomposer.org/doc/04-schema.md since composer 2.0 dots and underscores are allowed. 
"The name must be lowercase and consist of words separated by -, . or _. The complete name should match ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]|-{1,2})?[a-z0-9]+)*$

Note: Before Composer version 2.0, a name could contain any character, including white spaces."

At the composer console "my-vendor.com" is working.

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
@ChristianJohn-Softwareentwicklung Thank you for reporting it!
