### ISSUE TITLE
Rerun failed tests button is not getting enabled

### ISSUE THREAD

**Issue by Atrament666** [apache/netbeans#6199]
### Apache NetBeans version

Apache NetBeans 18

### What happened

I have noticed that when running unit tests, the button for reruning failed tests in Test Results never gets enabled. 

### How to reproduce

* Create Java with Maven project
* Add some unit tests that fail
* Run tests and check the button - should be enabled but it's not.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Manjaro Linux

### JDK

OpenJDK 11

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

I checked the source code and the problem seems to be in the condition
`rerunFailedButton.setEnabled(displayHandler.sessionFinished && 
                                     rerunHandler.enabled(RerunType.CUSTOM) &&
                                     !treePanel.getFailedTests().isEmpty());`
in netbeans/ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/StatisticsPanel.java

RerunType.CUSTOM doesn't seem to be used anywhere thus the condition is always false. Using `RerunType.ALL` fixes the issue, but I am not sure if it has any side-effects, I haven't found any yet.

### Are you willing to submit a pull request?

Yes

**Comment by asbachb** [comment]
Could reproduce this on NetBean 18, OpenJDK17, Maven Project:

Create Maven Project, Tools -> Create / Update Tests, `assertTrue(false);`, Right Click Test class -> Test File

Rerun failed button cannot be clicked.

**Comment by asbachb** [comment]
Same behavior on master (02dafb29b878e45d66be1e1dc95f018f8e71cf87)
