### ISSUE TITLE
Blog link is 404

### ISSUE THREAD

**Issue by silverbacknet** [apache/netbeans#6200]
### Apache NetBeans version

Apache NetBeans 18

### What happened

Clicked "Blog" in the main upper menu of the website. Landed on a 404 page, which said to report it here. Expected to see the blogs.

Link is to https://blogs.apache.org/netbeans/ which is redirecting to https://netbeans.apache.org/blog/ which doesn't exist.

There doesn't seem to be any way of reporting website errors despite the page explicitly sending you here for them. This is not about the software, so none of the following fields are useful.

### How to reproduce

Click "Blog" in the main upper menu of the website, from any page.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Win10 x64

### JDK

None

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

No

**Comment by asbachb** [comment]
Best guess: Should link/redirect to: https://netbeans.apache.org/blogs/geertjan/index.html

**Comment by mbien** [comment]
@asbachb not quite. Apache doesn't use roller anymore for their blogs, the old project blog entries are archived at:
https://blogsarchive.apache.org/#netbeans

**Comment by neilcsmith-net** [comment]
This is all working again, including the feed and link in the start page of the IDE (was actually relevant to the software too).  Thanks @ebarboni :1st_place_medal:
