### ISSUE TITLE
No proper way to report website issues

### ISSUE THREAD

**Issue by sebbASF** [apache/netbeans#6204]
### Apache NetBeans version

Apache NetBeans 18

### What happened

There is no easy way to report website issues.
This form appears to be the closest, but is almost entirely irrelevant for website issues.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

N/A

### JDK

N/A

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

No

**Comment by ebarboni** [comment]
Hi, I would say I agree, maybe opening github issue on netbeans-website may help.

**Comment by neilcsmith-net** [comment]
@sebbASF perhaps open discussion on dev@.  As @ebarboni says, enalbing issues on the website repo might be the way forward.  But we might also want to consider forms, labels, etc. and the right way to manage to stop it becoming a black hole.
