### ISSUE TITLE
Options to Import does not work correctly

### ISSUE THREAD

**Issue by pepness** [apache/netbeans#6214]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

When you select a file to import options it does not import options like :

- Java Platforms
- Libraries
- Font & Colors

It does import the Look and Feel option. The PR that introduce this bug was [PR-6094](https://github.com/apache/netbeans/pull/6094)

### How to reproduce

1. Start a clean instance of NetBeans
2. Activate Java SE & Java Web and EE plugins
3. Add new Java Platforms
4. Add a new library in Libraries
5. Change Font & Colors Profile from FlatLaf to any other
6. Change Font & Colors font and size to any other
7. Change Look and Feel from FlatLaf to any other
8. Export your options to a new file.
9. Start a clean instance of NetBeans
10. Activate Java SE & Java Web and EE plugins
11. Import your options file

Only the Look and Feel should have changed, no other option should have been imported.

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Linux Pop OS 22.04

### JDK

oracle-17

### Apache NetBeans packaging

Own source build

### Anything else

Reverting the file `org.netbeans.modules.options.export.OptionsExportModel.java` fix this. Will try to fix this tomorrow.

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
I think I found the issue. Let me take a look.
