### ISSUE TITLE
Committing SQL files does not change blue color on the file tab in editor

### ISSUE THREAD

**Issue by epliskin** [apache/netbeans#6224]
### Apache NetBeans version

Apache NetBeans 18

### What happened

SQL file name on the tab in editor remains blue after commit. This behaviour is specific for SQL files. 

### How to reproduce

I have a project supported by Git repository. Open an SQL file in NetBeans editor, and make changes to code. File name on the tab in editor changes color from black to blue which is correct for the files awaiting commit. Now perform commit to Git repository from Team menu. File name on the tab in editor remains blue which is wrong. While Projects tab correctly changes blue color to black for this file. Now switch focus to another file tab and then back to SQL file tab in editor. This time the SQL file tab changes color to black.

This behaviour is specific for SQL files. Other file types like txt, java, html etc. do not remain blue when committed.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

20 OpenJDK

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Problem is stable every time. And was present in previous NetBeans versions.

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
@epliskin thank you for your report. Indeed SQL files are treated specially and the way the editor is initialized needs adjustment to get updates when versioning status changes (indeed this is not git specific).

Could you please test the development build from the checks page:

https://github.com/apache/netbeans/actions/runs/5693713581

or directly:

https://github.com/apache/netbeans/suites/14647128496/artifacts/831058471

As NB19 is already in freeze and in the last steps of RC, that fix is targetted to NB20.

**Comment by neilcsmith-net** [comment]
> As NB19 is already in freeze and in the last steps of RC, that fix is targetted to NB20.

@matthiasblaesing well, we we will have at least one more NB19 RC (we're really only on the second of the guaranteed three).  I will leave it to you whether to target or not, but it seems reasonable and fairly minimal.

**Comment by epliskin** [comment]
> https://github.com/apache/netbeans/suites/14647128496/artifacts/831058471

Confirm the problem solved in this build.

**Comment by matthiasblaesing** [comment]
@epliskin thank you for the quick confirmation.
@neilcsmith-net I had another look at this and retargetted to NB19
