### ISSUE TITLE
XML validation breaks with multiple schema files

### ISSUE THREAD

**Issue by bernard01** [apache/netbeans#6226]
### Apache NetBeans version

Apache NetBeans 18

### What happened

If an XML file loaded in the editor is validated against multiple schema files, then validation breaks under an observed condition.

The condition is that definitions in the schema files reference each other. In this case, it appears to be important that the validator builds the schema from the multiple files in such a way that the order in which the files are loaded is matching the hierarchy. Dependent files need to be loaded after the files that they depend on.

I am coming to this conclusion after writing a test case. This test case builds the schema in the correct way, using an iterative brute force approach.

If the schema files are loaded in the incorrect order, then the schema cannot be built, and validation is not even started.

I am donating the code in the test case to Apache Netbeans with the aim that the validation using the editor is fixed, using the insight gained from the test case.
[MultiSchemaValidation.zip](https://github.com/apache/netbeans/files/12093607/MultiSchemaValidation.zip)

### How to reproduce

Open file mtn_2020-06-29_full_S1_R0.xml in directory xml.

In the editor, right click|Validate XML

Result:

cvc-elt.1.a: Cannot find the declaration of element 'rde:deposit'. [15] 

The main class ValidateXmlXsd.java in the attached project contains code to validate the XML.

Without any tricks, the validation crashes with a similar error.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 7

### JDK

Java: 14; Java HotSpot(TM) 64-Bit Server VM 14+36-1461

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

However, when a trick is applied via boolean CREATE_SCHEMA_ITERATIVELY in the attached class ValidateXmlXsd.java, then the validation proceeds normally with genuine validation errors printed.

I am not an expert in this area. So I would not know what the real error here is. Perhaps there is something else.

But NetBeans is very powerful tool and it has served me well whenever I needed it. Perhaps this is worthwhile fixing.

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
You are missing the schema reference. That ties the schema to the XML. If you update the document `mtn_2020-06-29_full_S1_R0` like this:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<rde:deposit xmlns:rde="urn:ietf:params:xml:ns:rde-1.0"
             xmlns:rdeHost="urn:ietf:params:xml:ns:rdeHost-1.0"
             xmlns:rdeEppParams="urn:ietf:params:xml:ns:rdeEppParams-1.0"
             xmlns:epp="urn:ietf:params:xml:ns:epp-1.0"
             xmlns:ns5="urn:ietf:params:xml:ns:rdeCsv-1.0"
             xmlns:rdeHeader="urn:ietf:params:xml:ns:rdeHeader-1.0"
             xmlns:rdeNNDN="urn:ietf:params:xml:ns:rdeNNDN-1.0"
             xmlns:rdeIDN="urn:ietf:params:xml:ns:rdeIDN-1.0"
             xmlns:rdeRegistrar="urn:ietf:params:xml:ns:rdeRegistrar-1.0"
             xmlns:rdeDomain="urn:ietf:params:xml:ns:rdeDomain-1.0"
             xmlns:domain="urn:ietf:params:xml:ns:domain-1.0"
             xmlns:secDNS="urn:ietf:params:xml:ns:secDNS-1.1"
             xmlns:rdeContact="urn:ietf:params:xml:ns:rdeContact-1.0"
             xmlns:contact="urn:ietf:params:xml:ns:contact-1.0"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="urn:ietf:params:xml:ns:rde-1.0 rde-1.0.xsd"
             type="FULL"
             id="F202006291123"
             resend="0">
```

You'll get further:

```
XML validation started.
Checking file:/home/matthias/tmp/MultiSchemaValidation/xml/mtn_2020-06-29_full_S1_R0.xml...
Referenced entity at "file:/home/matthias/tmp/MultiSchemaValidation/xml/rde-1.0.xsd".
Referenced entity at "file:/home/matthias/tmp/MultiSchemaValidation/xml/eppcom-1.0.xsd".
cvc-complex-type.2.4.a: Ungültiger Content wurde beginnend mit Element '{"urn:ietf:params:xml:ns:rdeHeader-1.0":header}' gefunden. '{"urn:ietf:params:xml:ns:rde-1.0":content}' wird erwartet. [35] 
XML validation finished.
```

As you can see, NetBeans now loads the `rde-1.0.xsd` and `eppcom-1.0.xsd`. The latter is referenced in line 14 -15 in `rde-1.0.xsd`.

What is problematic though is, that the NetBeans UserCatalog can't be used to resolve Namespaces to URIs. See: Menu "Tools" -> "DTDs und XML Schemas". The UserCatalog is writeable and you should be able to register your schemas there. But this currently does not work.

**Comment by bernard01** [comment]
Thanks for suggesting the change. Please excuse my ignorance in this field.

I would like to use the provided Maven test case to verify the modification because it should more flexible. So I changed the XML as you suggested and re-run the Maven project with the flag

CREATE_SCHEMA_ITERATIVELY = false;

Then I still get the error:

org.xml.sax.SAXParseException; lineNumber: 269; columnNumber: 47; src-resolve: Cannot resolve the name 'eppcom:clIDType' to a(n) 'type definition' component.


Which points to the element:

        <rdeDomain:clID>10001</rdeDomain:clID>
        
This indicates to me that the order of the schema files has some significance.

Perhaps you can help repair the Maven project first to that it becomes the base line for creating a NetBeans feature.

If that Maven project cannot be repaired to run without sorting the schema files, then it could be that the  parser used in it needs an enhancement and not NetBeans.

**Comment by matthiasblaesing** [comment]
We are drifting from the usecase of an issue tracker, but I think you are looking for is the code below.

```java
package multischema.validate;

import javax.xml.XMLConstants;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import javax.xml.validation.Validator;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.HashMap;
import java.util.Map;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.stream.StreamSource;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.w3c.dom.bootstrap.DOMImplementationRegistry;
import org.w3c.dom.ls.DOMImplementationLS;
import org.w3c.dom.ls.LSInput;
import org.w3c.dom.ls.LSResourceResolver;
import org.xml.sax.SAXException;

public class ValidateXmlXsd {

    private static final String SCHEMA_BASE = "xml/";
    private static final String NS_XMLSCHEMA = "http://www.w3.org/2001/XMLSchema";
    private static final String ELEMENT_SCHEMA = "schema";
    private static final String ATTR_TNS = "targetNamespace";

    public static void main(String... args) throws Exception {
        Map<String, URI> namespaceFileMap = buildNamespaceFilemap();

        DOMImplementationLS dls = (DOMImplementationLS) DOMImplementationRegistry
                .newInstance().getDOMImplementation("LS");

        SchemaFactory mySchemaFactory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
        Schema mySchema = mySchemaFactory.newSchema();
        Validator validator = mySchema.newValidator();
        validator.setResourceResolver(new LSResourceResolver() {
            @Override
            public LSInput resolveResource(String type, String namespaceURI, String publicId, String systemId, String baseURI) {
                if(namespaceFileMap.containsKey(namespaceURI)) {
                    LSInput lsi = dls.createLSInput();
                    lsi.setSystemId(namespaceFileMap.get(namespaceURI).toASCIIString());
                    return lsi;
                } else {
                    return null;
                }
            }
        });
        validator.setErrorHandler(new XsdErrorHandler());
        validator.validate(new StreamSource(new File(SCHEMA_BASE + "mtn_2020-06-29_full_S1_R0.xml")));
        System.out.println("Validation completed - please check for validation errors.");
    }

    private static Map<String,URI> buildNamespaceFilemap() throws SAXException, ParserConfigurationException, IOException {
        DocumentBuilder db = DocumentBuilderFactory
                .newDefaultNSInstance()
                .newDocumentBuilder();
        Map<String, URI> namespaceFileMap = new HashMap<>();
        for(File f: new File("xml").listFiles()) {
            URI fileUri = f.toURI();
            if(f.getName().endsWith(".xsd")) {
                Document d = db.parse(fileUri.toASCIIString());
                NodeList schemaNodes = d.getElementsByTagNameNS(NS_XMLSCHEMA, ELEMENT_SCHEMA);
                for(int i = 0; i < schemaNodes.getLength(); i++) {
                    Element schema = (Element) schemaNodes.item(i);
                    String targetNamespace = schema.getAttribute(ATTR_TNS);
                    if(! targetNamespace.isBlank()) {
                        namespaceFileMap.put(targetNamespace, fileUri);
                    }
                }
            }
        }
        return namespaceFileMap;
    }
}

```

**Comment by bernard01** [comment]
> We are drifting from the usecase of an issue tracker, but I think you are looking for is the code below.
> 
> ```java
... ```

Many thanks. Much appreciated!

**Comment by matthiasblaesing** [comment]
Great! Can I motivate you to have a look at the feature implementation this triggered?

#6245 is based on the problem this setup creates and maybe it even helps you. A testbuild is available from the checks page

https://github.com/apache/netbeans/actions/runs/5626316764

or directly via

https://github.com/apache/netbeans/suites/14481137800/artifacts/818355334

**Comment by bernard01** [comment]
Yes I will do. From a dummy perspective. I have often used NetBeans to teach me how to do things.

**Comment by bernard01** [comment]
I am struggling with this.

I created a new catalog file (the IDE supports creation of a new one as a template):
[OasisXMLCatalog.zip](https://github.com/apache/netbeans/files/12138506/OasisXMLCatalog.zip)

In that dialog it says:

"Creates an OASIS XML Catalog file that maps external entity references to local resources. You can then add the catalog to DTD and XML Schema Catalogs in Runtime window."

Could not find that Runtime Window so I selected:

Menu|Tools|DTD and XML Schema Catalogs|Add Catalog

Catalg Type:
OASIS Catalog Resolver
Browse
Is not a valid file
XML Catalog
Is not a valid file

So I must be wrong somewhere.

**Comment by matthiasblaesing** [comment]
Your approach is awfully complex. You can use the UI to create your IDE catalog:

1. Choose the "User Catalog" (it is the only one marked "read-write") and choose "Add Local DTD or Schema";
  ![Bildschirmfoto vom 2023-07-23 21-50-46](https://github.com/apache/netbeans/assets/2179736/779655fb-aef5-4fe1-951c-c3dbb38aad3d)
2. Enter the namespace as publicId and choose the local file you want to reference:
![Bildschirmfoto vom 2023-07-23 21-54-44](https://github.com/apache/netbeans/assets/2179736/94fdbe00-3993-48ef-a9be-8ebebb4f403d)

Repeat step 2 for all schemas.

If you want to use a catalog, please also use the `publicId` mapping. I tested with this catalog:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <public publicId="urn:ietf:params:xml:ns:rdeHost-1.0" uri="rdeHost-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:rde-1.0 uri" uri="rde-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:rdeEppParams-1.0" uri="rdeEppParams-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:epp-1.0" uri="epp-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:rdeCsv-1.0" uri="rdeCsv-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:rdeHeader-1.0" uri="rde-header-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:rdeNNDN-1.0" uri="rdeNNDN-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:rdeIDN-1.0" uri="rdeIDN-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:rdeRegistrar-1.0" uri="rdeRegistrar-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:rdeDomain-1.0" uri="rdeDomain-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:domain-1.0" uri="domain-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:secDNS-1.1" uri="secDNS-1.1.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:rdeContact-1.0" uri="rdeContact-1.0.xsd"/>
    <public publicId="urn:ietf:params:xml:ns:contact-1.0" uri="contact-1.0.xsd"/>
</catalog>
```

Placed in the folder with the XSDs and it works (Validation works too):

![image](https://github.com/apache/netbeans/assets/2179736/1e64d67d-2c27-4201-8edb-4af79d6dcd0e)

**Comment by bernard01** [comment]
Thanks for your good explanation. I could get #6245 to work for me (validation and code completion). The IDE assisted User Catalog is definitely a lot easier and not as error-prone as what I did.

**Comment by matthiasblaesing** [comment]
@bernard01 thank you for taking time to test and work through the issues. I'll wait a few more days and if noone objects, will merge. The change will not make it into NB19, but will be targetted to NB20.
