### ISSUE TITLE
Select multiple projects to open

### ISSUE THREAD

**Issue by kemperalves** [apache/netbeans#6230]
### Apache NetBeans version

Apache NetBeans 18

### What happened

In previous versions of Netbeans I can select many projects and then select OPEN to open all at same time, se the print below 

![image](https://github.com/apache/netbeans/assets/27026273/da1c0da5-22a1-4005-83ee-bb34273cefc4)

Actually in netbeans 18 I can't do this, I need to open one project at same time, I can't select various folders:

![image](https://github.com/apache/netbeans/assets/27026273/e93297c0-882c-44a4-9206-137f21f1173a)

### How to reproduce

a) Install netbeans 15
b) navigate to a folder that have inside this more than one project, select two or more project and then click OPEN PROJETC, all selected projects will be opened.

c) Install netbeans 18
d) Go to the same folder of step b and try to open all projects at same time, you can't do this...

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

MAC OS-X M1

### JDK

IRRELEVANT

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Have you switched on maximise native look and feel in the options? If so, try again without.

JDK in use is never irrelevant.
