### ISSUE TITLE
Reformat on save takes forever

### ISSUE THREAD

**Issue by gitsocko** [apache/netbeans#6231]
### Apache NetBeans version

Apache NetBeans 18

### What happened

I have Reformat enabled in Options > Editor > On Save.  Since installing NetBeans 18, reformatting takes a really long time with longer files (~2k+ lines).  I just timed reformatting at almost 30 seconds on a file I'm actively editing.  This slowness is new.  NetBeans 17 reformatted so quickly I hardly even noticed it was happening.

### How to reproduce

Create a PHP file with mixed HTML, PHP, JS, CSS, HTML, 2k+ lines.  Turn on the option mentioned above and change/save the file.

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Mac OS Ventura 13.4.1(c)

### JDK

Java: 20.0.2; Java HotSpot(TM) 64-Bit Server VM 20.0.2+9-78 - Runtime: Java(TM) SE Runtime Environment 20.0.2+9-78

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Occurs every time I save.  I cleared the cache, reinstalled v18, no improvement.  I reinstalled v17 and reformatting is very fast, so I'm uninstalling v18 until a fix is released.  Hopefully it will be fixed soon in an upcoming release.

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Please test with 19-rc1 - see #6225.  A number of things were changed / reverted from 18 that might be the cause of this.

cc/ @junichi11

**Comment by junichi11** [comment]
@gitsocko It would be nice if you can provide an example code to reproduce it. Otherwise, we can't investigate anything...

**Comment by neilcsmith-net** [comment]
No response, closing. We can reopen if the requested information is provided.
