### ISSUE TITLE
PHP Wrong suggestion in "Fix imports" feature (Provides)

### ISSUE THREAD

**Issue by zeleznypa** [apache/netbeans#6247]
### Apache NetBeans version

Apache NetBeans 18

### What happened

When I use a return type PHPDoc documentation part, the Netbeans thing that it is a unknown class that should be "imported"

### How to reproduce

With the following code in the new file

```php
<?php
namespace Test;

new class extends ArrayObject {

	/**
	 * @return static Provides fluent interface
	 */
	public function foo(): static
	{
		return $this;
	}
};
```

try to call a "Source > Fix imports..." function.

It shows the following dialog:
![Snímek obrazovky 2023-07-24 v 8 32 55](https://github.com/apache/netbeans/assets/1191472/03cbe620-5e58-4c78-b378-43225a13614b)

Expected result is the same but without the `Provides` row.

### Did this work correctly in an earlier version?

No

### Operating System

Mac OS X version 10.16 running on x86_64; UTF-8; cs_CZ (nb)

### JDK

14.0.2; Java HotSpot(TM) 64-Bit Server VM 14.0.2+12-46

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

I want to, but I'm not a Java developer

**Comment by junichi11** [comment]
@zeleznypa Declared return type is `void`. Why `static`?

**Comment by junichi11** [comment]
@zeleznypa I can't reproduce it with your example.

**Comment by zeleznypa** [comment]
@junichi11 I apologize for the imperfection in the original example. I have already corrected it.

**Comment by junichi11** [comment]
@zeleznypa Reproducible. Thanks!

**Comment by zeleznypa** [comment]
@junichi11 You are awesome... Many thanks from Czech Republic :)

**Comment by junichi11** [comment]
You are welcome :)
