### ISSUE TITLE
Drag and drop in tree views seems to be broken

### ISSUE THREAD

**Issue by jmborer** [apache/netbeans#6263]
### Apache NetBeans version

Apache NetBeans 18

### What happened

Drag and drop in any Tree view (project, files, navigator) does not longer work properly: the destination no longer falls between files but in the middle of them (see attached picture).

![image](https://github.com/apache/netbeans/assets/6607350/4b67c7be-afdd-47d0-bfbc-572babcd8e89)

I first thought it related to my `--fontsize 16` start option, but reverting to the standard value doens't change anything.

### How to reproduce

Drag a file in any view. 

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Windows 10 

### JDK

Java: 17.0.4.1; OpenJDK 64-Bit Server VM 17.0.4.1+1-LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Preferences have been imported from NB 17.

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Should be fixed by #6142 Please verify with 19-rc3 from #6225 Thanks!

**Comment by neilcsmith-net** [comment]
No response so closing.  Please comment if you see this with NB19.

**Comment by jmborer** [comment]
Sorry. Was away. I'll definitely check that.
