### ISSUE TITLE
Ugly characters in VSNetBeans wizards

### ISSUE THREAD

**Issue by MartinBalin** [apache/netbeans#6278]
### Apache NetBeans version

Apache NetBeans 19 release candidate

### What happened

VSNetBeans wizards in VSCode shows some weird characters when opened, see screenshot 
![Screenshot 2023-07-31 at 16 56 02](https://github.com/apache/netbeans/assets/26064232/3c2c1885-49e4-443e-8330-2389af04ce98)
It is also in Add Database wizard etc.
These are not shown for wizards which are only going in other extensions from TypeScript code. this looks like some error in encoding or some weird escaping...

### How to reproduce

Just install 19.0.0 RC3 from nightlies

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

macOS

### JDK

JDK17

### Apache NetBeans packaging

Apache VSNetBeans for VSCode

### Are you willing to submit a pull request?

No

**Comment by sdedic** [comment]
vscode 1.80.2 starts to display control characters in quickpick descriptions. NBLS leaves newlines and whitespaces after html->plaintext conversion, now these leftovers are displayed by vscode.
