### ISSUE TITLE
Module CSS Editor threw java.lang.NullPointerException when refactor renaming project folder

### ISSUE THREAD

**Issue by authentictech** [apache/netbeans#6279]
### Apache NetBeans version

Apache NetBeans 18

### What happened

In an HTML5 project, I attempted to refactor > rename a project folder and the following warning was produced:

`Module CSS Editor threw java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.css.refactoring.api.CssRefactoringInfo.getFileObject()" because "this.context" is null. Please report a bug against CSS Editor module and attach your var/log/messages.log.`

### How to reproduce

1. Create an HTML5 project. 
2. Add a new folder. 
3. Refactor > rename the folder to anything.

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Ubuntu 22.04.2 LTS / Linux version 5.15.0-78-lowlatency running on amd64

### JDK

17.0.7; OpenJDK 64-Bit Server VM 17.0.7+7-Ubuntu-0ubuntu122.04.2; Private Build

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Anything else

This is occurring every time I perform the specified actions.

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Duplicated by #6833
