### ISSUE TITLE
Can't continue install after terms and conditions

### ISSUE THREAD

**Issue by ezCriss** [apache/netbeans#6289]
### Apache NetBeans version

Apache NetBeans 18

### What happened

Can't continue the installation of Netbeans after acepting terms and conditions, when i click next, installer shows this:
![image](https://github.com/apache/netbeans/assets/138903549/92891957-e81e-454e-9cba-983972e91e8a)
and here is the log file : 
[20230802175342.log](https://github.com/apache/netbeans/files/12245350/20230802175342.log)
tried to install with netbeans 18 and many jdk (20, 18 and 17) having only one version of jdk installed per try, but shows the same error. 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Pro 22H2 x64

### JDK

JDK 20.0.2, JD 18.0.2.1 ,JDK 17.0.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by lalo-mx** [comment]
From the log:
```
Insufficient disk space for extracting the installation data.
````

Do you have enough free space in your drive?

**Comment by neilcsmith-net** [comment]
I'm confused - you mentioned this in the recent discussion post at #6272 but said they're you'd got past the comparison method error in the JDK?!

As a workaround, try the community packages built with NBPackage instead - https://www.codelerity.com/netbeans/

**Comment by ezCriss** [comment]
> From the log:
> 
> ```
> Insufficient disk space for extracting the installation data.
> ```
> 
> Do you have enough free space in your drive?

Yes , 60GB of free space. 




> I'm confused - you mentioned this in the recent discussion post at #6272 but said there you'd got past the comparison method error in the JDK?!
> 
> As a workaround, try the community packages built with NBPackage instead - https://www.codelerity.com/netbeans/

I got one main problem (this issue post and discussion post), and one extra secondary problem on discussion(JFileChooser doesnt open) ,the only problem that was fixed was the 2nd (JFileChooser) but not the main(Installer in this post).
anyway i'm using comunnity edition for now. but the reason why I try to install previous versions is because both my teacher and the study rubric of the institute where I study request it (outdated guides)

**Comment by mbien** [comment]
@neilcsmith-net can we add `-Djava.util.Arrays.useLegacyMergeSort=true` to the installer as workaround?

**Comment by mbien** [comment]
going to close this issue since we don't need so many duplicates.

also added a guide here: #6361
