### ISSUE TITLE
[C/C++] The editor freezes after some queries to clangd LSP unless the logger is turned up

### ISSUE THREAD

**Issue by marc-dll** [apache/netbeans#6297]
### Apache NetBeans version

Apache NetBeans 18

### What happened

I tried setting up Netbeans as an LSP client of `clangd`. After much trial and error from my part, I could configure a correctly formed `compile_commands.json` file to give to `clangd`.

In this state, I get the wanted feedback at first when introducing a parse error (code underlined in red at the error location + message in the statebar), but those reports stop for the subsequent errors. Code completion fails to finish, and trying to reformat the code (`"Source" > "Format"` or `Alt+Shift+F`) freezes the editor.

At first, I tried to analyze logs to see what's what, but nothing reported was coming from this part of NetBeans. I then saw how to turn logging up for specific loggers, thus passing the argument `-J-Dorg.netbeans.modules.cpplite.editor.lsp.LanguageServerImpl.level=100` to target the specific logger of class [`org.netbeans.modules.cpplite.editor.lsp.LanguageServerImpl`](https://github.com/apache/netbeans/blob/master/cpplite/cpplite.editor/src/org/netbeans/modules/cpplite/editor/lsp/LanguageServerImpl.java)

And to my surprise, this made everything work as expected.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 Home (build 19045.3208)

### JDK

Java; VM; Vendor        = 19.0.2; OpenJDK 64-Bit Server VM 19.0.2+7-44; Oracle Corporation

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

clangd version 13.0.1

I did not try to reproduce on Linux yet.

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
> At first, I tried to analyze logs to see what's what, but nothing reported was coming from this part of NetBeans. I then saw how to turn logging up for specific loggers, thus passing the argument `-J-Dorg.netbeans.modules.cpplite.editor.lsp.LanguageServerImpl.level=100` to target the specific logger of class [`org.netbeans.modules.cpplite.editor.lsp.LanguageServerImpl`](https://github.com/apache/netbeans/blob/master/cpplite/cpplite.editor/src/org/netbeans/modules/cpplite/editor/lsp/LanguageServerImpl.java)
> 
> And to my surprise, this made everything work as expected.

I love logging side effects!  This line possibly stands out https://github.com/apache/netbeans/blob/master/cpplite/cpplite.editor/src/org/netbeans/modules/cpplite/editor/lsp/LanguageServerImpl.java#L126  This doesn't seem to do anything with the error stream when logging doesn't redirect it?!  Now this can be Java 11+ this could use `Redirect.DISCARD`?

cc/ @matthiasblaesing @jlahoda

**Comment by matthiasblaesing** [comment]
@marc-dll could you check if #6305 helps?

A test build is available from the checks page of the PR:

 https://github.com/apache/netbeans/suites/14851690491/artifacts/845766405

or directly:

https://github.com/apache/netbeans/suites/14851690491/artifacts/845766405

**Comment by marc-dll** [comment]
@matthiasblaesing Hi, first, thank you for your work !

I was on vacation, and it seems that the link has expired. Could you re-generate it ? Thanks again !

**Comment by matthiasblaesing** [comment]
@marc-dll the tests were rerun and artifact is available again:
- Check Result: https://github.com/apache/netbeans/actions/runs/5772547627
- Direct download: https://github.com/apache/netbeans/suites/14851690491/artifacts/859803698
