### ISSUE TITLE
Cannot add Debian java platforms

### ISSUE THREAD

**Issue by tenzap** [apache/netbeans#6302]
### Apache NetBeans version

Apache NetBeans 18

### What happened

When trying to add java platform on  Debian bookworm it is actually not possible to use the subfolders of `/usr/lib/jvm/`

Moreover for the default JDK (JDK 17), The platform manager says:
`Error: The specified folder does not contain a Java platform.`

### How to reproduce

Got to Tools/Java platforms

The default platform says `Error: The specified folder does not contain a Java platform.`

![image](https://github.com/apache/netbeans/assets/46226844/7c72b92b-206a-4b86-af0c-4763ae6be7f3)

And when adding a platform: it is not possible to continue in the wizard
![image](https://github.com/apache/netbeans/assets/46226844/7ea19c4f-df10-4903-973d-e757aa33eadd)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian Bookworm (12.1)

### JDK

17, 8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I used the deb package provided by apache netbeans

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
i just tested this on debian 12 and it worked for me with openjdk-17 installed from the main debian repo.

bookworm is only offering openjdk-17, I am not sure where you have java 8 from, see:
https://packages.debian.org/bookworm/java/

looks like even debian is moving to modern java :)

**Comment by mbien** [comment]
correct, JDKs are required

**Comment by asbachb** [comment]
@tenzap can we close that issue? I think the only thing there could be improved that the wizards mention that's detected a JRE instead of a JDK.

**Comment by neilcsmith-net** [comment]
We could just change that error message to say `The specified folder does not contain a Java JDK` rather than `Java platform` for clarity?

Sometimes the way that Linux packages split up OpenJDK is a PITA!

**Comment by mbien** [comment]
> We could just change that error message to say The specified folder does not contain a Java JDK rather than Java platform..

I had similar thoughts but would simply replace platform with JDK everywhere in that window? JRE isn't well defined anymore and I don't even know what platform means these days.

Even if you jlink something it can end up being your custom JDK, or a custom runtime for your product, depending on what you throw out.

I just downloaded the temurin JRE `OpenJDK17U-jre_x64_linux_hotspot_17.0.8_7` and it can't be added either (as expected).

**Comment by neilcsmith-net** [comment]
@mbien we could make that wording change in 19-rc5.  We're definitely having another rc, and text should be a pretty safe change!  What do you think?

**Comment by mbien** [comment]
#6325 is this better?

**Comment by matthiasblaesing** [comment]
Closing as fix was merged.
