### ISSUE TITLE
PHP: A typed class field marked as deprecated is displayed as not deprecated

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#6310]
### Apache NetBeans version

Apache NetBeans 18

### What happened

A typed class field marked as deprecated is displayed as not deprecated.

Displaying a field in the navigator:
![deprecated_field](https://github.com/apache/netbeans/assets/9607501/2637645a-7a25-4ea0-a50a-8712df18931f)

Displaying a field in an autocomplete:
![deprecated_field_3](https://github.com/apache/netbeans/assets/9607501/e6c53cdc-83f9-4f1c-9f23-608591866386)

Displaying a field in the editor when "Resolve Deprecated Elements" is checked:
![deprecated_field_2](https://github.com/apache/netbeans/assets/9607501/44419676-503c-4721-9da5-5b7a8397f1cf)

### How to reproduce

 - create a `TestClass.php` file with the `TestClass` class:
 ```php
<?php

class TestClass {

    /** @deprecated */
    public $di1;

    /** @deprecated */
    public int $di2;

    /**
     * @deprecated
     * @var int
     */
    public $di3;

    /**
     * @deprecated
     * @var int
     */
    public int $di4;

}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian GNU/Linux 12 (bookworm)

### JDK

OpenJDK Runtime Environment 17.0.7+7-Debian-1deb12u1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Reproducible. Thank you for reporting it.
