### ISSUE TITLE
Website: Slack invitation link expired

### ISSUE THREAD

**Issue by asbachb** [apache/netbeans#6313]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

When you click on the slack link on the NetBeans main page it shows that the link expired and only people with an `@apache.org` mail address are able to join.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

N/A

### JDK

N/A

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Please bring this up on dev@
