### ISSUE TITLE
Servlet API Classes not on classpath for JSP editor

### ISSUE THREAD

**Issue by ampEducator** [apache/netbeans#6334]
### Apache NetBeans version

Apache NetBeans 18

### What happened

When editing a JSP I get the line 'Servlet API classes are not on the classpath, some scriplet features are disabled.'  

Running the code is fine, the JSP is compiled and runs properly. HTML highlighting / completion works, Tag highlighting / completion work, JS highlight works, it's anything in a Java block <% .... %> that is disabled.

I've looked through the project.properties file and can see that j2ee.platform.classpath is set properly and I also confirmed that j2ee.server.home is correct and pointing to the Tomcat 10 folder. I can see that Tomcat is included in the library folder and it contains the servlet-api jar. I've also tried to add the built it Jakarata EE 10 API and / or Jakarte EE 10 Web API libraries which doesn't work. 

Using Netbeans 18 with Tomcat 10.1.11, Open JDK 17 (17.0.7) on Linux (Ubuntu 18.04.6) . 

We were previously using Netbean 8.2 with Tomcat 8.5 and the JSP editor was fine.

I'm happy to provide any other information / details. I downloaded Netbeans 18 zip folder. I thought maybe this was the issue so I also tried with the installer and same results.

![image](https://github.com/apache/netbeans/assets/95502731/1e210097-9b27-4302-a55d-5f2aa29c2147)

### How to reproduce

Create a new Java App with Ant -> Java Web -> Web Application using the Tomcat Server 10.1 and Jakarta EE 10. Add a new JSP.  Edit the JSP. Editing anything in  Java block <% ..... %> produces the error.

### Did this work correctly in an earlier version?

Apache NetBeans 13 or earlier

### Operating System

Linux

### JDK

OPEN JDK 17.0.7

### Apache NetBeans packaging

Apache NetBeans provided installer, Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by ampEducator** [comment]
I see this was labelled as Ant. I have tried creating a identical new web project with Maven and Gradle and I get the same results. Editing Java blocks in a JSP brings up the 'Servlet API Classes not on classpath...'

**Comment by mbien** [comment]
this is likely due to the new jakarta namespace, if you set the version to 8.x it should work fine:

```xml
    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>8.0.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

**Comment by ampEducator** [comment]
Since we're using Ant I had to add the version 8 of the library (Jakarta EE Web 8 - which is still javax.servlet... instead of the jakarta.servlet....) and the JSP editor works fine but now I have version 8 in my class path and version 10 (from Tomcat). It doesn't make sense to have both? Does the JSP editor have to be updated to use the new version?

**Comment by ampEducator** [comment]
I just noticed you note about the new release candidate. I will try and see if the problem has been fixed in the newer version.

**Comment by mbien** [comment]
> Does the JSP editor have to be updated to use the new version?

Probably. It is likely expecting the old `javax.*` namespace of Java EE 8, since Jakarta EE 9+ uses the new `jakarta.*` namespace.

It got fixed for JSF #6160 (and for many other features), looks like JSPs need some attention too, but this would be too late for NB 19 and would have to wait for the next release.

**Comment by frpascua** [comment]
I have experienced the same behaviour using Netbeans 20 with Tomcat 10.1.5 and OpenJDK Runtime Environment 21.0.1+12-LTS on Windows 10.

Fortunately, it gets resolved if I change jakartaee version as @mbien indicated.

**Comment by matthiasblaesing** [comment]
I'll have a look, the disabling is trivial to fix, the places where the code will fail afterwards will be much more interesting ;-)

**Comment by matthiasblaesing** [comment]
Please see referenced PR for a suggested change. Please test the nightly build available from the checkspage of the PR and report back here:

https://github.com/apache/netbeans/actions/runs/7617306399

or directly:

https://github.com/apache/netbeans/actions/runs/7617306399/artifacts/1186921848

The build is available for the next 5 days.
