### ISSUE TITLE
Compiler Option is not available

### ISSUE THREAD

**Issue by tulsirai** [apache/netbeans#6337]
### Apache NetBeans version

Apache NetBeans 18

### What happened

I wanted to set "--enable-preview"  for the compiler which is availble Netbeans 8 but I don't see it in Netbeans 18. This  option is required to get the new features of JDK compiled. Since I cannot set this option, I am unable to compile the codes written in JDK 17 and get the following comiler error:

patterns in swithc statements are a preview feature and are disabled by default.
(use --enable-preview to enable patterns in switch statements)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows

### JDK

17

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
what project type are you using?

![image](https://github.com/apache/netbeans/assets/114367/73815d83-882a-4919-8074-80f2f6596977)

**Comment by mbien** [comment]
closing due to no response
