### ISSUE TITLE
Critical error when install netbeans (Comparison method violates its general contract!)

### ISSUE THREAD

**Issue by Uzumaki-Kontoru** [apache/netbeans#6339]
### Apache NetBeans version

Apache NetBeans 18

### What happened

when I try to install netbeans, a critical error appears saying:

"An unexpected exception happened in thread AWT-EventQueue-0

Exceptions:
java.lang.IllegalArgumentException:
Comparison method violates its general contract!"

### How to reproduce

Please help me solve the problem

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

Jdk-20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This problem occur when i click "next" after agree terms and conditions

### Are you willing to submit a pull request?

Yes

**Comment by troizet** [comment]
Dulplicate #6289.

**Comment by mbien** [comment]
JDK bug:
https://bugs.openjdk.org/browse/JDK-8305072

it has something to do of having the wrong combination of folders on your system which breaks the file chooser, not much we can do unfortunately.

**Comment by mbien** [comment]
for workarounds see #6361

**Comment by mbien** [comment]
fixed in JDK 23 -> https://github.com/openjdk/jdk/pull/18126
