### ISSUE TITLE
Delayed Startup.... or did not startup program ide 12

### ISSUE THREAD

**Issue by AzlanAbdullah** [apache/netbeans#6343]
### Apache NetBeans version

Apache NetBeans 12

### What happened

When click to start it just go into program but did not load the files in workarea..... just like that continously i had to close then restart back...

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

JDK 12

### Apache NetBeans packaging

Apache NetBeans provided installer, Apache NetBeans platform

### Anything else
```

<record>
  <date>2023-08-15T20:52:16</date>
  <millis>1692103936707</millis>
  <sequence>56</sequence>
  <level>700</level>
  <thread>29</thread>
  <message>UI_USER_CONFIGURATION</message>
  <key>UI_USER_CONFIGURATION</key>
  <catalog>org.netbeans.modules.uihandler.Bundle</catalog>
  <param>Windows 10, 10.0, amd64</param>
  <param>Java HotSpot(TM) 64-Bit Server VM, 12.0.2+10, Java(TM) SE Runtime Environment, 12.0.2+10</param>
  <param>Apache NetBeans IDE 12.0</param>
  <param></param>
  <param>org.netbeans.modules.deadlock.detector.Detector$DeadlockDetectedException: Editor Parsing Loop (12.0-u2-ba34c2dabd3091a6ee93cfde08a653816a7e19ea)</param>
  <param>&lt;Please provide a description of the problem or the steps to reproduce&gt;</param>
  <param>*********</param>
</record>

```

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
> `<param>Apache NetBeans IDE 12.0</param>`

The current version of NetBeans is 18. Please check that you are running the latest release before [reporting issues.](https://netbeans.apache.org/participate/report-issue.html) Closing.
