### ISSUE TITLE
In my JSP page after press ctl + space no suggestion is showing, JAVA code not showing in my Netbean JSP page

### ISSUE THREAD

**Issue by sudhirp5454** [apache/netbeans#6356]
### Apache NetBeans version

Apache NetBeans 18

### What happened

In my JSP page after press ctl + space no suggestion is showing, JAVA code not showing in my Netbean JSP page.

Many JSP page create but no any code suggestions showing also doing setting in tools-option-auto complete.

![image](https://github.com/apache/netbeans/assets/142535964/1751d04a-eb37-4deb-bc41-f32c0c794b95)

### How to reproduce

![image](https://github.com/apache/netbeans/assets/142535964/4aaba377-74d8-45c8-b8af-257567e56043)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 11

### JDK

jdk 20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

No

### Are you willing to submit a pull request?

No

**Comment by asbachb** [comment]
@sudhirp5454 

1) Which servlet spec version you're using?
2) Can you give NetBeans 19-rc5 a try there were quite a lot fixes for enterprise functionality.

**Comment by sudhirp5454** [comment]
I am using letest version of NetBeans.

**Comment by asbachb** [comment]
@sudhirp5454 the screenshots showing you're using NetBeans 18. Please try the Release Candidate of NetBeans 19.

**Comment by mbien** [comment]
sounds like #6334

**Comment by sudhirp5454** [comment]
Team,

There is no any 19th version release for download.


Pls help in this version, in java page suggestions showing but in jsp no
any suggestions showing.

**Comment by troizet** [comment]
You can download the release candidate at the links provided [here](https://github.com/apache/netbeans/discussions/6225).

**Comment by sudhirp5454** [comment]
Dear Team,

No any solution for NetBeans 19. No code suggestions in JSP file, in JAVA
file suggestions showing.

Team Pls help me on this issue sirji, with warm request.

[image: image.png]

[image: image.png]

**Comment by mbien** [comment]
> any solution for NetBeans 19. No code suggestions in JSP file

it should work as long you use Jakarta EE 8 (or Java EE 8) for JSPs. For Jakarta EE 9+ it will have to get fixed in NetBeans first.

This will have to wait for the next release unfortunately.

**Comment by sudhirp5454** [comment]
So for this issue, what should I do get fixed.

Instal JAVA EE 9 OR

**Comment by sudhirp5454** [comment]
Hi pls help on this or should I change NetBeans to another IDE for resolution of this issue

**Comment by asbachb** [comment]
NetBeans is a community driven project which most people or doing in their free time. So if this is an urgent issue for you feel free to have a look into that issue and open up a pull request or put a bug bounty on that issue.
Jakarta EE is still not fully supported as it's a lot of effort to bring back all the functionality.

**Comment by Hopex-Creator** [comment]
You managed to find a solution

**Comment by matthiasblaesing** [comment]
Please see referenced PR for a suggested change. Please test the nightly build available from the checkspage of the PR and report back here:

https://github.com/apache/netbeans/actions/runs/7617306399

or directly:

https://github.com/apache/netbeans/actions/runs/7617306399/artifacts/1186921848

The build is available for the next 5 days.
