### ISSUE TITLE
[PHP] No auto-completion for DEBUG_BACKTRACE_* pre-defined constants

### ISSUE THREAD

**Issue by marc-dll** [apache/netbeans#6358]
### Apache NetBeans version

Apache NetBeans 18

### What happened

The PHP pre-defined constants `DEBUG_BACKTRACE_PROVIDE_OBJECT` and `DEBUG_BACKTRACE_IGNORE_ARGS` (see [this PHP doc page](https://www.php.net/manual/en/function.debug-backtrace.php)) are not part of the auto-completed symbols.

I investigated a bit about that and they are not to be found in the generated stubs from the `<netbeans_path>/php/docs/phpsigfiles.zip` (which, if I understood correctly, are not poart of this repo but are grabbed from https://netbeans.osuosl.org/binaries/ when NetBeans is built). The `debug_backtrace()` function is correctly defined in the file `phpstubs/phpruntime/errorfunc.php` inside the last version of this zip file.

By the way, the [error level pre-defined constants](https://www.php.net/manual/en/errorfunc.constants.php) are correctly auto-completed, but they are incorrectly generated inside this same `phpstubs/phpruntime/errorfunc.php` stub file :

```
/**
 * Fatal run-time errors. These indicate errors that can not be recovered from, such as a memory allocation problem. Execution of the script is halted.
 */
define('1', null);

/**
 * User-generated notice message. This is like an <b><code>E_NOTICE</code></b>, except it is generated in PHP code by using the PHP function <code>trigger_error()</code>.
 */
define('1024', null);

/**
 * Compile-time warnings (non-fatal errors). This is like an <b><code>E_WARNING</code></b>, except it is generated by the Zend Scripting Engine.
 */
define('128', null);

/**
 * Fatal errors that occur during PHP's initial startup. This is like an <b><code>E_ERROR</code></b>, except it is generated by the core of PHP.
 */
define('16', null);

/**
 * User-generated warning message. This is like an <b><code>E_DEPRECATED</code></b>, except it is generated in PHP code by using the PHP function <code>trigger_error()</code>.
 */
define('16384', null);

/**
 * Run-time warnings (non-fatal errors). Execution of the script is not halted.
 */
define('2', null);

/**
 * Enable to have PHP suggest changes to your code which will ensure the best interoperability and forward compatibility of your code.
 */
define('2048', null);

/**
 * User-generated error message. This is like an <b><code>E_ERROR</code></b>, except it is generated in PHP code by using the PHP function <code>trigger_error()</code>.
 */
define('256', null);

/**
 * Warnings (non-fatal errors) that occur during PHP's initial startup. This is like an <b><code>E_WARNING</code></b>, except it is generated by the core of PHP.
 */
define('32', null);

/**
 * All errors, warnings, and notices.
 */
define('32767', null);

/**
 * Compile-time parse errors. Parse errors should only be generated by the parser.
 */
define('4', null);

/**
 * Catchable fatal error. It indicates that a probably dangerous error occurred, but did not leave the Engine in an unstable state. If the error is not caught by a user defined handle (see also <code>set_error_handler()</code>), the application aborts as it was an <b><code>E_ERROR</code></b>.
 */
define('4096', null);

/**
 * User-generated warning message. This is like an <b><code>E_WARNING</code></b>, except it is generated in PHP code by using the PHP function <code>trigger_error()</code>.
 */
define('512', null);

/**
 * Fatal compile-time errors. This is like an <b><code>E_ERROR</code></b>, except it is generated by the Zend Scripting Engine.
 */
define('64', null);

/**
 * Run-time notices. Indicate that the script encountered something that could indicate an error, but could also happen in the normal course of running a script.
 */
define('8', null);

/**
 * Run-time notices. Enable this to receive warnings about code that will not work in future versions.
 */
define('8192', null);

```

I guess all of this in automatically generated from the PHP documentation, so a manual fix would be out of the question.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 / Ubuntu 20.04

### JDK

OpenJDK Runtime Environment 19.0.2+7-44

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
> The PHP pre-defined constants `DEBUG_BACKTRACE_PROVIDE_OBJECT` and `DEBUG_BACKTRACE_IGNORE_ARGS` (see [this PHP doc page](https://www.php.net/manual/en/function.debug-backtrace.php)) are not part of the auto-completed symbols.

Maybe, they should be added to https://www.php.net/manual/en/errorfunc.constants.php, I think.
Can you do it?

> By the way, the [error level pre-defined constants](https://www.php.net/manual/en/errorfunc.constants.php) are correctly auto-completed, but they are incorrectly generated inside this same `phpstubs/phpruntime/errorfunc.php` stub file :

I'll fix it. Thanks!
