### ISSUE TITLE
[PHP] Cases of auto-completion not matching with single-line DocComments

### ISSUE THREAD

**Issue by marc-dll** [apache/netbeans#6359]
### Apache NetBeans version

Apache NetBeans 18

### What happened

I stumbled upon a strange - and rare - case where DocComment based auto-completion would fail when the said comment is single-line.

The concrete case I found this issue is working with CakePHP 3.x. In this framework, you can use a method to fill a `Controller` property with a `Table` subclass. For convenience, I explicitly declare this property with an attached DocComment, to be able to use method auto-completion, as follows :

```php
<?php

namespace App\Controller;

class ExampleController extends \Cake\Controller\Controller
{
    /** @var \App\Model\Table\ExamplesTable $Examples */
    protected $Examples;

    // This method is called in parent::__construct()
    public function initialize()
    {
        parent::initialize();

        // Cake\Controller\Controller::loadModel() instantiates the given table
        $this->loadModel('Examples');
    }
}
```

By auto-completion failing, I mean looking for results after typing `$this->` correctly gets `Examples` in the results, but cannot display its type/class, and after typing `$this->Examples->`, I get no method matches from this class.

Despite all my efforts, I could never get auto-completion to work... until today, when I wrote the DocComment on multiple lines !

This strange behavior only happens when the attribute instantiation is not straightforward (like when assigning to `$this->$var`). When `$this->Examples` is assigned an expression that can be typed as the target class, be it using `new` or a function/method that explicitly returns the wanted class), everything is fine in all cases.

See below the most simple repro I could write.

### How to reproduce

This works as expected :

```php
<?php

class X
{
    public function iShouldAppearInTheCompletionResults() {}
}

class Y
{
    /**
     * @var \X $X
     */
    protected $X;

    public function __construct()
    {
        $this->load('X');
    }

    public function load($class)
    {
        $this->$class = new $class();
    }

    public function callMethodOfX()
    {
        $this->/* Trigger autocomplete with the cursor to the left of this comment */
        $this->X->/* Trigger autocomplete with the cursor to the left of this comment */
    }
}

```

This doesn't :

```php
<?php

class X
{
    public function iShouldAppearInTheCompletionResults() {}
}

class Y
{
    /** @var \X $X */
    protected $X;

    public function __construct()
    {
        $this->load('X');
    }

    public function load($class)
    {
        $this->$class = new $class();
    }

    public function callMethodOfX()
    {
        $this->/* Trigger autocomplete with the cursor to the left of this comment */
        $this->X->/* Trigger autocomplete with the cursor to the left of this comment */
    }
}


```

The only difference being the DocComment being single-line.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 Home / Ubuntu 20.04

### JDK

OpenJDK Runtime Environment 19.0.2+7-44

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Reproducible. Thanks for reporting it.
