### ISSUE TITLE
java.lang.IllegalArgumentException   AWT-EventQueue-0

### ISSUE THREAD

**Issue by bimoso** [apache/netbeans#6360]
### Apache NetBeans version

Apache NetBeans 18

## Me sale este error a quererlo instalar, antes ya lo habia instalado pero lo borre y ahora que lo requiero de nuevo me da este error:

when I try to install netbeans, a critical error appears saying:

"An unexpected exception happened in thread AWT-EventQueue-0

Exceptions:
java.lang.IllegalArgumentException:
Comparison method violates its general contract!"

### How to reproduce

No se la causa, pero como a mencione al intentar instalarlo, despues de darle en aceptar a los terminos y condiciones y en aceptar me sale la ventana con el error

![imagen_2023-08-18_200322956](https://github.com/apache/netbeans/assets/129549698/0c21c013-6cd4-4c7b-bb36-b695334156bd)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

20 también probé con el 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Incluso borre todo lo relacionado con NetBeans pero sigue dando error, ya desinstale e instale JDK  y Java, incluso probé con NetBeans 17 y lo mismo

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
please use english if possible

this is a windows specific JDK bug and will keep happening even after installation (https://bugs.openjdk.org/browse/JDK-8305072).

The community installers which are linked from the download page are not affected by this. Once installed you will have to add `-J-Djava.util.Arrays.useLegacyMergeSort=true` to your netbeans.conf.

duplicates #6289, #6339, ....

**Comment by mbien** [comment]
added a guide here: #6361

**Comment by bimoso** [comment]
> please use english if possible
> 
> this is a windows specific JDK bug and will keep happening even after installation (https://bugs.openjdk.org/browse/JDK-8305072).
> 
> The community installers which are linked from the download page are not affected by this. Once installed you will have to add `-J-Djava.util.Arrays.useLegacyMergeSort=true` to your netbeans.conf.
> 
> duplicates #6289, #6339, ....

Hello, I don't have the possibility to modify the netbeans.conf because I don't have it installed, the error is in the installation so that file doesn't exist on my machine, I don't know if there is another solution

**Comment by bimoso** [comment]
> > please use english if possible
> > this is a windows specific JDK bug and will keep happening even after installation (https://bugs.openjdk.org/browse/JDK-8305072).
> > The community installers which are linked from the download page are not affected by this. Once installed you will have to add `-J-Djava.util.Arrays.useLegacyMergeSort=true` to your netbeans.conf.
> > duplicates #6289, #6339, ....
> 
> Hello, I don't have the possibility to modify the netbeans.conf because I don't have it installed, the error is in the installation so that file doesn't exist on my machine, I don't know if there is another solution

very well I will try with one of the community

**Comment by edcazu** [comment]
> ### Apache NetBeans version
> Apache NetBeans 18
> 
> ### What happened
> ## Me sale este error a quererlo instalar, antes ya lo habia instalado pero lo borre y ahora que lo requiero de nuevo me da este error:
> when I try to install netbeans, a critical error appears saying:
> 
> "An unexpected exception happened in thread AWT-EventQueue-0
> 
> Exceptions: java.lang.IllegalArgumentException: Comparison method violates its general contract!"
> 
> ### How to reproduce
> No se la causa, pero como a mencione al intentar instalarlo, despues de darle en aceptar a los terminos y condiciones y en aceptar me sale la ventana con el error
> 
> ![imagen_2023-08-18_200322956](https://user-images.githubusercontent.com/129549698/261751546-0c21c013-6cd4-4c7b-bb36-b695334156bd.png)
> 
> ### Did this work correctly in an earlier version?
> No / Don't know
> 
> ### Operating System
> Windows 11
> 
> ### JDK
> 20 también probé con el 17
> 
> ### Apache NetBeans packaging
> Apache NetBeans provided installer
> 
> ### Anything else
> Incluso borre todo lo relacionado con NetBeans pero sigue dando error, ya desinstale e instale JDK y Java, incluso probé con NetBeans 17 y lo mismo
> 
> ### Are you willing to submit a pull request?
> No

Encontré una forma "no muy elegante", intenta instalar con el parámetro "--silent"

**Comment by mbien** [comment]
fixed in JDK [22.0.2](https://bugs.openjdk.org/browse/JDK-8331058) and 23
