### ISSUE TITLE
The copy and paste feature sometimes doesn't work

### ISSUE THREAD

**Issue by tannancun** [apache/netbeans#6385]
### Apache NetBeans version

Apache NetBeans 18

### What happened

The copy and paste feature sometimes doesn't work

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

windowns 10

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

The copy and paste feature sometimes doesn't work

### Are you willing to submit a pull request?

Yes

**Comment by wumpz** [comment]
duplicate of #3962
