### ISSUE TITLE
ZIP file broken

### ISSUE THREAD

**Issue by zzador** [apache/netbeans#6388]
### Apache NetBeans version

Apache NetBeans 18

### What happened

Downloaded the ZIP file 3 times from different sources. Every file was broken and couldn't be decompressed.
Tested it with Windowws Explorer & 7Zip.

7Zip located the error in file: netbeans/apisupport/modules/org-netbeans-modules-maven-apisupport.jar

### How to reproduce

Just try to decompress netbeans-18-bin.zip

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Windows 10

### JDK

17

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by ebarboni** [comment]
I cannot reproduce. 
The download page https://www.apache.org/dyn/closer.cgi/netbeans/netbeans/18/netbeans-18-bin.zip leads to valid zip for me.

Using windows default unzip.

**Comment by neilcsmith-net** [comment]
Make sure to verify against the hash after downloading (as well as using trying the default unzip as mentioned).
