### ISSUE TITLE
I cannot convert the project to a jar file

### ISSUE THREAD

**Issue by Bassam1132** [apache/netbeans#6397]
### Apache NetBeans version

Apache NetBeans 18

### What happened

![‏‏لقطة الشاشة (24)](https://github.com/apache/netbeans/assets/108855005/caabf4a8-0b32-4d15-8414-5764ef339331)

### How to reproduce

I want same this 

![لقطة شاشة 2023-08-31 112256](https://github.com/apache/netbeans/assets/108855005/e4aa127c-f49d-4ca5-a934-85d730cdd49a)

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Window 11

### JDK

JDK-19

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Closing as you've already opened #6398 which is where usage questions really belong.
