### ISSUE TITLE
[PHP] PHP code sniffer warning Expected 1 lines after "if"

### ISSUE THREAD

**Issue by JoaquinBecerraAtValtech** [apache/netbeans#6400]
### Apache NetBeans version

Apache NetBeans 18

### What happened

When I use the autoformating function (shft + alt + f) Does not perform formatting correctly before and after IF commands:

Looks like there isn't an option on the formating tool to mark lines before and after the if statement

Correct:
```php
        if (!$something) {
            return;
        }
        
        $var3 = 1;`
```

Incorrect:
        
```php
        if (!$something) {
            return;
        }        
        $var3 = 1
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux Mint

### JDK

11.0.14; OpenJDK 64-Bit Server VM 11.0.14+9-Ubuntu-0ubuntu2.20

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
I can't reproduce it. Please write an example code to reproduce it.

**Comment by terax6669** [comment]
> I can't reproduce it. Please write an example code to reproduce it.

I think OP wants there to be an empty line after the if statement.

**Comment by junichi11** [comment]
No response. Please feel free to reopen it. Closing...
