### ISSUE TITLE
When tried to open netbeans 19 after updated by snap it complains about jdk previous to 11

### ISSUE THREAD

**Issue by alcarraz** [apache/netbeans#6423]
### Apache NetBeans version

Apache NetBeans 19 release candidate

### What happened

I have netbeans installed in ubuntu via snap, after automatic update to netbeans 19, it stopped working.

### How to reproduce

Launch netbeans, via terminal or via desktop and I get the advice says:

```
Cannot run on older versions of Java than Java 11.
Please install Java 11 or newer or use --jdkhome
switch to point to its installation directory.
```

Passing `--jdkhome` does not solve the issue.

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Ubuntu 23.04

### JDK

Tried with many, but I guess it is using the one packaged in the snap

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
> JDK
>
> Tried with many, but I guess it is using the one packaged in the snap

There is no JDK packaged in the Snap.  It should use the `javac` location found on the path, although I'm not 100% sure if the Snap packaging messes with that logic at all.  What does `javac -version` give you?

Not sure how you're passing `--jdkhome`?

If you do want a self-contained version with a packaged JDK runtime, check the community deb or appimage.

**Comment by alcarraz** [comment]
I was passing:

```shell-session
$ /snap/bin/netbeans  --jdkhome /usr/lib/jvm/java-11-openjdk-amd64/
```

But it seems there is where sources are, and not the jdk itself,

Passing `--jdkhome /usr/lib/jvm/java-11-openjdk-amd64/` works.

**Comment by psad73** [comment]
you may have the javac set to a previous version. In my case "sudo update-alternatives --config javac" and set the default worked without need  to add any additional params to netbeans.

**Comment by alcarraz** [comment]
Thank you, yes, my default is java 8, and on purpose because most of my developments are in that version, that's why I chose to modify the netbeans config instead. I use sdkman to chose different jdk/maven/gradle version on a per project basis, but my sane default as a developer is still java 8.

> you may have the javac set to a previous version. In my case "sudo update-alternatives --config javac" and set the default worked without need to add any additional params to netbeans.

**Comment by neilcsmith-net** [comment]
@alcarraz your two locations look the same above! 

You can create a secondary `netbeans.conf` in the userdir (wherever that is with the Snap). For other packages at `~/.netbeans/19/etc/netbeans.conf`.  Add a single line with the location of your desired runtime JDK.

`netbeans_jdkhome="/path/to/jdk"`

I'd also note that NetBeans IDE stopped supporting running on JDK 8 with NetBeans 13.  The platform stopped supporting it with NetBeans 19, which is why you're getting the new message now.  NetBeans 22 will drop support for JDK 11.

**Comment by arirzwn** [comment]
I got a similar problem but on Windows Os, how to solve it?

**Comment by neilcsmith-net** [comment]
@arirzwn use a different JDK, or use the community installer with local bundled JDK 20.

If you see this error you're trying to run on JDK 8. That has not been supported since NetBeans 12.6. It is now a hard fail.

**Comment by arirzwn** [comment]
I use jdk-21 version, should i use JDK 20?
