### ISSUE TITLE
Apache Netbeans Installer for macOS 10.x ?

### ISSUE THREAD

**Issue by autumoswitzerland** [apache/netbeans#6430]
### Description

Would it be so wrong to still support macOS 10.x? I assume in the app-package there should only be a netbeans wrapper binary "Contents/MacOS/netbeans" that can be run on macOS 10.x too.

### Use case/motivation

Installing & running Apache Netbeans on macOs 10.x.

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
> Would it be so wrong to still support macOS 10.x?

Does Apple?!

> I assume in the app-package there should only be a netbeans wrapper binary "Contents/MacOS/netbeans" that can be run on macOS 10.x too.

With NetBeans 19 we swapped to using NBPackage to build the macOS installer.  This builds the Swift launcher in `Contents/MacOS` as a universal binary when no local JDK is included (as we cannot from ASF). As part of that change https://github.com/apache/netbeans-nbpackage/pull/32 the minimum macOS version was raised from 10.13 to 11.

I think in theory we could build the x86_64 aspect against a lower macOS version, but that would complicate the process.  A PR might be accepted, but it would have to cover all three possible combinations of architecture cleanly and not cause complications.  I'm not sure if it's worth the effort?

If you need to use NetBeans 19 on macOS 10.x you're stuck with the zip distribution.

**Comment by autumoswitzerland** [comment]
No, I don't think it's worth the effort. I built Netbeans 19 from the ZIP distribution. Maybe I can create an executable file myself? But that doesn't seem to be so easy with "netbeans-nbpackage-master" - at least it doesn't seem obvious how to properly define the package command for it. The aim would be to run it without a command like "ant tryme".

Any suggestions?
Also, what are the downloadable builds? Basic, Full or Platform?

Thanks!
