### ISSUE TITLE
php 8.1 Use named arguments after unpacking: error hint

### ISSUE THREAD

**Issue by iliavlad** [apache/netbeans#6432]
### Apache NetBeans version

Apache NetBeans 19

### What happened

When using named arguments after unpacking Netbeans shows error hint (php version in Netbeans is set up to 8.2)

```php
<?php
function test($a, $b, $c) {}
test(...[1,2], c: 3);
```

Expected: no error hint

Actual: error hint presents

![hint in netbeans](https://github.com/apache/netbeans/assets/190661/00f3dbb4-8eda-4d8d-bf23-5e765400d452)

### How to reproduce

function test($a, $b, $c) {}

test(...[1,2], c: 3);

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Win11

### JDK

20.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

It occurs every time

Please, check https://www.php.net/manual/en/functions.arguments.php

Example 20 Use named arguments after unpacking

```php
<?php
function foo($a, $b, $c = 3, $d = 4) {
  return $a + $b + $c + $d;
}

var_dump(foo(...[1, 2], d: 40)); // 46
var_dump(foo(...['b' => 2, 'a' => 1], d: 40)); // 46
```

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Reproducible. Thank you for reporting it.
