### ISSUE TITLE
Illegal reflective access by org.netbeans.swing.dirchooser.DelegatingChooserUI

### ISSUE THREAD

**Issue by dannymk** [apache/netbeans#6433]
### Apache NetBeans version

Apache NetBeans 19

### What happened

Started netbeans and got the following error:

WARNING: package sun.awt.X11 not in java.desktop
WARNING: package com.sun.java.swing.plaf.gtk not in java.desktop
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.swing.dirchooser.DelegatingChooserUI (jar:file:/Users/daniel/Applications/netbeans/ide/modules/org-netbeans-swing-dirchooser.jar!/) to method com.apple.laf.AquaFileChooserUI.createUI(javax.swing.JComponent)
WARNING: Please consider reporting this to the maintainers of org.netbeans.swing.dirchooser.DelegatingChooserUI
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS Ventura (v13.5.2) - Apple M1 Max chip

### JDK

jdk14.0.2

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
JDK 14 is EOL, please switch to the latest update release of JDK 11, 17 or 20. There are also convenient community packages available which bundle an up to date JDK for NetBeans.

The warning is still a bit unusual, are you using the old aqua look and feel?

> Started netbeans and got the following error:

what isn't working? You posted only warning messages, no exception.
