### ISSUE TITLE
"optional" option not supported in less file

### ISSUE THREAD

**Issue by VinceT** [apache/netbeans#6447]
### Apache NetBeans version

Apache NetBeans 19

### What happened

Hi, 
The following line in a .less file:

@import (optional) "user.less";

generates the non-blocking error message "Unexpected token IDENT found" though it is valid code (https://lesscss.org/features/#import-atrules-feature-optional).

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 64

### JDK

Java 17.0.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
A fix is proposed as part of #6451. Please check it. Test builds are available:

- From the checks summary page: https://github.com/apache/netbeans/actions/runs/6190122968
- Or directly: https://github.com/apache/netbeans/suites/16181456062/artifacts/924240381
