### ISSUE TITLE
IntegrationTest results of aQuarkus-project are not shown in Test Results window

### ISSUE THREAD

**Issue by ChMThiel** [apache/netbeans#6448]
### Apache NetBeans version

Apache NetBeans 19

### What happened

After running an IT of a Quarkus-project i expect to see the test-results in the Test Results tab. 
But nothing is shown...

### How to reproduce

1. Create a new Quarkus-project (see https://quarkus.io/get-started/)
2. Open the project in netbeans
3. Navigate to the GreetingResourceIT
3.1. right-klick -> 'Test file' 
3.2 Re-run with different parameters, add skipITs=false (IT will be skipped by default, see https://quarkus.io/guides/getting-started-testing#quarkus-integration-test)

### Did this work correctly in an earlier version?

Apache NetBeans 13 or earlier

### Operating System

Kubuntu

### JDK

jdk-17.0.2

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Can replicate with a basic project. Only unit test results are shown in the test result window.

This didn't work correctly before, btw - it would run the integration test as a unit test.

Putting the milestone on for tracking purposes for now.

**Comment by sroeper** [comment]
@neilcsmith-net Can also replicate this behaviour. Switching to an older maven version (i.e. 3.8.6) shows the test results in the output window (no test result window is shown).
With maven >= 3.9.3 there is no output from the maven-failsafe-plugin shown, only  build success.

_"This didn't work correctly before, btw - it would run the integration test as a unit test."_

I don#t think you are right with this. I can clearly see the maven command at the beginning of the output window and this says mvn  pre-integration-test failsafe:integration-test
What would you expect as maven command for an integration test?

**Comment by sroeper** [comment]
@neilcsmith-net, @ChMThiel 
If you go to Project Properties / Actions / Integration test file and remove all properties except it.test=${packageClassName} then you will get at least an output to the output window (but the Test result window will not open)

**Comment by neilcsmith-net** [comment]
> I don't think you are right with this. I can clearly see the maven command at the beginning of the output window and this says mvn pre-integration-test failsafe:integration-test What would you expect as maven command for an integration test?

@sroeper that!  This changed in NB14 with #4096 The Test Results UI was reported as working above in NB13 or earlier - eg. _when the integration test was being run as a unit test_.

**Comment by neilcsmith-net** [comment]
Added a minimal change that at least triggers the test output UI if `failsafe:integration-test` is in the goals.  Curious if you can check a dev build from https://github.com/apache/netbeans/actions/runs/6732400660 when it completes (zip will be under graph), and see if that helps at all with your particular project?

**Comment by ChMThiel** [comment]
I'll give it a try

**Comment by neilcsmith-net** [comment]
Thanks @ChMThiel .  This change is in 20-rc3 now linked from #6581 

Will close, but comment if there are any problems.  There's certainly some more we could improve just here, as mentioned in the pull request description.
