### ISSUE TITLE
Netbeans 19 Maven RCP project references SNAPSHOT nbm-maven-plugin

### ISSUE THREAD

**Issue by onkelrico** [apache/netbeans#6450]
### Apache NetBeans version

Apache NetBeans 19

### What happened

Create Maven based NB platform application project in NB19
pom.xml references nbm-maven-plugin:14.0-SNAPSHOT which doesn't exist:

```
[ERROR] Unresolveable build extension: Plugin org.apache.netbeans.utilities:nbm-maven-plugin:14.0-SNAPSHOT or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.netbeans.utilities:nbm-maven-plugin:jar:14.0-SNAPSHOT (absent): Could not find artifact org.apache.netbeans.utilities:nbm-maven-plugin:jar:14.0-SNAPSHOT @ 
[ERROR] Unknown packaging: nbm-application @ line 12, column 16
```

```xml
<plugin>
    <groupId>org.apache.netbeans.utilities</groupId>
    <artifactId>nbm-maven-plugin</artifactId>
    <version>14.0-SNAPSHOT</version>
    <extensions>true</extensions>
    <configuration>
        <brandingToken>${brandingToken}</brandingToken>
        <cluster>${brandingToken}</cluster>
    </configuration>
</plugin>
```

Workaround: Adjusting version to 4.8 will do.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Win11

### JDK

15

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

No

**Comment by ramiswailem** [comment]
You need to include the right repo wich include the artefacts

https://repository.apache.org/content/groups/snapshots/org/apache/netbeans/utilities/nbm-maven-plugin/14.0-SNAPSHOT/


        <repository>
            <id>apache-snapshots1</id>
            <name>Apache Snapshot Repository</name>
            <url>https://repository.apache.org/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>

**Comment by mbien** [comment]
@onkelrico have you built the maven plugin locally in past (e.g is  it in your local repo)? If you put the cursor inside the version tag and use auto completion, what versions does it suggest?

I tested both, the "NetBeans Module" and "NetBeans Application" wizards and both generated a variant of:
```xml
                <plugin>
                    <groupId>org.apache.netbeans.utilities</groupId>
                    <artifactId>nbm-maven-plugin</artifactId>
                    <version>4.8</version>
                    <extensions>true</extensions>
                    <configuration>
                        <brandingToken>${brandingToken}</brandingToken>
                        <cluster>${brandingToken}</cluster>
                    </configuration>
                </plugin>
```
no need to add extra repos, all NB artifacts are on maven central.

**Comment by onkelrico** [comment]
> @onkelrico have you built the maven plugin locally in past (e.g is it in your local repo)? If you put the cursor inside the version tag and use auto completion, what versions does it suggest?
> 
> I tested both, the "NetBeans Module" and "NetBeans Application" wizards and both generated a variant of:
> 
> ```
>                 <plugin>
>                     <groupId>org.apache.netbeans.utilities</groupId>
>                     <artifactId>nbm-maven-plugin</artifactId>
>                     <version>4.8</version>
>                     <extensions>true</extensions>
>                     <configuration>
>                         <brandingToken>${brandingToken}</brandingToken>
>                         <cluster>${brandingToken}</cluster>
>                     </configuration>
>                 </plugin>
> ```
> 
> no need to add extra repos, all NB artifacts are on maven central.

Hi @mbien, I did the action in previous versions, but I am fully setting up a new project in the new version. Auto completion gives me all versions up to 4.8 and 14.0-SNAPSHOT and 4.9-SNAPSHOT. Repeating the procedure (setup new NB platform Application) always leads me to the same result. pom.xml includes 14.0-SNAPSHOT and further project actions stuck therefore. Is it an option issue somehow? Following repositories are configured:

- https://repo.maven.apache.org/maven2/
- https://repository.apache.org/content/repositories/snapshots/

**Comment by mbien** [comment]
4,8 is the latest release which is on maven central. The snapshots are not released.

You shouldn't use the snapshot repository in most cases, unless you are testing staged builds of upcoming releases for example.

What we should do however is to filter snapshot releases from the new project wizard so that it doesn't upgrade the version to unreleased artifacts. I remember doing this in other wizards, this one must have slipped through.
