### ISSUE TITLE
aarch64 is used instead of amd64 when installing a module with "OpenIDE-Module-Requires: org.openide.modules.jre.JavaFX".

### ISSUE THREAD

**Issue by philippefichet** [apache/netbeans#6460]
### Apache NetBeans version

Apache NetBeans 19

### What happened

When I want to install the asciidoc4netbeans module (download from https://plugins.netbeans.apache.org/catalogue/?id=91), I get the message "Some plugins require capability org.openide.modules.arch.aarch64"

![javafx-aarch64-on-amd64](https://github.com/apache/netbeans/assets/6843043/abf1afaf-9ebd-409d-aeb4-9199f83cf916)

### How to reproduce

From an "Ubuntu 22.04.3 LTS" installation on an AMD64 CPU (`System.getProperty("os.arch") must return "amd64")

Download the file https://plugins.netbeans.apache.org/catalogue/download/404/asciidoc4netbeans-1.0.1.nbm.
Add the file to the "Downloaded" section of the plugins and launch the installation.

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Ubuntu 22.04.3 LTS

### JDK

17.0.8.1+1-Ubuntu-0ubuntu122.04

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Other JavaFX-based plug-ins are disabled.

![embedded-browser-disabled](https://github.com/apache/netbeans/assets/6843043/fe79062b-dfe1-4e56-8233-0b5e8f8157d7)

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
I could install it on a dev build (manjaro linux, x86_64):
![image](https://github.com/apache/netbeans/assets/114367/cc871a60-2771-430d-9f02-b1b2e23bf178)

the only change I remember in that area would be #6028

**Comment by matthiasblaesing** [comment]
@philippefichet please check the dev build from PR #6477:

- Checkspage: https://github.com/apache/netbeans/actions/runs/6265181725
- Directdownload: https://github.com/apache/netbeans/suites/16422578776/artifacts/938626335

**Comment by philippefichet** [comment]
@matthiasblaesing Sorry for the wait, I tested by building Netbeans with the patch on the "master" branch and everything is OK for me.
A big thank you :)
