### ISSUE TITLE
Netbeans parses property in __constuct() as unused

### ISSUE THREAD

**Issue by iliavlad** [apache/netbeans#6461]
### Apache NetBeans version

Apache NetBeans 19

### What happened

please, check the code. Both "testA" and "testB" are used in __constuct(), but "testB" is marked as "unused"

```php
class A
{
    public function __construct(
            private string $testA,
            private string $testB,
        )
    {
        echo $this->testA;
        echo $testB;
    }
}

$a = new A('testA', 'testB');
```

screenshot
![unused vars](https://github.com/apache/netbeans/assets/190661/1ff9a33e-3ee3-416c-a824-810f03d03945)

expected result: testB should not be marked as unused

php 8.2 is set in project settings

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Netbeans 19, Win11

### JDK

JDK 20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

every time

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Thank you for reporting it.

**Comment by junichi11** [comment]
One question: What is the reason to set it to a property?
I think that it is not used as a property.

We can write like the following:
```php
class A
{
    public function __construct(
            private string $testA,
            string $testB,
    ) {
        echo $this->testA;
        echo $testB;
    }
}
$a = new A('testA', 'testB');
```
We should write like this if we don't use it as a property, I think...

**Comment by iliavlad** [comment]
yes, you are right.

Now I think Netneans shows correct message.

Thanks for explanation!
