### ISSUE TITLE
"mvnd" closes prematurely when using "--serial" or "--threads 1" parameter

### ISSUE THREAD

**Issue by negora** [apache/netbeans#6472]
### Apache NetBeans version

Apache NetBeans 19

### What happened

If you configure NetBeans to use `mvnd` with the parameter `--serial` (or `--threads 1`), the background process closes prematurely (after 10 seconds approximately). This makes `mvnd` useless, because if you run it again after that period, the gains (optimized code, cache, etc.) will be lost by then and a new process will have to be started.

On the contrary, if we not set that parameter (or if we set `--threads` to a number greater than 1), the background process survives.

---

I've realized that, when you use `--serial`, the command of the background process has an additional parameter:

```
-Dmvnd.extClasspath=/usr/local/lib/netbeans/java/maven-nblib/netbeans-eventspy.jar
```

Without `--serial`, this parameter is not added to the command. I don't know whether it has any relation with the behaviour described here or not. Just in case.

---

This report has its origin in the following discussion: [Has NetBeans 19 changed the life time of the "mvnd" process?](https://github.com/apache/netbeans/discussions/6470).

### How to reproduce

1. Go to *Tools* -> *Options* -> *Java* -> *Maven* -> *Execution*.

1. In the *Maven home* field, enter the path to `mvnd`.

1. In the *Global execution options* field, enter the `--serial` parameter.

1. Click on *OK*.

1. Open the process viewer of your OS.

1. Build any Maven project in NetBeans.

1. Open the process viewer again, and look how the Java process started for `mvnd` closes after 10 seconds approximately.

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Debian GNU/Linux 11.7 (Bullseye)

### JDK

OpenJDK Runtime Environment (build 17.0.7+7-Debian-1deb11u1)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
this is likely a mvnd bug or configuration issue.

i couldn't reproduce it with mvnd 1.0-m7 at all, so I tried it with 0.8.2 and saw it a few times.

I added this to my mvnd deamon config and it disappeared:
```
mvnd.duplicateDaemonGracePeriod = 5 seconds
```
for testing purposes i set `mvnd.idleTimeout = 10 minutes`, and the process shut down in about that time.

**Comment by negora** [comment]
I've tried *mvnd* 1.0-m7-m39 and, effectively, it works 😁 (the background process survives).

> this is likely a mvnd bug or configuration issue.

My *mvnd* installation had (and has) the default configuration. I don't understand why the affected version of *mvnd* worked fine when I run it from the terminal but not from NetBeans (using exactly the same parameters). I guess I'm missing something.

Either way, what matters is that the latest version of *mvnd* works fine with the latest version of NetBeans. So thank you a lot for your help and apologizes for spending your time.

**Comment by mbien** [comment]
> I don't understand why the affected version of mvnd worked fine when I run it from the terminal but not from NetBeans (using exactly the same parameters). I guess I'm missing something.

timing likely, since increasing the grace period fixes it
