### ISSUE TITLE
JDK 21

### ISSUE THREAD

**Issue by genamiga** [apache/netbeans#6475]
### Apache NetBeans version

Apache NetBeans 19

### What happened

With JDK 21 impossible to build something.

Error message is "Build failed" nothing else...

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Pro

### JDK

21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

The same project woks fine with JDK 20

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
You still didn't mention which build system.

Run NetBeans on JDK 20, then register JDK 21 with `Tools / Java Platforms` and use that from your project.

**Comment by genamiga** [comment]
It works. Thx

**Comment by mbien** [comment]
are we talking about Ant builds? If yes, this could be #6436 which I just merged. The workaround is stated in the PR text, but running NB 19 on JDK 20 like recommended would do the same.
