### ISSUE TITLE
Copy & paste from Netbeans to Windows fails often

### ISSUE THREAD

**Issue by terifan** [apache/netbeans#6501]
### Apache NetBeans version

Apache NetBeans 19

### What happened

While editing a Java source file, ctrl+c and ctrl+v work inside Netbeans but pasting text in e.g. Notepad doesn't work.

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Windows 10

### JDK

JDK 21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

The problem doesn't always occur and there likely is something triggering it.

This problem has existed in prior versions but Netbeans 19 is especially broken.

Restarting Netbeans doesn't work.

### Are you willing to submit a pull request?

No

**Comment by terifan** [comment]
Ohh found a duplicate. Ignore this.

**Comment by alibttb** [comment]
> Ohh found a duplicate. Ignore this.

Would please reference the duplicate so I can continue there, because I failed to find it. @terifan
