### ISSUE TITLE
Javascript editor reporting spurious errors

### ISSUE THREAD

**Issue by cclose1** [apache/netbeans#6509]
### Apache NetBeans version

Apache NetBeans 19

### What happened

Private class fields i.e. starting with # report error 'Expected ident but found error'

In CSS position: sticky; Reports 'Unexpected character(s) "sticky" found.

In both cases the error can be ignored and the code executes correctly.

### How to reproduce

Just add the above to the relevant file e.g. add #name to a javascript class and add position: sticky; to a css file.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 version 10.0 running on amd64; Cp1252; en_GB (nb)

### JDK

17.0.7; Java HotSpot(TM) 64-Bit Server VM 17.0.7+8-LTS-224

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time.

I would be surprised if this is not already known about. A search has not revealed anyone reporting a similar problem.

Perhaps there is a Netbeans configuration option I'm not setting.

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
I claim, that you are not running NB19. Both points are fixed:

- css position sticky: https://github.com/apache/netbeans/pull/4480 (part of NB16)
- private class members: https://github.com/apache/netbeans/pull/5677 (part of NB18)

This was manually verified on NB19 with a clean user dir.

1. Create a "HTML5/JS Application"
2. Create `test.js` with:
    ```javascript
    // Direct copy from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

    class ClassWithPrivate {
      #privateField;
      #privateFieldWithInitializer = 42;

      #privateMethod() {
        // …
      }

      static #privateStaticField;
      static #privateStaticFieldWithInitializer = 42;

      static #privateStaticMethod() {
        // …
      }
    }
    ```
3. Create `test.css` with 
    ```css
    .demo {
        position: sticky;
    }
    ```

Results:

![image](https://github.com/apache/netbeans/assets/2179736/3f8bd365-979a-4849-a8d0-e56bec805b22)

![image](https://github.com/apache/netbeans/assets/2179736/5fdc89f9-aa71-4451-97ed-e7777b3440ae)
