### ISSUE TITLE
source window

### ISSUE THREAD

**Issue by ineed2b** [apache/netbeans#6519]
### Apache NetBeans version

Apache NetBeans 19

### What happened

i cant find the source window anymore ?
![Capture6](https://github.com/apache/netbeans/assets/79831135/a9321884-6979-45b1-9d5b-9ab55134c478)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by troizet** [comment]
Try resetting the windows `Window -> Reset Windows`

**Comment by ineed2b** [comment]
I have found a solution ,  i had to delete the user and the cache directory under  help ->about , thanks @troizet
