### ISSUE TITLE
New JAXB Binding wizard doesn't work with JDK17 and JakartaEE 10

### ISSUE THREAD

**Issue by roberto-cisternino** [apache/netbeans#6534]
### Apache NetBeans version

Apache NetBeans 19

### What happened

The maven plugin maven-jaxb2-plugin is outdated.
Also it is unuseful to use other plugins such as com.evolvedbinary.maven.jvnet jaxb23-maven-plugin because they rely on glassfish jaxb library that in turn creates "duplicate key"  issues with openapi.

java.lang.IllegalStateException: Duplicate key jakarta.xml.bind.annotation.XmlInlineBinaryData (attempted merging values AnnotationTypeImpl{name='jakarta.xml.bind.annotation.XmlInlineBinaryData', annotations=[ java.lang.annotation.Retention java.lang.annotation.Target java.lang.annotation.Retention java.lang.annotation.Target], subclasses=[], parent=null, interfaces=[], implementors=[], referenced from []} and InterfaceModelImpl{name='jakarta.xml.bind.annotation.XmlInlineBinaryData', annotations=[], subclasses=[], parent=null, interfaces=[], implementors=[ org.glassfish.jaxb.runtime.v2.model.annotation.XmlInlineBinaryDataQuick]})

Is there any maven plugin that is usable to work with jakartaEE ?

### How to reproduce

Using the JAXB Binding wizard...

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by roberto-cisternino** [comment]
It looks NB 19 asserts to be JDK17 compatible but inside all tools are tuned for older javax.***
If I import Metro it is the older version.... I really think that a multi-JDK IDE should havae separate repositories with relevant libraries and tools such as maven plugins consistent with the JDK/Jakarta version. :-|

**Comment by matthiasblaesing** [comment]
@roberto-cisternino the JDK is not relevant for this discussion. What you are seeing is the fallout of the situation Oracle and the Eclipse Foundation produced, because they decided to change namespaces. You can play the blame game or get hacking and fix it in NetBeans. There are people working on support for JakartaEE and infrastructure is coming up for it, but contributors have real life, other projects or other reasons not to DONATE more time.

**Comment by matthiasblaesing** [comment]
@roberto-cisternino can you please give precise steps to reproduce, i.e. where to get the sample you used, which steps did you take. I'd have a look, but I don't want to guess what you see.

**Comment by roberto-cisternino** [comment]
What I understood is that for instance when creating a maven project and then trying to generate JAXB classes from a given schema, the maven plugin available in Netbeans 19 is not ready for jakarta*** it is limited to javax***.
Once the project has been correctly configured for JakartaEE the maven plugin for JAXB should be able to generate classes using latest jakarta libs and XJC.  I had to use it manually with a batch file.

**Comment by matthiasblaesing** [comment]
That is correct. The point is: What sample did you use? You mentioned "openapi". Whenever I had contact with OpenAPI it was a description in JSON/yaml, so I'm missing the connection here.

**Comment by matthiasblaesing** [comment]
@roberto-cisternino as said I had a look at the module at the result is in #6736. My gut feeling is, that it is as hard learning to use the wizard correctly, as it is to learn manually binding XSDs, but I started from the manual path.

The PR updates the version of the used module in general, adds separation/detection of Java XML Binding vs. Jakarta XML Binding and thus should at least leave a skeleton in the pom, that can then be further customized.

A test build is available from the check page of the PR for the next 4 days:

- Checks Page: https://github.com/apache/netbeans/actions/runs/6949568104
- Direct Link: https://github.com/apache/netbeans/suites/18391749729/artifacts/1065501838

It would be good if you could give it a spin.

In general: maven is perfectly capable of generating both variants (javax and jakarta), there is no need for an external batch/shell file.
