### ISSUE TITLE
FlatLaf Dark style folders

### ISSUE THREAD

**Issue by piraids** [apache/netbeans#6571]
### Apache NetBeans version

Apache NetBeans 19

### What happened

in v17 theme FlatLaf Dark work fine with icon folders in Projects / Services / Files tabs:
![Screenshot_4804](https://github.com/apache/netbeans/assets/8865695/b931c7d1-4ae0-4797-9182-7d319f98a516)

in v19 icon folders not dark:
![Screenshot_4803](https://github.com/apache/netbeans/assets/8865695/5a79b5ed-3667-4115-a2d0-793f82236ee4)

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Win 10

### JDK

Apache NetBeans 17

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
it was deliberately changed in #5760 to use the standard icons for consistency reasons, but it can be still customized via properties if you like the FlatLaf icons:

`tools -> options -> apparance -> flatlaf -> edit custom properties`

and add:
```properties
Tree.closedIcon = com.formdev.flatlaf.icons.FlatTreeClosedIcon
Tree.openIcon = com.formdev.flatlaf.icons.FlatTreeOpenIcon
```
