### ISSUE TITLE
DATABASES panel inconsistent after VSCode Color theme is changed

### ISSUE THREAD

**Issue by MartinBalin** [apache/netbeans#6578]
### Apache NetBeans version

Apache NetBeans 19

### What happened

VSNetBeans 19.0.301 with Oracle ATP DB.

1. Connect to ATP Database in OCI.
2. You will see correct profile with tables under DB named e.g VSCodeTest2.
3. Selecte VSCode > Settings ... > Color Theme and change color theme.
4. VSNetBeans is reloaded on the background.
5. DATABASES panel disappears and when it appears again then name of DB is something like name of one of the table e.g. JOBS.
6. When VSCode Reload Window command is invoked then it is corrected. 
Seems like color theme change does partial reload of VSCode which is not fully consistent like e.g. command Reload Window.

### How to reproduce

See above

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS 13.3.1 (a)

### JDK

GraalVM JDK17

### Apache NetBeans packaging

Apache VSNetBeans for VSCode

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
@MartinBalin is this still an active issue?  Does it need closing or moving to another milestone?

**Comment by MartinBalin** [comment]
Cannot reproduce with VSNetBeans 20.0.301
