### ISSUE TITLE
Menu entry disappeared - Upload/Download

### ISSUE THREAD

**Issue by rodrigojob** [apache/netbeans#6603]
### Apache NetBeans version

Apache NetBeans 19

### What happened

Menu entries Upload/Download disappeared , when in a normal file. I tried find in folder .config and edit any files, but don't recovery the menu entries.

### How to reproduce

I believe that this occurs when I made CTRL+W in menu tree project

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

UBUNTU 20.04

### JDK

javac 11.0.20.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
You were in the "Projects" view and closed this when you pressed CTRL+W. What you are looking at now is "Files" view. You can get back "Projects" by choosing "Window -> Projects".
