### ISSUE TITLE
problem with output

### ISSUE THREAD

**Issue by Ta226** [apache/netbeans#6611]
### Apache NetBeans version

Apache NetBeans 19

### What happened

The output does not appear in the window 

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Windows 64x - core i7

### JDK

jdk 19 for windows 

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by ramiswailem** [comment]
You can use the Window > Reset Windows menu item. This will reset the IDE's GUI back to the default state and then try it again to open the output window.

**Comment by neilcsmith-net** [comment]
Did the reset windows work for you?
