### ISSUE TITLE
NB20rc2 Crashes the Whole Desktop on Wayland with FlatLaf Window Decorations

### ISSUE THREAD

**Issue by lkishalmi** [apache/netbeans#6627]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

I've been testing Wayland for a few days, since upgraded my main Laptop to 23.10, in order to test #6587.
On NB20-rc1 was running fine, except the mentioned issue (however I have not tested that really hard).

After yesterday drop of rc2, I've checked #6587 again, which is really solved, however after a few popups (code completion, context menus), my whole desktop hangs and I have to reboot my system.

This only happened in the combination of using Wayland and FlatLaF window decorations enabled.

I'm continuing the testing, feeding more details here as they come.

### How to reproduce

Use NetBeans in Wayland (XWayland) with FlatLaF when the Window Decorations feature is switched on.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 23.10

### JDK

OpenJDK 21

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Have you tried with the FlatLaf natives library disabled? eg. https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java/com/formdev/flatlaf/FlatSystemProperties.java#L169

I think that only uses X11 so I suspect some bad interaction with the Wayland compatibility layer?

**Comment by mbien** [comment]
you can't recover from that freeze with `ctrl+alt+F6` (or other F keys) to switch to another session? From there you can kill the process which often recovers freezes without having to hard reset. (I never used wayland outside of virtual environments though, this works for X fairly well though)

**Comment by lkishalmi** [comment]
It seem multi and or external monitor setup is needed to reproduce the issue.

Probably even even rc1 was affected, though I was solely on my laptop display, till got back home.  Still testing.

**Comment by lkishalmi** [comment]
Well, it happened with me two times this morning, not ever since. Tested on another computer of mine with Ubuntu 23.04 and 23.10 again. Nothing. 

Further research indicates, that there could be an issue in the `amdgpu` driver in Linux Kernel 6.5.x which Ubuntu 23.10 uses. We had a Kernel update today, i hope that one fixed this for me, closing.
