### ISSUE TITLE
Rename Hudson to Jenkins

### ISSUE THREAD

**Issue by mbien** [apache/netbeans#6628]
[Hudson is no more](https://en.wikipedia.org/wiki/Hudson_(software)) but NetBeans is still using it in the UI:
![image](https://github.com/apache/netbeans/assets/114367/01306de7-12da-4246-9f28-2003d0658d91)

The service integration still seems to work with Jenkins:
![image](https://github.com/apache/netbeans/assets/114367/5ee370e6-b9de-42d3-ac7f-586627066bec)

**Comment by rothardo** [comment]
Hi there I am new to the Open shource Please guide me on how do I Proceed and which directory to look for

**Comment by mbien** [comment]
the hudson modules are in `ide/hudson*`.

**Comment by troizet** [comment]
Also present is the `hudson.php` module in the `php` cluster.

**Comment by rothardo** [comment]
thank you so much for the giving updates and saving time @mbien and troizet

**Comment by rothardo** [comment]
I have renamed hudson to jenkins for the frontend should I be also renaming the directories, files and as well as the method names?

**Comment by mbien** [comment]
@rothardo good question, let me ask

@matthiasblaesing @lkishalmi @ebresie what do you think, should we rename everything?

I believe in this case, where Hudson was discontinued and lives on as Jenkins and we have several releases on maven central with modules which support Hudson (and Jenkins incidentally), we should simply rename everything.

Since copy + deprecate doesn't make a lot of sense here. It would create just a bunch of dead modules in the repo which have to be built and tested.

**Comment by mbien** [comment]
what is the point of providing a hudson API? We won't test it with hudson anymore so it essentially already is API for jenkins. The modules which use the old namespace are on maven central for anyone who would still depend on them.

It would be a false promise to keep using the hudson namespace while serving jenkins users since it will likely break old hudson apps anyway at some point.

**Comment by mbien** [comment]
lets take a look:
ide/hudson/nbproject/project.xml and
ide/hudson.ui/nbproject/project.xml exposes API only to friends (as far as I see, please double check)

**Comment by lkishalmi** [comment]
Well, I'm not really serious about backward compatibility and against folder/package renaming.

There is a thing though:
```xml
<friend>oracle.jdevimpl.nbteam.ide</friend>
```

That's out of our realm. I do not know if that is still used or not though...

**Comment by mbien** [comment]
> <friend>oracle.jdevimpl.nbteam.ide</friend>

we could try to ask someone. The linux kernel does the same. They sometimes ask before removing drivers of esoteric devices which likely nobody uses anymore.

**Comment by matthiasblaesing** [comment]
I think we should learn from the disaster Oracle and the Eclipse Foundation produced. We will see many years where the split between the `jakarta.*` and `javax.*` packages will hurt. And it will serve as a reminder that renaming technical identifiers (packages, classes, ...) will in many cases just create noise. It is not that uncommon in the NetBeans code base not to follow marking BS: Many modules are still called `j2ee*` and several modules support JavaEE and JakartaEE.

That said: If there are people willing to do this work and audit and review, fine with me.

**Comment by rothardo** [comment]
@mbien Could you please advise on the recommended course of action, or should I await further guidance? Thank you

**Comment by mbien** [comment]
@rothardo you mentioned you made the changes in the UI already, so if you want you can open a PR so that someone can take a look at the changes and test it.

To do that simply push your changes to a new branch of your clone of the NetBeans repo, then you should see a button somewhere which lets you open a PR against the apache repo.

**Comment by rothardo** [comment]
@mbien I have opened a PR, hence please let me know if there are any changes required, thank you
