### ISSUE TITLE
Java editor inserting extra space after opening brace

### ISSUE THREAD

**Issue by jeffrey-easyesi** [apache/netbeans#6638]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

When editing Java code, if I type a left brace, NetBeans 20 adds an extra space to the right of the cursor.

### How to reproduce

Under Options > Editor > Code Completion, make sure "Insert Closing Brackets Automatically" is on. Open a Java file.

Type "class A {" and then press enter. Notice extra space after the automatically generated "}".
Also:
Type "class A {}", and do not press enter but use the arrow keys to move around. Notice again extra space after "}".

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Ubuntu 20.04

### JDK

OpenJDK 11.0.20.1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Thanks for reporting.  I can replicate.  In fact, had noticed the extra spaces when working on some code recently, but not when they were being added.

**Comment by mbien** [comment]
ran a bisection and it was caused by #6415
 
I also tested #6637, but it doesn't fix this particular issue
