### ISSUE TITLE
struts-core 1.3.10 jar present

### ISSUE THREAD

**Issue by glauber-experian** [apache/netbeans#6686]
### Apache NetBeans version

Apache NetBeans 19

### What happened

/enterprise/modules/ext/struts/struts-core-1.3.10.jar

This jar file gets flagged as containing a serious vulnerability. 
There doesn't seem to be a higher version.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mac OS Ventura

### JDK

openjdk 20.0.2 2023-07-18 OpenJDK Runtime Environment Zulu20.32+12-SA (build 20.0.2+9) OpenJDK 64-Bit Server VM Zulu20.32+12-SA (build 20.0.2+9, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by glauber-experian** [comment]
I don't know what this jar file is used for. Netbeans is able to start after deleting the file.

**Comment by mbien** [comment]
> My company's policy wouldn't allow it.

but it allows to consume open source projects? My freetime policy really wants me to close this issue.
