### ISSUE TITLE
Package xxx is declared in an unnamed module, but module YYY does not read it - code compiles fine

### ISSUE THREAD

**Issue by rhobincu** [apache/netbeans#6704]
### Apache NetBeans version

Apache NetBeans 19

### What happened

We have two development stations with different OSes (Ubuntu 18.04 and Linux Mint 21.2) with Netbeans 19 and JDK 21 used to compile the same software, at the same Git revision and we get the following realtime code analysis error, altough the code compiles fine (as can be seen in the screenshot):

![netbeans_bug](https://github.com/apache/netbeans/assets/8833880/313a3930-deac-4ab9-97e5-11cdad759da5)

We have another station, running the same Linux Mint 21.2, with Netbeans 18 and JDK 21, compiling the same Git revision of the same application which does not exhibit this error.

Running "ant jar" from the command line also compiles everything without issues on both versions. 

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Linux Mint 21.1/ Ubuntu 18.04

### JDK

openjdk-21-jdk

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I have tried to remove all projects and re-add them, the problem persists. I have even deleted the ${HOME}/.netbeans folder and restarted it, the problem still persists.

### Are you willing to submit a pull request?

No

**Comment by rhobincu** [comment]
Update: after installing Netbeans 18 on the Linux Mint computer exhibiting the problem, it worked fine for half a day, and after doing a `git stash && git pull && git stash apply`, everything broke again.

**Comment by mbien** [comment]
NB 18 never supported JDK 21 as you can see on the old download page: https://netbeans.apache.org/download/nb21/

But this looks like an ant project specific issue to me.

**Comment by rhobincu** [comment]
Issue dissapeared in Netbeans 20 and 21.

**Comment by stodge** [comment]
I'm seeing this in Netbeans 22 with JDK 21:

Product Version: Apache NetBeans IDE 22
Java: 21.0.3; OpenJDK 64-Bit Server VM 21.0.3+9-LTS
Runtime: OpenJDK Runtime Environment 21.0.3+9-LTS
System: Windows 11 version 10.0 running on amd64; UTF-8; en_CA (nb)

**Comment by matthiasblaesing** [comment]
@stodge as with most "XYZ does not work" report: Please provide a minimal sample, that reproduces the problem. Else noone will look at the problem.
