### ISSUE TITLE
"Insert closing brackets automatically" doesn't handle closing square bracket "]" correctly

### ISSUE THREAD

**Issue by php4fan** [apache/netbeans#6706]
### Apache NetBeans version

Apache NetBeans 19

### What happened

The number one rule of an IDE is that, if I type everything myself (as opposed to taking advantage of what the IDE automatically fills in for me), the IDE shouldn't get in my way.

So, in PHP, say I want to type:
```
$array['key']
```
I start by typing:
```
$array[
```
The IDE autocompletes it to:
```
$array[]
```
and my cursor is between the `[` and the `]`.
Now I type a single `'`, and the IDE autocompletes it to:
```
$array['']
```
and my cursor is now between the two `''`s, excellent.

Now I type `key'`, with the closing `'`.
Intelligently and as expected, when I type the closing `'`, the IDE does not add an extra `'`; rather, it replaces the one that it had already added for me with the one that I'm typing, so now I have:
```
$array['key']
```
and my cursor is right before the `]`. So far so good.

Now here comes the problem. **When I type the closing `]`** (either because I'm used to, or because in the end it's the exact same effort as hitting the right-arrow key to move past the `]` that is already there), **the IDE now blindly outputs the `]`** that I've just typed in front of the one that is already there, and I end up with this:
```
$array['key']]
```
and the cursor is between the two `]`s.

Note that this is **ACTUALLY WORSE** than doing no autocomplete at all and leaving me type on my own. That forces me to turn off "insert closing brackets automatically" because it's unusable. However (a) I don't want to turn it off, I want to have it on and have it work correctly so that it's helpful instead of getting in my way; and (b) that turns it off also for parenthesis `()` (and I guess it'll turn it off for `{}` braces too, I haven't tested that) but parenthesis are handled correctly, so I'm forced to also turn off a helpful tool that works fine.

PHPStorm does this right. **Even Kate does this right**.

### How to reproduce

In a php file type:
```
$array['key']
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Manjaro Linux

### JDK

Java: 21; OpenJDK 64-Bit Server VM 21+35

### Apache NetBeans packaging

Third-party package

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Please remove unnecessary things from the issue title.

**Comment by junichi11** [comment]
I can't reproduce it. Maybe, there is a difference between your context and mine.
So, please write a reproducible example.

![nb-gh-6706](https://github.com/apache/netbeans/assets/738383/58391aee-ee76-4b2f-b435-663b6b0cd949)

**Comment by php4fan** [comment]
The exact literal example I gave reproduces it for me, I don't know why it doesn't for you.

**Comment by php4fan** [comment]
You're right, it does depend on the context.

I have found a minimal reproducing example.
Try this:

```
<?php

$yyy = 123;

$xxx = "[$yyy lalala]"; 

// Type below here
```

And there you type `$array['key']`.

The `$yyy = 123;` is not necessary, it's just to make sure that you reproduce the issue with 100% valid code.

The line provoking the issue (i.e. `$xxx = .....`) doesn't have to be near to where you type, the mere presence of something like that in the whole file will cause the issue, as far as I can tell wherever you type.

If you change this:
```
$xxx = "[$yyy lalala]"; 
```
to this:
```
$xxx = "[$yyy]"; 
```
then it will no longer reproduce.

**Comment by junichi11** [comment]
OK, Reproducible, now. Thanks for your example to reproduce it.

**Comment by junichi11** [comment]
Fixed.
