### ISSUE TITLE
[PHP] Add PER-compliant multiline method formatting

### ISSUE THREAD

**Issue by terax6669** [apache/netbeans#6715]
### Description

https://www.php-fig.org/per/coding-style/#45-method-and-function-parameters

> When the argument list is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.

Currently there is no multiline option in formatting options. Code formatted by NetBeans is out of spec:

```php
class ArrayPropertyType extends PropertyType
{
	public function __construct(
		public readonly PropertyType $key,
		public readonly PropertyType $value,
	)
	{
		
	}
}
```

![image](https://github.com/apache/netbeans/assets/19204073/727b98e9-cefc-4cdd-89d9-378b444f82f5)

### Use case/motivation

PER standard compliance.

### Are you willing to submit a pull request?

No

**Comment by terax6669** [comment]
Old ticket: https://issues.apache.org/jira/browse/NETBEANS-471

**Comment by junichi11** [comment]
Maybe, I've already implemented this.
![nb-php-gh-6715](https://github.com/apache/netbeans/assets/738383/c6383906-dfe5-4365-947d-cc3392d81dfa)

**Comment by terax6669** [comment]
You are right, I didn't see this option.
