### ISSUE TITLE
Wrong indentation after multi-line function call

### ISSUE THREAD

**Issue by php4fan** [apache/netbeans#6731]
### Apache NetBeans version

Apache NetBeans 19

### What happened

After the following code:

```
<?php

$result = someFunction(
    "example {$postId}"
);
```
the next line after that should have zero indentation.

Instead, it gets indented with 4 spaces, i.e. one indentation.

A real-world use case might be something like this:

```
<?php

$result = queryDatabase(
    "SELECT field1, field2, field3, field4, field5 "
        . "FROM table AS t1 "
        . "JOIN table2 AS t2 ON t2.whatever_id = t1.id "
        . "JOIN table2 AS t3 ON t3.whatever_id = t2.id "
        . "WHERE t1.id = {$something['id']}"
);
```
after which I get even 2 indentations (i.e. 8 spaces).

### How to reproduce

In a PHP file type this:
```
<?php

$result = someFunction(
    "example {$postId}"
);
```
and then add a newline. Observe how the new line gets automatically indented.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Manjaro Linux

### JDK

21; OpenJDK 64-Bit Server VM 21+35

### Apache NetBeans packaging

Third-party package

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Please write an actual result and an expected result. I'm not sure what you expect yet.

**Comment by php4fan** [comment]
What's unclear about this?:

>  the next line after that should have zero indentation.
> Instead, it gets indented with 4 spaces, i.e. one indentation.

**Comment by junichi11** [comment]
Please write them as code to avoid misunderstanding.

**Comment by php4fan** [comment]
Write what as code? The expected and observed behavior? That makes no sense. 

I honestly don't understand what you want  from me.
Have you understood what the issue is or not? 

I gave you the example code, the instructions to reproduce, the expected and observed behavior. I don't understand what else you need and I don't see what part of the report can possibly be unclear.

Have you tried the example code? You don't notice anything strange?
Maybe it's not reproducing for you? Maybe the fix for 6706 fixed this as well?

**Comment by junichi11** [comment]
Please write like this
```php
<?php

$result = someFunction(
    "example {$postId}"
); // type enter key here
```
Expected result:
```php
<?php

$result = someFunction(
    "example {$postId}"
);
// no indentation here
```
Actual result:
```php
<?php

$result = someFunction(
    "example {$postId}"
);
    // one indentation is added here
```

Maybe, what you expect is this, right?
Don't you think it's easier to understand without misunderstanding?

**Comment by php4fan** [comment]
Yes that's what I meant. Can you reproduce?

**Comment by junichi11** [comment]
Reproducible.

**Comment by junichi11** [comment]
Fixed.
