### ISSUE TITLE
javascript autocomplete private members

### ISSUE THREAD

**Issue by lbuchs** [apache/netbeans#6734]
### Apache NetBeans version

Apache NetBeans 19

### What happened

The autocomplete of private class members in JavaScript is not working properly.

when you write `this.` , the autocomplete appears with all the values, including private fields.

when you add a # (`this.#`), it should filter for all Members beginning with #, but the autocomplete disappears. Writing more, the autocomplete comes back, but not only with the existing members, but also with a lot of non-matching values like `try {`,  the currently written Text (like `this.#testTe`) which is not a defined variable, etc.

screen recording:

https://github.com/apache/netbeans/assets/37619779/88a0c120-8588-4276-9c45-1fa2b2cfd056

### How to reproduce
see screen recording
```javascript
class TestCls {

    #test = 0;
    #testTest = 0;
    test = 0;
    testTest = 0;

    aa() {
        this.testTest = 1;
        this.#testTest = 1;
    }
}
```

### Did this work correctly in an earlier version?

No

### Operating System

Windows 11

### JDK

Java(TM) SE Runtime Environment 17.0.1+12-LTS-39

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
@lbuchs could you please have a look at #6741.

There is a test build available from the check page, please have a look.

- Checks Page: https://github.com/apache/netbeans/actions/runs/6961761816
- Direct link: https://github.com/apache/netbeans/suites/18423458806/artifacts/1067900146
