### ISSUE TITLE
New Project Group dialog not being brought to front

### ISSUE THREAD

**Issue by gwinstanley** [apache/netbeans#6768]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

Small GUI-related issue; probably a simple fix. Couldn't find it already listed as bug, so decided to file.

Trying to create a new **Project Group** from **Manage Groups** dialog leaves the new group dialog in the background, so need to deselect/reselect application to bring it to focus (or similar needless shenanigans).

### How to reproduce

_File_ / _Project Groups..._ / _New Group..._

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS Sonoma 14.1.1 (Apple Silicon)

### JDK

Adoptium OpenJDK 21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
interesting. I put the mac label on it since I can't reproduce this on linux. Clicking new-group closes the dialog and opens the create-group dialog, the (modal) window is in front of the main window for me.

**Comment by mbien** [comment]
oh, found the problem: 

 - enable window decorations
 - get to the create-group dialog
 - now click on the main window

-> dialog is gone and you can't get it easily back

**Comment by mbien** [comment]
thanks a lot for verifying
