### ISSUE TITLE
server change not happening

### ISSUE THREAD

**Issue by raja7689** [apache/netbeans#6775]
### Apache NetBeans version

Apache NetBeans 19

### What happened

in maven project server is runnning but if u create new ant project or other server not running and servlets linking html not working properly and also include all libraries we need for servlets default because its time taking for manually keeping them for every project

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

jdk-21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
i have no clue what that means

**Comment by matthiasblaesing** [comment]
I agree with @mbien the error message does not make sense and there are no steps to reproduce. Closing.
