### ISSUE TITLE
Add project statistics

### ISSUE THREAD

**Issue by PavelTurk** [apache/netbeans#6776]
### Description

Currently NB doesn't provide any project statistics. At the same time IntelliJ has  [this one](https://plugins.jetbrains.com/plugin/4509-statistic) with 1,915,900 Downloads (I don't know if it's true). So, I suggest to add such feature to NB:

- must separate files by type (java, xml, css etc)
- must allow to exclude files/directories (node_modules, for example)
- must provide easy access to biggest/smallest files

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
this is most likely covered by existing maven/gradle reporting plugins.

We also don't really track plugin requests on the NetBeans issue tracker -> closing.
