### ISSUE TITLE
[PHP] Generate `__toString` in a Plain Object class

### ISSUE THREAD

**Issue by hantsy** [apache/netbeans#6783]
### Description

Currently when generating a `__toString`, it is an empty function, try to generate a method as Java, print all fields in a Plain Object class.

### Use case/motivation

Given the following plain PHP class. When overriding the `__toString`, we hope print all fileds as we overrides a Java POJO.

```php
class PersonDto
{

    private string $firstName;
    private string $lastName;

    // setters, getters
    
   public function __toString():string
   {  
      // generate the following codes instead of an empty function
      return "PersonDto[firstName=".$this->firstName
          .", lastName=".$this->lastName
          ."]"; 
   }

```

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Please write an example code.

**Comment by hantsy** [comment]
@junichi11 Updated the original post.
