### ISSUE TITLE
I cant copy and paset

### ISSUE THREAD

**Issue by AYMEN-ATIYA** [apache/netbeans#6795]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

I cannot copy, paste, or add an external file to the project

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

21

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Duplicate of #3962
