### ISSUE TITLE
Connection refused while attaching debugger

### ISSUE THREAD

**Issue by dir1337** [apache/netbeans#6796]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

Hello, 
Respected devs,

I am attaching debugger to my main.js file but it shows connection refused.
Provided host : 127.0.0.1
Strange thing is neovim's nvim-dap also shows same error ECONNREFUSED.
Is there something missing or need to change ?

### How to reproduce

What I do is simple open a javascript file and try to attach debugger on it.
And found this error.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Arch Linux 

### JDK

openjdk 21 2023-09-19

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
You can't "attach" to a javascript file. What is possible depends highly on your environment. JS in the browser currently can't be debugged with NetBeans, but then the Browsers dev tools got pretty good at that. You most probably try to debug a node execution. Then you will be faced with https://github.com/apache/netbeans/issues/4127 on recent node versions.
