### ISSUE TITLE
Support javax.faces.WEBAPP_RESOURCES_DIRECTORY

### ISSUE THREAD

**Issue by jepsar** [apache/netbeans#6803]
Since JSF 2.2 the resources directory can be specified using a context parameter (to hide them from HTTP requests for example). NetBeans does not support it, so it does not allow you to use (for example) composite components from the configured folder.

<img width="714" alt="Screenshot 2023-12-06 at 15 29 10" src="https://github.com/apache/netbeans/assets/7500178/847821d2-4016-4b0c-9d13-490aa563927f">

https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0.html#a6088

https://stackoverflow.com/questions/13671704/is-it-possible-to-change-the-resources-folder-name-which-is-used-by-houtputsty

**Comment by jepsar** [comment]
It looks like support is not totally absent

https://github.com/apache/netbeans/blob/5b768b89eb89a511d3e78ea07ad922626feeccad/enterprise/web.jsf/src/org/netbeans/modules/web/jsf/wizards/CompositeComponentWizardPanel.java#L304-L324

**Comment by matthiasblaesing** [comment]
@jepsar you might get help if you produce a minimal reproducer. Few people want to waste time to learn some new cool feature he does not need just to fix someone elseses problem.

**Comment by jepsar** [comment]
It turned out that having the components in a folder called `composites` did not work. Renaming it to `components` does work. 🤷🏼‍♂️
