### ISSUE TITLE
Hibernate Installation

### ISSUE THREAD

**Issue by patildevashish** [apache/netbeans#6810]
### Apache NetBeans version

Apache NetBeans 19

### What happened

Some plugins require plugin Freemarker Integration to be installed.
The plugin Freemarker Integration is requested in implementation version 238.  The following plugin is affected:       Hibernate

### How to reproduce

Try installing hibernate plugins from the plugins.

### Did this work correctly in an earlier version?

Apache NetBeans 13 or earlier

### Operating System

Windows 11

### JDK

jdk 21

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
> Try installing hibernate plugins from the plugins.

I don't see a hibernate plugin in the available plugins list. Any plugin which requested validation against NB 20 (or 19 for that matter) should show up there and work (hopefully).

**Comment by mbien** [comment]
right. Well, the old plugin portal isn't validated anymore, it contains old, mostly unmaintained plugins. There is probably nothing we can do about this.

I checked the catalog.xml of the 8.2 update center and the namespace is `org.netbeans.modules.hibernate4lib`. I don't think the code was donated to apache. Its not in https://github.com/timboudreau/netbeans-contrib and not in the netbeans repo.
