### ISSUE TITLE
System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/home/pdelhaise/netbeans/platform/lib/boot.jar)

### ISSUE THREAD

**Issue by pdelhaise** [apache/netbeans#6831]
### Apache NetBeans version

Apache NetBeans 19

### What happened

I get this message:
pdelhaise@Ubuntu:~$ netbeans/bin/netbeans
WARNING: package com.apple.eio not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/home/pdelhaise/netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release

### How to reproduce

pdelhaise@Ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
pdelhaise@Ubuntu:~$ java -version
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-29)
OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

ubuntu 22.04.3 LTS

### JDK

openjdk version "21.0.1" 2023-10-17

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Duplicate of #5747 A known issue but not a concern with current JDKs.
