### ISSUE TITLE
Input wont type

### ISSUE THREAD

**Issue by rodjnn** [apache/netbeans#6858]
### Apache NetBeans version

Apache NetBeans 19

### What happened

So basically, if I run the code and the output comes out just fine, it won't allow me to input anything. For example, if I code something asking for a name, when I run it, it will come out, but it won't allow me to type what is being asked.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 and 11

### JDK

I used every jdk verison as possible to solve it

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
is this about JShell or the output window or something else?

```java
    public static void main(String[] args) {
        System.out.println("write something:");
        System.out.println("you typed: '"+new Scanner(System.in).nextLine()+"'");
    }
```
output window seems to work as expected

input not working in JShell is a known bug: https://github.com/apache/netbeans/issues/3804

**Comment by rodjnn** [comment]
its when you running the file but it wont allow you to input what you wanna type. Lets say the code you wrote above worked and the "write something: " appeared but I cant type anything.

**Comment by mbien** [comment]
yes, but what I am saying is that it does work for me:
```
--- exec:3.1.0:exec (default-cli) @ mavenproject1 ---
write something:
Hello There!
you typed: 'Hello There!'
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time:  18.114 s
Finished at: 2023-12-17T06:13:47+01:00
------------------------------------------------------------------------
```
Where are you trying to type something? Are we talking about the "Output" window or the "Java Shell" window? Did you scroll to the very bottom of the output window?

**Comment by rodjnn** [comment]
I dont really get it but this what comes out out of mine.

**Comment by matthiasblaesing** [comment]
Everytime something does not work as you expect, a good approach is to create a minimal sample, that is runnable and reproduces your problem. The trace you show is a broken project, there is no input, that could be use, because the project does not even start. So mae this minimal, zip it (File -> Export project -> To ZIP), attach it here.

**Comment by mbien** [comment]
@rodjnn what happens if you press `Shift+F11` (or run->`clean and build project`)?

**Comment by rodjnn** [comment]
-----------------------< com.mycompany:Luz_Rod >------------------------
Building Luz_Rod 1.0-SNAPSHOT
  from pom.xml
--------------------------------[ jar ]---------------------------------

--- clean:3.2.0:clean (default-clean) @ Luz_Rod ---
Deleting C:\Users\asus\Documents\NetBeansProjects\Luz_Rod\target

--- resources:3.3.0:resources (default-resources) @ Luz_Rod ---
skip non existing resourceDirectory C:\Users\asus\Documents\NetBeansProjects\Luz_Rod\src\main\resources

--- compiler:3.10.1:compile (default-compile) @ Luz_Rod ---
Changes detected - recompiling the module!
Compiling 1 source file to C:\Users\asus\Documents\NetBeansProjects\Luz_Rod\target\classes

--- resources:3.3.0:testResources (default-testResources) @ Luz_Rod ---
skip non existing resourceDirectory C:\Users\asus\Documents\NetBeansProjects\Luz_Rod\src\test\resources

--- compiler:3.10.1:testCompile (default-testCompile) @ Luz_Rod ---
No sources to compile

--- surefire:3.0.0:test (default-test) @ Luz_Rod ---
No tests to run.

--- jar:3.3.0:jar (default-jar) @ Luz_Rod ---
Building jar: C:\Users\asus\Documents\NetBeansProjects\Luz_Rod\target\Luz_Rod-1.0-SNAPSHOT.jar

--- install:3.1.0:install (default-install) @ Luz_Rod ---
Installing C:\Users\asus\Documents\NetBeansProjects\Luz_Rod\pom.xml to C:\Users\asus\.m2\repository\com\mycompany\Luz_Rod\1.0-SNAPSHOT\Luz_Rod-1.0-SNAPSHOT.pom
Installing C:\Users\asus\Documents\NetBeansProjects\Luz_Rod\target\Luz_Rod-1.0-SNAPSHOT.jar to C:\Users\asus\.m2\repository\com\mycompany\Luz_Rod\1.0-SNAPSHOT\Luz_Rod-1.0-SNAPSHOT.jar
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time:  1.733 s
Finished at: 2023-12-17T18:36:12+08:00
------------------------------------------------------------------------

it shows this

**Comment by mbien** [comment]
ok, well your project builds fine. I agree with @matthiasblaesing, the easiest way from here would be to zip the project and attach it here, see https://github.com/apache/netbeans/issues/6858#issuecomment-1859061068
