### ISSUE TITLE
Tailwind: 'Unexpected token IDENT found' Error in a sass file

### ISSUE THREAD

**Issue by mhrownaghi** [apache/netbeans#6860]
### Apache NetBeans version

Apache NetBeans 20

### What happened

When I use `@apply` with more than one class, second class is marked as 'Unexpected token IDENT found' error.

### How to reproduce

In a sass file copy following code:
```
@layer components {
  .card {
    @apply bg-white p-5 rounded-lg shadow; // Unexpected token IDENT found
  }
}
```
`p-5` is marked as error.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

OpenSUSE Leap 15.5 - x64

### JDK

11

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Where is @apply defined in CSS?

**Comment by mhrownaghi** [comment]
It is related to the Tailwind CSS framework. If a plugin is made for Tailwind CSS framework, it is good.

**Comment by matthiasblaesing** [comment]
So on top of CSS, SCSS and LESS, now every framework invents its own @rules. Great! We have to rethink how to handle @rules so that this mess can somehow be supported.

**Comment by matthiasblaesing** [comment]
@mhrownaghi please check the build available from PR #7837. [Checkpage](https://github.com/apache/netbeans/pull/7837/checks), [direct link](https://github.com/apache/netbeans/suites/29318048260/artifacts/2025809464)

**Comment by Chris2011** [comment]
I want just mention here, that every new framework which getting more and more popular is bringing their own language server, so tailwind too: https://www.npmjs.com/package/@tailwindcss/language-server. This means, we could use this to have also code completion and maybe no error for stuff which is coming from this (?). Just an idea.

**Comment by matthiasblaesing** [comment]
Sure, you'd only need to persuade to treat this file not as CSS, call the language server and all that. I will not go down that road.

**Comment by Chris2011** [comment]
yeah, I thought so. I mean it is still css with some extra bling bling. Everywhere you can use css. No worries, it was just an idea you can sleep about it and bring a solution tomorrow 1!!1111
