### ISSUE TITLE
Make Test Runner API/ Coverage API and Gototest API public APIs

### ISSUE THREAD

**Issue by albilu** [apache/netbeans#6863]
quoted from a Netbeans dev : _friend APIs are APIs which are not stable and therefore not public. If you want to use them anyway, you have to pretend to be a friend and use them. Since they can change from release to release, you have to do provide a build for every release_
...

https://github.com/apache/netbeans/tree/master/ide/gototest
https://github.com/apache/netbeans/tree/master/ide/gsf.codecoverage
https://github.com/apache/netbeans/tree/master/ide/gsf.testrunner

As those 3 APIs are very important part of a Language support module they need to be made available to allow plugin developers to work with them more smoothly.

It is now several years since those APIs are not public if i am not wrong.

I worked with them recently and didn't noticed any instability or harm to the IDE.

So what is preventing to made them public ?

_Originally posted by @albilu in https://github.com/apache/netbeans/discussions/5942_

### Are you willing to submit a pull request?
Yes

**Comment by neilcsmith-net** [comment]
Please don't bypass the issue forms.  Feel free to bump your thread on the dev@ list.  I'm personally 100% in favour of this, but then I also think friend APIs should never have been used for unstable APIs in the first place!
