### ISSUE TITLE
2 "Contexts and Dependency Injection" choices for New

### ISSUE THREAD

**Issue by richard-grin** [apache/netbeans#6875]
### Apache NetBeans version

Apache NetBeans 20

### What happened

Right clic on a project, choose New > Other. In the list displayed,  "Contexts and Dependency Injection" and "Contexts and Dependency Injection (Jakarta EE)". Is it normal? If it is, it would be good to explain better when to use one rather than the other.

### Language / Project Type / NetBeans Component

Java

### How to reproduce

Explained in "What happened".

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Family 64-bit, version 21H2

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
What would you suggest? When Oracle decided to drop JavaEE and donate code to the Eclipse Foundation, lawyers/marketing were involved. The JavaEE name was not donated and some clever soul thought, yeah, then the package name has to change. This in turn kills compatbility between JavaEE and JakartaEE. The package names and XML namespaces were changed.

That schism will hunt us for the next decade. CDI is one of the places where it pops up. You have to choose which is the right namespace.

**Comment by richard-grin** [comment]
If the difference between the two choices is only the names of the packages, name them "Contexts and Dependency Injection (javax)" and "Contexts and Dependency Injection (jakarta)". It's clearer because the first versions of Jakarta use javax (Jakarta 8 or 9).
Another better solution (is it possible in a NetBeans wizard?) would be to read the version of web.xml or beans.xml, or something similar that distinguishes the version of Jakarta EE (and Java EE) and decide to use jakarta or javax in the packages.

**Comment by matthiasblaesing** [comment]
@richard-grin should be fixed by #7958. Development build available from [Checkspage](https://github.com/apache/netbeans/actions/runs/11822741985) or [directly](https://github.com/apache/netbeans/actions/runs/11822741985/artifacts/2183455569)

**Comment by richard-grin** [comment]
Hello Matthias,Currently, I am totally overwhelmed with a new course that I will be doing at the beginning of December. Sorry.Richard Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Matthias Bläsing ***@***.***> Date : 13/11/2024  18:50  (GMT+01:00) À : apache/netbeans ***@***.***> Cc : richard-grin ***@***.***>, Mention ***@***.***> Objet : Re: [apache/netbeans] 2 "Contexts and Dependency Injection" choices for New (Issue #6875) 
@richard-grin should be fixed by #7958. Development build available from Checkspage or directly.
Would be great if you could test.
