### ISSUE TITLE
Navigator - No View Available

### ISSUE THREAD

**Issue by DaveWP** [apache/netbeans#6879]
### Apache NetBeans version

Apache NetBeans 20

### What happened

I have created a new javascript file with a simple class.  I find that the Navigator window is blank with the statement "<No View Available>".  I'm sure the problem is probably linked to the file contents, but I cannot see any invalid characters.

![Screenshot 2023-12-24 194212](https://github.com/apache/netbeans/assets/343015/8537c3ac-ffc9-427b-9328-37fd6fc0ad05)

I notice that folding does not appear to be working, and there are errors reported in the IDE log associated with an undefined fold types.  I've no idea how to reset the issue.

### Language / Project Type / NetBeans Component

Netbeans Editor

### How to reproduce

The issue seems to relate to specific files, as the Navigator is working with other Javascript files.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 10.0.22621 Build 22621

### JDK

Java(TM) SE Runtime Environment 19+36-2238

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by DaveWP** [comment]
I've attached the actual file with the extension changed from .js to .txt (in case there is something wrong in the character sets), and the log file.

[messages.log](https://github.com/apache/netbeans/files/13766415/messages.log)
[config.txt](https://github.com/apache/netbeans/files/13766424/config.txt)

**Comment by DaveWP** [comment]
Have just found #268411, and changing the file name so that it does not include 'config' in the file name seems to resolve the issue.

**Comment by matthiasblaesing** [comment]
@DaveWP thank you for the test case and the bug reference. The issue in this case is indeed not the content of the file, but the filename. Every file that ends with "js" and contains "karma" or "conf" is currently not recognized as "text/javascript" but as "mimetype text/karmaconf+javascript". This causes issues for the editor.

Could you please have a look at #6883 and test the nightly build available from the checks page https://github.com/apache/netbeans/actions/runs/7332864699 or directly from https://github.com/apache/netbeans/actions/runs/7332864699/artifacts/1136087617
