### ISSUE TITLE
Bad OutlineView javadoc links

### ISSUE THREAD

**Issue by tbw777** [apache/netbeans#6886]
### Apache NetBeans version

Apache NetBeans 20

### What happened

OutlineView class javadoc:

```
 * <ul>
 * <li><a href="https://netbeans.apache.org/blogs/timboudreau/egads_an_actual.html">Egads! An actual Swing Tree-Table!</a>
 * <li><a href="https://netbeans.apache.org/blogs/geertjan/swing_outline_component.html">Swing Outline Component</a>
 * </ul>
```

this links doesnt work

Its was changed in old commit from:

```
 * <ul>
 * <li><a href="http://weblogs.java.net/blog/timboudreau/archive/2008/06/egads_an_actual.html">Egads! An actual Swing Tree-Table!</a>
 * <li><a href="http://blogs.oracle.com/geertjan/entry/swing_outline_component">Swing Outline Component</a>
 * </ul>
```

WebArchive:

- https://web.archive.org/web/20130613214139/http://weblogs.java.net:80/blog/timboudreau/archive/2008/06/egads_an_actual.html
- https://web.archive.org/web/20131214191810/http://blogs.oracle.com:80/geertjan/entry/swing_outline_component

### How to reproduce

click on links

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

17

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

**Comment by ebarboni** [comment]
should be fixed for geertjan link as was not good redirected as we use the "clear url".
For tim boudreau blog I need to upload a page to the site.

**Comment by ebarboni** [comment]
should be fixed on the site now
