### ISSUE TITLE
Error with file servlet

### ISSUE THREAD

**Issue by MrC123456789654** [apache/netbeans#6916]
### Apache NetBeans version

Apache NetBeans 20

### What happened

I have 2 issues about file servlet are : 
- When I create new file servlet it can not close notification but the file sevrlet is still created 
- When I click in the file is empty, I mean the file don't have any code inside but when I wrrite down some code to run, it still okay
And I post video my issue on driver in the link below so I hope u can help me to fix this problem. Tks u!
https://drive.google.com/drive/folders/1t0aufOO--Kp39RFkCM3LP6bq_hBBz6_3?usp=sharing

### Language / Project Type / NetBeans Component

Java Web/Web Application

### How to reproduce

.

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Windown 11

### JDK

jdk-17.0.9_windows-x64_bin

### Apache NetBeans packaging

Apache NetBeans platform

### Anything else

.

### Are you willing to submit a pull request?

Yes

**Comment by matthiasblaesing** [comment]
Not reproducible (tested against Glassfish 7.X). Please provide the message log (can be found in `c:/Users/$username/AppData/Roaming/NetBeans/20/var/log/messages`)

**Comment by matthiasblaesing** [comment]
There were improvements in the area of servelets/jakarata transition. As no futher info was provided closing this.
