### ISSUE TITLE
Automatically import types when selected on code completion

### ISSUE THREAD

**Issue by stollr** [apache/netbeans#6947]
### Description

Almost every time I am using Netbeans I am missing the automatic import of types when I select them from code completion.

To make it clear I would like to provide some screenshots. The first one shows how Netbeans suggests a class:

![grafik](https://github.com/apache/netbeans/assets/1118790/43ed1228-5af6-4f2d-96c9-dc5b616e7c50)

This works great. Now I select the suggested type by hitting enter:

![grafik](https://github.com/apache/netbeans/assets/1118790/0a0b592e-fc44-4a6e-9ec3-55b642e199a1)

As you see in the screenshot the full qualified class name is inserted.

But usually I want the class to be added as import and only the class name to be inserted at the caret's position.
So the result should look like this:

![grafik](https://github.com/apache/netbeans/assets/1118790/2ceaab68-05bc-42d5-912a-0d811532bf6e)

### To be considered

Before Netbeans inserts the import, it has to check if the type already is imported or if there is already another type imported with the same name but different namespace. In the latter case it might insert the full qualified class name (like today).

### Use case/motivation

The current situation requires some manual work for each code completion, when working with namespace.

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
As an old issue: https://bz.apache.org/netbeans/show_bug.cgi?id=270083

**Comment by junichi11** [comment]
@stollr It would be nice if you can test it with the dev version: https://github.com/apache/netbeans/suites/20437665071/artifacts/1219370144

**Comment by stollr** [comment]
Thanks for your work on this. To enable this behaviour one has to check "Auto import" in Options -> Editor -> Code Completion -> Language [PHP].

I'd suggest to add a separate checkbox instead of a fourth type of code completion which could be checked to enable automatic import for **smart** and **unqualified** code completion. Because both of these types may benefit from the automatic import ;-)

I have tried to create an example how this could look like:

![grafik](https://github.com/apache/netbeans/assets/1118790/b4ecc3e8-f223-4ad3-b09c-7f169d1bb726)


Apart from that, the feature works well. I have only one notice:

If the class has a doc block. The import statement is placed between the doc block and the class definition. Better would be, if the import is added below the namespace declaration or at the beginning of the file if there is no namespace declaration.

What do you think?

**Comment by junichi11** [comment]
@stollr Thank you for testing it! I'll improve a bit.

**Comment by junichi11** [comment]
Improved:
https://github.com/apache/netbeans/suites/20483680915/artifacts/1223080861

![nb-php-auto-import-options-01](https://github.com/apache/netbeans/assets/738383/730e3c4a-4a41-4efb-94b5-e4bc86b4eb4c)

**Comment by stollr** [comment]
I have tested your update and it works great :-)
But I still suggest to enable the "Auto import" per default.

I have one question: It is not clear to me what the "Auto import for Scope" option is for?

**Comment by junichi11** [comment]
Thanks for testing it.

> But I still suggest to enable the "Auto import" per default.

I will do it in the future but I would not like to do it now because some people don't like to change behavior without permission.

> I have one question: It is not clear to me what the "Auto import for Scope" option is for?

"Namespace Scope" means as it is.

"File Scope" means... like the following case (i.e. without namespaces)

```php
<html>
    something...
    <p><?php echo \NS\something(); ?></p>
</html>
```

**Comment by stollr** [comment]
>>  But I still suggest to enable the "Auto import" per default.
>
> I will do it in the future but I would not like to do it now because some people don't like to change behavior without permission.

Okay, this is reasonable.

> "File Scope" means... like the following case (i.e. without namespaces)

Alright. Thanks for clarification 👍

**Comment by junichi11** [comment]
OK. I'll merge the PR. Please report a new issue if you come across problems. Thanks!
