### ISSUE TITLE
Diff window scroll bug

### ISSUE THREAD

**Issue by trixon** [apache/netbeans#6995]
### Apache NetBeans version

Apache NetBeans 20

### What happened

When I place the mouse on any of the line number columns in the Diff window and swipe two fingers up/down to scroll the lines, only the line number part scrolls, not the lines themselves.

I can reproduce this with NB20 & NB21-rc1 on different linux systems with X and Wayland,
on windows it works as expected.

Screenshot with scrolled numbers in a file without major changes..

![bild](https://github.com/apache/netbeans/assets/153314/74f4bcdb-88f4-43e0-9bba-90845ed424c7)

### How to reproduce

Place the mouse on any of the line number columns in the Diff window and swipe two fingers up/down to scroll the lines.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux

### JDK

21.0.1; OpenJDK 64-Bit Server VM 21.0.1+12-LTS; Azul Systems, Inc.

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
also reproducible on windows.

**Comment by mbien** [comment]
so, this might be a jdk bug.
```diff
diff --git a/ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/editable/DiffContentPanel.java b/ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/editable/DiffContentPanel.java
index d693f77..4b78741 100644
--- a/ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/editable/DiffContentPanel.java
+++ b/ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/editable/DiffContentPanel.java
@@ -67,7 +67,7 @@
         add(scrollPane);
         
         linesActions = new LineNumbersActionsBar(this, master.isActionsEnabled());
+        linesActions.addMouseWheelListener(e -> {});
 
         actionsScrollPane = new JScrollPane(linesActions);
         actionsScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
```


this did already stop the line numbers component from scrolling - which is unusual. I originally planned on adding `e.consume()` as quick fix, but the empty listener was enough.

please take a look at the dev build of https://github.com/apache/netbeans/pull/7009, it delegates the mouse events to the editor.
