### ISSUE TITLE
Save As dialog freezes IDE for about 10 seconds

### ISSUE THREAD

**Issue by tztztztz** [apache/netbeans#7003]
### Apache NetBeans version

Apache NetBeans 20

### What happened

When I'm trying to save existing file to a new file using "Save As", whole IDE freezes for about 10 seconds. 

During that time Task manager shows extreme usage of processor by NetBeans IDE process.

Netebeans log doesn't show anything.

It doesn't make any problems when im just saving file after changes, it is problematic only when im trying to "Save As".

Here is part of the print screen from a moment when it freezes. After freeze is done, the Save As dialog appears.

![netbeans_freeze](https://github.com/apache/netbeans/assets/7032308/28164f87-ffbf-44cc-8102-549d6dc54472)

### Language / Project Type / NetBeans Component

PHP 7.4

### How to reproduce

I have not idea how exactly reproduce it, because it started to happen just few days ago, before that it was working flawlessly. I didn't change anything in my system that runs on Windows 10 Pro.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

System: Windows 10 version 10.0 running on amd64; UTF-8; pl_PL (nb)

### JDK

Runtime: Java(TM) SE Runtime Environment 19.0.1+10-21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

It is occuring every time I'm trying to save file by "Save As" option.

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Please try with a current supported JDK, such as latest JDK 17 or 21.

Have you added network drives, any broken shortcuts on the desktop, etc.?  Sounds like it could be JDK issue.

**Comment by tztztztz** [comment]
I've updated Java version, now the About Dialog shows:

Java: 21.0.2; Java HotSpot(TM) 64-Bit Server VM 21.0.2+13-LTS-58
Runtime: Java(TM) SE Runtime Environment 21.0.2+13-LTS-58

Unfortunately it didn't resolve the problem.

I didn't add any network drivers or anything, but I'm connecting from time to time my phone to the PC using USB cable, and then disconnect.

Myabe IDE somewhat remembered that additional "phone disk" somewhere and now it is trying to find it every time I want to view folders? But I as doing for for a long time, it's not like I did it 1st time few days ago.

Because the problem is not only with "Save As", for example: if im trying to use Tools -> Java Platforms and "Add Platform" or perform any other operation that requires reading form directory, it freezes, which is quite frustrating.

Is there any way to debug it besides the messages.log file?

Anyway, I'm posting latest messages.log here

[messages.log](https://github.com/apache/netbeans/files/14071965/messages.log)

**Comment by neilcsmith-net** [comment]
This is probably similar to #4673 and other related issues.  It might be this won't-fix bug in the JDK? https://bugs.java.com/bugdatabase/view_bug?bug_id=8265446  Which might be one more reason to progress with removing the security manager from the IDE.

Do you have a shortcut for that phone disk on your desktop?

**Comment by tztztztz** [comment]
I have found the problem. I've uninstalled few days ago some applications, and afther that there was a shortcut left on the desktop to non existing file. After deleting the shortcut, IDE stopped to do the freeze.

Thank You for help, case closed.
