### ISSUE TITLE
New file created by copy/paste in git repo ignores commit exclusion flag

### ISSUE THREAD

**Issue by gwinstanley** [apache/netbeans#7006]
### Apache NetBeans version

Apache NetBeans 20

### What happened

New files created in git repo via copy/paste of an already committed file are automatically staged for commit, contrary to expectation when relevant flag is set in options.

### Language / Project Type / NetBeans Component

NetBeans git support

### How to reproduce

1. Ensure selected: Options / Team / Versioning / Git / Exclude new file from commit automatically
2. In existing git repo, copy/paste a file already committed.
3. Check repo status; new file is already staged.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS 14.3 Sonoma

### JDK

Adoptium OpenJDK 21.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
I suppose a copied file would qualify as new file broadly speaking. So yeah it should be probably excluded using the same option.

**Comment by gwinstanley** [comment]
That was my thinking; not exactly a high-profile issue though. I'm not familiar with NB dev at all, but it may make a good starting place to dip a toe in at some point in the near future. If you happen to have a suggestion which part of the codebase to look at to get started it could be helpful, otherwise I'll dip in when I get a chance and see how far I get.

**Comment by mbien** [comment]
starting point is probably the config itself:
https://github.com/apache/netbeans/blob/1c19e60bc6b995e5c0228eca4785ec4ad7a26171/ide/git/src/org/netbeans/modules/git/GitModuleConfig.java#L109-L111
including typo ;)

next step would be to find the place where versioning hooks into the copy action. Searching for usages of `GitModuleConfig` might lead to the right path.

**Comment by matthiasblaesing** [comment]
@gwinstanley please have a look at PR #7070. That should fix the issue. Please see if it works for you. A nightly build is available from the Checkpage: https://github.com/apache/netbeans/actions/runs/7907454984 or directly: https://github.com/apache/netbeans/actions/runs/7907454984/artifacts/1246122472. The nightly is available for the next 4 days.

**Comment by matthiasblaesing** [comment]
@gwinstanley thank you for testing and confirming the fix. There is no need to close the issues manually, as the PRs are normally linked to the issues and close these when merged. That indeed not yet the case and thus the fix will only be in NB22.
