### ISSUE TITLE
Unable to open Preview Design window on Mac OS X

### ISSUE THREAD

**Issue by brunogptavares** [apache/netbeans#7007]
### Apache NetBeans version

Apache NetBeans 20

### What happened

If I'm using the Netbeans Swing GUI Builder with the Mac OS X L&F enable by default, and clicking in button to show "Preview Disgn" in the toolbar nothing happens, it just gives an exception in the messages.log.    

![screen1](https://github.com/apache/netbeans/assets/2218801/bf199e19-b007-4a0b-956a-219fff9becaa)

In alternative if we have another L&F enabled, we can right click in Navigator panel and selected "Preview Design" -> "Mac OS X" with the same result, other previews work fine.

![screen2](https://github.com/apache/netbeans/assets/2218801/bcd3e76b-fb4f-421b-babf-251a4b13801c)

[messages.log](https://github.com/apache/netbeans/files/14072807/messages.log)

### Language / Project Type / NetBeans Component

Java Maven Project with Swing GUI Editor

### How to reproduce

1. Create New Project -> Java with Maven -> Java Application
2. Add New -> Swing GUI Forms -> JFrame Form
3. Edit the form in Design mode
4. Right click in JFrame in the Navigator panel and selected Preview Design -> Mac OS X

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS Somona 14.2.1

### JDK

JDK 21.0.1 Temurin

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I fixed this problem by adding `-J--add-opens=java.desktop/com.apple.laf=ALL-UNNAMED` to `netbeans_default_options` in netbeans.conf file.

### Are you willing to submit a pull request?

Yes

**Comment by brunogptavares** [comment]
I have got the same problem on Windows 11 Pro, when I click on Preview Design -> Windows and Preview Design -> Windows Classic.

On Windows I fixed with `-J--add-opens=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED`

**Comment by mbien** [comment]
closing, since the PR was already merged
