### ISSUE TITLE
Session beans cannot be generated for entity classes

### ISSUE THREAD

**Issue by aadiaf** [apache/netbeans#7066]
### Apache NetBeans version

Apache NetBeans 20

### What happened

Till version 18, it was straight forward with no problems of using the wizard of creating session beans for entity classes, but this version, 20, gives an error saying "Cannot be generated because EJB Lite classes are not available on project classpath".
Also the wizard of "creating entity classes from database" in version 20 does not produce validation annotation as before in version 18.

### Language / Project Type / NetBeans Component

Java EE Maven Web Application

### How to reproduce

What I do now is use version 18 to help me producing entities from database and their session beans (Facades) and proceed in version 20

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Windows 10

### JDK

11, 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
There was at least one wrong change, that might have influenced this. This report is lacking a clear error report, as no steps to reproduce are given. Based on my interpretation I created #7080, which should fix this.

@aadiaf there is a nightly build available from the checks page: https://github.com/apache/netbeans/actions/runs/7963454053 or directly https://github.com/apache/netbeans/actions/runs/7963454053/artifacts/1257313039. It is available for the next 5 days. Please test it.

**Comment by akaouane** [comment]
I think the problem apear on Linux and not on Windows.
I created a new virtualbox instance (windows 10) and I installed apache netbeans 21, and all things work fine.
But on my linux (Ubuntu 22.04), I get problems when trying to create JSF pages from entity classes:
1- I get classes in the list that not exists in my project
2- I get the message error : 
![Screenshot from 2024-02-22 22-59-40](https://github.com/apache/netbeans/assets/101929111/5576377e-e41a-4e21-8192-24defd9ffbeb)
