### ISSUE TITLE
NetBeans  21 console Chinese characters are garbled

### ISSUE THREAD

**Issue by yuedaxia76** [apache/netbeans#7098]
### Apache NetBeans version

Apache NetBeans 21 release candidate

### What happened

System.out.println("中文a");   result is :中文a
in netbeans 21 it is:����a

Even after setting   set -J-Dfile.encoding=UTF-8 ,-J-Dfile.encoding=GBK  ,there are still garbled characters

### Language / Project Type / NetBeans Component

maven project

### How to reproduce

run 👍 
    public static void main(String[] argm) throws Exception {
        System.out.println(System.getProperty("file.encoding"));
        System.out.println(Charset.defaultCharset());
        //System.setProperty("console.encoding", "UTF-8");
        System.out.println("中文a");
        System.setOut(new PrintStream(System.out,true,"UTF-8"));
        System.out.println("中文a");
        
        
    }

### Did this work correctly in an earlier version?

Apache NetBeans 20

### Operating System

windows 10

### JDK

test in 17、21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by yuedaxia76** [comment]
I user netbeans 21 release version.

**Comment by yuedaxia76** [comment]
![test result](https://github.com/apache/netbeans/assets/12583400/5c5fdfe6-cc6f-4dde-b640-65b997563f90)

**Comment by yuedaxia76** [comment]
![test reult](https://github.com/apache/netbeans/assets/12583400/45c48d28-53a2-40f1-818c-667854cdcf00)

**Comment by neilcsmith-net** [comment]
You need to set `stdout.encoding` - see also #4771

**Comment by yuedaxia76** [comment]
set  -J-Dstdout.encoding=utf-8  in netbeans.conf or set project run vm param -Dstdout.encoding=utf-8  no effect。 Old version ready to use out of the box, no need to set up。

**Comment by yuedaxia76** [comment]
set -J-Dstdout.encoding=GBK in netbeans.conf  is ok 。 Old version ready to use out of the box, no need to set up。
