### ISSUE TITLE
Problemas en el portapapeles (copy and paste)

### ISSUE THREAD

**Issue by kgalarza95** [apache/netbeans#7101]
### Apache NetBeans version

Apache NetBeans 20

### What happened

Al momento de copiar y pegar, es decir, el portapapeles no está funcionando correctamente. A veces no permite copiar y pegar código desde otro lado, esto solo sucede en netbeans 20 porque en el 17 si funciona bien.

### How to reproduce

no sé que lo produce.

### Did this work correctly in an earlier version?

Apache NetBeans 20

### Operating System

windwos

### JDK

17

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
This is a duplicate of #3962

**Comment by IngeAida** [comment]
En el paquete en netbeans está desabilitado la opción copiar y pegar por lo tanto no puedo agregar imágenes en mi proyecto, alguien me puede ayudar

**Comment by mikaelarh** [comment]
I created a Netbeans plugin to fix that error.

https://github.com/mikaelarh/CopyPasteFixNetbeans/releases/tag/Release_0.1
