### ISSUE TITLE
Apache NetBeans does't launch on Windows if userdir contains non-English symbols

### ISSUE THREAD

**Issue by Sergey7701** [apache/netbeans#7109]
### Apache NetBeans version

Apache NetBeans 21

### What happened

After installing netbeans, I found that it does not start because it incorrectly identifies the user's folder. Replacing the launcher with the old one from version 20 solved the problem
![netbeans](https://github.com/apache/netbeans/assets/46502232/6f0d4a89-f48a-42cc-9094-cdaf6792df84)

### How to reproduce

rename the user's folder to a Cyrillic name

### Did this work correctly in an earlier version?

Apache NetBeans 20

### Operating System

Windows 11 23H2

### JDK

jdk-17.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
@eirikbakke @ebarboni I think this might be the first version of NetBeans that has actually shipped with the launcher changes introduced in https://github.com/apache/netbeans-native-launchers/pull/7 ???  Is this actually a regression caused by that somehow?

**Comment by eirikbakke** [comment]
@Sergey7701 Some follow-up questions:
1) What is the correct name of the user directory here? (In Cyrillic characters)
2) Could you see if the problem persists (with the latest version of the launcher that caused the problem) if you delete the NetBeans *cache* directory and try to restart NetBeans? (The cache directory is a different directory that is likely at C:\Users\<username>\AppData\Local\NetBeans\Cache\dev
3) Could you try running the netbeans64.exe launcher from the Windows command line, with the "--trace launcherlog.txt" option, and include both the output on the command line and the contents of the launcherlog.txt file?
4) In the Windows control panel, go to Time & language > Language & region -> Related settings -> Administrative language settings -> Change system locale. What is listed as the "Current system locale"? Is the "Beta: Use Unicode UTF-8 for worldwide language support" checkbox checked or not? (It shouldn't have to be.)

**Comment by eirikbakke** [comment]
Ah, I think you might need a newer Java version; at least Java 17.0.5, which contains a backport of JDK bug [JDK-8272352](https://bugs.openjdk.org/browse/JDK-8272352).

NetBeans 21 does work for me without modification on Java 17.0.9 when run with a user with cyrillic characters in their username and home directory:

<img width="379" alt="about-cyrillic" src="https://github.com/apache/netbeans/assets/886243/83b44d90-e026-4c77-ae35-54b51eb944bf">

**Comment by Sergey7701** [comment]
I reinstalled Netbeans with jdk 21 and the problem was resolved
![netbeans](https://github.com/apache/netbeans/assets/46502232/91b2edd0-24fc-48c8-8f9b-9c7358fe24df)

**Comment by eirikbakke** [comment]
Great! I'm fairly certain that the issue is the aforementioned JDK bug, then, and so the recommendation to others who encounter this would be to upgrade to the latest Java version. (Or latest the latest patch release of Java 11 or Java 17 if they prefer those Java versions for any reason.)

Thanks for the report!
