### ISSUE TITLE
Auto-close of brackets not working in C++

### ISSUE THREAD

**Issue by iahung3** [apache/netbeans#7129]
### Apache NetBeans version

Apache NetBeans 21

### What happened

Brackets are not auto-closed.

### Language / Project Type / NetBeans Component

C++

### How to reproduce

For example, type `{` or `(`. It will do nothing.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows

### JDK

21 LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

No

### Are you willing to submit a pull request?

No

**Comment by bitrunner** [comment]
It's working for me.  Do you have "Insert Closing Brackets Automatically" checked under Tools -> Options -> Editor -> Code Completion for All Languages?

**Comment by iahung3** [comment]
> Do you have "Insert Closing Brackets Automatically" checked under Tools -> Options -> Editor -> Code Completion for All Languages?

Yes.
