### ISSUE TITLE
Formatting problems in callback functions in PHP

### ISSUE THREAD

**Issue by Eugene-Melbourne** [apache/netbeans#7140]
### Apache NetBeans version

Apache NetBeans 21

### What happened

an indent expected when it is a function parameters

### Language / Project Type / NetBeans Component

PHP project

### How to reproduce

actual formatting

```php
class Foo
{
    public function foo(): void
    {
        $this->app->singleton(Factory::class,
            function (): Factory {
                return new Factory(
                foo: 0,
                );
            });
    }
}
```
expected formatting 

```php
class Foo
{
    public function foo(): void
    {
        $this->app->singleton(Factory::class,
            function (): Factory {
                return new Factory(
                    foo: 0,
                );
            });
    }
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64; UTF-8; en_AU (nb)

### JDK

19.0.2; Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by Eugene-Melbourne** [comment]
here is another example:

actual formatting

    Foo::foo()
        ->boo();

    Foo::foo()
        ->boo(function () {
            Foo::foo()
            ->boo();
        });

expected formatting

    Foo::foo()
        ->boo();

    Foo::foo()
        ->boo(function () {
            Foo::foo()
                ->boo();
        });
        
Would you like me to add this example to the original request, or would you like me to create a different request?

**Comment by junichi11** [comment]
@Eugene-Melbourne 
> Would you like me to add this example to the original request, or would you like me to create a different request?

Please separate it. (Please report it as a new issue.)
