### ISSUE TITLE
Unable to type in the output panel with single Java file

### ISSUE THREAD

**Issue by sabit-sbbt** [apache/netbeans#7142]
### Apache NetBeans version

Apache NetBeans 21

### What happened

I like to work with single java file without project because of learning purpose. If I create a Java file under a project (that maybe maven or ant etc.), then it will be too heavy and will take more time & cpu to run in the output panel.

So I feel comfortable to run single java file. While learning any programming language, it needs to run a file again and again to practice & understand code.
But the main problem is when I run a single java file with some simple user input statement, then I am unable to type in the output to give user input.
On the other hand if I run same java code under a project (maven or others), then it is possible to type in the output panel to give user input.

It means, typing in the output panel is not possible with single java file.
But why?
Please, I am seeking for help to fix this issue as it become possible to type in the output panel with single java file.

I also attached two screenshots where the problem is simply visible.
![First](https://github.com/apache/netbeans/assets/73186632/2d9e4f66-d227-4e12-85e0-e52416777b07)
![Second](https://github.com/apache/netbeans/assets/73186632/b030d8c8-17b4-459b-8c58-99a75bf16006)

### How to reproduce

**Step 1:** Find out the config file of the output panel,
**Step 2**: Look for properties which are associated for single java file,
**Finally** serach out the typing control for user input.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 Pro

### JDK

JDK 21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
the single file launcher seems to use a very basic output window. e.g stop button is missing too. This is something which would be good to improve I agree.

> If I create a Java file under a project (that maybe maven or ant etc.), then it will be too heavy and will take more time & cpu to run in the output panel.

I highly doubt that this makes a difference. Ant projects should have very low overhead. Maven projects should start in less than a second on most systems and if you configure NetBeans to use mvnd (https://github.com/apache/maven-mvnd) it starts almost instantly.
