### ISSUE TITLE
Entity classes from database wizard not working. NetBeans 21.

### ISSUE THREAD

**Issue by klermangutierrez** [apache/netbeans#7144]
### Apache NetBeans version

Apache NetBeans 21

### What happened

The Entity Classes from Database Wizard doesn't work anymore in version 21. I haven't used it for some time, and I suspect that it doesn't work after a NetBeans upgrade from version 20.

### Language / Project Type / NetBeans Component

Java Desktop Maven Hibernate

### How to reproduce

In the Services Tab, I have created a new connection to a MySQL Server database. Tables, fields can be seen, and queries execute as expected.
In the Projects Tab, I select a project package, right click and select New -> Other -> Persistence -> Entity Classes from Database, and clic on Next.
A red label in the wizard window says "Select the table source". At the bottom of the NetBeans Window an information warning appears. "You have one unread notification".
In the Notification Tab, I click on the Unexpected exception, and I read "Width and height must be > 0". I click on Show Details, and I get a log of warnings.

### Did this work correctly in an earlier version?

Apache NetBeans 20

### Operating System

Linux Ubuntu 22.04.4 LTS

### JDK

OpenJDK Runtime Environment (build 21.0.1+12-29), OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Please provide the message log when the problem appears.

**Comment by klermangutierrez** [comment]
Hello,
Here I include the requested file.
[messages.log](https://github.com/apache/netbeans/files/14608330/messages.log)

**Comment by matthiasblaesing** [comment]
Thank you. The problem was reproducible and the core information missing above is, that this happens for java projects without ties to a concrete server/without explicit JPA support. I created a PR that should fix that (see link above).

Please test if the nightly build fixes the issue for you (it will be available for the next 4 days):

- Overview page: https://github.com/apache/netbeans/actions/runs/8302458674
- Direct link: https://github.com/apache/netbeans/actions/runs/8302458674/artifacts/1330914673

**Comment by matthiasblaesing** [comment]
@sgparry without seeing the project I can't say. Provide the project or a minimal reproducer and I'll take a look.

> I have not had a chnace to try the fix out and we cannot move to 22+ because of the JDK requirements..

There is no hardlink between the JDK used for your project and the JDK running NetBeans. You can still register JDK 8 as target platform on NB24, while the IDE is running on JDK 17/21/23.
