### ISSUE TITLE
IllegalArgumentException: URI is not hierarchical

### ISSUE THREAD

**Issue by mtbadi39** [apache/netbeans#7156]
### Apache NetBeans version

Apache NetBeans 21

### What happened

Always when open xhtml files

### Language / Project Type / NetBeans Component

Maven JoinFaces Spring Boot Project

### How to reproduce

Don't know !

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64

### JDK

21.0.1; OpenJDK 64-Bit Server VM 21.0.1+12-LTS; BellSoft

### Apache NetBeans packaging

Other

### Anything else

installed with chocolatey : https://community.chocolatey.org/packages/apache-netbeans.portable

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
> How to reproduce
> Don't know !

Then this is not fixable.

**Comment by mtbadi39** [comment]
[messages.log](https://github.com/apache/netbeans/files/14600497/messages.log)
