### ISSUE TITLE
java.lang.IllegalArgumentException: URI is not hierarchical

### ISSUE THREAD

**Issue by mtbadi39** [apache/netbeans#7157]
### Apache NetBeans version

Apache NetBeans 21

### What happened

[messages.log](https://github.com/apache/netbeans/files/14600596/messages.log)

### Language / Project Type / NetBeans Component

Java Maven Project with JoinFaces and Spring Boot

### How to reproduce

open xhtml file for editing

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64

### JDK

21.0.1; OpenJDK 64-Bit Server VM 21.0.1+12-LTS; BellSoft

### Apache NetBeans packaging

Third-party package

### Anything else

when open xhtml for editing

### Are you willing to submit a pull request?

No

**Comment by mtbadi39** [comment]
![netbeans](https://github.com/apache/netbeans/assets/8750684/bb2f74d5-f67d-4ea7-9f06-dbdebfb89786)
[messages.log](https://github.com/apache/netbeans/files/14600714/messages.log)

**Comment by matthiasblaesing** [comment]
@mtbadi39  you are hitting a fallback path, that is not prepared for your situation. I suspect, that your userdir is damaged. Anyway, Please test the development version available from the PR checks page, whether it helps:

Checks page: https://github.com/apache/netbeans/actions/runs/8287322390
Direct link: https://github.com/apache/netbeans/actions/runs/8287322390/artifacts/1327529549

**Comment by mtbadi39** [comment]
Hi @matthiasblaesing 
I can confirm that with development version there is no errors (my test was : open / edit / close / re-open all .xhtml files in my project).

Thanks.
