### ISSUE TITLE
When I create multiple new modules using the USE code in X3D, the latest USE module is displayed in the view window, the old USE is not, and the BScontact software is displayed correctly.

### ISSUE THREAD

**Issue by flztqlzy** [apache/netbeans#7173]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

When I create an X3D scene in which USE reuse code is used, the screen displays a 3D image in which the newly used USE overwrites the previously used USE, but if I run the file on BS, the image is fine again.Notice the wheels of the tank
![tank-BScontact](https://github.com/apache/netbeans/assets/163950814/63c5e9b0-bff3-4108-93eb-ac5f8bc6f081)

![tank-X3D](https://github.com/apache/netbeans/assets/163950814/9b146611-a513-4575-b403-20c99434478f)

### How to reproduce

I will share my X3D model with you, I hope it will help you.
[tank.zip](https://github.com/apache/netbeans/files/14644427/tank.zip)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows11

### JDK

jdk-21_windows-x64_bin.exe

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Sorry,About the previous question, I don't know which platform this software belongs to. The full name of this software is X3D-Edit 4.0 Authoring Tool. I hope I can help with this problem.

### Are you willing to submit a pull request?

Yes

**Comment by matthiasblaesing** [comment]
This is the issue tracker for the NetBeans project itself. You are referring to the X3D integration, for which you can find the homepage here: https://savage.nps.edu/X3D-Edit/

**Comment by flztqlzy** [comment]
ok,thank you
