### ISSUE TITLE
Add ability to change between worspaces easily

### ISSUE THREAD

**Issue by andreszs** [apache/netbeans#7179]
### Description

We are using NetBeans to work on several projects simultaneously, such as Apache Cordova and different PHP applications.

Since each project involves opening **lots** of files, switching from one project to the other is and endless process of closing and reopening the relevant files. To avoid this we simply leave **all files open all the time**, resulting in and endless scroll of colored tabs to reach the files from the required project we want to switch to.

A "**Save / Load workspace**" option to directly reopen all files from previous session/project would be great, this way the users could switch between workspaces in a matter of seconds and restore all the opened files in the same order they were saved.

### Use case/motivation

Quickly and easily restore a collection of opened files from one session.

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
What you're describing already exists. You want to look at the Project Groups option.
