### ISSUE TITLE
PHP - Format adds blank lines each time it is run

### ISSUE THREAD

**Issue by jnmills** [apache/netbeans#7185]
### Apache NetBeans version

Apache NetBeans 21

### What happened

This is similar/same as legacy report 235228.  Does not appear to be in the current NetBeans issues database. If you have an if statement without braces, each time format is run a new blank line is added after the "then" clause.

### Language / Project Type / NetBeans Component

PHP code formatting

### How to reproduce

Use this code.   Note that if you remove " //comment 1" the problem does not occur. When you run (right click)-Format a new line is added before "another comment".

```php
<?php

if (1)
    $y = 0;  // comment 1

    
// another comment
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

WIndows 10

### JDK

11.0.13

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Product Version: Apache NetBeans IDE 21
Java: 11.0.13; Java HotSpot(TM) 64-Bit Server VM 11.0.13+10-LTS-370
Runtime: Java(TM) SE Runtime Environment 11.0.13+10-LTS-370
System: Windows 10 version 10.0 running on amd64; Cp1252; en_GB (nb)
User directory: D:\Users\xxx\AppData\Roaming\NetBeans\21
Cache directory: D:\Users\xxx\AppData\Local\NetBeans\Cache\21

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Please also write an expected result and an actual result. Thanks.

**Comment by junichi11** [comment]
OK. Reproducible. Thanks for reporting it.

**Comment by junichi11** [comment]
Old issue: https://bz.apache.org/netbeans/show_bug.cgi?id=235228
