### ISSUE TITLE
Formatting problems in class properties defaults declaration in PHP

### ISSUE THREAD

**Issue by Eugene-Melbourne** [apache/netbeans#7190]
### Apache NetBeans version

Apache NetBeans 21

### What happened

class properties defaults declaration in PHP does not format correctly if types are provided

### Language / Project Type / NetBeans Component

PHP project

### How to reproduce

actual formatting

```
use Carbon\Carbon;
class Foo
{
    private ?string $a   = '';
    private ?Carbon $b   = null;
    private ?int $c   = null;
    private ?array $foo = [];
}
```

expected formatting

```
use Carbon\Carbon;
class Foo
{
    private ?string $a   = '';
    private ?Carbon $b   = null;
    private ?int $c      = null;
    private ?array $foo  = [];
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64; UTF-8; en_AU (nb)

### JDK

19.0.2; Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Please also write your formatting option.
