### ISSUE TITLE
Formating of "match" expression same as arrays in PHP

### ISSUE THREAD

**Issue by Eugene-Melbourne** [apache/netbeans#7191]
### Apache NetBeans version

Apache NetBeans 21

### What happened

when you formatting PHP code, the match expression is being formatted without columns support

### How to reproduce

alt + shift + f - is making a formatting

this is the actual formatting

```
match ($type) {
    'integer' => 'a',
    'string' => 'b',
    default => null,
};
```

this is the expected formatting

```
match ($type) {
    'integer' => 'a',
    'string'  => 'b',
    default   => null,
};

```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 10.0 running on amd64; UTF-8; en_AU (nb)

### JDK

19.0.2; Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I know it may sound like a feature request, but as a feature it was already implemented in the ticket
https://github.com/apache/netbeans/issues/6074

but the formatting is still not being fixed, so I suspect it is a bug this time.

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Did you check formatting options?

![image](https://github.com/apache/netbeans/assets/738383/207580e2-e524-466f-878c-ae9891f3e73c)

**Comment by junichi11** [comment]
I can't reproduce it with NB22. If it does not work fine, please feel free to reopen this with your exact steps to reproduce it.

**Comment by Eugene-Melbourne** [comment]
`Alignment > Group Multiline Alignment >Match Arm Arrow` is working for me. Thank you
