### ISSUE TITLE
nbm-maven-plugin does not work with Java 22

### ISSUE THREAD

**Issue by GuyDaniel** [apache/netbeans#7197]
### Apache NetBeans version

Apache NetBeans 21

### What happened

Any nbm module with code in it set to JDK 22 fails with :
 ` Execution default-manifest of goal org.apache.netbeans.utilities:nbm-maven-plugin:14.0:manifest failed: Unsupported class file major version 66 from directory = .... blah blah blah`

### Language / Project Type / NetBeans Component

Java Maven Project using Netbeans Modules

### How to reproduce

1. Create a new Project using Netbeans Modules. 
2. Set the JDK to 22. 
3. Create a Java class in the project.
4. Try and build the project.

### Did this work correctly in an earlier version?

Apache NetBeans 16 or earlier

### Operating System

OS: Garuda Linux x86_64 Kernel: 6.7.0-zen3-1-zen

### JDK

Azul 22

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

The last version of nbm-maven-plugin to work is 3.13.3
The newest version of the plugin - 14.0 does not, presumably as from about version 4.0 it started using the asm libraries.
JDK 22 is quite new, and support for it probably only got included in the ASM release in March?
This is easy to work around - just configure the nbm plugin as per:
```xml  
<plugin>
    <groupId>org.apache.netbeans.utilities</groupId>
    <artifactId>nbm-maven-plugin</artifactId>
    <extensions>true</extensions>
    <dependencies>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>9.7</version>
        </dependency>
    </dependencies>
</plugin>         
```
 

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
hi, the repo for this plugin including issues would be here: https://github.com/apache/netbeans/issues/7197

I checked and nothing in there directly depends on asm, which means this is automatically resolved just by updating regular dependencies and rolling a new version. Would you like to copy this issue over?

**Comment by GuyDaniel** [comment]
Yep, I'll do that. I did think about putting it there now that we have a github repo for nbm-maven-plugin. Thanks!
