### ISSUE TITLE
[bug] On `text/x-properties` Comment/Uncomment buttons not showing

### ISSUE THREAD

**Issue by cesarreyes3** [apache/netbeans#7207]
### Apache NetBeans version

Apache NetBeans 21

### What happened

On `text/x-properties` Comment/Uncomment buttons not showing

Apparently the necessary code exists, but it is not working
https://github.com/apache/netbeans/blob/cfedd4410d1f84b909bdfe914377d72dcc9c066a/ide/properties.syntax/src/org/netbeans/modules/properties/syntax/PropertiesKit.java#L53-L58
https://github.com/apache/netbeans/blob/cfedd4410d1f84b909bdfe914377d72dcc9c066a/ide/properties.syntax/src/org/netbeans/modules/properties/syntax/PropertiesKit.java#L37

### How to reproduce

Just open an `.properties` file, no Comment/Uncommet buttons

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

12

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by cesarreyes3** [comment]
Sorry, I'm on Windows and I don't know how to test that build, 
I tried to replace the `org-netbeans-modules-properties-syntax.jar` and `org-netbeans-modules-xml-tools.jar` .jars, 
but i didn't get any result

**Comment by matthiasblaesing** [comment]
1. Unzip the build
2. Find the `bin` directory
3. Run NetBeans using the `netbeans64.exe` launcher

The nightly builds use their own cache and user directory, so testing should be clean. Please do not import settings from old versions.

After testing please ensure, that to remove the cache and user dir again (use Help -> About to find the paths).

**Comment by cesarreyes3** [comment]
>I tried to replace the `org-netbeans-modules-properties-syntax.jar` and `org-netbeans-modules-xml-tools.jar` jars,

The nightly build was not necessary, i just remove netbeans cache, now works on my instalation, thanks

**Comment by cesarreyes3** [comment]
On this part, porperties has a highlight bug(_i did write it twice to show the problem_)

**Netbeans**

![image](https://github.com/apache/netbeans/assets/109559100/a8749df3-cc41-48cc-9558-9e97fb93554b)

**Github**
```properties
[new_oids]

[ new_oids ]

# We can add new OIDs in here
tsa_policy1 = 1.2.3.4.1
```
