### ISSUE TITLE
the profiler can not start (NB 21/ JAVA17/Ubuntu 20.04)

### ISSUE THREAD

**Issue by GisTom2** [apache/netbeans#7214]
### Apache NetBeans version

Apache NetBeans 21

### What happened

The profile cannot start 
Error occurred during initialization of VM
Could not find agent library /usr/lib/apache-netbeans/profiler/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so in absolute path, with error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/apache-netbeans/profiler/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so)

I can compile and debug the project.
[messages.log](https://github.com/apache/netbeans/files/14815970/messages.log)

### Language / Project Type / NetBeans Component

Java Maven Web application project

### How to reproduce

1. Install NB21
2. Create the maven project
3. Try to profile the project

### Did this work correctly in an earlier version?

Apache NetBeans 16 or earlier

### Operating System

Ubuntu 20.04  Linux version 5.15.0-101-generic running on amd64 

### JDK

17.0.6; Java HotSpot(TM) 64-Bit Server VM 17.0.6+9-LTS-190; Oracle Corporation

### Apache NetBeans packaging

Apache NetBeans provided installer, Apache NetBeans Snap Package

### Anything else

[messages.log](https://github.com/apache/netbeans/files/14815967/messages.log)
This is a stable issue. 
How to replicate
1. Install NB21
2. Create the maven project
3. Try to profile the project
----------------< com.BratzoCermak:binanceSpikeTrader >-----------------
Building binanceSpikeTrader 1.0-SNAPSHOT
  from pom.xml
--------------------------------[ jar ]---------------------------------

--- exec:3.1.0:exec (default-cli) @ binanceSpikeTrader ---
Error occurred during initialization of VM
Could not find agent library /usr/lib/apache-netbeans/profiler/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so in absolute path, with error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/apache-netbeans/profiler/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so)
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Can you try running with an up-to-date JDK, or from a different vendor / the OS package?

**Comment by kmusser2** [comment]
#### On ubuntu 20.04, this error occurs on NetBeans installed as a snap (version 102), running netbeans under openjdk 21.
--> profiling is unusable.  Other netbeans functions work fine.

$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.16) 2.31

#### On the jvm (also running openjdk 21) to which netbeans is trying to attach to profile:
Caused by: java.lang.UnsatisfiedLinkError: /snap/netbeans/102/netbeans/profiler/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/netbeans/102/netbeans/profiler/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so)

**Comment by JessHolle** [comment]
I have the same issue with RHEL 8 running under WSL.

$ ldd --version
ldd (GNU libc) 2.28

Why is this bug closed?!?

**Comment by GisTom2** [comment]
> Can you try running with an up-to-date JDK, or from a different vendor / the OS package?

FYI
This configuration works
Product Version: Apache NetBeans IDE 25
Java: 21.0.6; OpenJDK 64-Bit Server VM 21.0.6+7-Ubuntu-124.04.1
Runtime: OpenJDK Runtime Environment 21.0.6+7-Ubuntu-124.04.1
System: Linux version 6.11.0-21-generic running on amd64; UTF-8; en_US (nb)

**Comment by JessHolle** [comment]
As per my comment above:

```It would appear NB assumes RHEL 9 -- but doesn't document that only the latest Linux versions are supported, nor does this seem to make sense to me. Why so limiting?

Why is this bug closed?!?
```
