### ISSUE TITLE
[PHP] Some constants are missing in stubs

### ISSUE THREAD

**Issue by mvorisek** [apache/netbeans#7219]
### Description

Some core constants like `DEBUG_BACKTRACE_IGNORE_ARGS` are missing in the Netbeans PHP stubs.

### Use case/motivation

All classes/functions/methods/properties/constants should be present to improve IDE typehinting.

some good source is https://github.com/JetBrains/phpstorm-stubs or https://3v4l.org/RUUPW

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
I've already fixed it. 
https://github.com/apache/netbeans/issues/6358
