### ISSUE TITLE
Debugger: show BigDecimal value in variables

### ISSUE THREAD

**Issue by NicolaIsotta** [apache/netbeans#7228]
### Description

During debugging, in the "Variables" tab, it would useful to see the BigDecimal value instead of its reference, just like it currently happens for Double or other Number implementations.

### Use case/motivation

![image](https://github.com/apache/netbeans/assets/18428155/a216d5c4-8264-405d-a5c4-ad87b2e16f29)

### Are you willing to submit a pull request?

No

**Comment by NicolaIsotta** [comment]
Workaround found: add a formatter under Tools -> Options -> Java -> Java Debugger -> Variable Formatters
![image](https://github.com/apache/netbeans/assets/18428155/45ba39a7-c301-485e-9f38-2c11b2216875)

**Comment by mbien** [comment]
default formatters would be here: https://github.com/apache/netbeans/blob/668bca250cd66fd580b6bc3bc34412e80e324f66/java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/expr/formatters/VariablesFormatter.java#L303
