### ISSUE TITLE
NetBeans bundled Truffle Version incompatbile with JDK 22

### ISSUE THREAD

**Issue by Manmej** [apache/netbeans#7245]
### Apache NetBeans version

Apache NetBeans 21

### What happened

[messages.log](https://github.com/apache/netbeans/files/14888161/messages.log)

### How to reproduce

Just create a new project File>New Project > HTML5/Javascript >HTML/JS Aplication

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Windows 11 Home x64

### JDK

jdk-22_Windows_x64

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by matthiasblaesing** [comment]
@Manmej please test if PR #7248 fixes your problem. You can download a nightly build from the checks page (Artifacts dropdown, https://github.com/apache/netbeans/pull/7248/checks)  or directly https://github.com/apache/netbeans/suites/22509804037/artifacts/1392177585.

**Comment by matthiasblaesing** [comment]
Forget it - it does not work

**Comment by sdedic** [comment]
FWIW the error reported in the log is just a "side effect" of insufficient protection against linkage errors in script engines. When I tried to debug the issue, the HTML client project Wizard actually asked for `freemaker` scripting engine. But the Scripting initialization attempted to load (registered) JS engine, and the LinkageError aborted the whole process.

this issue should be solved separately from #7248 to avoid further similar issues.

**Comment by MartinBalin** [comment]
I've seen the above exception as well but when I invoke New from template again it works.

**Comment by sdedic** [comment]
Yes, according to my testing, 1st exception was a `ServiceConfigurationError`, but subsequent exceptions are caught by Scripting infrastructure and the operation (actually asking for `freemaker`) proceeds. The outcome depends on what operation triggers the 1st exception - that one fails now: the New from Template action - or for example proxy PAC evaluation running delayed on the background. Or some network-related operation that indirectly triggers proxy eval.
