### ISSUE TITLE
Invalid error detection in Javascript syntax

### ISSUE THREAD

**Issue by grelf-net** [apache/netbeans#7260]
### Apache NetBeans version

Apache NetBeans 21

### What happened

```js
for (let i = 0; i < cellsInRange.length; i++)
  { let ci = cellsInRange[i];
    if (!ci.cell.open)
    { let ims = ci.cell.getWallImages();
      let data = [
        {s:ci.sxydNW, i:ims[0]},//Bug in NetBeans!
        {s:ci.sxydNE, i:ims[1]},//It says ims is an undeclared global
        {s:ci.sxydSW, i:ims[2]},//OK in browser though
        {s:ci.sxydSE, i:ims[3]}];
      data.sort(function(a, b) {return b.s.d - a.s.d;}); // Descending distance
      this.drawWall(data[1].s, data[3].s, data[1].i, ci.fogNo);
      this.drawWall(data[2].s, data[3].s, data[2].i, ci.fogNo);
  } }

```

### Language / Project Type / NetBeans Component

HTML5/Javascript project (vanilla, for browser use)

### How to reproduce

![Screenshot 2024-04-11 155614](https://github.com/apache/netbeans/assets/38698437/587c6b4c-9549-4c3c-b777-da0918ce54f2)

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

WIndows 11 latest

### JDK

JDK 11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time. If I change the let ims to var ims it is OK. The error is in NetBeans syntax checker.

### Are you willing to submit a pull request?

No

**Comment by grelf-net** [comment]
Sorry - it did NOT work correctly in NB 18. That's what I was using when I found the problem. That prompted me to upgrade to 21 and the problem was still there. I have used NetBeans for many years without any such problems.

**Comment by matthiasblaesing** [comment]
Lets reopen - I'll see what to do about this.

**Comment by grelf-net** [comment]
I should perhaps add that there is no other variable or property called ims that might be confusing things. Also that I have tested the code in FireFox, Edge, and the built-in WebKit browser and they all work fine, finding the variable ims as required.

**Comment by matthiasblaesing** [comment]
Tested with current master and this:

```javascript
/* global cellsInRange */

for (let i = 0; i < cellsInRange.length; i++)
  { let ci = cellsInRange[i];
    if (!ci.cell.open)
    { let ims = ci.cell.getWallImages();
      let data = [
        {s:ci.sxydNW, i:ims[0]},//Bug in NetBeans!
        {s:ci.sxydNE, i:ims[1]},//It says ims is an undeclared global
        {s:ci.sxydSW, i:ims[2]},//OK in browser though
        {s:ci.sxydSE, i:ims[3]}];
      data.sort(function(a, b) {return b.s.d - a.s.d;}); // Descending distance
      this.drawWall(data[1].s, data[3].s, data[1].i, ci.fogNo);
      this.drawWall(data[2].s, data[3].s, data[2].i, ci.fogNo);
  } }
```

comes up without errors. Seeing no reaction, I assume this can be considered fixed.
