### ISSUE TITLE
Why does netbeans not support language internationalization(i18n)?

### ISSUE THREAD

**Issue by jyc19961212** [apache/netbeans#7274]
### Description

I need it to support Chinese interface and English interface，Thank u

### Are you willing to submit a pull request?

Yes

**Comment by matthiasblaesing** [comment]
If you want to translate your own application base on NetBeans modules, it is supported:

http://bits.netbeans.org/dev/javadoc/org-openide-modules/org/openide/modules/doc-files/i18n-branding.html
https://netbeans.apache.org/wiki/main/wiki/TranslateNetbeansModule/
https://netbeans.apache.org/tutorial/main/kb/docs/java/gui-automatic-i18n/
