### ISSUE TITLE
error Ajava.util.ServiceConfigurationError.

### ISSUE THREAD

**Issue by KendoPant** [apache/netbeans#7287]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

[messages.log](https://github.com/apache/netbeans/files/15056629/messages.log)
no me deja crear proyectos 

### How to reproduce

no me deja crear proyectos 
[messages.log](https://github.com/apache/netbeans/files/15056631/messages.log)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

so

### JDK

20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
```
  Product Version         = Apache NetBeans IDE 19
  Operating System        = Windows 11 version 10.0 running on amd64
  Java; VM; Vendor        = 22; Java HotSpot(TM) 64-Bit Server VM 22+36-2370; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 22+36-2370
```
NB 19 does not support running on JDK 22.

you can find the supported runtime JDK versions on the download page or on the readme, for example NB 21 supports running on JDK 11, 17 and 21 as you see here https://netbeans.apache.org/download/nb21/

NB 22 will support JDK 17, 21 and 22 once released
