### ISSUE TITLE
Rename method leads to naming conflicts

### ISSUE THREAD

**Issue by DongChunHao** [apache/netbeans#7300]
### Apache NetBeans version

Apache NetBeans 21

### What happened

When I select "k()" and perform the rename method refactoring,  new naem "m()" and i click "OK", a syntax error：

public class A {
    void m(Object m){
        System.out.println("A");
    }
}
class B extends A{
// rename k to m
    void k(String m){
        System.out.println("B");
    }
    void f(){
        m("1");
    }
}

refactoring result:
![image](https://github.com/apache/netbeans/assets/77560508/bb1ffe0a-b33d-4764-959f-1345a22c91c3)

Expected result: Check for grammar conflicts before renaming. If there are any grammar errors, a warning should be given

### How to reproduce

When I select "k()" and perform the rename method refactoring,  new naem "m()" and i click "OK", a syntax error：

public class A {
    void m(Object m){
        System.out.println("A");
    }
}
class B extends A{
// rename k to m
    void k(String m){
        System.out.println("B");
    }
    void f(){
        m("1");
    }
}

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows11

### JDK

20

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Please hold fire on making further issue reports until these can be assessed.  Swamping the project with multiple similar issues is not helpful.  Consider whether they can be encapsulated in a single meta issue.

Did you mean to select the NetBeans platform as packaging type?  Are these problems in the NetBeans IDE or in your own platform application based on the NetBeans IDE?
