### ISSUE TITLE
[PHP] function "use" variable linking is broken

### ISSUE THREAD

**Issue by mvorisek** [apache/netbeans#7348]
### Apache NetBeans version

Apache NetBeans 21

### What happened

![image](https://github.com/apache/netbeans/assets/2228672/5b282a5c-8327-48b4-909b-5ea2003e12cc)

Notice the `$fx();` line is not highlighted when other `$fx` variable usages are.

![image](https://github.com/apache/netbeans/assets/2228672/81e15a76-411f-4c66-8200-1faf5f2eaaa0)

It seems it is otherwise supported, but the `$otherFx = function () {};` line is breaking it.

As a consequence of this bug, `$fx` cannot be refactored/renamed using IDE in one step.

### Language / Project Type / NetBeans Component

PHP

### How to reproduce

```php
<?php

function test() {
    $fx = function () {};

    $callFx = function () use ($fx) {
        $otherFx = function () {};
        $fx();
        $otherFx();
    };
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

any

### JDK

any

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Reproducible. Thanks for reporting it.
