### ISSUE TITLE
NPE When Attempting to Add an Entity Class from the Database

### ISSUE THREAD

**Issue by SeanCarrick** [apache/netbeans#7360]
### Apache NetBeans version

Apache NetBeans 21

### What happened

Created a database on the *Services* tab of the IDE, using **Apache Derby *10.17.1.0***, then tried to add an entity class from the database in my project from the *Projects* tab. The *New Entity Classes from Database* dialog opened, but had the message "*Please wait...*" with a radio button, but never did populate the combo box with the databases from my Derby server. When I selected the *Local Data Source* radio button, the combo box stayed empty, without even the option to select a database:

![image](https://github.com/apache/netbeans/assets/25845416/de2a19dd-e048-4cef-8041-2f4cd368e545)

### Language / Project Type / NetBeans Component

Standard Java (JDK21) Application project using Ant

### How to reproduce

- Configure the *Services...Java DB* node with Apache Derby 10.17.1.0 for the server
- Start the database server
- Create a database, or use the sample database
- Create a standard Java application project from the *Projects* tab
- Add an *Entity Class from Database* to the project

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

System:
  Kernel: 6.1.0-17-amd64 [6.1.69-1] arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-6.1.0-17-amd64 root=UUID=<filter> ro quiet splash
  Desktop: KDE Plasma v: 5.27.5 wm: kwin_x11 vt: 7 dm: SDDM Distro: MX-23.2_KDE_x64 Libretto
    January 21 2024 base: Debian GNU/Linux 12 (bookworm)
Machine:
  Type: Laptop System: Dell product: Inspiron 3583 v: N/A serial: <superuser required> Chassis:
    type: 10 serial: <superuser required>
  Mobo: Dell model: 0WHCP7 v: A00 serial: <superuser required> UEFI: Dell v: 1.19.0
    date: 04/12/2022
Battery:
  ID-1: BAT0 charge: 31.1 Wh (100.0%) condition: 31.1/42.0 Wh (74.1%) volts: 12.7 min: 11.4
    model: Samsung SDI DELL CYMGM8C type: Li-ion serial: <filter> status: full
CPU:
  Info: model: Intel Core i5-8265U bits: 64 type: MT MCP arch: Whiskey Lake gen: core 8 level: v3
    note: check built: 2018 process: Intel 14nm family: 6 model-id: 0x8E (142) stepping: 0xB (11)
    microcode: 0xF4
  Topology: cpus: 1x cores: 4 tpc: 2 threads: 8 smt: enabled cache: L1: 256 KiB
    desc: d-4x32 KiB; i-4x32 KiB L2: 1024 KiB desc: 4x256 KiB L3: 6 MiB desc: 1x6 MiB
  Speed (MHz): avg: 600 high: 800 min/max: 400/3900 scaling: driver: intel_pstate
    governor: powersave cores: 1: 400 2: 800 3: 800 4: 400 5: 400 6: 400 7: 800 8: 800
    bogomips: 28800
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
  Vulnerabilities:
  Type: gather_data_sampling mitigation: Microcode
  Type: itlb_multihit status: KVM: VMX disabled
  Type: l1tf status: Not affected
  Type: mds mitigation: Clear CPU buffers; SMT vulnerable
  Type: meltdown status: Not affected
  Type: mmio_stale_data mitigation: Clear CPU buffers; SMT vulnerable
  Type: retbleed mitigation: IBRS
  Type: spec_rstack_overflow status: Not affected
  Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via prctl
  Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization
  Type: spectre_v2 mitigation: IBRS, IBPB: conditional, STIBP: conditional, RSB filling,
    PBRSB-eIBRS: Not affected
  Type: srbds mitigation: Microcode
  Type: tsx_async_abort status: Not affected
Graphics:
  Device-1: Intel WhiskeyLake-U GT2 [UHD Graphics 620] vendor: Dell driver: i915 v: kernel
    arch: Gen-9.5 process: Intel 14nm built: 2016-20 ports: active: HDMI-A-1,eDP-1 empty: none
    bus-ID: 00:02.0 chip-ID: 8086:3ea0 class-ID: 0300
  Device-2: Realtek Integrated_Webcam_HD type: USB driver: uvcvideo bus-ID: 1-6:5
    chip-ID: 0bda:5520 class-ID: 0e02 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 compositor: kwin_x11 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x1168 s-dpi: 96 s-size: 1013x308mm (39.88x12.13")
    s-diag: 1059mm (41.68")
  Monitor-1: HDMI-A-1 mapped: HDMI-1 pos: primary,bottom-l model: ONA18HO015 serial: <filter>
    built: 2017 res: 1920x1080 hz: 60 dpi: 70 gamma: 1.2 size: 698x393mm (27.48x15.47")
    diag: 552mm (21.7") ratio: 16:10, 15:9 modes: max: 1920x1080 min: 720x400
  Monitor-2: eDP-1 pos: top-right model: ChiMei InnoLux 0x15d5 built: 2018 res: 1920x1080 hz: 60
    dpi: 142 gamma: 1.2 size: 344x193mm (13.54x7.6") diag: 394mm (15.5") ratio: 16:9 modes: 1920x1080
  API: OpenGL v: 4.6 Mesa 23.1.2-1~mx23ahs renderer: Mesa Intel UHD Graphics 620 (WHL GT2)
    direct-render: Yes
Audio:
  Device-1: Intel Cannon Point-LP High Definition Audio vendor: Dell driver: snd_hda_intel
    v: kernel alternate: snd_soc_skl,snd_sof_pci_intel_cnl bus-ID: 00:1f.3 chip-ID: 8086:9dc8
    class-ID: 0403
  API: ALSA v: k6.1.0-17-amd64 status: kernel-api tools: alsamixer,amixer
  Server-1: PipeWire v: 1.0.0 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin 4: pw-jack type: plugin
    tools: pactl,pw-cat,pw-cli,wpctl
Network:
  Device-1: Realtek RTL810xE PCI Express Fast Ethernet vendor: Dell driver: r8169 v: kernel pcie:
    gen: 1 speed: 2.5 GT/s lanes: 1 port: 3000 bus-ID: 01:00.0 chip-ID: 10ec:8136 class-ID: 0200
  IF: eth0 state: down mac: <filter>
  Device-2: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter vendor: Dell
    driver: ath10k_pci v: kernel modules: wl pcie: gen: 1 speed: 2.5 GT/s lanes: 1 bus-ID: 02:00.0
    chip-ID: 168c:0042 class-ID: 0280
  IF: wlan0 state: up mac: <filter>
Bluetooth:
  Device-1: Qualcomm Atheros type: USB driver: btusb v: 0.8 bus-ID: 1-10:6 chip-ID: 0cf3:e009
    class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 2.1 lmp-v: 4.2
    sub-v: 25a hci-v: 4.2
  Info: acl-mtu: 1024:8 sco-mtu: 50:8 link-policy: rswitch hold sniff
    link-mode: peripheral accept service-classes: rendering, capturing, object transfer, audio,
    telephony
Drives:
  Local Storage: total: 297.07 GiB used: 84.07 GiB (28.3%)
  SMART Message: Unable to run smartctl. Root privileges required.
  ID-1: /dev/nvme0n1 maj-min: 259:0 vendor: Toshiba model: KBG30ZMS256G NVMe 256GB
    size: 238.47 GiB block-size: physical: 512 B logical: 512 B speed: 15.8 Gb/s lanes: 2 type: SSD
    serial: <filter> rev: ADDA0105 temp: 39.9 C scheme: GPT
  ID-2: /dev/sda maj-min: 8:0 type: USB vendor: Generic model: Flash Disk size: 58.59 GiB
    block-size: physical: 512 B logical: 512 B type: SSD serial: <filter> rev: 8.01
  SMART Message: Unknown USB bridge. Flash drive/Unsupported enclosure?
Partition:
  ID-1: / raw-size: 70 GiB size: 68.35 GiB (97.64%) used: 27.34 GiB (40.0%) fs: ext4
    dev: /dev/nvme0n1p2 maj-min: 259:2
  ID-2: /boot/efi raw-size: 256 MiB size: 252 MiB (98.46%) used: 274 KiB (0.1%) fs: vfat
    dev: /dev/nvme0n1p1 maj-min: 259:1
  ID-3: /home raw-size: 164.22 GiB size: 160.59 GiB (97.79%) used: 33.08 GiB (20.6%) fs: ext4
    dev: /dev/nvme0n1p4 maj-min: 259:4
Swap:
  Kernel: swappiness: 15 (default 60) cache-pressure: 100 (default)
  ID-1: swap-1 type: partition size: 4 GiB used: 2.2 MiB (0.1%) priority: -2 dev: /dev/nvme0n1p3
    maj-min: 259:3
Sensors:
  System Temperatures: cpu: 51.0 C pch: 50.0 C mobo: 38.0 C
  Fan Speeds (RPM): cpu: 0
Repos:
  Packages: pm: dpkg pkgs: 2810 libs: 1501 tools: apt,apt-get,aptitude,nala pm: rpm pkgs: 0
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/debian-stable-updates.list
    1: deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
  Active apt repos in: /etc/apt/sources.list.d/debian.list
    1: deb http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
    2: deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
  Active apt repos in: /etc/apt/sources.list.d/mx.list
    1: deb http://mirrors.rit.edu/mxlinux/mx-packages/mx/repo/ bookworm main non-free
    2: deb http://mirrors.rit.edu/mxlinux/mx-packages/mx/repo/ bookworm ahs
Info:
  Processes: 248 Uptime: 9d 15h 4m wakeups: 29642 Memory: 23.33 GiB used: 4.58 GiB (19.6%)
  Init: SysVinit v: 3.06 runlevel: 5 default: graphical tool: systemctl Compilers: gcc: 12.2.0
  alt: 12 Client: shell wrapper v: 5.2.15-release inxi: 3.3.26
Boot Mode: UEFI

### JDK

JDK21 downloaded from the Oracle Java page

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This is the first time that I have seen this issue. However, I have not attempted to add entity classes from a database since at least NB19. I used to use this feature a lot back in the *good old days* of JDK8/NB8.2.

### Are you willing to submit a pull request?

No

**Comment by SeanCarrick** [comment]
I forgot to add the `messages.log` file to this issue. Apologies...
[messages.log](https://github.com/apache/netbeans/files/15213198/messages.log)

**Comment by matthiasblaesing** [comment]
Duplicate of #7163 - please check the RC for the upcoming NB22 release: https://github.com/apache/netbeans/discussions/7281

**Comment by SeanCarrick** [comment]
Thank you @matthiasblaesing Your work is appreciated!
