### ISSUE TITLE
StackOverflowError during scan ant/javafx

### ISSUE THREAD

**Issue by davd211** [apache/netbeans#7375]
### Apache NetBeans version

Apache NetBeans 21

### What happened

estoy intentando que me funcione javafx.

### How to reproduce
```java

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package javafx;

import static javafx.application.Application.launch;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 *
 * @author David.P
 */
public class Javafx {

 public static void main(String[] args)
 {
 // TODO code application logic here
 launch(args);
 }

 
 
 public void start(Stage stage) throws Exception
 {
 Parent root = FXMLLoader.load(getClass().getResource("FXML.fxml"));

 Scene scene = new Scene(root);

 stage.setScene(scene);
 stage.show();
 }

}

```

este es el codigo que me han dado para ejecutarlo y me tendri aque saltar una ventanita, tambien tengo instalado scenebuilder

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 

### JDK

21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

[messages.log](https://github.com/apache/netbeans/files/15293083/messages.log)
este es el mensaje de log 
![image](https://github.com/apache/netbeans/assets/149159001/14674c60-9212-4dde-a337-7001d170254f)
![image](https://github.com/apache/netbeans/assets/149159001/ac2e8b22-c3a6-43c1-a32f-891f13fc547e)

### Are you willing to submit a pull request?

Yes

**Comment by johntor** [comment]
Try File / New Project...

Select: Java with Maven
then: FXML JavaFX Maven Archetype

Chick Next and then Finish.

You should have a running JavaFX Example with FXML files.

Chears!
J!

**Comment by mbien** [comment]
the stack trace looks like it is walking a cyclic java module tree or something similar. Difficult to say without seeing the project - it might be a invalid `module-info.java` cycle or something like that.

it had some ant project stack frames in it, would be worth a try and check if it works with maven like @johntor suggested.
