### ISSUE TITLE
Link to test source doesn't work

### ISSUE THREAD

**Issue by PavelTurk** [apache/netbeans#7385]
### Apache NetBeans version

Apache NetBeans 22 release candidate

### What happened

NB doesn't open link to test file and test method.

### Language / Project Type / NetBeans Component

Java Maven Project using Java Modules (JPMS)

### How to reproduce

This is a test project - https://github.com/PavelTurk/nb-test-link. The project contains one broken test. If you try to build in in NB you will get:

![Screenshot from 2024-05-20 13-03-23](https://github.com/apache/netbeans/assets/10261361/103eac39-6717-471d-b658-7333a5bd4e09)

The problem is that when you click the link to test source (link is selected in the picture) then nothing happens - NB doesn't open that test file in test method.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 20.04.3 LTS

### JDK

Java: 22.0.1; OpenJDK 64-Bit Server VM 22.0.1+8-16

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Product Version: Apache NetBeans IDE 22-rc1

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Confirmed!  Same thing was bugging me last week.

**Comment by mbien** [comment]
seems to be module system related again

the test results window (alt+shift+R) and also the stack trace analyzer should work as workaround. Duplicated code strikes again!

**Comment by mbien** [comment]
https://github.com/apache/netbeans/pull/7391 might fix it
