### ISSUE TITLE
[UI REGRESSION] (Minor) `project > properties > Sources > Source/Binary Format` truncated

### ISSUE THREAD

**Issue by errael** [apache/netbeans#7409]
### Apache NetBeans version

Apache NetBeans 22 release candidate

### What happened

Opened project (`Gradle` project if that matters); brought up Project properties sources. Observed the `Source/Binary Format` truncated.

### Language / Project Type / NetBeans Component

project properties dialog

### How to reproduce

Context menu click on project > properties > Sources Source/Binary Format.
Observe:
![nb22-props-SrcBin](https://github.com/apache/netbeans/assets/20450427/f30b2065-aec3-4ec1-a6b8-a9f879d2a5a8)

Click on the truncate field can scroll to see "21 / 1" and truncated on the other side

`Java Platform` is a new field on this dialog in NB-22. Notice that this new field extends to the right border. 

In NB-21, the `Project > Sources` Source/Binary extends to the right border. This is NB-21
![nb21-props-SrcBin](https://github.com/apache/netbeans/assets/20450427/e4448cf1-6d25-462a-b87c-095d3ebca03b)

(In the unlikely event there's difficultly reproducing, the project is https://github.com/errael/astrology-castro)

### Did this work correctly in an earlier version?

Apache NetBeans 21

### Operating System

Linux harmony 6.8.0-76060800daily20240311-generic #202403110203~1714077665~22.04~4c8e9a0 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux

### JDK

JDK-22

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
https://github.com/apache/netbeans/pull/7861 quick fix which sets the width from fixed to default which should allow the text field to size itself as needed.

I haven't tested it since the linked project didn't build for me, devbuild should show up on the summary page: https://github.com/apache/netbeans/actions/runs/11264567009?pr=7861

**Comment by errael** [comment]
> devbuild should show up on the summary page

Tried it, looks correct. See `21/11` in bounded box rather than extending into the right edge.

**Comment by mbien** [comment]
@errael awesome, thanks for checking!
