### ISSUE TITLE
Syntax preview does not work for faces

### ISSUE THREAD

**Issue by helper14** [apache/netbeans#7449]
### Apache NetBeans version

Apache NetBeans 22

### What happened

The syntax preview for JSF files does not work. E.g. pressing Strg-Space after "<h:" in a faces source file brings up a "no suggestions" pop-up.

### Language / Project Type / NetBeans Component

Java / Java web application / Faces

### How to reproduce

Create a new maven web application. Create a new JSF file. Type <h: in the JSF source file and klick Strg-Space ... (the project is provided as attachment).

[mavenwebproject1.zip](https://github.com/user-attachments/files/15747241/mavenwebproject1.zip)

![netbeans-screenshot](https://github.com/apache/netbeans/assets/83238864/4c8c2fc0-5544-43ed-af9f-8e68116a86a4)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Win10

### JDK

openJDK21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Still no reproducible for me. Please provide full message.log maybe there is something visible there.
See: https://stackoverflow.com/questions/50462124/netbeans-where-to-find-the-ide-log

**Comment by helper14** [comment]
Thank you for the quick response! Here are the logs:
[netbeans-messages-log.zip](https://github.com/user-attachments/files/15764322/netbeans-messages-log.zip)

**Comment by matthiasblaesing** [comment]
@helper14 please see if #7464 improves the situation. A nightly build is available from the "Checks" page or directly via: https://github.com/apache/netbeans/suites/24837488249/artifacts/1595526139

**Comment by helper14** [comment]
I tried the nightly build: Syntax preview for Faces-Tags and preview for CDI-Beans are working with the given example project now. I tested some of my projects and all works properly too - except one issue: If there is a module-info.java file in the project then the CDI-Bean preview does still not work (Faces tag preview is OK). See: Syntax completion in Faces for CDI-Beans does not work #7136

**Comment by matthiasblaesing** [comment]
@helper14 I suspect we see the same reason as #6659. I still fail to see the usage of modular jars in a JakartaEE environment.

**Comment by helper14** [comment]
@matthiasblaesing
> ... I still fail to see the usage of modular jars in a JakartaEE environment.

Splitting up big web projects in modules is as useful as it is in any other environment. Doing this with java modules gives you more control over the dependencies than just dropping jars. So e.g. concurrent dependencies are detected easier ...

**Comment by matthiasblaesing** [comment]
So you chose to use java modules for an environment, that drops the module boundaries on execution? Or is there an Application/WebApplication container out there, that respects module boundaries?

**Comment by helper14** [comment]
Design and architectural aspects are in focus for us in this case - the runtime behavior isn't that much. The compiler and Netbeans support moduls in war's pretty well, so it is a pitty that it spoils the syntax preview in JSF's.
