### ISSUE TITLE
[PHP] Warning for magic methods

### ISSUE THREAD

**Issue by qmegas** [apache/netbeans#7458]
### Apache NetBeans version

Apache NetBeans 22

### What happened

Three standard magic methods `__debugInfo`, `__serialize` & `__unserialize` are not known for Netbeans, so it get warning about PSR-1 violation.

### How to reproduce

Example class:

```php
class Foo
{
	public function __debugInfo(): array
	{
	}
	
	public function __serialize(): array
	{
	}

	public function __unserialize(array $data): void
	{
	}
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

v19

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
No warning about PSR-1 violation.

![nb-php-issue-7458](https://github.com/apache/netbeans/assets/738383/391fe6ea-5cdf-44fd-bb49-0b3b8a96c8e9)

```
Product Version: Apache NetBeans IDE 22
Java: 19.0.2; OpenJDK 64-Bit Server VM 19.0.2+7-Ubuntu-0ubuntu322.04
Runtime: OpenJDK Runtime Environment 19.0.2+7-Ubuntu-0ubuntu322.04
System: Linux version 6.5.0-35-generic running on amd64; UTF-8;
```

**Comment by qmegas** [comment]
@junichi11 That's how it looks on my side.

![Capture](https://github.com/apache/netbeans/assets/2444896/db403724-9364-49c0-8baf-e025767edf2c)

Any ideas why it looks different? Just to emphasize that all other magic methods besides these 3 don't have a warning.

**Comment by junichi11** [comment]
Ah, OK, it's not available by default. 
I can reproducible now. Thanks for reporting it.
