### ISSUE TITLE
I tried to open Netbeans 22 but it showed a strange message

### ISSUE THREAD

**Issue by muratia** [apache/netbeans#7485]
### Apache NetBeans version

Apache NetBeans 22

### What happened

![Java Version 20](https://github.com/apache/netbeans/assets/10488821/51ec19c8-601c-4c3c-bb73-1a12066b5f99)

I tried to open Netbeans 22 and it showed a strange message that it cannot run in older java versions than 17 but as you see in the attached screenshot I have Java 20 on my Windows 11 Pro machine and I think thisis a bug because olderversion netbeans 12 opened fine

### Language / Project Type / NetBeans Component

PHP

### How to reproduce

In Windows 11 Pro installed version of JRE version 20 and JDK 20 ![Java Version 20](https://github.com/apache/netbeans/assets/10488821/51ec19c8-601c-4c3c-bb73-1a12066b5f99)

and try to open the Netbeans version 22.

### Did this work correctly in an earlier version?

Apache NetBeans 16 or earlier

### Operating System

Windows 11 Pro 64 bit

### JDK

JDK 20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This is first time it happened 

### Are you willing to submit a pull request?

Yes

**Comment by junichi11** [comment]
@muratia Please try to the following on your command line(`cmd`) although I'm not a Windows user:
```
> java -version
```

```
> where java
```

```
> echo %JAVA_HOME%
```

Check `Help > About` in NetBeans 12: You can confirm your java version

**Comment by mbien** [comment]
The download page links to community installers which package an up to date runtime JDK and latest NB in one installer. The bundle installers are probably one of the easier ways to use NetBeans on windows. The JDK runtime is installed just for NetBeans and the paths are properly set up.

**Comment by muratia** [comment]
To overcome this problem I unistalled all older java sdk from 1.8 till 
![image](https://github.com/user-attachments/assets/9a2f2cf4-4cf0-4f1b-9b79-8b7bf978396b)
 the 21 and then installed JDK 23 and then I tried to run netbeans but nothing happened then I uninstalled the apache netbeans 23 and reinstalled again. Then Netbeans is open now no more problems with Java 17 
 
 Here you see opened Apache Netbeans 23 64 bit on Windows 11 Pro 64 bit too 
![image](https://github.com/user-attachments/assets/26bf246c-eb6b-4ef4-96ac-8687408b1d57)
