### ISSUE TITLE
An internal error occurred during: "Fetch from remote-cli - origin". Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory

### ISSUE THREAD

**Issue by VietHungPhan** [apache/netbeans#7492]
### Apache NetBeans version

Apache NetBeans 22

### What happened

In my all Eclipse versions including 4.30.0/4.31.0/4.32.0, when I do a Fetch data from git repository, ssh woks fine, but https is never working.

### How to reproduce

In Eclipse, WIndows-->Perspective-->Open perspective-->Git, then import a git repository.
On git repositories, select origin, then change ssh to https as https://username@git-server:port/git-repository
Select ssh to https as https://username@git-server:port/git-repository, then Right click on it to fetch data from git server.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

RHEL8

### JDK

21.0.2

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
This is the NetBeans issue tracker, not the Eclipse one.
