### ISSUE TITLE
Adoptium Java Not Recognized During Installation

### ISSUE THREAD

**Issue by Lushove** [apache/netbeans#7517]
### Apache NetBeans version

Apache NetBeans 22

### What happened

NetBeans installer does not recognize an existing Adoptium Java installation and prompts to download Java from Oracle.

### How to reproduce

I have installed the Adoptium Java Development Kit (JDK) on my system.
When attempting to install NetBeans, the installer does not recognize the existing Adoptium Java installation.
The installer prompts me to download and install Java from Oracle.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 64 bits

### JDK

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
I tested with temurin last release and it worked fine. Are you sure you checked "set JAVA_HOME" (can't remember the exact wording) while installing the JDK?
