### ISSUE TITLE
not finding plugin hibernate

### ISSUE THREAD

**Issue by Vlnmalayali** [apache/netbeans#7530]
### Apache NetBeans version

Apache NetBeans 22

### What happened

in netbeans 22 i can't find the plugin hibernate in the plugin

### Language / Project Type / NetBeans Component

JAVA  Maven project

### How to reproduce

please add hibernate to netbeans

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 11

### JDK

21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
the hibernate plugin is not part of this repo and is also no longer maintained by the original author https://github.com/apache/netbeans/pull/6991#issuecomment-1936990808

We kept the old NetBeans 8 plugin portal for quite a while but had to remove it at some point https://github.com/apache/netbeans/pull/6991
