### ISSUE TITLE
faulty upgrade netbeans 22

### ISSUE THREAD

**Issue by grantleyT** [apache/netbeans#7544]
### Apache NetBeans version

Apache NetBeans 22

### What happened

Downloaded netbeans from snap - for new Ubuntu 24.04 install.
netbeans would not load even though it had prior to some other application downloads.
Able to get it to load from command line with the following errors. Application seems to run ok although the fonts look faint (like never before) and browser won't run when deploying a web app. tried all browsers on system, would only run the browser in the webkit.
here is the cli error.
```
sudo  netbeans --jdkhome /usr/lib/jvm/java-21-openjdk-amd64
WARNING: package com.apple.eio not in java.desktop
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package com.apple.laf not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/snap/netbeans/102/netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release

(java:50949): libsecret-WARNING **: 16:54:53.577: couldn't get session bus: Failed to execute child process “dbus-launch” (No such file or directory)
```

regards Grant

### How to reproduce

Downloaded from snap (where it has always been fine)
Tried removing and reinstalling, same problem. by running netbeans with hard reference to openjdk it runs but I can't see why it isn't accessing the same jdk from normal startup. It appears to be locating it in java settings.
tried removing and re-installing from command line with the same result.

### Did this work correctly in an earlier version?

Apache NetBeans 21

### Operating System

ubuntu 24.04

### JDK

openjdk-21-amd64

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

Yes

**Comment by grantleyT** [comment]
resolved, needed complete clean install of ubuntu 24.04 then all ok.

**Comment by grantleyT** [comment]
resolved with complete clean install of ubuntu 24.04

**Comment by mbien** [comment]
don't run desktop apps with `sudo` this will break config and cache folders in many cases and could cause other problems. I suspect this is what happened here.

**Comment by samuel-maina** [comment]
solved?
