### ISSUE TITLE
Show Build Overview button is disabled with mvnd

### ISSUE THREAD

**Issue by Saljack** [apache/netbeans#7547]
### Apache NetBeans version

Apache NetBeans 22

### What happened

When I use mvnd for building projects then the Show Build Overview button is disabled and I cannot debug maven goals. It works find with normal mvn.
![image](https://github.com/apache/netbeans/assets/614424/5747c081-6741-4475-a37d-9ebab32df447)

### Language / Project Type / NetBeans Component

Java Maven

### How to reproduce

1. Setup mvnd for building
2. build application
3. Show Build Overview - is disabled

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

Temurin 21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
NB disables a few features if mvnd is run in parallel mode (e.g you see it on the folding bar in the output too), this is intended. 

You should see that button again if you run mvnd in sequential mode, e.g by setting `-T 1`.

**Comment by Saljack** [comment]
You are right with `-T 1` it works. It would be mentioned somewhere.
