### ISSUE TITLE
NebBeans unusable in fullscreen on current macOS (arm64) SOLVED

### ISSUE THREAD

**Issue by AJK-Muc** [apache/netbeans#7602]
### Apache NetBeans version

Apache NetBeans 22

### What happened

Preamble: in order to use **all space** on the display, the macOS menubar and dock is set to automatically disappear
# As soon as fullscreen is activated, NetBeans becomes unusable
1. Not the full screen is being used, only the top macOS window bar (with the 3 dots red, yellow, green) gets subtracted and the resulting window is repositioned to the top without expanding to the bottom (creates unused empty space on the bottom)
2. This resulting gap is the offset for the cursor: you can no longer position anything (always anything else is getting clicked)

### Language / Project Type / NetBeans Component

General GUI issue

### How to reproduce

1. Enter fullscreen mode (window top left green dot)
2. Try to position your cursor on any position

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS Sonoma 14.5 (23F79) on ARM64 (M1)

### JDK

openjdk 21.0.1 2023-10-17 LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

happens always

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
> openjdk 21.0.1 2023-10-17 LTS

if you experience UI issues, please always check the latest update release of the JDK (would be 21.0.4 or 22.0.2 by now).

does `shift+alt+enter` produce different/better results than the green button? Does using a different look and feel also trigger the mouse click offset issue?

**Comment by AJK-Muc** [comment]
Hallelujah – it works now - everything as expected! Thank you dear programmers 🎉
> `shift+alt+enter` does something else (it's probably a Windows thing, since there is no [alt] on a Mac). The standard fullscreen shortcut on current Mac's is `[fn] + F` but in NetBeans this enters just a letter "f" (if in the editor) or opens the search input field (when in the projects list). But anyway, thanks @mbien for checking JDK issues.
## Product Version
Apache NetBeans IDE 24
## System
Mac OS X version 15.1.1 running on aarch64; UTF-8; de_DE (nb)
## JDK
OpenJDK Runtime Environment Corretto-23.0.1.8.1
