### ISSUE TITLE
Smart Search

### ISSUE THREAD

**Issue by NexusSynergos** [apache/netbeans#7625]
### Description

It is hard for me to find what I am looking for on your site, even attempting to use the search bar.  I have heard that your company is heavily involved in AI.  Could you please think about putting an AI 

### Use case/motivation

I see a person typing in their search and when they hit enter the AI analyzes the search request, and any past searches with this particular customer if they have a log in. But with the frequency and amounts of people performing searches and the information on the styles of questions being asked, your search bar would get a close as could be or spot-on search result. Happy simple first time search.

### Related issues

When I searched for this topic there were nothing in the list to suggest that there was. Also I do not know what a pull request is.

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Issue does not make sense in context of NetBeans IDE / NetBeans VSCode does not make sense.
