### ISSUE TITLE
restore netbeans 8.2 plugin portal repository option.

### ISSUE THREAD

**Issue by patsummit** [apache/netbeans#7627]
### Description

The repository for the old 8.2 plugin portal has been removed and the c/c++ plugin from that portal is very useful as opposed the the lightwight c/c++ project which is next to useless. 

While it is possible to add the portal knowing where it is difficult to find. 

### Use case/motivation

The c/c++ plugin in that portal is very useful.

Another option would be to upgrade the lightwight c/c++ plugin to handle the various project types that the 8.2 plugin handles. 

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
This was removed in #6991 for the reasons given there. It is not coming back. Contributions welcome to helping get the cnd code here into a releasable state.

**Comment by patsummit** [comment]
Is there a worthwhile alternative to the c/c++ plugin?  The current lightweight c/c++ plugin is not useful.

**Comment by SirFalc0n** [comment]
We need the C++ plugin that the portal provides.

**Comment by neilcsmith-net** [comment]
@SirFalc0n so add it yourself - `Tools / Plugins / Settings / Add` - add http://updates.netbeans.org/netbeans/updates/8.2/uc/final/distribution/catalog.xml.gz and give it a name.
