### ISSUE TITLE
Cannot auto indent in TypeScript files (*.ts)

### ISSUE THREAD

**Issue by hebrerillo** [apache/netbeans#7645]
### Apache NetBeans version

Apache NetBeans 22

### What happened

When I open TypeScript files (*.ts), the auto indentation does not work. The cursor starts at the beginning of the line.

### Language / Project Type / NetBeans Component

HTML5/JS Application

### How to reproduce

Just open any file with the 'ts' extension, for example "app.ts

https://github.com/user-attachments/assets/d9eeefd5-ef25-445b-a56e-88335f440c9b

![Screenshot 2024-08-08 at 08 39 44](https://github.com/user-attachments/assets/19f8eeec-78e3-41c4-a5fe-1894c51c950d)
"

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

MACOs Monterey, version 12.6.3

### JDK

19.0.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
I use the typescript integration daily, so it is not a general problem. This looks as if the typescript language server is not active. Do you have `node` on your path? Please provide the `message.log` and a sample project, that reproduces your problem.

**Comment by hebrerillo** [comment]
Hello @matthiasblaesing ! 

Yes, I have node on my path. The command "node -v" yields version v19.6.0.

I attach a sample project. But I can't find any message.log file in the project.

[typescript.zip](https://github.com/user-attachments/files/16557485/typescript.zip)

Thank you so much!

**Comment by matthiasblaesing** [comment]
@hebrerillo thanks for the test project. That works for me, so we need to dig further. Could you please provide the `message.log` file (or the full output from the `View` -> `IDE Log` command)? I suspect, that the language server could not be started.

**Comment by hebrerillo** [comment]
@matthiasblaesing it is my pleasure! I love the NetBeans IDE.

I attach the IDE Log.
[ide_log_MACOS.txt](https://github.com/user-attachments/files/16569059/ide_log_MACOS.txt)


I have a Linux computer where the bug is also happening. I provide some info:

- Java version: openjdk 21.0.4 2024-07-16
- OS version: Ubuntu 22.04.4 LTS
- Linux kernel version: 6.5.0-44-generic

I also attach the IDE log and a sample project from the Linux computer
[ide_log_LINUX.txt](https://github.com/user-attachments/files/16569068/ide_log_LINUX.txt)
[typescript_LINUX.zip](https://github.com/user-attachments/files/16569069/typescript_LINUX.zip)

**Comment by hebrerillo** [comment]
Hello @matthiasblaesing , I have some news

To open the projects I attached before, I used the [PKG installation](https://www.apache.org/dyn/closer.lua/netbeans/netbeans-installers/22/Apache-NetBeans-22.pkg) on Mac and the [deb installation](https://www.apache.org/dyn/closer.lua/netbeans/netbeans-installers/22/apache-netbeans_22-1_all.deb) on Linux.

If the project is opened using [a binary](https://www.apache.org/dyn/closer.lua/netbeans/netbeans/22/netbeans-22-bin.zip), the auto indentation in TypeScript files works!

**Comment by matthiasblaesing** [comment]
Thanks. Regrettably the message logs are inconclusive. I tested the Ubuntu 22.04 live iso, installed Amazon Corretto as JDK via the deb installer, nodejs via https://deb.nodesource.com/setup_18.x and netbeans using the deb installer, works with your sample.

Please run NetBeans with the parameter `-J-Dorg.netbeans.modules.lsp.client.LSPBindings.level=FINEST`. That raises the log level for the LSP integration and might reveal some more information. At least it should print anything regarding LSP, as that is currently missing.

**Comment by hebrerillo** [comment]
Hello @matthiasblaesing , 

Something very very wrong just happened... The auto indentation in TypeScript now works in the installable Netbeans, both Ubuntu and MacOS.

Even if I uninstall the installable packages and install them again, the auto-indentation in TypeScript files still works.

It seems the execution of the binary Netbeans changed some global configuration on the computers that make auto-indentation work in TypeScript.

I cannot reproduce the bug anymore.

**Comment by matthiasblaesing** [comment]
@hebrerillo this is a cup-half-empty-full situation. As indicated I could not reproduce the issue with a clean Ubuntu image (with the deb installer), so your final finding matches the baseline. I understand, that it is frustrating not to know _why_ it suddenly works, but without reproducability, we should be happy, that it now works.

Feel free to reopen if the issue comes up again.
