### ISSUE TITLE
Duplicate text in hint tooltip

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#7647]
### Apache NetBeans version

Apache NetBeans 23 release candidate

### What happened

Duplicate text in hint tooltip:

PHP examples:
![hint_tooltip_bug_php_1](https://github.com/user-attachments/assets/eda8351b-95a5-4d75-9b81-1210f26a0a2a)
![hint_tooltip_bug_php_2](https://github.com/user-attachments/assets/63b07ed7-4aa4-4334-bfda-402646a0f4eb)
![hint_tooltip_bug_php_3](https://github.com/user-attachments/assets/209673c9-ffeb-47ab-aecf-b14c9064b760)

JS example:
![hint_tooltip_bug_js](https://github.com/user-attachments/assets/dec1349e-1a8d-49e0-90f9-b265363aa4cd)

### Language / Project Type / NetBeans Component

PHP, JavaScript

### How to reproduce

- Create a new php file
- Add code to the file

```php
<?php

function func($param) {
    $var = 2;
    $var = 3;
}

?>
```

### Did this work correctly in an earlier version?

Apache NetBeans 22

### Operating System

Ubuntu 22.04.4 LTS

### JDK

17.0.11; OpenJDK 64-Bit Server VM 17.0.11+9-Ubuntu-122.04.1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by troizet** [comment]
This bug seems to have appeared in PR #7579.

**Comment by matthiasblaesing** [comment]
@troizet your analysis is spot on. The problem as I see it is, that #7579 removed the default registration of `JavaErrorProvider` in NetBeans IDE and registers it only in NetBeans VSCode. But that fix is incomplete, as the NB Codebase holds other `ErrorProvider` implementations, that need to be removed also. A quick grep hints:

- `enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolErrorProvider.java:`
- `enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/VulnerabilityWorker.java`
- `extide/gradle.editor/src/org/netbeans/modules/gradle/editor/hints/LspErrorProvider.java`
- `ide/spi.editor.hints/src/org/netbeans/modules/editor/hints/lsp/HintsDiagnosticsProvider.java`
- `ide/csl.api/src/org/netbeans/modules/csl/hints/GsfErrorProvider.java`
- `java/maven.hints/src/org/netbeans/modules/maven/hints/pom/LspMavenErrorProvider.java`
- `java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/idebinding/HintsErrorProvider.java`
- `java/java.hints/src/org/netbeans/modules/java/hints/infrastructure/JavaErrorProvider.java`

Some of these are covered, but they need to be checked.

@jtulach can you provide a fix?

**Comment by jtulach** [comment]
Thank you for the report. I'll take a look over the weekend and see how to eliminate the duplicated hints for PHP & co.

**Comment by jtulach** [comment]
CCing @jlahoda, @ppisl, @dbalek..

> @troizet your analysis is spot on. The problem as I see it is, that #7579 removed the default registration of `JavaErrorProvider` in NetBeans IDE and registers it only in NetBeans VSCode. But that fix is incomplete, as the NB Codebase holds other `ErrorProvider` implementations, that need to be removed also.
> ...
> Some of these are covered, but they need to be checked.
> 
> For PHP the errors flow through the `GsfErrorProvider`.

Yes, the flow goes thru `GsfErrorProvider`. The `PHPLanguage` uses `@LanguageRegistration(mimeType=PHP_MIME_TYPE...)` registration which registers `ErrorProvider` as well as a Gsf own implementation that fills the `HintsCollector.setErrors`.

I somehow need to find out in the `ErrorProviderBridge` that the delegation shouldn't happen. If we want to do it in really compatible way, then:
- we need to differentiate between the providers written prior to #7579
- and providers that want to benefit from #7579 support

> @jtulach can you provide a fix?

#7659 is my attempt to make the #7579 support change as compatible as possible.

**Comment by mbien** [comment]
the PR in question got reverted and the change is merged to delivery. 

Would be good if someone could verify that everything is ok again once NB 23 rc3 is built and close this issue. Github often forgets about issues if PRs aren't merged to master in the most direct way and leaves them open.

**Comment by troizet** [comment]
> Would be good if someone could verify that everything is ok again once NB 23 rc3 is built and close this issue.

Tried NB 23 rc3. No duplicate text in the hint.
