### ISSUE TITLE
annotationProcessorPaths in Maven ignored, if child element name is not path

### ISSUE THREAD

**Issue by matthiasblaesing** [apache/netbeans#7658]
### Apache NetBeans version

Apache NetBeans 22

### What happened

When a maven project has a `pom.xml` with a `annotationProcessorPaths` configuration, where the element names are not `path` like this:

```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <parameters>true</parameters>
                    <annotationProcessorPaths>
                        <annotationProcessorPath>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.5.5.Final</version>
                        </annotationProcessorPath>
                        <annotationProcessorPath>
                            <groupId>io.soabase.record-builder</groupId>
                            <artifactId>record-builder-processor</artifactId>
                            <version>42</version>
                        </annotationProcessorPath>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

the annotation processors are not found/ran, as NetBeans currently expects the children of `annotationProcessorPaths` are named `path`:

```xml
           <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <parameters>true</parameters>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.5.5.Final</version>
                        </path>
                        <path>
                            <groupId>io.soabase.record-builder</groupId>
                            <artifactId>record-builder-processor</artifactId>
                            <version>42</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
```

Full project: [annotation-processor-netbeans-reproducer.zip](https://github.com/user-attachments/files/16570859/annotation-processor-netbeans-reproducer.zip)

### Language / Project Type / NetBeans Component

Java Maven project

### How to reproduce

Open attached test project in NetBeans

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 24.04

### JDK

Amazon Corretto 21

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
regarding
```
    <annotationProcessorPaths>
        <annotationProcessorPath>
```
when I look at the [usage doc](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPaths) it only mentions `<path>` as list element.

The type of `annotationProcessorPaths` is [`List<DependencyCoordinate>`](https://maven.apache.org/plugins/maven-compiler-plugin/apidocs/org/apache/maven/plugin/compiler/DependencyCoordinate.html). So i am wondering if the element name matters at all (maybe there is a convention I am not aware of). I will take a look at this later, I am not near an IDE atm.

**Comment by mbien** [comment]
https://github.com/apache/maven-compiler-plugin/blob/419f1b614f41e855a7b384d88b5324e22defb200/src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java#L347

so I believe the way it works is that `List`s can have arbitrary element names, this will likely work too:
```xml
    <annotationProcessorPaths>
        <hugo>
            ...
        </hugo>
        <otto>
           ...
        </otto>
    </annotationProcessorPaths>
```
so if NB is only checking `annotationProcessorPaths/path` it should be updated to check `annotationProcessorPaths/*`

going to take a look if this can be fixed.

**Comment by matthiasblaesing** [comment]
No need. A patch branch is already locally done on my side.

Your assessment is correct and was documented already here: https://github.com/apache/netbeans/issues/7611#issuecomment-2282267641

**Comment by mbien** [comment]
oops, I just opened a PR

**Comment by mbien** [comment]
fix got integrated into NB 23 but gh didn't close the issue
