### ISSUE TITLE
Characters corrupt when scrolling available methods after typing this.

### ISSUE THREAD

**Issue by alexgmuir** [apache/netbeans#7718]
### Apache NetBeans version

Apache NetBeans 22

### What happened

type this. and scroll down

![image](https://github.com/user-attachments/assets/fb512b84-bf7a-461d-b43e-ea64d4734f58)

### Language / Project Type / NetBeans Component

Content Display

### How to reproduce

type this. and scroll down

![image](https://github.com/user-attachments/assets/fb512b84-bf7a-461d-b43e-ea64d4734f58)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 22

### JDK

penjdk 17.0.12 2024-07-16 OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu222.04) OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Anything else

It began occurring recently. Also happening on Netbeans 18. I haven't changed my settings though so I don't know if this is related to ubuntu update however no other application I use has this issue

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
this looks like it is going beyond just the completion popup. The tabs are also not rendered properly. Looks like bitmap/texture related to me. Might be even graphics memory or driver / wayland related.

**Comment by alexgmuir** [comment]
Okay I'm running Ubuntu 22 in vmware workstation. I don't have the issue
with my Ubuntu 18 vm though. Any suggestions as to what i might do to
resolve. The ubuntu 22 is fully updated.

**Comment by alexgmuir** [comment]
I switched to using xorg and the issue is resolved

**Comment by mbien** [comment]
ok good to know. Going to close this issue since this likely was a graphics driver or some other rendering issue (virtualization +  wayland + swing is probably not completely reliable yet).
