### ISSUE TITLE
[ PHPUnit ] Skipped tests marked as passed in the Test Results window

### ISSUE THREAD

**Issue by SolracLeinad** [apache/netbeans#7739]
### Apache NetBeans version

Apache NetBeans 22

### What happened

Whether a test is skipped because of annotations or because a dependency failed it will be marked as passed (it should be marked as skipped). There is no mention of the number of skipped tests anywhere and the "show skipped" button does nothing.

The output window does show the results of the tests correctly and the nb-phpunit-log.xml file does contain information about the skipped tests.

### Language / Project Type / NetBeans Component

PHPUnit

### How to reproduce

Just run this simple test:

```
use PHPUnit\Framework\TestCase;

/**
 * Description of testTest
 *
 */
class testTest extends TestCase {

    /**
     * @test
     */
    function testA() {
        self::assertEquals(1, 1);
        return true;
    }


    /**
     * @test
     * @depends testA
     */
    function testA2($varFromTestA) {
        self::assertEquals($varFromTestA, 1);
    }

    /**
     * @test
     */
    function testAB() {
        self::assertEquals(1, 1);
        throw new Exception('This test fails');
    }

    /**
     * @test
     * @depends testAB
     */
    function testAB2($varFromTestA) {
        self::assertEquals($varFromTestA, 1);
    }

    /**
     * @test
     * @depends testAB
     */
    function testAB3($varFromTestA) {
        self::assertEquals($varFromTestA, 1);
    }

    /**
     * @test
     * @skip
     */
    function testSkipped() {
        self::markTestSkipped('Manually skipped');
        self::assertEquals(1, 1);
    }
}
```

As you can see, you will find every skipped test passed:
![imagen](https://github.com/user-attachments/assets/bf65f657-cdbd-42a9-8313-634363a4b6b9)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian 12

### JDK

OpenJDK Runtime Environment 17.0.12+7-Debian-2deb12u1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This is the output of the "Output window" which shows both tests skipped due errors and the one manually skipped:

```
PHPUnit 9.6.20 by Sebastian Bergmann and contributors.

..ESSS                                                              6 / 6 (100%)

Time: 00:00.002, Memory: 12.88 MB

There was 1 error:

1) testTest::testAB
Exception: This test fails

/home/****/NetBeansProjects/****/.tests/testTest.php:33

ERRORS!
Tests: 6, Assertions: 3, Errors: 1, Skipped: 3.
Done.
```

### Are you willing to submit a pull request?

No

**Comment by troizet** [comment]
Fixed in #7836.
