### ISSUE TITLE
UTF-8 output on Netbeans console with Java > 18

### ISSUE THREAD

**Issue by kovwolff** [apache/netbeans#7751]
### Apache NetBeans version

Apache NetBeans 22

### What happened

German Umlaute does not correctly displayed on Netbeans Console. Seems to be the same es Eclipse bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=579383

### Language / Project Type / NetBeans Component

Java

### How to reproduce

public class BugSample {
  public static void main( String[] args ) {
    System.out.println( "<äöüÄÖÜß>");
  }
}

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

JDK 21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Duplicate of #4771  In general, not a bug.  See that issue for how to configure the project, JDK, or OS to handle this.

**Comment by kovwolff** [comment]
I still think it's a missconfig in Netbeans. If i run the project on the command line, the output ist right. If i run the project inside Netbeans, the output (console) is wrong.

**Comment by neilcsmith-net** [comment]
Please share the output from the "Anything else" section of #4771 on your setup, both in the console and the IDE.

```java
        System.out.println("Charset.defaultCharset(): " + Charset.defaultCharset());
        System.out.println("file.encoding property:" + System.getProperty("file.encoding"));
        System.out.println("native.encoding property:" + System.getProperty("native.encoding"));
        System.out.println("sun.jnu.encoding property:" + System.getProperty("sun.jnu.encoding"));
        System.out.println("stdout.encoding property:" + System.getProperty("stdout.encoding"));
        System.out.println("sun.stdout.encoding property:" + System.getProperty("sun.stdout.encoding"));
```

**Comment by ly269nva** [comment]
Charset.defaultCharset():UTF-8
file.encoding property:UTF-8
native.encoding property:null
sun.jnu.encoding property:UTF-8
stdout.encoding property:UTF-8
sun.stdout.encoding property:UTF-8
I also have this problems on netbeans20,   i write System.out.println("png压缩完成");   it can output chinese in 'Test Results' tab, but Output garbled text in ‘Output’ tab.    And no matter how I configure it in netbeans.exe, it doesn't work，example:   netbeans_default_options="*** -J-Dfile.encoding=UTF-8 -J-Dsun.jnu.encoding=UTF-8 -J-Dnetbeans.output.encoding=UTF-8 -J-Dconsole.encoding=UTF-8 -J-Dsun.stdout.encoding=UTF-8 -J-Dstdout.encoding=UTF-8 -J-Dstderr.encoding=UTF-8 -J-Dmaven.opts=-Dfile.encoding=UTF-8 -J-Ddefault.charset=UTF-8 -J-Dclient.encoding.override=UTF-8"
