### ISSUE TITLE
Not Installing Java JDK 23 On NetBeans 

### ISSUE THREAD

**Issue by MHMITHUN** [apache/netbeans#7763]
### Apache NetBeans version

Apache NetBeans 23 release candidate

### What happened

Not Installing Java JDK 23 On NetBeans. It Is Showing an Error message. But Working with JDK 17
![Screenshot 2024-09-18 080135](https://github.com/user-attachments/assets/cac6c969-6608-4246-a49e-e75612ff20bc)

### Language / Project Type / NetBeans Component

NetBeans Windows Installer

### How to reproduce

I Downloaded leatest version of java and NetBeans I think need to update NetBeans and make sure it suitable with leatest version

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Windows 11

### JDK

JAVA JDK 23

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
if you see this message, it means that the launcher is started on a java version which is older than JDK 17.

You can set the path to the JDK via `--jdkhome <path>` or the config file `etc/netbeans.conf` or you uninstall all java versions which are older than JDK 17.

NetBeans 23 should be available in a few days from now.
