### ISSUE TITLE
PHP Auto-Complete of "->" 

### ISSUE THREAD

**Issue by resih5** [apache/netbeans#7794]
### Apache NetBeans version

Apache NetBeans 23

### What happened

I just upgraded to v23 (from v22) and copied all the settings from v22. and the autocomplete of the arrow for class methods and properties is no longer working. In previous versions, when typing a hyphen after a class variable, the IDE would auto-complete the arrow "->" and open the intelli-sense pop-up with list of class methods and properties.
`$classVar = new SomeClass()`
Typing `$classVar-` would auto add '>' and  open intelli-sense options. Now I have to type in the ">".

### Language / Project Type / NetBeans Component

PHP Project

### How to reproduce

In a PHP Project open/create new php file (ex. index.php)
1) Create new instance variable of a class (`$varName = new SomeClass()`)
2) with class variable, attempt to access one of the class properties or methods by typing `$varName-`

in previous versions (back to at least v12), after typing variable and then hyphen, the ">" would autocomplete and intellis-sense would appear.

### Did this work correctly in an earlier version?

Apache NetBeans 22

### Operating System

Windows 11

### JDK

23

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I downloaded and installed the community installer with JDK 23 from code https://www.codelerity.com/netbeans/

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
That feature is not supported in NB.
I supported it with the plugin (https://github.com/junichi11/netbeans-php-enhancements).
Did you install it?
If you installed it, please report it there. Thanks.
