### ISSUE TITLE
Cannot open projects based on Apache Ant

### ISSUE THREAD

**Issue by HiranChaudhuri** [apache/netbeans#7808]
### Apache NetBeans version

Apache NetBeans 23

### What happened

I want to develop for Apache Nutch. For this I clone the git repository, then want to open the project in Netbeans 23.
The project is not recognized. Apparently I first have to create a pom.xml so it can be recognized as Maven build - which it is not. Instead it contains build.xml.

As Ant is also not available via plugins it looks like Ant support has completely dropped out. This contradicts Tools/Options, where on the Java tab you find a configuration screen for Ant. Thus I suspect not being able to open Ant projects is either a bug or feature creep.

### Language / Project Type / NetBeans Component

Java Ant

### How to reproduce

Clone the Apache Nutch repository from https://github.com/apache/nutch.git
Then try to open your clone as project in Netbeans 23.

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Ubuntu 22 LTS

### JDK

Netbeans is running on OpenJDK 64-Bit Server VM 21.0.4+7-Ubuntu-1ubuntu222.04

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

This problem occurs every time I try to open the nutch project.

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
the repo you linked does not contain a netbeans ant project (or any other IDE project) so you can't open it right away. To interface with arbitrary ant projects you can use the free-form project wizard under: `new project -> java with ant -> java free-form project` and then map the actions to the build (default usually works).

maven projects are different since they have a standard structure, those can be simply opened without extra configuration

**Comment by matthiasblaesing** [comment]
There was a contrib plugin that tried autodetection for ant, but it was never mainlined. So @mbien is right, this is not a bug.

**Comment by matthiasblaesing** [comment]
@HiranChaudhuri ant does not give you information about the structure of the project. @mbien gave you instructions how to setup the project in NetBeans. You can choose $random IDE and they might make educated guesses about the project structure, but they remain guesses.
