### ISSUE TITLE
Lsp not displaying Navigator symbols anymore

### ISSUE THREAD

**Issue by albilu** [apache/netbeans#7809]
### Apache NetBeans version

Apache NetBeans 23

### What happened

Language server protocol symbols are not displayed anymore in Netbeans 23

See Netbeans 22 vs Netbeans 23 for a typescript file using Netbeans LSP Client

![2024-09-28_15-34](https://github.com/user-attachments/assets/c01a1e0c-557f-4b1c-af28-5e003a05c7a4)
![2024-09-28_15-37](https://github.com/user-attachments/assets/44d8d7e8-9b38-4791-8312-cd4581ad85aa)

**Netbeans 23 logs**
[netbeans.log](https://github.com/user-attachments/files/17174580/netbeans.log)

### Language / Project Type / NetBeans Component

LSP Client

### How to reproduce

Open a simple typescript file

### Did this work correctly in an earlier version?

Apache NetBeans 22

### Operating System

Ubuntu

### JDK

21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Please check #7757

**Comment by albilu** [comment]
> Please check #7757

@matthiasblaesing is there any chance to get this in a patch and not having to wait 4 months for the next release?!

**Comment by matthiasblaesing** [comment]
@albilu you can always build from the patch branch or from master once the patch is merged.

**Comment by matthiasblaesing** [comment]
@albilu if you can't build from source, I can rerun the CI pipeline for the PR and you could test that build and potentially use it until NB24.

**Comment by albilu** [comment]
Works for me.Thanks
