### ISSUE TITLE
Cursor defaults to Overwrite Mode

### ISSUE THREAD

**Issue by jatinbht** [apache/netbeans#7825]
### Apache NetBeans version

Apache NetBeans 23

### What happened

Cursor defaults to Overwrite Mode and "--insert--" appears at the bottom right when I enter the insert mode (by pressing the insert key on the keyboard).

### How to reproduce

Just install the jvi plugin.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows x64

### JDK

21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by ausernameausernameausername** [comment]
Delete the jVi plugin.

**Comment by jatinbht** [comment]
thanks!
