### ISSUE TITLE
context.xml formatted when project properties -> run selected

### ISSUE THREAD

**Issue by r1gm** [apache/netbeans#7863]
### Apache NetBeans version

Apache NetBeans 23

### What happened

my context.xml file formatted from multiline(new line every attribute)  to single line

### Language / Project Type / NetBeans Component

Java Maven Project

### How to reproduce

project properties -> run 

then press ok

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

Oracle JDK 21 

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Please provide a reproducer

**Comment by r1gm** [comment]
[thisisexample.zip](https://github.com/user-attachments/files/17433434/thisisexample.zip)

**Comment by matthiasblaesing** [comment]
Not reproducible with a more or less recent build from master. Please provide exact steps.

**Comment by r1gm** [comment]
Step : 
1. Open Project
2. Open context.xml
3. Right Click on Project
4. Select Properties on menu
5. Select Run
6. Then Press OK

you will see, context.xml formated from :

```
<?xml version="1.0" encoding="UTF-8"?>
<Context path="/thisisexample">
    <Resource auth="Container" 
              defaultAutoCommit="true" 
              driverClassName="org.supersql.jdbc.SuperDriver" 
              maxIdle="10" 
              maxTotal="20" 
              maxWaitMillis="10000" 
              name="jdbc/testDB" 
              password="password" 
              type="javax.sql.DataSource" 
              url="jdbc:supersql://localhost/test" 
              username="username" 
              validationQuery="SELECT * FROM foo"/>
</Context>
```

to : 
```
<?xml version="1.0" encoding="UTF-8"?>
<Context path="/thisisexample">
  <Resource auth="Container" defaultAutoCommit="true" driverClassName="org.supersql.jdbc.SuperDriver" maxIdle="10" maxTotal="20" maxWaitMillis="10000" name="jdbc/testDB" password="password" type="javax.sql.DataSource" url="jdbc:supersql://localhost/test" username="username" validationQuery="SELECT * FROM foo"/>
</Context>
``

**Comment by matthiasblaesing** [comment]
Thank you for the update, but this still does not happen for me. Please retry with a clean user dir. You can run NetBeans like this:

```
<PATH_TO_NETBEANS>\bin\netbeans64.exe --userdir c:\temp\nb-userdir --cachdir c:\temp\nb-cachedir
```

That way a "clean" installation is started and you could recheck if it is still reproducible.

**Comment by r1gm** [comment]
confirmed not happen with clean installation...

i will try using clean installation and report again if i found more reproducible action

Thank you

**Comment by matthiasblaesing** [comment]
@r1gm thanks for the update. I'll close this then, as in the base case no changes happen. I would advice to look for formatter plugins, that might affect files.
