### ISSUE TITLE
Adding JavaFX sources to Ant Library

### ISSUE THREAD

**Issue by trashgod** [apache/netbeans#7888]
### Apache NetBeans version

Apache NetBeans 23

### What happened

**Problem**: After creating a Library for JavaFX as shown in [_JavaFX and NetBeans: Non-modular projects: IDE_](https://openjfx.io/openjfx-docs/#IDE-NetBeans) and adding `src.zip` to the "Sources" pane of the Ant  Library Manager, navigating to a source file produces a disassembled listing, as from `javap -c`, and the source is not available for debugging. A Maven project with downloaded sources works as expected

**Mitigation**: Because the <kbd>Add URL…</kbd> button is disabled, editing the corresponding library XML manually  to use a [`jar URL`](https://netbeans.apache.org/wiki/main/netbeansdevelopperfaq/DevFaqUriVsUrl/) for each module, as shown [here](https://stackoverflow.com/a/78991493/230513), restores the expected navigation and debugging functionality.

```
<resource>jar:file:/…/lib/javafx-sdk-21.0.4/src.zip!/javafx.base/</resource>
<resource>jar:file:/…/lib/javafx-sdk-21.0.4/src.zip!/javafx.controls/</resource>
…
```

### Language / Project Type / NetBeans Component

Java with Ant Library, Java Application

### How to reproduce

1. Download a JavaFX SDK from [here](https://gluonhq.com/products/javafx/); the problem may reproduced with any of several iterations of versions 21 or 17.
2. Create a project and shown in [_JavaFX and NetBeans: Non-modular projects: IDE_](https://openjfx.io/openjfx-docs/#IDE-NetBeans).
3. Add the `src.zip` file to the "Sources" pane of the Ant  Library Manager for the Library created in the previous step.
4. Open any JavaFX program and attempt to navigate to any source class.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

MacOS Intel

### JDK

java version "21.0.4" 2024-07-16 LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

As Maven works correctly, Ant source access is a low priority issue that is easily mitigated.

### Are you willing to submit a pull request?

No

**Comment by trashgod** [comment]
Issue confirmed with `javafx-sdk-21.0.5`. Please consider adding JavaFX label.

**Comment by matthiasblaesing** [comment]
@trashgod could you please check whether #7932 fixes the issue for you? A nightly build is available from the [Checkspage](https://github.com/apache/netbeans/pull/7932/checks) or [directly](https://github.com/apache/netbeans/suites/30399297335/artifacts/2135211439). Thank you.

**Comment by trashgod** [comment]
@matthiasblaesing: Thank you for looking at this issue. Yes, [#7932](https://github.com/apache/netbeans/pull/7932) works as expected, both
1. Via import from the previous version on initial startup, and
2. Via the <kbd>Add URL…</kbd> button of the "Sources" pane.

**Comment by matthiasblaesing** [comment]
@trashgod thanks for testing!

**Comment by matthiasblaesing** [comment]
Lets reopen until the fix is merged to master.
