### ISSUE TITLE
OutlineView header popup menu contains double column names.

### ISSUE THREAD

**Issue by itzlewitz** [apache/netbeans#7909]
### Apache NetBeans version

Apache NetBeans 23

### What happened

The OutlineView header popup menu contains double column names.
Here is my code:
```

    final List<String> attributes = new ArrayList<>();
    attributes.add(NotificationTypeProperty.NAME);
    attributes.add(NotifyCreationTimeProperty.NAME);
    attributes.add(CauseProperty.NAME);
    Collections.sort(attributes);
    final String[] propertyColumns = new String[attributes.size()*2];
    int i = 0;
    for (String attr : attributes) {
      propertyColumns[i++] = attr; // name
      propertyColumns[i++] = attr; // display name
    }
    outlineView.setPropertyColumns(propertyColumns);

```

### Language / Project Type / NetBeans Component

Java / Java Maven Application / NB21

### How to reproduce

Right click on the header line of a OutlineView table.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu

### JDK

Java: 21.0.2; OpenJDK 64-Bit Server VM 21.0.2+13-LTS

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

**Comment by itzlewitz** [comment]
![OutlineViewPopupMenuOfTableHeader](https://github.com/user-attachments/assets/9ffa5488-a231-4249-ab7e-9db7589f78c0)

**Comment by neilcsmith-net** [comment]
It contains name and description.  The description is probably falling back to the name if not set.  Without knowing the full context of what you're using and in what context it's hard to know what the right answer is for you.  If in the platform, this display is brandable.

**Comment by itzlewitz** [comment]
Thank you for your answer. I am in the Platform.
I would like to display only the column name.
Setting the column description to " " removes the double name display, however the colon after the name ist displayed. How can I display only the column name in the popup menu?

**Comment by neilcsmith-net** [comment]
This text, like most things in the platform, can be changed via branding.  Look up via outline.

**Comment by itzlewitz** [comment]
Is there sample code to do so?

**Comment by matthiasblaesing** [comment]
Have a look here: https://bits.netbeans.org/23/javadoc/org-openide-modules/org/openide/modules/doc-files/i18n-branding.html

The idea is, that the IDE/Platform contains many strings/formats you might want to customize. you need to set the Branding token, that identifies your application and create a ResourceBundle for that. Minimal sample:

```java
import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JFrame;
import org.openide.explorer.view.OutlineView;
import org.openide.util.NbBundle;

public class TestX {

    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
            NbBundle.setBranding("dummy");
            OutlineView outlineView = new OutlineView() {

            };
            final List<String> attributes = new ArrayList<>();
            attributes.add("test1");
            attributes.add("test2");
            attributes.add("test3");
            Collections.sort(attributes);
            final String[] propertyColumns = new String[attributes.size() * 2];
            int i = 0;
            for (String attr : attributes) {
                propertyColumns[i++] = attr; // name
                propertyColumns[i++] = null; // display name
            }
            outlineView.setPropertyColumns(propertyColumns);
            JFrame jframe = new JFrame("X");
            jframe.setSize(800, 600);
            jframe.setLayout(new BorderLayout());
            jframe.add(outlineView);
            jframe.setVisible(true);
        });
    }
}
```

The Branding token is here set programmatically, the NB launcher should take care of it. Create the ResourceBundle in file `org/openide/explorer/view/Bundle_dummy.properties`. Input this:

```properties
OutlineViewOutline_NameAndDesc={0}
```

This code: 

https://github.com/apache/netbeans/blob/45696ba6af2d663818daf33c49c3b2710e8d35e1/platform/openide.explorer/src/org/openide/explorer/view/OutlineView.java#L1913-L1935

Builds the menu entry string via:

https://github.com/apache/netbeans/blob/45696ba6af2d663818daf33c49c3b2710e8d35e1/platform/o.n.swing.outline/src/org/netbeans/swing/etable/ColumnSelectionPanel.java#L122-L219

You can't set the description to `null` (`FeatureDescription` will return the displayname in that case), so you will always land here:

https://github.com/apache/netbeans/blob/45696ba6af2d663818daf33c49c3b2710e8d35e1/platform/openide.explorer/src/org/openide/explorer/view/OutlineView.java#L1924

And there is the Key you need to override (the path comes from the package).
