### ISSUE TITLE
Fix problem with palette in output window

### ISSUE THREAD

**Issue by PavelTurk** [apache/netbeans#7911]
### Apache NetBeans version

Apache NetBeans 23

### What happened

This is a screenshot of javadoc plugin warnings:
![Screenshot from 2024-10-26 16-56-01](https://github.com/user-attachments/assets/def6ee14-5fbd-40a3-b760-e6e4e0834589)

Yellow color is `#ffcb55`. The contrast is very poor see https://coolors.co/contrast-checker/ffcb55-ffffff

### How to reproduce

In any project produce situation with javadoc warnings.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 20.04.6 LTS

### JDK

Java: 22.0.1; OpenJDK 64-Bit Server VM 22.0.1+8-16

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
yellow/orange is always difficult on white. But a darker orange is probably possible there without interfering with errors.
255, 153, 0
![image](https://github.com/user-attachments/assets/b300aaac-fd10-4368-bda0-56abff8cf187)

225, 153, 0 less red
![image](https://github.com/user-attachments/assets/86626c2b-aad7-40fa-b4b5-bc2f227023e3)

153, 153, 0 even less red
![image](https://github.com/user-attachments/assets/562fa08e-fccd-4705-8e56-5885bf315b97)
