### ISSUE TITLE
Subword completion for SQL

### ISSUE THREAD

**Issue by vulewuxe86** [apache/netbeans#7912]
### Description

Provide subword completion for SQL

### Use case/motivation

I think it would be a good idea to provide subword completion for SQL too. In the GIF you can see why it might be useful.

![SQL-Completion](https://github.com/user-attachments/assets/f2dda610-78d8-43d9-9030-bf165c30d167)

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Is there _any_ site in NetBeans, where completion that is implemented? If there is reasonable amout of such implementation I'm willing to have a look, but if it not used anywhere, I don't see this as a valid addition.

**Comment by vulewuxe86** [comment]
Hi, it is already implemented for Java: https://netbeans.apache.org/tutorial/main/kb/docs/java/editor-codereference/#_subword_completion Looking forward to your implementation. :)

**Comment by vulewuxe86** [comment]
Hi @matthiasblaesing, I had a look into the code and found this line: https://github.com/apache/netbeans/blob/813ddb886703784372a55bf993590db9b56d99f5/ide/db.sql.editor/src/org/netbeans/modules/db/sql/editor/completion/SQLCompletionItems.java#L228

If you change it to `return prefix == null || string.toLowerCase().contains(prefix.toLowerCase());` then the completion also works for subwords. Due to the fact that this method is used for every identifier it might produce unwanted results. I didn't check it thoroughly. I don't know if you still want to look into implementing this feature but the aforementioned line might be a good starting point.

Kind regards

**Comment by neilcsmith-net** [comment]
@vulewuxe86 please be careful about any use of `toLowerCase()` without a Locale.  You probably want to use `Locale.ROOT` to get similar behaviour to the region matching?  See also docs for https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/lang/String.html#toLowerCase() and https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/lang/String.html#regionMatches(boolean,int,java.lang.String,int,int)

**Comment by matthiasblaesing** [comment]
@vulewuxe86 implementation is in #7945, nightly build is available from [check](https://github.com/apache/netbeans/pull/7945/checks) page or [directly}(https://github.com/apache/netbeans/suites/30677948413/artifacts/2164887950)

**Comment by vulewuxe86** [comment]
Seems to work. Thank you!
