### ISSUE TITLE
Isn't the presence of settings.xml in the project root confusing?

### ISSUE THREAD

**Issue by PavelTurk** [apache/netbeans#7916]
### Apache NetBeans version

Apache NetBeans 23

### What happened

This is my screenshot
![Screenshot from 2024-10-28 10-26-59](https://github.com/user-attachments/assets/0fee92a4-43d8-463e-b190-5705b22d1263)

`Settings.xml` is maven `.m2/settings.xml`. I think that showing this file in the project was done intentionally. But isn't it confusing because project does NOT contain `settings.xml` file, so why is it shown in project tree? Besides the same file is shown in all projects.

### How to reproduce

Create `.m2/settings.xml` file and use it in maven plugins.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 20.04.6 LTS

### JDK

Java: 22.0.1; OpenJDK 64-Bit Server VM 22.0.1+8-16

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
From my POV this is not a bug, but a feature. The global `settings.xml` can have a direct impact on the users build of a project. For example I have to adjust/override the lombok version, as it typically lacks behind in projects.

What is the problem you are seeing?
