### ISSUE TITLE
Navigate context menu contains duplicated entries

### ISSUE THREAD

**Issue by mbien** [apache/netbeans#7918]
### Apache NetBeans version

Apache NetBeans 23

### What happened

The `Navigate` context menu has some Java EE actions show up twice (at least in disabled state)
![double-actions](https://github.com/user-attachments/assets/65cdbe94-5bae-4acb-aaf7-0f259aa22a20)

Is no regression, also reproducible in NB 21

### Language / Project Type / NetBeans Component

java maven project, the actions seem to be from the EE cluster though

### How to reproduce

- create hello world maven project
- make sure EE modules are loaded (e.g quickly go to "web application" wizard and cancel after cluster activation)
- right click somewhere in the code, e.g `println()` and use `Navigate` menu

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

linux

### JDK

Corretto 23.0.1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No (at least not right now ;))

**Comment by matthiasblaesing** [comment]
Gut feeling: Introduced when the javax/jakarta split happend and NetBeans spun two modules to support both namespaces.
