### ISSUE TITLE
Console 'Find' Doesn't Populate Correctly When the First Character is Selected

### ISSUE THREAD

**Issue by IanKrL** [apache/netbeans#7942]
### Apache NetBeans version

Apache NetBeans 23

### What happened

With text in the console, select a portion of text and "CTRL+F" to open the Find dialog. The text box is pre-populated with the selected text, unless the first character is selected. If the first character in the Output window is included in the selection, the Find is populated with the previous value just as if nothing were selected.
![Screenshot from 2024-11-07 14-22-45](https://github.com/user-attachments/assets/b92eaf4e-98b2-46ca-9cf1-f1d36d17e140)
![Screenshot from 2024-11-07 14-22-56](https://github.com/user-attachments/assets/a5a7eb6f-24ab-4f9b-a2d5-54e89547c0d6)

### How to reproduce

Create a javascript project
CTRL+SHIFT+F5 to Debug File
Select Output->Debugger Console
Select the first word "Listening"
CTRL+F
The 'Find' Dialog is displayed, but not populated with "Listening" as it should be.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Alma Linux

### JDK

17.0.8; OpenJDK 64-Bit Server VM 17.0.8+7

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
can reproduce and I think I found the issue, will open a PR soon
