### ISSUE TITLE
Unable to Create customized , user package in NetBeans

### ISSUE THREAD

**Issue by abhich260** [apache/netbeans#7948]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

I am unable to create user packages or packages with kind of customized name from user that is my end except for the already created packages by default like Source packages or default package in Netbeans after I am creating a new java project . Everytime I am attempting to create Netbeans is creating a file with the name i am entering for package instead of creating package . The NetBeans version is 9.0 and I am launching the netbeans ide application by extracting the incubating Netbenas bin compressed folder that is available from apache net beans site becasue installer zip folder is not available for installing net beans 9.0 . 
Please troubleshoot this issue . 

### Language / Project Type / NetBeans Component

Java SE Application 

### How to reproduce

Please any support agent connect to me and let me reproduce the issue ,and let the support agent view the issue by remote screensharing cum cat option of Microsoft that is Quick Assist app . 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Home single language

### JDK

JDK 8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

The issue is occuring everytime

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
NetBeans 9 is long out of data. Please get JDK 21 and the current NetBeans: https://netbeans.apache.org/front/main/download/

Your "How to reproduce" expressions hints that you assume, that you are entitled to support. If so, you are at the wrong location. Apache NetBeans does not provide support, so you might have bought support from a different entity, please turn to that.

**Comment by abhich260** [comment]
Hello , I have not bought support from different entity or anything like that . 
And I am facing inconvenience in using latest or modern version Netbeans , am only finding the display view looks of Netbeans user friendly so i would like to use 9 version only . Kindly please extend or provide support to my said elaborated issue .
