### ISSUE TITLE
Incorrect Bundle localization in /o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory

### ISSUE THREAD

**Issue by FredAncestris** [apache/netbeans#7950]
### Apache NetBeans version

Apache NetBeans 23

### What happened

There has been a translation issue since the many versions of Netbeans.

In ./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:124
in the line: 124

button.setToolTipText( java.util.ResourceBundle.getBundle("org/netbeans/swing/tabcontrol/plaf/Bundle").getString("Tip_Scroll_Documents_Right") );

It seems the direct call to getBundle() prevents the use of branding overlay translations: if I create a bundle_fr file in org-netbeans-swing-tabcontrol/plaf, the new translation does not get picked up.

For most other modules, Netbeans picks it up correctly.

I think it should be changed to NbBundle.getMessage() instead.

Thanks.

### Language / Project Type / NetBeans Component

Ancestris application using Netbeans platform 

### How to reproduce

Just create a branding/modules/org-netbeans-swing-tabcontrol.jar/org/netbeans/swing/tabcontrol/plaf/Bundle.properties with the text :

Tip_Scroll_Documents_Right=Scroll Tab Right

and you will see that your app will not pick this new translation: if you mouse over the window right button, it will still say "Scroll Document Right", and not "Scroll Tab Right".

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux

### JDK

OpenJDK Runtime Environment Temurin-17+35 (build 17+35)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

There are other lines to change in this module:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:118:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:124:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:136:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:153:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:200:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:201:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:236:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:282:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:345:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:346:
./o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java:459:

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Please test the nightly for PR #7970 available from [checks page](https://github.com/apache/netbeans/pull/7970/checks) or [directly](https://github.com/apache/netbeans/suites/30954413825/artifacts/2195227504)
