### ISSUE TITLE
App doesn't launch on new Mac mini M4/Sequoia

### ISSUE THREAD

**Issue by dvitcompte** [apache/netbeans#7955]
### Apache NetBeans version

Apache NetBeans 23

### What happened

Hello,

I installed Apache Netbeans 23 application on my new mac mini m4 (pro) with sequoia 15.1
When I click on the dock icon, the icon bounces but nothing appears.

I tried uninstall & install severals times, tried netbeans 22.

I don't know how to get Netbeans to work.
Do you have an idea ?

Regards,

### How to reproduce

1. Go on the Apache Netbeans website to download the last version (23), pkg file.
2. Install it
3. Launch it
4. The icon bounce but the app does not appear.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Macos Sequoia 15.1

### JDK

-

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Almost certainly because no JDK is installed or found. Please check for a JDK, or try the community installers (which bundle a runtime JDK) instead.

**Comment by dvitcompte** [comment]
Great thanks !
I had never tried these installers.
It works like a charm.

Regards,
