### ISSUE TITLE
JSF new file "JSF Composite Component" dialog does not work

### ISSUE THREAD

**Issue by stevaber** [apache/netbeans#8004]
### Apache NetBeans version

Apache NetBeans 23

### What happened

New file "JSF Composite Component" does not work any more. When I try to create file template, "user" in example below, dialog create empty file and report error "user.xhtml already exist" in the bottom of dialog and stays opened.  

![image](https://github.com/user-attachments/assets/46e61059-5656-4c31-854a-5095cbde1dba)

In previous NB versions dialog created JSF composite component with following content:
```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite">

    <!-- INTERFACE -->
    <cc:interface>
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
    </cc:implementation>
</html>
```
Also in previous NB versions dialog was not finished. The "Prefix:" and "Implementation:" sections were disabled.

### Language / Project Type / NetBeans Component

Java "Web application" Maven and Ant

### How to reproduce

Just try to add new file ->  JavaServer Faces -> JSF Composite Component
enter file name and click finish.

### Did this work correctly in an earlier version?

Apache NetBeans 16 or earlier

### Operating System

Windows 10 version 10.0 running on amd64; UTF-8; en_US (nb)

### JDK

17.0.10; Java HotSpot(TM) 64-Bit Server VM 17.0.10+11-LTS-240

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Please retest with NB24 RC: https://github.com/apache/netbeans/discussions/7898

If it fails, please provide the IDE/messsage.log.

**Comment by stevaber** [comment]
Thanks for your quick response. I have installed/copied NB24-RC4 from
netbeans-24-rc4-bin.zip
<https://nightlies.apache.org/netbeans/candidate/netbeans/netbeans-24-rc4-bin.zip>
archive.
The bug with dialog "JSF Composite Component" still exists. Ide log file is
in attachment.

Best regards Stevan Berberović

**Comment by matthiasblaesing** [comment]
@stevaber the message log did not make it through.

**Comment by stevaber** [comment]
Sorry I am traying to send ide log again 
[messages.log](https://github.com/user-attachments/files/17955516/messages.log)

**Comment by matthiasblaesing** [comment]
@stevaber thank you, that was helpful. Could you please do this:

1. Open the Template dialog (Tools -> Templates)
2. Choose "JavaServer Faces" -> "JSF Composite Component"
3. Choose "Open in Editor"
4. Change line 6 to (remove the space between `#else if`:
  ```freemarker
  <#elseif isJSF22?? || isJSF30??>
  ```
5. Save the file
6. Retry the generation

By doing this you replace the NB provided template with your own fixed one. To return to the NB version, just choose the template again (Step 2) and select "Revert to default".

If this fixes the problem, I'll prepare an PR for NB25.

**Comment by stevaber** [comment]
Hello Matthias,
I have followed your instruction and that is the solution for issue #8004.
Best regards Stevan Berberović
[image: image.png]
