### ISSUE TITLE
TypeScript navigator empty in NetBeans 23, works in 22.

### ISSUE THREAD

**Issue by gugrim** [apache/netbeans#8012]
### Apache NetBeans version

Apache NetBeans 23

### What happened

Opened a typescript file.
Expected the Navigator to show methods and attributes.
The Navigator is empty.

### Language / Project Type / NetBeans Component

FreeForm project with TypeScript code

### How to reproduce

Open the simple project attached in in NetBeans 22. In the Source folder view there is a typescript class, NothingReally.ts. Open it. The Navigator shows the attribute and method.

Do the same in NetBeans 23. Empty navigator.

[TypeScript.tar.gz](https://github.com/user-attachments/files/17982510/TypeScript.tar.gz)

### Did this work correctly in an earlier version?

Apache NetBeans 22

### Operating System

OpenSuse Leap 15.4

### JDK

OpenJDK 64-Bit Server VM 17.0.13+11-suse-150400.3.48.2-x8664

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Occurs every time.

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Please show your message.log. (on linux: `$HOME/.netbeans/<VERSION>/var/log/messages.log`).

**Comment by gugrim** [comment]
The IDE log as requested:
[messages.log](https://github.com/user-attachments/files/18129687/messages.log)

**Comment by gugrim** [comment]
Just tested with NetBeans 24 and the TypeScript navigator is back.

**Comment by matthiasblaesing** [comment]
@gugrim thanks for the check. You most probably saw the issue fixed by #7757. Closing this as it is fixed in NB24.
