### ISSUE TITLE
Right Click context menu stays open when I switch windows on ubunty 24

### ISSUE THREAD

**Issue by sasebt** [apache/netbeans#8050]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Right Click context menu stays open when I switch windows on ubunty 24

### Language / Project Type / NetBeans Component

does not matter

### How to reproduce

open netbeans
right click on the code window -> context menu will show
use alt+tab to switch to another application
the context menu is still displayed on top of everything

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 24

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by neilcsmith-net** [comment]
Thanks for the report.  This appears to be an issue with Xwayland, on Ubuntu 24.04 at least.  Can replicate the same issue by running `GDK_BACKEND=x11 gnome-text-editor`, so it does not seem to be specific to NetBeans or even the JDK.  I'm not sure we can do anything about this, so marking won't fix here.
