### ISSUE TITLE
Find in Projects not working in NetBeans 24

### ISSUE THREAD

**Issue by stant** [apache/netbeans#8064]
### Apache NetBeans version

Apache NetBeans 24

### What happened

Just installed newest NB 24 and tried using ctrl-shift-f and anything i try to search for it finds nothing. I try a string in the code file I am in that I see in front of me and it does not find that either.

### Language / Project Type / NetBeans Component

Java Spring Boot gradle project

### How to reproduce

Have a java file open. hit ctrl-shift-f enter any text, like "logger" and it says match: literal. hit find and it never finds anything.

### Did this work correctly in an earlier version?

Apache NetBeans 23

### Operating System

Linux mypc 6.12.1-4-MANJARO #1 SMP PREEMPT_DYNAMIC Mon, 25 Nov 2024 05:36:03 +0000 x86_64 GNU/Linux

### JDK

Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

### Apache NetBeans packaging

Other

### Anything else

i think it is installed with netbeans-bin 24-1 manjaro AUR package

this is newest manjaro. there are other weird things maybe just in netbeans. menu's not dropping down correctly....

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
> this is newest manjaro. there are other weird things maybe just in netbeans. menu's not dropping down correctly....

and

> Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

please update the JDK to the latest update release. Manjaro does have all up to date packages in its repo.

```
$ archlinux-java status
Available Java environments:
  java-11-openjdk
  java-17-openjdk (default)
  java-21-openjdk
  java-23-openjdk
$ java -version
openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment (build 17.0.13+11)
OpenJDK 64-Bit Server VM (build 17.0.13+11, mixed mode, sharing)
```

> i think it is installed with netbeans-bin 24-1 manjaro AUR package

the arch user repo is a collection of user maintained build scripts. We can only support the artifacts you can find on the download page. If something is broken there - we can't fix it.

**Comment by hichamglia** [comment]
> ### Apache NetBeans version
> 
> Apache NetBeans 24
> ### What happened
> 
> Just installed newest NB 24 and tried using ctrl-shift-f and anything i try to search for it finds nothing. I try a string in the code file I am in that I see in front of me and it does not find that either.
> ### Language / Project Type / NetBeans Component
> 
> Java Spring Boot gradle project
> ### How to reproduce
> 
> Have a java file open. hit ctrl-shift-f enter any text, like "logger" and it says match: literal. hit find and it never finds anything.
> ### Did this work correctly in an earlier version?
> 
> Apache NetBeans 23
> ### Operating System
> 
> Linux mypc 6.12.1-4-MANJARO #1 SMP PREEMPT_DYNAMIC Mon, 25 Nov 2024 05:36:03 +0000 x86_64 GNU/Linux
> ### JDK
> 
> Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
> ### Apache NetBeans packaging
> 
> Other
> ### Anything else
> 
> i think it is installed with netbeans-bin 24-1 manjaro AUR package
> 
> this is newest manjaro. there are other weird things maybe just in netbeans. menu's not dropping down correctly....
> ### Are you willing to submit a pull request?
> 
> No

Same issue here with JDK21 and macOS 15.1.1

**Comment by matthiasblaesing** [comment]
Guys, seriously, you are developers, how do you expect people to help you, if you don't provide basic information?I suspect, that search is working, you are just not seeing the result, that can be trivially be fixed (by you)

**Comment by matthiasblaesing** [comment]
What I mean is, could it be, that you get a search result and it looks like this:

![grafik](https://github.com/user-attachments/assets/0570e220-6c7f-421f-81c6-1a5adad0d970)

Then, just pull open the result area:

![grafik](https://github.com/user-attachments/assets/f0e0f21a-0c97-4bb3-8e69-9e4e5a0f1af2)

I saw this a few times, but currently all instances work as they should.

**Comment by salochin** [comment]
Ubuntu auto updated me yesterday to from NB23 to NB24. I had what appeared to be the exact same issue of no search results that I could see. I almost rolled back to ND23. Your suggestion of just pulling open the hidden results worked for me. Even after you told me where to look, it look me a bit to figure out where to drag.

**Comment by mbien** [comment]
the search results panel probably needs a minimal width set so that it can't completely collapse. Usages/Refactoring doesn't seem to have the same problem - haven't checked the other inspection windows.

> this is newest manjaro. there are other weird things maybe just in netbeans. **menu's not dropping down correctly....**

turns out this remark was a red herring if this issue is just about a panel splitter

**Comment by mbien** [comment]
[dev-build](https://github.com/apache/netbeans/actions/runs/12472168247/artifacts/2357168257) with proposed fix (https://github.com/apache/netbeans/pull/8088)
