### ISSUE TITLE
24 search not working

### ISSUE THREAD

**Issue by sysmat** [apache/netbeans#8072]
### Apache NetBeans version

Apache NetBeans 24

### What happened

basic search in java file not work

### Language / Project Type / NetBeans Component

maven

### How to reproduce

just search

### Did this work correctly in an earlier version?

Apache NetBeans 23

### Operating System

win 11

### JDK

jdk 23

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by patton73** [comment]
I confirm that. The graphical search does not work. If you get the text using "show all details button" at least you can see the text complete search output.

**Comment by mbien** [comment]
can't reproduce

**Comment by sysmat** [comment]
hm, strange, I also se with 24 copy/paste from other apps(browser, VSC, ...) dosn't work

**Comment by patton73** [comment]
This is a duplicate of https://github.com/apache/netbeans/issues/8064

**Comment by sysmat** [comment]
@patton73 thx
