### ISSUE TITLE
PHP 8.3 Lazy static initialization for non constants

### ISSUE THREAD

**Issue by Wukkopi** [apache/netbeans#8073]
### Apache NetBeans version

Apache NetBeans 24

### What happened

I'm getting syntax error on valid syntax when language level is on 8.3.

Since PHP 8.3 lazy static initialization happens during runtime instead of compile time, allowing non-constants to be assigned (functions, and even class variables).

### How to reproduce

```php
class MyClass
{
    private int $variable = 1;
    function run() : void
    {
        static $functionResult = rand(); // shows "unexpected '(' after rand" error
        static $classVariable = $this->variable; // shows "unexpected '$this' after =" error
    }
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian 12

### JDK

OpenJDK 64-Bit Server VM (build 17.0.13+11-Debian-2deb12u1, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Thanks for reporting it.

https://wiki.php.net/rfc/arbitrary_static_variable_initializers

**Comment by junichi11** [comment]
@Wukkopi It would be nice if you can test a dev version: https://github.com/apache/netbeans/suites/32363378994/artifacts/2354210960

**Comment by Wukkopi** [comment]
@junichi11 Tested it just now. It doesn't complain anymore :+1:
