### ISSUE TITLE
False syntax error on static variable assignment with require

### ISSUE THREAD

**Issue by sk757a** [apache/netbeans#8086]
### Apache NetBeans version

Apache NetBeans 24

### What happened

Netbeans shows syntax error on correct source line:
```
Syntax error
unexpected:	require
after:	=
expected:	integer, double, identifier, String, String, array, __CLASS__, __TRAIT__, __METHOD__, __FUNCTION__, __LINE__, __FILE__, <<<"...", __NAMESPACE__, __DIR__, define, +, -, !, ~, [, new, static, (, <<<'...'
```
### Language / Project Type / NetBeans Component

PHP project

### How to reproduce

```
function foo()
{
    static $bar = require 'bar.php';
}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 x64

### JDK

Eclipse Temurin 21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

PHP 8.3.14

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Duplicate: https://github.com/apache/netbeans/issues/8073
